import { Restaurant } from "@/lib/types/types";

export const glacierBayRestaurants: Restaurant[] = [
  {
    name: "Golden & Co.",
    description:
      "Experience authentic Italian cuisine with a local twist, featuring gourmet street food served in an atmosphere of seasonal floral displays overlooking the cultural center.",
    cuisine: "Italian",
    priceRange: "$",
    rating: 4.6,
    openingHours: {
      monday: "10:00-20:00",
      tuesday: "10:00-19:00",
      wednesday: "10:00-19:00",
      thursday: "11:00-19:00",
      friday: "9:00-20:00",
      saturday: "10:00-20:00",
      sunday: "11:00-19:00",
    },
    contactInfo: {
      contactNumber: "+1-555-284-5588",
      contactEmail: "customerservice@grandtableglacier-bay.com",
    },
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: true,
    isHalalFriendly: false,
    isKosherFriendly: false,
    isFineDining: false,
    isAdultOnly: false,
    isIndoorSeating: true,
    isReservationsAccepted: true,
    isRomantic: true,
    isPopular: true,
  },
  {
    name: "Royal Eatery",
    description:
      "A charming Japanese restaurant near the city museum, offering fresh produce and other local favorites in a setting with elegant atmosphere.",
    cuisine: "Japanese",
    priceRange: "$",
    rating: 3.9,
    openingHours: {
      monday: "9:00-19:00",
      tuesday: "9:00-21:00",
      wednesday: "9:00-22:00",
      thursday: "Closed",
      friday: "9:00-21:00",
      saturday: "11:00-21:00",
      sunday: "10:00-19:00",
    },
    contactInfo: {
      contactNumber: "+1-555-742-3185",
      contactEmail: "customerservice@royalpatisserieglacier-bay.com",
    },
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: false,
    isHalalFriendly: false,
    isKosherFriendly: false,
    isFineDining: false,
    isAdultOnly: false,
    isIndoorSeating: true,
    isReservationsAccepted: true,
    isRomantic: false,
    isPopular: false,
  },
  {
    name: "Royal Inn",
    description:
      "Experience authentic Italian cuisine with a local twist, featuring regional wines served in an atmosphere of local ambiance overlooking the waterfront.",
    cuisine: "Italian",
    priceRange: "$",
    rating: 3.9,
    openingHours: {
      monday: "10:00-19:00",
      tuesday: "9:00-19:00",
      wednesday: "Closed",
      thursday: "11:00-20:00",
      friday: "11:00-20:00",
      saturday: "10:00-19:00",
      sunday: "11:00-21:00",
    },
    contactInfo: {
      contactNumber: "+1-555-321-8410",
      contactEmail: "customerservice@royalcurryhouseglacier-bay.com",
    },
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: false,
    isHalalFriendly: false,
    isKosherFriendly: false,
    isFineDining: false,
    isAdultOnly: false,
    isIndoorSeating: true,
    isReservationsAccepted: true,
    isRomantic: false,
    isPopular: true,
  },
  {
    name: "Royal Curry House",
    description:
      "This popular Mediterranean establishment combines traditional recipes and signature dishes, all served in a unique setting with seasonal floral displays.",
    cuisine: "Mediterranean",
    priceRange: "$",
    rating: 4.7,
    openingHours: {
      monday: "11:00-22:00",
      tuesday: "9:00-19:00",
      wednesday: "10:00-22:00",
      thursday: "10:00-21:00",
      friday: "9:00-21:00",
      saturday: "Closed",
      sunday: "10:00-21:00",
    },
    contactInfo: {
      contactNumber: "+1-555-491-7754",
      contactEmail: "customerservice@royalcurryhouseglacier-bay.com",
    },
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: true,
    isHalalFriendly: false,
    isKosherFriendly: false,
    isFineDining: false,
    isAdultOnly: false,
    isIndoorSeating: true,
    isReservationsAccepted: true,
    isRomantic: false,
    isPopular: false,
  },
  {
    name: "Grand Bar & Kitchen",
    description:
      "This popular Mediterranean establishment combines traditional recipes and heritage recipes, all served in a unique setting with artisan markets.",
    cuisine: "Mediterranean",
    priceRange: "$",
    rating: 4.8,
    openingHours: {
      monday: "11:00-20:00",
      tuesday: "9:00-20:00",
      wednesday: "11:00-19:00",
      thursday: "Closed",
      friday: "10:00-20:00",
      saturday: "10:00-20:00",
      sunday: "11:00-20:00",
    },
    contactInfo: {
      contactNumber: "+1-555-229-4407",
      contactEmail: "customerservice@goldentaproomglacier-bay.com",
    },
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: false,
    isHalalFriendly: true,
    isKosherFriendly: false,
    isFineDining: false,
    isAdultOnly: true,
    isIndoorSeating: true,
    isReservationsAccepted: false,
    isRomantic: true,
    isPopular: true,
  },
  {
    name: "Grand Inn",
    description:
      "Experience authentic Mediterranean cuisine with a local twist, featuring farm-to-table meals served in an atmosphere of local ambiance overlooking the city museum.",
    cuisine: "Mediterranean",
    priceRange: "$",
    rating: 4.5,
    openingHours: {
      monday: "9:00-22:00",
      tuesday: "11:00-21:00",
      wednesday: "11:00-20:00",
      thursday: "10:00-22:00",
      friday: "10:00-22:00",
      saturday: "10:00-19:00",
      sunday: "10:00-19:00",
    },
    contactInfo: {
      contactNumber: "+1-555-597-9360",
      contactEmail: "ask@bluesaloonglacier-bay.com",
    },
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: true,
    isHalalFriendly: true,
    isKosherFriendly: false,
    isFineDining: true,
    isAdultOnly: false,
    isIndoorSeating: true,
    isReservationsAccepted: true,
    isRomantic: false,
    isPopular: false,
  },
  {
    name: "Grand Artisan",
    description:
      "Experience authentic Mediterranean cuisine with a local twist, featuring seasonal specialties served in an atmosphere of live street performances overlooking the city museum.",
    cuisine: "Mediterranean",
    priceRange: "$",
    rating: 4.8,
    openingHours: {
      monday: "9:00-19:00",
      tuesday: "10:00-22:00",
      wednesday: "11:00-22:00",
      thursday: "10:00-20:00",
      friday: "11:00-20:00",
      saturday: "11:00-22:00",
      sunday: "10:00-22:00",
    },
    contactInfo: {
      contactNumber: "+1-555-724-7323",
      contactEmail: "ask@grandramen-yaglacier-bay.com",
    },
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: true,
    isHalalFriendly: true,
    isKosherFriendly: false,
    isFineDining: true,
    isAdultOnly: false,
    isIndoorSeating: true,
    isReservationsAccepted: false,
    isRomantic: false,
    isPopular: false,
  },
  {
    name: "The Marketplace",
    description:
      "A charming French restaurant near downtown, offering artisanal creations and other local favorites in a setting with beautiful decor.",
    cuisine: "French",
    priceRange: "$",
    rating: 4.2,
    openingHours: {
      monday: "10:00-21:00",
      tuesday: "9:00-20:00",
      wednesday: "10:00-22:00",
      thursday: "9:00-21:00",
      friday: "9:00-22:00",
      saturday: "Closed",
      sunday: "9:00-21:00",
    },
    contactInfo: {
      contactNumber: "+1-555-818-2882",
      contactEmail: "ask@royalbakeryglacier-bay.com",
    },
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: true,
    isHalalFriendly: false,
    isKosherFriendly: false,
    isFineDining: true,
    isAdultOnly: false,
    isIndoorSeating: true,
    isReservationsAccepted: true,
    isRomantic: false,
    isPopular: false,
  },
  {
    name: "The Seafood Shack",
    description:
      "A charming French restaurant near the city museum, offering gourmet street food and other local favorites in a setting with charming streetscapes.",
    cuisine: "French",
    priceRange: "$",
    rating: 3.9,
    openingHours: {
      monday: "11:00-22:00",
      tuesday: "10:00-21:00",
      wednesday: "11:00-20:00",
      thursday: "9:00-20:00",
      friday: "11:00-22:00",
      saturday: "Closed",
      sunday: "9:00-19:00",
    },
    contactInfo: {
      contactNumber: "+1-555-187-4628",
      contactEmail: "welcome@grandpavilionglacier-bay.com",
    },
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: false,
    isHalalFriendly: false,
    isKosherFriendly: false,
    isFineDining: false,
    isAdultOnly: false,
    isIndoorSeating: true,
    isReservationsAccepted: true,
    isRomantic: false,
    isPopular: false,
  },
  {
    name: "Grand Bistro",
    description:
      "A culinary gem serving French specialties including heritage recipes, where guests enjoy local ambiance in the heart of the city.",
    cuisine: "French",
    priceRange: "$$$",
    rating: 4.3,
    openingHours: {
      monday: "11:00-22:00",
      tuesday: "9:00-19:00",
      wednesday: "10:00-19:00",
      thursday: "9:00-19:00",
      friday: "9:00-19:00",
      saturday: "9:00-19:00",
      sunday: "11:00-22:00",
    },
    contactInfo: {
      contactNumber: "+1-555-146-2491",
      contactEmail: "contact@royalkebabhouseglacier-bay.com",
    },
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: true,
    isHalalFriendly: false,
    isKosherFriendly: false,
    isFineDining: true,
    isAdultOnly: false,
    isIndoorSeating: true,
    isReservationsAccepted: true,
    isRomantic: false,
    isPopular: true,
  },
  {
    name: "The Grill",
    description:
      "A culinary gem serving Italian specialties including seasonal specialties, where guests enjoy charming streetscapes in the heart of the city.",
    cuisine: "Italian",
    priceRange: "$$$$",
    rating: 4.8,
    openingHours: {
      monday: "11:00-22:00",
      tuesday: "11:00-20:00",
      wednesday: "10:00-21:00",
      thursday: "9:00-21:00",
      friday: "10:00-22:00",
      saturday: "10:00-22:00",
      sunday: "11:00-21:00",
    },
    contactInfo: {
      contactNumber: "+1-555-446-4872",
      contactEmail: "reachus@thecafeglacier-bay.com",
    },
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: false,
    isHalalFriendly: true,
    isKosherFriendly: false,
    isFineDining: true,
    isAdultOnly: false,
    isIndoorSeating: true,
    isReservationsAccepted: false,
    isRomantic: false,
    isPopular: true,
  },
  {
    name: "Grand Supper Club",
    description:
      "Experience authentic Mediterranean cuisine with a local twist, featuring seasonal specialties served in an atmosphere of boutique shops overlooking the iconic clock tower.",
    cuisine: "Mediterranean",
    priceRange: "$",
    rating: 3.9,
    openingHours: {
      monday: "10:00-22:00",
      tuesday: "11:00-19:00",
      wednesday: "11:00-20:00",
      thursday: "11:00-22:00",
      friday: "11:00-22:00",
      saturday: "11:00-19:00",
      sunday: "10:00-20:00",
    },
    contactInfo: {
      contactNumber: "+1-555-959-3522",
      contactEmail: "help@grandcharcuterieglacier-bay.com",
    },
    isVegetarianFriendly: false,
    isVeganFriendly: false,
    isGlutenFreeFriendly: true,
    isHalalFriendly: false,
    isKosherFriendly: false,
    isFineDining: false,
    isAdultOnly: false,
    isIndoorSeating: true,
    isReservationsAccepted: false,
    isRomantic: false,
    isPopular: false,
  },
  {
    name: "Grand Boulangerie",
    description:
      "A culinary gem serving Mediterranean specialties including local ingredients, where guests enjoy local ambiance in the heart of the city.",
    cuisine: "Mediterranean",
    priceRange: "$",
    rating: 4.6,
    openingHours: {
      monday: "11:00-21:00",
      tuesday: "9:00-19:00",
      wednesday: "11:00-22:00",
      thursday: "11:00-21:00",
      friday: "11:00-20:00",
      saturday: "Closed",
      sunday: "Closed",
    },
    contactInfo: {
      contactNumber: "+1-555-703-2271",
      contactEmail: "help@goldenteahouseglacier-bay.com",
    },
    isVegetarianFriendly: false,
    isVeganFriendly: false,
    isGlutenFreeFriendly: true,
    isHalalFriendly: true,
    isKosherFriendly: false,
    isFineDining: false,
    isAdultOnly: false,
    isIndoorSeating: true,
    isReservationsAccepted: true,
    isRomantic: false,
    isPopular: false,
  },
];
