import { RestaurantMenu } from "@/lib/types/types";

/**
 * Menu data for The Wok in montevideo
 */
export const montevideotheWokMenu: RestaurantMenu[] = [
  {
    title: "Main Course Menu",
    description:
      "Our carefully crafted selection of hearty Mediterranean dishes",
    category: [
      {
        name: "Signature Dishes",
        description:
          "Inspired by nature, mood, and season—our chef’s ever-evolving vision on a plate.",
        items: [
          {
            name: "Handcrafted Spiced Caribbean-Style Jerk Duck with Mango Slaw",
            price: 37.2,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Authentic Sizzling Black Garlic Glazed Beef Tenderloin",
            price: 35.95,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Gourmet Grilled Traditional Family Paella",
            price: 37.85,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Handcrafted Crispy Molecular Gastronomy Showcase Tasting",
            price: 30.13,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Exquisite 24-Hour Braised Short Ribs",
            price: 32.28,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: true,
          },
          {
            name: "Hearty Tangy Japanese A5 Wagyu with Ponzu Butter",
            price: 27.49,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Aromatic Chef's Special Surf and Turf",
            price: 27.06,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Chef's Specials",
        description:
          "A hand-picked menu selection that reflects the chef’s current inspirations and exceptional skill.",
        items: [
          {
            name: "Fresh Luscious Chef's Tasting Menu Experience",
            price: 25.79,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Classic Wholesome Signature Spice-Rubbed Protein",
            price: 31.96,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Juicy Miso-Glazed Black Cod",
            price: 39.16,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Pan-seared Pan-Seared Scallops with Citrus Beurre Blanc",
            price: 39.61,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Homestyle Steamed Cast Iron Seafood Presentation",
            price: 30.92,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Appetizers",
        description:
          "A delightful array of appetizers that highlight the best of Mediterranean flavors—perfect for sharing or enjoying solo.",
        items: [
          {
            name: "Spinach Artichoke Dip",
            price: 9.18,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Cheese Nachos",
            price: 15.31,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Tempura",
            price: 8.3,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Prawn Cocktail",
            price: 9.25,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Baba Ganoush",
            price: 10.99,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Baked Brie",
            price: 13.53,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Bruschetta",
            price: 15.31,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Ceviche",
            price: 10.72,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Soups",
        description:
          "Warm, nourishing soups that reflect the heart of Mediterranean cooking—perfect for any season.",
        items: [
          {
            name: "Homestyle Creamy Thai Coconut Soup",
            price: 11.05,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Zesty Minestrone",
            price: 9.06,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Gourmet Enticing Clam Chowder",
            price: 13.61,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Authentic Crunchy Mushroom Soup",
            price: 9.2,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: false,
            isKosher: true,
          },
        ],
      },
      {
        name: "Salads",
        description:
          "Light, clean, and energizing—each salad is a visual and flavorful delight.",
        items: [
          {
            name: "Watermelon Feta Salad",
            price: 10.43,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Farro Salad",
            price: 10.22,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Cobb Salad",
            price: 14.55,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Arugula Salad",
            price: 13.37,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Cucumber Salad",
            price: 9.11,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Main Courses",
        description:
          "Robust and satisfying center-of-plate dishes that deliver flavor and artistry.",
        items: [
          {
            name: "Premium Tangy Grilled Tofu",
            price: 21.68,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "House Special Luscious Pulled Pork Sandwich",
            price: 31.85,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Fresh Zingy Salmon",
            price: 18.18,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Fresh Herbed Enchiladas",
            price: 25.59,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Grilled Chili con Carne",
            price: 20.66,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: false,
            isKosher: true,
          },
          {
            name: "Authentic Creamy Fish and Chips",
            price: 20.48,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: true,
          },
          {
            name: "Seasonal Irresistible Stuffed Zucchini Boats",
            price: 27.41,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Premium Flaky Stuffed Peppers",
            price: 25.74,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Seafood Specialties",
        description:
          "Daily catches transformed into exquisite plates by our skilled kitchen team.",
        items: [
          {
            name: "Fresh Succulent Cedar Plank Roasted Salmon",
            price: 35.34,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Deluxe Crispy Seafood Gumbo with Okra",
            price: 29.82,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Fresh Smoked Blackened Mahi-Mahi with Pineapple Salsa",
            price: 29.16,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Irresistible Crab-Stuffed Mushrooms",
            price: 26.82,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Fresh Braised Lemon-Herb Calamari Steak",
            price: 31.65,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Side Dishes",
        description:
          "Flavorful companions that round out your meal with harmony and flair.",
        items: [
          {
            name: "Garlic Bread with Herb Butter",
            price: 7.95,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Herbed Bulgur Wheat with Lemon",
            price: 8.82,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Creamed Spinach with Nutmeg",
            price: 8.63,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Cauliflower Gratin with Gruyère",
            price: 7.46,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Maple-Glazed Baby Carrots",
            price: 7.07,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Sautéed Garlic Mushrooms",
            price: 7.79,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Non-Alcoholic Beverages",
        description:
          "Bright, invigorating options that cleanse the palate and refresh the spirit.",
        items: [
          {
            name: "Handcrafted Sweet Iced Tea",
            price: 7.08,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Homestyle Spicy Soda",
            price: 7.86,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Handcrafted Sizzling Water",
            price: 4.57,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Traditional Sizzling Juice",
            price: 7.29,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Gourmet Luscious Lemonade",
            price: 7.03,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Handcrafted Flaky Milkshake",
            price: 6.35,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
  {
    title: "Dessert Menu",
    description:
      "A tasty selection of desserts that will satisfy your cravings",
    category: [
      {
        name: "Baked Goods",
        description:
          "Perfectly baked pastries and breads that bring warmth to your table.",
        items: [
          {
            name: "Hearty Crunchy Cinnamon Rolls",
            price: 9.67,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "House Special Crispy Custard Tart",
            price: 9.17,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Pan-seared Red Velvet Cake",
            price: 6.02,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: true,
          },
          {
            name: "Classic Spicy Muffins",
            price: 8.02,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Gourmet Braised Shortbread",
            price: 9.8,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Frozen Desserts",
        description:
          "Smooth, rich frozen creations featuring local fruits and seasonal flavors.",
        items: [
          {
            name: "Hearty Crispy Frozen Pudding",
            price: 10.53,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Traditional Tender Ice Cream",
            price: 11.37,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Homestyle Crispy Popsicles",
            price: 7.97,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Creamy Ice Cream Cake",
            price: 9.22,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Homestyle Golden Frozen Cheesecake",
            price: 11.38,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
  {
    title: "Drinks Menu",
    description:
      "A fine assortment of libations to accompany your culinary journey",
    category: [
      {
        name: "Signature Cocktails",
        description:
          "Each sip tells a story—of ingredients, technique, and passion for mixology.",
        items: [
          {
            name: "Seasonal Crunchy Bloody Mary",
            price: 14.3,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Gourmet Exquisite Cosmopolitan",
            price: 14.84,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Classic Hearty Martini",
            price: 14.99,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Spicy Old Fashioned",
            price: 13.61,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Herbed Mojito",
            price: 11.21,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Deluxe Grilled Margarita",
            price: 14.4,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Homestyle Zesty Mai Tai",
            price: 12.81,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Wine Selection",
        description:
          "From crisp whites to structured reds, our wine list offers something for every palate.",
        items: [
          {
            name: "Marsanne",
            price: 13.73,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Chardonnay",
            price: 11.22,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Verdicchio",
            price: 12.83,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Merlot",
            price: 8.01,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Roussanne",
            price: 8.63,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Vermentino",
            price: 10.88,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Spirits and Liqueurs",
        description:
          "A curated collection of fine spirits and artisan liqueurs from around the world.",
        items: [
          {
            name: "Gourmet Exquisite Pisco",
            price: 10.64,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Traditional Herbed Whiskey",
            price: 16.41,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Seasonal Crunchy Campari",
            price: 14.86,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Seasonal Crispy Chambord",
            price: 14.49,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: false,
            isKosher: true,
          },
          {
            name: "Premium Sizzling Sambuca",
            price: 17.92,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
];
