import { RestaurantMenu } from "@/lib/types/types";

/**
 * Menu data for Blue Supper Club in philipsburg
 */
export const philipsburgblueSupperClubMenu: RestaurantMenu[] = [
  {
    title: "Main Course Menu",
    description:
      "An immersive dining experience defined by homestyle Japanese cuisine",
    category: [
      {
        name: "Signature Dishes",
        description:
          "A curated collection of our most iconic and requested plates, each a testament to our culinary excellence.",
        items: [
          {
            name: "Dry-Aged Tomahawk Steak",
            price: 37.83,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Traditional Family Paella",
            price: 24.44,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Modernist Foie Gras Sphere with Rhubarb Gel",
            price: 35.15,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Korean BBQ Short Ribs with Kimchi Rice",
            price: 37.3,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Celebrity Favorite Lobster Dish",
            price: 29.68,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Flambéed Tableside Specialty",
            price: 34.67,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Japanese A5 Wagyu with Ponzu Butter",
            price: 32.19,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Chef's Specials",
        description:
          "Seasonal offerings crafted by our executive chef, available for a limited time to reflect peak freshness.",
        items: [
          {
            name: "Organic Aromatic Collaborative Limited Edition Special",
            price: 29.62,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Mouthwatering Black Garlic Marinated Octopus",
            price: 39.9,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Handcrafted Pan-seared Herb-Crusted Rack of Lamb",
            price: 26.3,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Authentic Appetizing Seared Foie Gras with Fig Compote",
            price: 31.15,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Authentic Steamed Roasted Quail with Truffle Jus",
            price: 30.18,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Appetizers",
        description:
          "Crafted to excite the palate, our starters are a perfect introduction to the world of Japanese.",
        items: [
          {
            name: "Stuffed Peppers",
            price: 15.18,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Edamame",
            price: 9.66,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Stuffed Avocado",
            price: 11.68,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Dumplings",
            price: 15.47,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Cheese Platter",
            price: 12.85,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Mezze Platter",
            price: 9.96,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Mini Quesadillas",
            price: 12.24,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Cheese Nachos",
            price: 12.01,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Soups",
        description:
          "Classic and modern takes on soup that reflect our culinary roots and creative spirit.",
        items: [
          {
            name: "Minestrone",
            price: 11.24,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Clam Chowder",
            price: 12.83,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Zuppa Toscana",
            price: 12.05,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Turkey and Wild Rice Soup",
            price: 8.55,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
        ],
      },
      {
        name: "Salads",
        description:
          "A seasonal showcase of the garden’s bounty—thoughtfully composed and artfully arranged.",
        items: [
          {
            name: "Pear and Gorgonzola Salad",
            price: 15.53,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Southwest Black Bean Salad",
            price: 9.7,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Caprese Salad",
            price: 13.9,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Lentil and Feta Salad",
            price: 11.99,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Mediterranean Chopped Salad",
            price: 15,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Main Courses",
        description:
          "From the kitchen to your table, our mains are crafted to delight and satisfy.",
        items: [
          {
            name: "Deluxe Luscious Spaghetti Bolognese",
            price: 31.37,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Gourmet Pan-seared Lamb Chops",
            price: 22.2,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: true,
          },
          {
            name: "Fresh Sautéed Salmon",
            price: 22.25,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Hearty Sizzling Stuffed Zucchini Boats",
            price: 22.06,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Homestyle Flaky Thai Curry",
            price: 23.65,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Marinated Eggplant Parmesan",
            price: 24.67,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Hearty Pan-seared Stir-fry",
            price: 26.35,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Aromatic Shakshuka",
            price: 24.94,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: false,
            isKosher: false,
          },
        ],
      },
      {
        name: "Seafood Specialties",
        description:
          "Crafted with care, our seafood offerings are a testament to our commitment to quality.",
        items: [
          {
            name: "Premium Smoked Grilled Lobster with Lemon Butter",
            price: 32.38,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Homestyle Aromatic Oysters Rockefeller with Pernod Cream",
            price: 32.43,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Traditional Spiced Shrimp Scampi over Linguine",
            price: 25.14,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Gourmet Creamy Seafood Alfredo with Spinach Fettuccine",
            price: 31.41,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Deluxe Luscious Alaskan King Crab Legs with Drawn Butter",
            price: 24.03,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
        ],
      },
      {
        name: "Side Dishes",
        description:
          "Crafted to enhance your meal, these sides are a celebration of Japanese flavors.",
        items: [
          {
            name: "Fresh Sizzling Herbed Bulgur Wheat with Lemon",
            price: 6.42,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Homestyle Tangy French Fries",
            price: 7.43,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Pan-seared Israeli Couscous with Roasted Tomatoes",
            price: 8.56,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Classic Succulent Creamy Colcannon (Irish Potato Mash)",
            price: 6.15,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Crispy Mashed Potatoes",
            price: 5.3,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Pan-seared Wild Mushroom Risotto",
            price: 9.8,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
        ],
      },
      {
        name: "Non-Alcoholic Beverages",
        description:
          "Refreshing selections ranging from house-made sodas to premium juices.",
        items: [
          {
            name: "Juice",
            price: 6.71,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Smoothie",
            price: 5.95,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Tea",
            price: 4.2,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Hot Chocolate",
            price: 5.15,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Soda",
            price: 5.66,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Iced Tea",
            price: 5.25,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
  {
    title: "Dessert Menu",
    description: "Complete your meal with our delicious dessert selection",
    category: [
      {
        name: "Baked Goods",
        description:
          "From flaky croissants to rich breads—our oven's finest, ready to enjoy.",
        items: [
          {
            name: "Croissants",
            price: 10.94,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Cupcakes",
            price: 10.48,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Tiramisu",
            price: 8.46,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Donuts",
            price: 9.75,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Cheesecake",
            price: 10.57,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Frozen Desserts",
        description:
          "From rich gelatos to refreshing sorbets, our frozen desserts are a must-try.",
        items: [
          {
            name: "Fresh Zingy Frozen Cheesecake",
            price: 7.09,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Luscious Granita",
            price: 10.21,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Hearty Zesty Frozen Pudding",
            price: 8.53,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Flavorful Kulfi",
            price: 11.89,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Homestyle Flaky Sorbet",
            price: 11.53,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
  {
    title: "Drinks Menu",
    description: "Our bartenders' fine creations to complete your meal",
    category: [
      {
        name: "Signature Cocktails",
        description:
          "Each cocktail tells a story—bold, balanced, and unmistakably ours.",
        items: [
          {
            name: "Seasonal Zesty Mai Tai",
            price: 12.91,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Premium Enticing Mojito",
            price: 14.04,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Flaky Martini",
            price: 12.51,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Sautéed Manhattan",
            price: 15.8,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Sweet Negroni",
            price: 11.72,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: true,
          },
          {
            name: "Authentic Crunchy Margarita",
            price: 13.16,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Authentic Sweet Old Fashioned",
            price: 13.24,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
        ],
      },
      {
        name: "Wine Selection",
        description:
          "Explore our wine list, where each bottle is a testament to craftsmanship and tradition.",
        items: [
          {
            name: "Moscato",
            price: 11.76,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Pinot Grigio",
            price: 8.88,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Albariño",
            price: 13.51,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Nebbiolo",
            price: 13.23,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Marsanne",
            price: 10.66,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Pinot Noir",
            price: 12.83,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Spirits and Liqueurs",
        description:
          "Crafted for those who appreciate the finer things in life—our spirits selection.",
        items: [
          {
            name: "Bourbon",
            price: 16.22,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Limoncello",
            price: 13.69,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Kahlúa",
            price: 11.44,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Aquavit",
            price: 10.42,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Gin",
            price: 14.88,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
];
