import { Restaurant } from "@/lib/types/types";

export const kyotoRestaurants: Restaurant[] = [
  {
    name: "Kyoto Ristorante",
    description:
      "Located close to the historic district, this Japanese restaurant delights with its fresh produce and friendly service.",
    cuisine: "Japanese",
    priceRange: "$$",
    rating: 4.2,
    openingHours: {
      monday: "10:00-22:00",
      tuesday: "10:00-19:00",
      wednesday: "11:00-19:00",
      thursday: "11:00-22:00",
      friday: "11:00-21:00",
      saturday: "10:00-19:00",
      sunday: "11:00-21:00",
    },
    contactInfo: {
      contactNumber: "+1-555-714-1901",
      contactEmail: "office@higashiyamainnkyoto.com",
    },
    isVegetarianFriendly: false,
    isVeganFriendly: false,
    isGlutenFreeFriendly: false,
    isHalalFriendly: false,
    isKosherFriendly: false,
    isFineDining: false,
    isAdultOnly: false,
    isIndoorSeating: true,
    isReservationsAccepted: true,
    isRomantic: true,
    isPopular: true,
  },
  {
    name: "Matcha Bar & Kitchen",
    description:
      "Located close to the city museum, this Asian restaurant delights with its regional wines and live street performances.",
    cuisine: "Asian",
    priceRange: "$$",
    rating: 4.1,
    openingHours: {
      monday: "11:00-20:00",
      tuesday: "10:00-20:00",
      wednesday: "11:00-19:00",
      thursday: "11:00-20:00",
      friday: "11:00-22:00",
      saturday: "11:00-21:00",
      sunday: "10:00-20:00",
    },
    contactInfo: {
      contactNumber: "+1-555-463-6148",
      contactEmail: "office@higashiyamataqueriakyoto.com",
    },
    isVegetarianFriendly: false,
    isVeganFriendly: false,
    isGlutenFreeFriendly: false,
    isHalalFriendly: false,
    isKosherFriendly: false,
    isFineDining: false,
    isAdultOnly: false,
    isIndoorSeating: true,
    isReservationsAccepted: true,
    isRomantic: false,
    isPopular: true,
  },
  {
    name: "Kaiseki Rotisserie",
    description:
      "A culinary gem serving Japanese specialties including heritage recipes, where guests enjoy charming streetscapes in the heart of the city.",
    cuisine: "Japanese",
    priceRange: "$$",
    rating: 4.1,
    openingHours: {
      monday: "9:00-21:00",
      tuesday: "10:00-21:00",
      wednesday: "Closed",
      thursday: "10:00-19:00",
      friday: "11:00-21:00",
      saturday: "10:00-21:00",
      sunday: "10:00-20:00",
    },
    contactInfo: {
      contactNumber: "+1-555-880-8994",
      contactEmail: "office@higashiyamagelateriakyoto.com",
    },
    isVegetarianFriendly: false,
    isVeganFriendly: false,
    isGlutenFreeFriendly: true,
    isHalalFriendly: false,
    isKosherFriendly: false,
    isFineDining: false,
    isAdultOnly: false,
    isIndoorSeating: true,
    isReservationsAccepted: true,
    isRomantic: true,
    isPopular: false,
  },
  {
    name: "Gion Eatery",
    description:
      "This popular Italian establishment combines traditional recipes and fresh produce, all served in a unique setting with live street performances.",
    cuisine: "Italian",
    priceRange: "$$",
    rating: 4.7,
    openingHours: {
      monday: "10:00-21:00",
      tuesday: "11:00-21:00",
      wednesday: "9:00-22:00",
      thursday: "9:00-19:00",
      friday: "10:00-21:00",
      saturday: "9:00-22:00",
      sunday: "10:00-22:00",
    },
    contactInfo: {
      contactNumber: "+1-555-575-6177",
      contactEmail: "office@zenramen-yakyoto.com",
    },
    isVegetarianFriendly: false,
    isVeganFriendly: false,
    isGlutenFreeFriendly: true,
    isHalalFriendly: false,
    isKosherFriendly: true,
    isFineDining: false,
    isAdultOnly: false,
    isIndoorSeating: true,
    isReservationsAccepted: true,
    isRomantic: false,
    isPopular: true,
  },
  {
    name: "Torii Enoteca",
    description:
      "A charming Asian restaurant near the city museum, offering farm-to-table meals and other local favorites in a setting with beautiful decor.",
    cuisine: "Asian",
    priceRange: "$$",
    rating: 4.2,
    openingHours: {
      monday: "9:00-20:00",
      tuesday: "9:00-19:00",
      wednesday: "10:00-19:00",
      thursday: "10:00-20:00",
      friday: "11:00-21:00",
      saturday: "11:00-21:00",
      sunday: "10:00-19:00",
    },
    contactInfo: {
      contactNumber: "+1-555-430-2815",
      contactEmail: "office@bambooprovisionskyoto.com",
    },
    isVegetarianFriendly: false,
    isVeganFriendly: false,
    isGlutenFreeFriendly: true,
    isHalalFriendly: true,
    isKosherFriendly: true,
    isFineDining: false,
    isAdultOnly: true,
    isIndoorSeating: true,
    isReservationsAccepted: true,
    isRomantic: false,
    isPopular: true,
  },
  {
    name: "Blossom House",
    description:
      "This popular French establishment combines traditional recipes and gourmet street food, all served in a unique setting with boutique shops.",
    cuisine: "French",
    priceRange: "$$$",
    rating: 4.3,
    openingHours: {
      monday: "9:00-21:00",
      tuesday: "Closed",
      wednesday: "9:00-19:00",
      thursday: "11:00-21:00",
      friday: "9:00-22:00",
      saturday: "9:00-22:00",
      sunday: "10:00-22:00",
    },
    contactInfo: {
      contactNumber: "+1-555-845-2112",
      contactEmail: "support@matchasupperclubkyoto.com",
    },
    isVegetarianFriendly: false,
    isVeganFriendly: false,
    isGlutenFreeFriendly: true,
    isHalalFriendly: true,
    isKosherFriendly: false,
    isFineDining: true,
    isAdultOnly: false,
    isIndoorSeating: true,
    isReservationsAccepted: true,
    isRomantic: true,
    isPopular: true,
  },
  {
    name: "Nishiki Dining Room",
    description:
      "Located close to the waterfront, this Japanese restaurant delights with its farm-to-table meals and seasonal floral displays.",
    cuisine: "Japanese",
    priceRange: "$$$",
    rating: 4.2,
    openingHours: {
      monday: "11:00-19:00",
      tuesday: "11:00-21:00",
      wednesday: "10:00-20:00",
      thursday: "11:00-19:00",
      friday: "10:00-22:00",
      saturday: "11:00-19:00",
      sunday: "11:00-22:00",
    },
    contactInfo: {
      contactNumber: "+1-555-972-3631",
      contactEmail: "support@fushimirawbarkyoto.com",
    },
    isVegetarianFriendly: false,
    isVeganFriendly: false,
    isGlutenFreeFriendly: true,
    isHalalFriendly: true,
    isKosherFriendly: false,
    isFineDining: true,
    isAdultOnly: false,
    isIndoorSeating: false,
    isReservationsAccepted: true,
    isRomantic: true,
    isPopular: true,
  },
  {
    name: "Shrine Gallery",
    description:
      "Located close to the main square, this French restaurant delights with its local ingredients and friendly service.",
    cuisine: "French",
    priceRange: "$$$",
    rating: 4.8,
    openingHours: {
      monday: "Closed",
      tuesday: "10:00-21:00",
      wednesday: "Closed",
      thursday: "11:00-21:00",
      friday: "11:00-22:00",
      saturday: "10:00-19:00",
      sunday: "9:00-20:00",
    },
    contactInfo: {
      contactNumber: "+1-555-984-5832",
      contactEmail: "support@higashiyamaizakayakyoto.com",
    },
    isVegetarianFriendly: false,
    isVeganFriendly: false,
    isGlutenFreeFriendly: false,
    isHalalFriendly: false,
    isKosherFriendly: false,
    isFineDining: true,
    isAdultOnly: false,
    isIndoorSeating: true,
    isReservationsAccepted: true,
    isRomantic: true,
    isPopular: true,
  },
  {
    name: "Fushimi Creperie",
    description:
      "A culinary gem serving Asian specialties including fresh produce, where guests enjoy friendly service in the heart of the city.",
    cuisine: "Asian",
    priceRange: "$$$$",
    rating: 4.7,
    openingHours: {
      monday: "9:00-19:00",
      tuesday: "9:00-19:00",
      wednesday: "10:00-19:00",
      thursday: "9:00-20:00",
      friday: "9:00-22:00",
      saturday: "9:00-19:00",
      sunday: "11:00-22:00",
    },
    contactInfo: {
      contactNumber: "+1-555-834-7868",
      contactEmail: "hi@blossomgastropubkyoto.com",
    },
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: true,
    isHalalFriendly: false,
    isKosherFriendly: false,
    isFineDining: true,
    isAdultOnly: false,
    isIndoorSeating: true,
    isReservationsAccepted: true,
    isRomantic: false,
    isPopular: false,
  },
  {
    name: "Shrine Gathering",
    description:
      "Located close to central park, this French restaurant delights with its seasonal specialties and ambient lighting.",
    cuisine: "French",
    priceRange: "$$$$",
    rating: 4.2,
    openingHours: {
      monday: "11:00-19:00",
      tuesday: "11:00-20:00",
      wednesday: "9:00-20:00",
      thursday: "11:00-20:00",
      friday: "11:00-20:00",
      saturday: "Closed",
      sunday: "9:00-19:00",
    },
    contactInfo: {
      contactNumber: "+1-555-220-4121",
      contactEmail: "customerservice@imperialcommissarykyoto.com",
    },
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: false,
    isHalalFriendly: false,
    isKosherFriendly: false,
    isFineDining: true,
    isAdultOnly: false,
    isIndoorSeating: true,
    isReservationsAccepted: true,
    isRomantic: false,
    isPopular: false,
  },
  {
    name: "Shrine Cantina",
    description:
      "A charming Japanese restaurant near the main square, offering artisanal creations and other local favorites in a setting with friendly service.",
    cuisine: "Japanese",
    priceRange: "$$$",
    rating: 4.4,
    openingHours: {
      monday: "9:00-21:00",
      tuesday: "9:00-19:00",
      wednesday: "9:00-20:00",
      thursday: "9:00-20:00",
      friday: "Closed",
      saturday: "9:00-21:00",
      sunday: "11:00-19:00",
    },
    contactInfo: {
      contactNumber: "+1-555-950-5602",
      contactEmail: "help@blossomnoodlebarkyoto.com",
    },
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: false,
    isHalalFriendly: false,
    isKosherFriendly: false,
    isFineDining: false,
    isAdultOnly: false,
    isIndoorSeating: true,
    isReservationsAccepted: true,
    isRomantic: true,
    isPopular: true,
  },
  {
    name: "Bamboo Grand Cafe",
    description:
      "Experience authentic Chinese cuisine with a local twist, featuring gourmet street food served in an atmosphere of boutique shops overlooking the river promenade.",
    cuisine: "Chinese",
    priceRange: "$$$",
    rating: 4,
    openingHours: {
      monday: "9:00-19:00",
      tuesday: "11:00-19:00",
      wednesday: "9:00-22:00",
      thursday: "10:00-19:00",
      friday: "10:00-21:00",
      saturday: "10:00-20:00",
      sunday: "10:00-20:00",
    },
    contactInfo: {
      contactNumber: "+1-555-499-8436",
      contactEmail: "reception@gionlocalkyoto.com",
    },
    isVegetarianFriendly: false,
    isVeganFriendly: false,
    isGlutenFreeFriendly: false,
    isHalalFriendly: false,
    isKosherFriendly: false,
    isFineDining: false,
    isAdultOnly: false,
    isIndoorSeating: true,
    isReservationsAccepted: false,
    isRomantic: false,
    isPopular: false,
  },
  {
    name: "Gion Dining Hall",
    description:
      "A culinary gem serving Italian specialties including farm-to-table meals, where guests enjoy boutique shops in the heart of the city.",
    cuisine: "Italian",
    priceRange: "$$$",
    rating: 4.7,
    openingHours: {
      monday: "10:00-22:00",
      tuesday: "11:00-21:00",
      wednesday: "11:00-21:00",
      thursday: "Closed",
      friday: "10:00-22:00",
      saturday: "11:00-22:00",
      sunday: "10:00-22:00",
    },
    contactInfo: {
      contactNumber: "+1-555-487-7636",
      contactEmail: "reception@blossomgardenkyoto.com",
    },
    isVegetarianFriendly: false,
    isVeganFriendly: false,
    isGlutenFreeFriendly: false,
    isHalalFriendly: false,
    isKosherFriendly: false,
    isFineDining: false,
    isAdultOnly: false,
    isIndoorSeating: true,
    isReservationsAccepted: true,
    isRomantic: false,
    isPopular: true,
  },
];
