import { RestaurantMenu } from "@/lib/types/types";

/**
 * Menu data for Middle Eastern Salumeria in paris
 */
export const parismiddleEasternSalumeriaMenu: RestaurantMenu[] = [
  {
    title: "Main Course Menu",
    description:
      "Discover our classic interpretation of classic Italian recipes",
    category: [
      {
        name: "Signature Dishes",
        description:
          "Our chef's pride—carefully selected Italian specialties that define our culinary identity, honed through years of experience and passion.",
        items: [
          {
            name: "Traditional Family Paella",
            price: 34.26,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Legendary Prime Rib",
            price: 24.23,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Sous Vide Perfected Wagyu",
            price: 29.68,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Black Garlic Glazed Beef Tenderloin",
            price: 28.45,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Japanese A5 Wagyu with Ponzu Butter",
            price: 34.89,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Celebrity Favorite Lobster Dish",
            price: 25.81,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Award-Winning Seafood Boil",
            price: 29.63,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Chef's Specials",
        description:
          "Inspired by nature, mood, and season—our chef’s ever-evolving vision on a plate.",
        items: [
          {
            name: "Deconstructed Classic with Modern Technique",
            price: 24.51,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Chef's Tasting Menu Experience",
            price: 27.69,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Cedar Plank Salmon",
            price: 38.56,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Hand-Selected Wine Pairing Experience",
            price: 24.63,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Whole Animal Butchery Showcase",
            price: 31.69,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Appetizers",
        description:
          "Crafted to excite the palate, our starters are a perfect introduction to the world of Italian.",
        items: [
          {
            name: "Deluxe Savory Calamari",
            price: 14.38,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Crunchy Cheese Platter",
            price: 13.42,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Golden Antipasto Platter",
            price: 11.56,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Traditional Fried Stuffed Mushrooms",
            price: 11.52,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Golden Zucchini Fries",
            price: 10.68,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Seasonal Delectable Baba Ganoush",
            price: 10.27,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Irresistible Stuffed Jalapeños",
            price: 8.77,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Seasonal Flavorful Onion Rings",
            price: 10.08,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Soups",
        description:
          "Each bowl is a journey through the heart of Italian, crafted with care and expertise.",
        items: [
          {
            name: "Peanut Soup (West African)",
            price: 8.63,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Borscht",
            price: 9.42,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Gazpacho",
            price: 12.9,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Tomato Soup",
            price: 12.14,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Salads",
        description:
          "Crafted with care, our salads are a celebration of freshness and flavor.",
        items: [
          {
            name: "Broccoli Crunch Salad",
            price: 10.06,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Waldorf Salad",
            price: 12.73,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Chickpea Salad",
            price: 13.99,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Watermelon Feta Salad",
            price: 9.04,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Roasted Beet and Goat Cheese Salad",
            price: 9.94,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
        ],
      },
      {
        name: "Main Courses",
        description:
          "Timeless classics and innovative creations that highlight the best of Italian.",
        items: [
          {
            name: "Pasta Primavera",
            price: 22.37,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Ramen",
            price: 25.92,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Coq au Vin",
            price: 19.59,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Grilled Tofu",
            price: 20.62,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Pulled Pork Sandwich",
            price: 26.11,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: true,
          },
          {
            name: "Katsu Curry",
            price: 27.52,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Biryani",
            price: 27.02,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fajitas",
            price: 25.18,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Seafood Specialties",
        description:
          "Expertly prepared seafood that highlights the natural flavors of the ocean.",
        items: [
          {
            name: "Miso-Marinated Chilean Sea Bass",
            price: 32.92,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Blackened Mahi-Mahi with Pineapple Salsa",
            price: 34.73,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Steamed Littleneck Clams in Garlic Broth",
            price: 28.4,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Basa Fillet with Dill Cream Sauce",
            price: 31.12,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Grilled Spanish Octopus with Smoked Paprika",
            price: 30.91,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
        ],
      },
      {
        name: "Side Dishes",
        description:
          "Flavorful companions that round out your meal with harmony and flair.",
        items: [
          {
            name: "Warm Buttermilk Dinner Rolls",
            price: 8.5,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Truffle Parmesan Fries",
            price: 6.92,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Steamed Jasmine Rice",
            price: 5.08,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Soft Polenta with Parmesan",
            price: 5.51,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "French Fries",
            price: 5.48,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Roasted Brussels Sprouts with Balsamic Glaze",
            price: 6.3,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Non-Alcoholic Beverages",
        description:
          "Bright and revitalizing beverages for all ages and preferences.",
        items: [
          {
            name: "Gourmet Luscious Lemonade",
            price: 6.38,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Smoked Coffee",
            price: 6.61,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Handcrafted Wholesome Hot Chocolate",
            price: 4.87,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Hearty Grilled Juice",
            price: 4.11,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Seasonal Hearty Milkshake",
            price: 7.34,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Gourmet Golden Water",
            price: 7.81,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
  {
    title: "Dessert Menu",
    description: "Satisfy your sweet tooth with our classic treats",
    category: [
      {
        name: "Baked Goods",
        description:
          "A selection of sweet and savory baked delights, crafted with love and care.",
        items: [
          {
            name: "Cheesecake",
            price: 7.66,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Pumpkin Pie",
            price: 9.25,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Custard Tart",
            price: 10.4,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Macarons",
            price: 6.32,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Banana Bread",
            price: 9.46,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Frozen Desserts",
        description:
          "Indulge in our selection of frozen delights, perfect for any time of year.",
        items: [
          {
            name: "Authentic Herbed Granita",
            price: 10.66,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Authentic Crispy Frozen Yogurt",
            price: 8.79,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "House Special Baked Ice Cream Cake",
            price: 10.12,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Grilled Sorbet",
            price: 8.81,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Pan-seared Frozen Custard",
            price: 7.99,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
  {
    title: "Drinks Menu",
    description:
      "Enjoy refreshing cocktails designed to pair effortlessly with our seasonal menu",
    category: [
      {
        name: "Signature Cocktails",
        description:
          "Custom-designed drinks created exclusively by our mixologists to complement our menu.",
        items: [
          {
            name: "Authentic Smoked Martini",
            price: 15,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Gourmet Herbed Negroni",
            price: 11.32,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Gourmet Grilled Whiskey Sour",
            price: 11.47,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "House Special Pan-seared Bloody Mary",
            price: 14.14,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Creamy Mojito",
            price: 12.23,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Fresh Grilled Margarita",
            price: 12.28,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Aromatic Old Fashioned",
            price: 14.77,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Wine Selection",
        description:
          "An expertly curated wine list featuring standout bottles from around the globe.",
        items: [
          {
            name: "Gourmet Creamy Viognier",
            price: 10.21,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Stuffed Sangiovese",
            price: 10.89,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Seasonal Creamy Chardonnay",
            price: 13.7,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Seasonal Delicious Roussanne",
            price: 10.33,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Handcrafted Appetizing Gewürztraminer",
            price: 11.85,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Hearty Fried Petit Verdot",
            price: 8.65,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Spirits and Liqueurs",
        description:
          "From classic cocktails to sipping spirits, our bar is stocked with quality and character.",
        items: [
          {
            name: "Gourmet Sweet Midori",
            price: 17.28,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Handcrafted Sweet Frangelico",
            price: 10.31,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Classic Satisfying Gin",
            price: 11.67,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Handcrafted Creamy Drambuie",
            price: 14.78,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Aromatic Aquavit",
            price: 13.39,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
];
