import { RestaurantMenu } from "@/lib/types/types";

/**
 * Menu data for Italian Juice Bar in melbourne
 */
export const melbourneitalianJuiceBarMenu: RestaurantMenu[] = [
  {
    title: "Main Course Menu",
    description:
      "Elevated Australian dishes showcasing our most homestyle culinary ideas",
    category: [
      {
        name: "Signature Dishes",
        description:
          "Exclusive, time-tested recipes that highlight the heart and soul of authentic Australian cooking.",
        items: [
          {
            name: "Signature Truffle Pasta with Aged Pecorino",
            price: 32.37,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Heritage Recipe Lamb Shank",
            price: 34.76,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Chef’s Wild Game Selection",
            price: 30.45,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Flambéed Tableside Specialty",
            price: 35.52,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Caribbean-Style Jerk Duck with Mango Slaw",
            price: 25,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Executive Chef's Daily Inspiration Entrée",
            price: 28.26,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Captain's Favorite Seafood Tower",
            price: 32.15,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
        ],
      },
      {
        name: "Chef's Specials",
        description:
          "A rotating selection of dishes that highlight the chef's creativity and passion for Australian.",
        items: [
          {
            name: "Grilled Venison with Juniper Berry Sauce",
            price: 37.07,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Modern Interpretation of Regional Classic",
            price: 39.1,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Pan-Seared Scallops with Citrus Beurre Blanc",
            price: 34.94,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Collaborative Limited Edition Special",
            price: 31.1,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Smoked and Slow-Roasted Heritage Meat",
            price: 39.99,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
        ],
      },
      {
        name: "Appetizers",
        description:
          "Traditional and reimagined Australian appetizers made for sharing or solo indulgence.",
        items: [
          {
            name: "Spinach Puffs",
            price: 15.57,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Stuffed Peppers",
            price: 14.21,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Mini Quesadillas",
            price: 9.54,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Mini Crab Cakes",
            price: 10.27,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Chicken Satay",
            price: 12.97,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Bruschetta",
            price: 8.52,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Spring Rolls",
            price: 8.6,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Chicken Wings",
            price: 8.24,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
        ],
      },
      {
        name: "Soups",
        description: "Each spoonful offers depth, comfort, and craftsmanship.",
        items: [
          {
            name: "Miso Soup",
            price: 10.09,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Thai Coconut Soup",
            price: 8.53,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Tomato Soup",
            price: 8.87,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Zuppa Toscana",
            price: 11.07,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Salads",
        description:
          "Balanced, clean, and flavorful options featuring local and organic ingredients where possible.",
        items: [
          {
            name: "Coleslaw",
            price: 9.15,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Watermelon Feta Salad",
            price: 13.83,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Caprese Salad",
            price: 11.07,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Roasted Vegetable Salad",
            price: 12.65,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Roasted Beet and Goat Cheese Salad",
            price: 14.42,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: true,
          },
        ],
      },
      {
        name: "Main Courses",
        description:
          "A journey through Australian flavors, expertly prepared and beautifully presented.",
        items: [
          {
            name: "Classic Savory Pesto Pasta",
            price: 31.59,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Mouthwatering Salmon",
            price: 26.67,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Seasonal Grilled Jambalaya",
            price: 22.81,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Classic Zesty Mac and Cheese",
            price: 24.61,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Homestyle Stuffed Biryani",
            price: 26.94,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Homestyle Herbed Fajitas",
            price: 22.78,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Organic Flavorful Chicken Parmesan",
            price: 26.91,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Hearty Juicy Beef Burger",
            price: 31.5,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
        ],
      },
      {
        name: "Seafood Specialties",
        description:
          "Fresh, sustainable seafood prepared using timeless Australian traditions.",
        items: [
          {
            name: "Cajun Shrimp and Grits",
            price: 29.74,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Basa Fillet with Dill Cream Sauce",
            price: 30.57,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Steamed Littleneck Clams in Garlic Broth",
            price: 29.49,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Classic British Fish and Chips",
            price: 29.08,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Traditional Provençal Bouillabaisse",
            price: 35.51,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Side Dishes",
        description:
          "Flavor-packed sides made to share—or keep all to yourself.",
        items: [
          {
            name: "Fresh Crunchy Wild Mushroom Risotto",
            price: 8.91,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Classic Pan-seared Grilled Zucchini and Peppers",
            price: 9.66,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Classic Succulent Israeli Couscous with Roasted Tomatoes",
            price: 6.05,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Homestyle Spiced Soft Polenta with Parmesan",
            price: 9.62,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Creamy French Fries",
            price: 9.55,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Deluxe Roasted Sweet Potato Wedges with Smoked Paprika",
            price: 5.68,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Non-Alcoholic Beverages",
        description:
          "Handcrafted drinks designed to hydrate and delight—no spirits necessary.",
        items: [
          {
            name: "Traditional Stuffed Smoothie",
            price: 5.71,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Seasonal Irresistible Lemonade",
            price: 4.74,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Premium Spicy Tea",
            price: 6.55,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Classic Grilled Water",
            price: 7.88,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Hearty Flaky Coffee",
            price: 5.77,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Gourmet Fried Iced Tea",
            price: 4.57,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
  {
    title: "Dessert Menu",
    description: "Indulge in our gooey sweet creations",
    category: [
      {
        name: "Baked Goods",
        description:
          "Each bite tells a story—layered, textured, and baked to perfection.",
        items: [
          {
            name: "Crumb Cake",
            price: 10.44,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Banana Bread",
            price: 8.73,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Pumpkin Pie",
            price: 8.58,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Eclairs",
            price: 10.6,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Cheesecake",
            price: 8.93,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Frozen Desserts",
        description:
          "From creamy gelato to fruity sorbet, our frozen desserts are a must-try.",
        items: [
          {
            name: "Fresh Crunchy Kulfi",
            price: 11.47,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Handcrafted Herbed Frosty",
            price: 7.49,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Zingy Ice Cream",
            price: 9.19,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: true,
          },
          {
            name: "Fresh Zingy Frozen Pie",
            price: 7.33,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Flavorful Ice Cream Cake",
            price: 11,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
  {
    title: "Drinks Menu",
    description:
      "Unwind with our inviting beverages crafted for connoisseurs and casual sippers alike",
    category: [
      {
        name: "Signature Cocktails",
        description:
          "Elevate your evening with our signature cocktails, each a unique expression of flavor.",
        items: [
          {
            name: "Hearty Baked Margarita",
            price: 13.7,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Classic Spiced Mojito",
            price: 13.91,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Gourmet Smoked Mai Tai",
            price: 12.24,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Homestyle Grilled Bloody Mary",
            price: 11.43,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Grilled Manhattan",
            price: 12.34,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Baked Martini",
            price: 12.5,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Flaky Old Fashioned",
            price: 15.88,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Wine Selection",
        description:
          "An expertly curated wine list featuring standout bottles from around the globe.",
        items: [
          {
            name: "Marsanne",
            price: 8.58,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Chenin Blanc",
            price: 10.68,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Pinot Grigio",
            price: 9.57,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Pinot Noir",
            price: 13.79,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Pinot Blanc",
            price: 8.22,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Zinfandel",
            price: 9.31,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Spirits and Liqueurs",
        description:
          "From classic cocktails to sipping spirits, our bar is stocked with quality and character.",
        items: [
          {
            name: "Bourbon",
            price: 14.4,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Limoncello",
            price: 14.38,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Whiskey",
            price: 13.11,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Baileys Irish Cream",
            price: 17.67,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Kahlúa",
            price: 17.93,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
];
