import { RestaurantMenu } from "@/lib/types/types";

/**
 * Menu data for Grand Eatery + Bar in victoria
 */
export const victoriagrandEateryBarMenu: RestaurantMenu[] = [
  {
    title: "Main Course Menu",
    description: "Where flavorful creativity meets timeless French inspiration",
    category: [
      {
        name: "Signature Dishes",
        description:
          "A hand-picked menu selection that reflects the chef’s current inspirations and exceptional skill.",
        items: [
          {
            name: "Flambéed Tableside Specialty",
            price: 35.61,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Seasonal Tasting Platter",
            price: 37.56,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Age-Old Recipe Osso Buco with Gremolata",
            price: 26.48,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Whole Roasted Heritage Chicken",
            price: 34.84,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Secret Recipe Bouillabaisse",
            price: 33.05,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Signature Truffle Pasta with Aged Pecorino",
            price: 35.66,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Celebrity Favorite Lobster Dish",
            price: 28.73,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
        ],
      },
      {
        name: "Chef's Specials",
        description:
          "A hand-picked menu selection that reflects the chef’s current inspirations and exceptional skill.",
        items: [
          {
            name: "Tableside Prepared Tartare",
            price: 37.79,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Seasonal Farm-to-Table Vegetable Plate",
            price: 27.89,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Cedar Plank Salmon",
            price: 30.75,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "High-End Ingredient Showcase",
            price: 35.85,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Duck Confit with Roasted Root Vegetables",
            price: 37.46,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Appetizers",
        description:
          "Mouthwatering previews of what's to come—crafted to tease and please.",
        items: [
          {
            name: "Traditional Comforting Shrimp Cocktail",
            price: 13.01,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Traditional Smoked Caprese Salad",
            price: 15.32,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Traditional Appetizing Samosas",
            price: 8.15,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Gourmet Tangy Spring Rolls",
            price: 14.33,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Premium Herbed Spinach Artichoke Dip",
            price: 11.52,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Hearty Spicy Falafel",
            price: 13.79,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Organic Exquisite Garlic Knots",
            price: 13.03,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Spiced Baba Ganoush",
            price: 10.34,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
        ],
      },
      {
        name: "Soups",
        description:
          "Crafted with care, our soups are a celebration of French flavors and traditions.",
        items: [
          {
            name: "Split Pea Soup",
            price: 9.51,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Beef Stew",
            price: 12.57,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: true,
          },
          {
            name: "Tomato Soup",
            price: 12.16,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Chicken Noodle Soup",
            price: 12.61,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
        ],
      },
      {
        name: "Salads",
        description:
          "Crafted with care, our salads are a celebration of freshness and flavor.",
        items: [
          {
            name: "Spinach Salad",
            price: 9.34,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Caprese Salad",
            price: 15.08,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Orzo Salad",
            price: 15.63,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Mango Avocado Salad",
            price: 10.06,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Broccoli Crunch Salad",
            price: 14,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Main Courses",
        description:
          "From the kitchen to your table, our mains are crafted to delight and satisfy.",
        items: [
          {
            name: "Organic Comforting Paella",
            price: 31.41,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Hearty Tangy Tacos",
            price: 25.07,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Hearty Spicy Seafood Platter",
            price: 30.29,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Tender Shish Kebabs",
            price: 25.54,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: true,
          },
          {
            name: "Premium Juicy Burrito",
            price: 29.29,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Homestyle Satisfying Risotto",
            price: 24.97,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Organic Grilled Bibimbap",
            price: 21.85,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Homestyle Exquisite Fish and Chips",
            price: 21.42,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Seafood Specialties",
        description:
          "From the sea to your plate—each dish is a tribute to the ocean’s bounty.",
        items: [
          {
            name: "Traditional Hearty Pan-Seared Scallops with Pea Purée",
            price: 33.36,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Seasonal Mouthwatering Sushi-Grade Sashimi Platter",
            price: 23.84,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Homestyle Zesty Traditional Provençal Bouillabaisse",
            price: 27.78,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Tangy Stuffed Flounder with Crab and Spinach",
            price: 33.09,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Organic Grilled Alaskan King Crab Legs with Drawn Butter",
            price: 24.12,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Side Dishes",
        description:
          "From roasted vegetables to artisanal grains, our sides are a perfect match for any dish.",
        items: [
          {
            name: "Deluxe Tangy Grilled Asparagus with Lemon Zest",
            price: 7.19,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "House Special Flaky Macaroni and Aged Cheddar",
            price: 6.09,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Traditional Golden Wild Mushroom Risotto",
            price: 6.76,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Sautéed Mashed Potatoes",
            price: 7.7,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Handcrafted Savory Crispy Beer-Battered Onion Rings",
            price: 9.64,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Stuffed Yukon Gold Potato Gratin",
            price: 5.98,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Non-Alcoholic Beverages",
        description:
          "Sophisticated non-alcoholic choices made to complement any dish.",
        items: [
          {
            name: "Coffee",
            price: 6.19,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Juice",
            price: 7.72,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Lemonade",
            price: 6.21,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Iced Tea",
            price: 4.89,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Milkshake",
            price: 7.34,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Soda",
            price: 6.23,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
  {
    title: "Dessert Menu",
    description:
      "Finish on a high note with our crowd-pleasing and memorable sweets",
    category: [
      {
        name: "Baked Goods",
        description:
          "Each bite tells a story—layered, textured, and baked to perfection.",
        items: [
          {
            name: "Pumpkin Pie",
            price: 7.7,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Muffins",
            price: 8.68,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Berry Tart",
            price: 9.61,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Danish Pastries",
            price: 10.6,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Brownies",
            price: 6.31,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Frozen Desserts",
        description:
          "Crafted with the finest ingredients, our frozen desserts are a treat for the senses.",
        items: [
          {
            name: "Fresh Comforting Frozen Banana",
            price: 8.52,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Classic Fried Popsicles",
            price: 9.24,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Organic Flavorful Sherbet",
            price: 8.7,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Handcrafted Appetizing Frozen Fruit Bars",
            price: 9.97,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Handcrafted Creamy Frozen Yogurt",
            price: 7.99,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
  {
    title: "Drinks Menu",
    description:
      "A quality array of beverages specially selected by our sommeliers",
    category: [
      {
        name: "Signature Cocktails",
        description:
          "From reinvented classics to bold new creations, every glass is an experience.",
        items: [
          {
            name: "Negroni",
            price: 10,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Margarita",
            price: 15.63,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Manhattan",
            price: 11.27,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Cosmopolitan",
            price: 12.41,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Mai Tai",
            price: 15.45,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Mojito",
            price: 10.5,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Bloody Mary",
            price: 13.16,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Wine Selection",
        description:
          "An expertly curated wine list featuring standout bottles from around the globe.",
        items: [
          {
            name: "Classic Smoked Roussanne",
            price: 12.98,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Spiced Viognier",
            price: 8.93,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Flaky Vouvray",
            price: 12.7,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Handcrafted Juicy Chenin Blanc",
            price: 11.12,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: true,
          },
          {
            name: "House Special Crispy Albariño",
            price: 8.75,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Hearty Mouthwatering Petit Verdot",
            price: 12.65,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Spirits and Liqueurs",
        description:
          "Crafted for those who appreciate the art of distillation—each pour is a journey.",
        items: [
          {
            name: "Kahlúa",
            price: 14.49,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Pisco",
            price: 16.46,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "St-Germain",
            price: 10.56,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Maraschino",
            price: 15.56,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Scotch",
            price: 13.32,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
];
