import { RestaurantMenu } from "@/lib/types/types";

/**
 * Menu data for Mediterranean Fish House in milan
 */
export const milanmediterraneanFishHouseMenu: RestaurantMenu[] = [
  {
    title: "Main Course Menu",
    description:
      "Our comforting kitchen reimagines Japanese for today’s palate",
    category: [
      {
        name: "Signature Dishes",
        description:
          "Unforgettable signatures that define who we are and what we serve, crafted to perfection.",
        items: [
          {
            name: "Chef's Special Surf and Turf",
            price: 30.19,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Seasonal Tasting Platter",
            price: 33.67,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Signature Truffle Pasta with Aged Pecorino",
            price: 26.18,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Heritage Recipe Lamb Shank",
            price: 36.54,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Seasonal Tasting Menu Experience",
            price: 25.5,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Tableside Carved Chateaubriand",
            price: 31.2,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Crusted Rack of Lamb with Dijon Herb Crust",
            price: 36.89,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Chef's Specials",
        description:
          "A showcase of our chef's creativity, featuring dishes that are as unique as they are delicious.",
        items: [
          {
            name: "Locally Foraged Mushroom Selection",
            price: 33.02,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Signature Spice-Rubbed Protein",
            price: 37.67,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Sous Vide Perfection with Molecular Gastronomy Elements",
            price: 30.93,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Truffle-Infused Filet Mignon",
            price: 31,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: true,
          },
          {
            name: "Freshly Harvested Seasonal Creation",
            price: 38.17,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Appetizers",
        description:
          "Crafted to excite the palate, our starters are a perfect introduction to the world of Japanese.",
        items: [
          {
            name: "Hummus Platter",
            price: 11.42,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Falafel",
            price: 10.86,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Antipasto Platter",
            price: 15.98,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Mini Sliders",
            price: 9.33,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Tuna Tartare",
            price: 14.57,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Potato Skins",
            price: 9.16,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Stuffed Avocado",
            price: 9.67,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Chicken Satay",
            price: 12.92,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: false,
            isKosher: true,
          },
        ],
      },
      {
        name: "Soups",
        description:
          "A comforting range of house-made soups, from clear and delicate broths to rich, hearty bowls.",
        items: [
          {
            name: "Carrot Ginger Soup",
            price: 11.67,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Gazpacho",
            price: 9.54,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Split Pea Soup",
            price: 13.6,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Chicken Noodle Soup",
            price: 10.76,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
        ],
      },
      {
        name: "Salads",
        description:
          "Lively salads combining texture, temperature, and taste for a refreshing start or light meal.",
        items: [
          {
            name: "Nicoise Salad",
            price: 14.3,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Arugula Salad",
            price: 11.35,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Cucumber Salad",
            price: 10.16,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Quinoa Salad",
            price: 9.89,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Watermelon Feta Salad",
            price: 14.98,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Main Courses",
        description:
          "Crafted with the finest ingredients, our mains are a testament to our culinary philosophy.",
        items: [
          {
            name: "House Special Savory Beef Burger",
            price: 27.45,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: true,
          },
          {
            name: "Homestyle Herbed Lasagna",
            price: 19.35,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Organic Juicy Chili con Carne",
            price: 20.28,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Grilled Eggplant Parmesan",
            price: 26.49,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Handcrafted Crunchy Korma",
            price: 28.11,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Seasonal Spiced Chicken Parmesan",
            price: 24.77,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Deluxe Zesty Lentil Stew",
            price: 24.89,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Sweet Spaghetti Bolognese",
            price: 30,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
        ],
      },
      {
        name: "Seafood Specialties",
        description:
          "From raw bar delicacies to grilled perfection—our tribute to the ocean.",
        items: [
          {
            name: "Classic Tangy Cedar Plank Roasted Salmon",
            price: 27.34,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Traditional Creamy New England Lobster Roll",
            price: 27.44,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Hearty Delectable Classic British Fish and Chips",
            price: 32.75,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Organic Steamed Lobster Thermidor with Gruyère Crust",
            price: 35.65,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Organic Sizzling Mussels Mariniere in White Wine",
            price: 34.76,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
        ],
      },
      {
        name: "Side Dishes",
        description:
          "Crafted to enhance your meal, these sides are a celebration of Japanese flavors.",
        items: [
          {
            name: "Hearty Flaky Cauliflower Gratin with Gruyère",
            price: 9.3,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Juicy Sweet Corn and Cheddar Fritters",
            price: 9.12,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Classic Herbed Wild Mushroom Risotto",
            price: 9.05,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Premium Crunchy Garlic Bread with Herb Butter",
            price: 7.76,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Tangy Sweet Potato Wedges with Smoked Paprika",
            price: 9.12,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Steamed Fragrant Basmati Rice Pilaf",
            price: 5.2,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Non-Alcoholic Beverages",
        description:
          "Bright, invigorating options that cleanse the palate and refresh the spirit.",
        items: [
          {
            name: "House Special Hearty Lemonade",
            price: 4.48,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "House Special Steamed Smoothie",
            price: 7.27,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Classic Succulent Juice",
            price: 5.81,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Steamed Soda",
            price: 7.98,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Zesty Milkshake",
            price: 5.73,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Handcrafted Delicious Iced Tea",
            price: 7.64,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
  {
    title: "Dessert Menu",
    description:
      "A comforting selection of desserts that will satisfy your cravings",
    category: [
      {
        name: "Baked Goods",
        description:
          "Artisanal baked items showcasing skill, tradition, and a touch of creativity.",
        items: [
          {
            name: "Shortbread",
            price: 9.84,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Red Velvet Cake",
            price: 7.49,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Custard Tart",
            price: 6.09,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Danish Pastries",
            price: 8.82,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Treacle Tart",
            price: 6.41,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Frozen Desserts",
        description:
          "From rich gelatos to refreshing sorbets, our frozen desserts are a must-try.",
        items: [
          {
            name: "Frozen Pie",
            price: 9.94,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Snow Cone",
            price: 9.54,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Ice Cream Cake",
            price: 9.28,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Frozen Yogurt",
            price: 8.07,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Baked Alaska",
            price: 11.44,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
  {
    title: "Drinks Menu",
    description:
      "A inviting selection of wines, beers, and spirits to suit every taste",
    category: [
      {
        name: "Signature Cocktails",
        description:
          "A selection of signature drinks that reflect our culinary philosophy and creativity.",
        items: [
          {
            name: "Mojito",
            price: 13.01,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Mai Tai",
            price: 12.25,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Bloody Mary",
            price: 11.52,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Whiskey Sour",
            price: 15.31,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Old Fashioned",
            price: 13.3,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Negroni",
            price: 10.63,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Margarita",
            price: 11.56,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Wine Selection",
        description:
          "Explore our wine list, where each bottle is a testament to craftsmanship and tradition.",
        items: [
          {
            name: "Moscato",
            price: 12.66,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Chardonnay",
            price: 8.71,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Cabernet Sauvignon",
            price: 10.5,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Torrontés",
            price: 11.73,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Pinot Blanc",
            price: 12.66,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Zinfandel",
            price: 9.05,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Spirits and Liqueurs",
        description:
          "For aficionados and explorers alike—top-shelf selections with depth and pedigree.",
        items: [
          {
            name: "Traditional Smoked Frangelico",
            price: 16.45,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Classic Braised Campari",
            price: 15.04,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Steamed Tequila",
            price: 14.77,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Enticing Bénédictine",
            price: 11.13,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Golden Kahlúa",
            price: 11.61,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
];
