import { RestaurantMenu } from "@/lib/types/types";

/**
 * Menu data for Royal Social in dubrovnik
 */
export const dubrovnikroyalSocialMenu: RestaurantMenu[] = [
  {
    title: "Main Course Menu",
    description:
      "An immersive dining experience defined by tasty American cuisine",
    category: [
      {
        name: "Signature Dishes",
        description:
          "House favorites that have stood the test of time and showcase our refined approach to American cuisine.",
        items: [
          {
            name: "Homestyle Zesty Captain's Favorite Seafood Tower",
            price: 24.02,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Classic Grilled Tableside Carved Chateaubriand",
            price: 30.01,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Handcrafted Spicy Founder's Family Recipe Pasta",
            price: 32.55,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Traditional Flaky Chef's Special Surf and Turf",
            price: 30.91,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Homestyle Creamy Japanese A5 Wagyu with Ponzu Butter",
            price: 26.57,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Organic Steamed Korean BBQ Short Ribs with Kimchi Rice",
            price: 25.08,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: false,
            isKosher: true,
          },
          {
            name: "Deluxe Steamed Heritage Recipe Lamb Shank",
            price: 24.35,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: true,
          },
        ],
      },
      {
        name: "Chef's Specials",
        description:
          "Crafted daily based on what’s freshest and most inspiring at the market.",
        items: [
          {
            name: "Premium Marinated Cast Iron Seafood Presentation",
            price: 24.19,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Crispy Signature Spice-Rubbed Protein",
            price: 39.72,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Homestyle Succulent Smoked and Slow-Roasted Heritage Meat",
            price: 27.72,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Premium Mouthwatering Slow-Roasted Prime Rib",
            price: 26.57,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Crispy Chef's Tasting Menu Experience",
            price: 32.66,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: false,
            isKosher: true,
          },
        ],
      },
      {
        name: "Appetizers",
        description:
          "Mouthwatering previews of what's to come—crafted to tease and please.",
        items: [
          {
            name: "Shrimp Cocktail",
            price: 14.09,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Mini Crab Cakes",
            price: 9.5,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Lettuce Wraps",
            price: 10.03,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Ceviche",
            price: 10.71,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Mini Quesadillas",
            price: 8.82,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Prawn Cocktail",
            price: 13.47,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Antipasto Platter",
            price: 9.61,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Onion Rings",
            price: 14.62,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Soups",
        description:
          "Each bowl is a journey through the heart of American, crafted with care and expertise.",
        items: [
          {
            name: "Italian Wedding Soup",
            price: 8.3,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Tomato Soup",
            price: 7.39,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Tortilla Soup",
            price: 9.89,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Carrot Ginger Soup",
            price: 10.11,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Salads",
        description:
          "Lively salads combining texture, temperature, and taste for a refreshing start or light meal.",
        items: [
          {
            name: "Spinach Salad",
            price: 13.26,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Nicoise Salad",
            price: 10.9,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Southwest Black Bean Salad",
            price: 9.73,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Chickpea Salad",
            price: 9.51,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Cobb Salad",
            price: 13.11,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Main Courses",
        description:
          "Each dish is a culinary journey, showcasing the richness of American traditions.",
        items: [
          {
            name: "Fresh Satisfying Steak",
            price: 31.98,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Deluxe Smoked Gnocchi",
            price: 31.18,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Luscious Pesto Pasta",
            price: 23.65,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Spiced Shish Kebabs",
            price: 20,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Seasonal Hearty Pho",
            price: 26.81,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Marinated Lentil Stew",
            price: 26.28,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: true,
          },
          {
            name: "Premium Braised Chili con Carne",
            price: 19.43,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "House Special Delectable Quiche",
            price: 23.95,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Seafood Specialties",
        description:
          "From raw bar selections to grilled specialties, our seafood dishes are a must-try.",
        items: [
          {
            name: "Authentic Zesty Mussels Mariniere in White Wine",
            price: 30.78,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Deluxe Aromatic Lemon-Herb Calamari Steak",
            price: 29.73,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Seasonal Baked Shrimp Scampi over Linguine",
            price: 28.66,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Fresh Delectable Traditional Provençal Bouillabaisse",
            price: 33.33,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "House Special Spiced Sushi-Grade Sashimi Platter",
            price: 28.16,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Side Dishes",
        description:
          "Each side is a testament to our commitment to quality and flavor.",
        items: [
          {
            name: "Classic Steamed Fragrant Basmati Rice Pilaf",
            price: 5.35,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Baked Wild Mushroom Risotto",
            price: 8.41,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Tangy Flaky Cheddar and Chive Biscuits",
            price: 7.1,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Gourmet Juicy Green Beans Almondine",
            price: 6.24,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Smoked Charred Broccolini with Garlic Oil",
            price: 6.2,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Delectable Grilled Zucchini and Peppers",
            price: 5.63,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Non-Alcoholic Beverages",
        description:
          "Bright and revitalizing beverages for all ages and preferences.",
        items: [
          {
            name: "Smoothie",
            price: 6.59,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Tea",
            price: 7.64,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Coffee",
            price: 6.26,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Lemonade",
            price: 5.4,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Water",
            price: 5.04,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Milkshake",
            price: 4.95,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
  {
    title: "Dessert Menu",
    description:
      "A warm selection of desserts that celebrate the art of pastry",
    category: [
      {
        name: "Baked Goods",
        description:
          "Each bite tells a story—layered, textured, and baked to perfection.",
        items: [
          {
            name: "Macarons",
            price: 9.36,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Carrot Cake",
            price: 8.43,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Lemon Bars",
            price: 10.66,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Banana Bread",
            price: 7.21,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Soufflé",
            price: 6.84,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Frozen Desserts",
        description:
          "Chilled, house-crafted desserts offering a perfect ending to your meal.",
        items: [
          {
            name: "Baked Alaska",
            price: 9.79,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Sorbet",
            price: 7.99,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Gelato",
            price: 7.53,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Ice Cream Sandwich",
            price: 8.76,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Frozen Pudding",
            price: 10.04,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
  {
    title: "Drinks Menu",
    description:
      "A carefully chosen selection of alcoholic beverages to complement your meal",
    category: [
      {
        name: "Signature Cocktails",
        description:
          "Crafted with care, our cocktails are a perfect pairing for any dish on our menu.",
        items: [
          {
            name: "Authentic Grilled Mai Tai",
            price: 14.64,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Fresh Grilled Martini",
            price: 14.58,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Smoked Manhattan",
            price: 10.88,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Hearty Delectable Margarita",
            price: 12.52,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Hearty Tangy Mojito",
            price: 10.06,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Hearty Mouthwatering Old Fashioned",
            price: 13.05,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Gourmet Sweet Negroni",
            price: 15.75,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Wine Selection",
        description:
          "Our sommelier's picks, chosen for balance, terroir expression, and quality.",
        items: [
          {
            name: "Fiano",
            price: 13.43,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Chardonnay",
            price: 10.25,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Pinot Noir",
            price: 10.29,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Sangiovese",
            price: 11.8,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Verdicchio",
            price: 11.09,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Sémillon",
            price: 8.06,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Spirits and Liqueurs",
        description:
          "For aficionados and explorers alike—top-shelf selections with depth and pedigree.",
        items: [
          {
            name: "Amaretto",
            price: 11.76,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Mezcal",
            price: 10.79,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Limoncello",
            price: 16.79,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Cointreau",
            price: 12.99,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Calvados",
            price: 12.6,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
];
