import { RestaurantMenu } from "@/lib/types/types";

/**
 * Menu data for The Public House in dubrovnik
 */
export const dubrovnikthePublicHouseMenu: RestaurantMenu[] = [
  {
    title: "Main Course Menu",
    description:
      "From appetizers to main courses: tasty dishes prepared with passion",
    category: [
      {
        name: "Signature Dishes",
        description:
          "House favorites that have stood the test of time and showcase our refined approach to American cuisine.",
        items: [
          {
            name: "Chef's Special Surf and Turf",
            price: 28.07,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Restaurant's Namesake Signature Entrée",
            price: 25.08,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Modernist Foie Gras Sphere with Rhubarb Gel",
            price: 33.85,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Japanese A5 Wagyu with Ponzu Butter",
            price: 29.14,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Award-Winning Seafood Boil",
            price: 28.24,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Age-Old Recipe Osso Buco with Gremolata",
            price: 32.24,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Crusted Rack of Lamb with Dijon Herb Crust",
            price: 33.62,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
        ],
      },
      {
        name: "Chef's Specials",
        description:
          "Seasonal offerings crafted by our executive chef, available for a limited time to reflect peak freshness.",
        items: [
          {
            name: "Smoked and Slow-Roasted Heritage Meat",
            price: 36.02,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Cast Iron Seafood Presentation",
            price: 29.54,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Chef's Market Inspiration of the Day",
            price: 28.27,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Off-Menu Secret Preparation",
            price: 34.86,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Seared Foie Gras with Fig Compote",
            price: 37,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Appetizers",
        description:
          "Mouthwatering previews of what's to come—crafted to tease and please.",
        items: [
          {
            name: "Hummus Platter",
            price: 9.08,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deviled Eggs",
            price: 9.77,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Edamame",
            price: 14.38,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Prawn Cocktail",
            price: 14.74,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Garlic Bread",
            price: 12.35,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Falafel",
            price: 8.34,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Caprese Salad",
            price: 15.16,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Stuffed Avocado",
            price: 10.33,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Soups",
        description:
          "Daily-prepared soups made from seasonal ingredients and traditional American methods.",
        items: [
          {
            name: "Avgolemono (Greek Lemon Soup)",
            price: 7.63,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Cabbage Soup",
            price: 8.97,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Broccoli Cheddar Soup",
            price: 8,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Butternut Squash Soup",
            price: 11.02,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Salads",
        description:
          "A seasonal showcase of the garden’s bounty—thoughtfully composed and artfully arranged.",
        items: [
          {
            name: "Coleslaw",
            price: 9.4,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Apple Pecan Salad",
            price: 10.88,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Lentil and Feta Salad",
            price: 12.5,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Greek Salad",
            price: 9.93,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Chickpea Salad",
            price: 12.58,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Main Courses",
        description:
          "Robust and satisfying center-of-plate dishes that deliver flavor and artistry.",
        items: [
          {
            name: "Authentic Creamy Thai Curry",
            price: 24.42,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Deluxe Grilled Roast Duck",
            price: 21.37,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Authentic Herbed Beef Burger",
            price: 25.57,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: true,
          },
          {
            name: "Classic Juicy Vegetable Stir-Fry",
            price: 18.55,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Tender Lasagna",
            price: 25.41,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Gourmet Aromatic Chicken Parmesan",
            price: 28.72,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Deluxe Baked Lamb Chops",
            price: 27.9,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Deluxe Aromatic Grilled Tofu",
            price: 30.46,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Seafood Specialties",
        description:
          "Crafted with care, our seafood offerings are a testament to our commitment to quality.",
        items: [
          {
            name: "Deluxe Flavorful Grilled Lobster with Lemon Butter",
            price: 28.52,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Fresh Herbed Steamed Littleneck Clams in Garlic Broth",
            price: 33.25,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Hearty Tender Grilled Spanish Octopus with Smoked Paprika",
            price: 23.04,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Gourmet Aromatic Mussels Mariniere in White Wine",
            price: 34.56,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Traditional Aromatic Shrimp Scampi over Linguine",
            price: 30.85,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
        ],
      },
      {
        name: "Side Dishes",
        description:
          "Crafted to enhance your meal, these sides are a celebration of American flavors.",
        items: [
          {
            name: "Warm Buttermilk Dinner Rolls",
            price: 7.52,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Charred Broccolini with Garlic Oil",
            price: 5.74,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Garlic Bread with Herb Butter",
            price: 9.06,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Truffle Parmesan Fries",
            price: 6.99,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Creamed Spinach with Nutmeg",
            price: 6.19,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Green Beans Almondine",
            price: 9.37,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Non-Alcoholic Beverages",
        description:
          "Bright, invigorating options that cleanse the palate and refresh the spirit.",
        items: [
          {
            name: "Lemonade",
            price: 7.85,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Soda",
            price: 6.64,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Iced Tea",
            price: 7.7,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Coffee",
            price: 5.1,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Water",
            price: 7.69,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Smoothie",
            price: 6.62,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
  {
    title: "Dessert Menu",
    description:
      "Our pastry chef's comforting creations to end your meal on a sweet note",
    category: [
      {
        name: "Baked Goods",
        description:
          "A selection of artisanal breads and pastries, baked fresh daily.",
        items: [
          {
            name: "Apple Pie",
            price: 7.33,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Cannoli",
            price: 7.47,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Muffins",
            price: 6.99,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Scones",
            price: 9.07,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Cheesecake",
            price: 7,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Frozen Desserts",
        description:
          "Indulge in our selection of frozen delights, perfect for any time of year.",
        items: [
          {
            name: "Frozen Yogurt",
            price: 8.56,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Gelato",
            price: 7.69,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Semifreddo",
            price: 7.1,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Ice Cream",
            price: 7.23,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Frozen Fruit Bars",
            price: 11.17,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
  {
    title: "Drinks Menu",
    description: "Our bartenders' fine creations to complete your meal",
    category: [
      {
        name: "Signature Cocktails",
        description:
          "Unique, house-crafted cocktails that offer a memorable sip every time.",
        items: [
          {
            name: "Organic Golden Cosmopolitan",
            price: 12.51,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "House Special Fried Bloody Mary",
            price: 11.65,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Seasonal Creamy Manhattan",
            price: 13.56,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Tangy Negroni",
            price: 14.58,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "House Special Luscious Mojito",
            price: 11.22,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Homestyle Spiced Whiskey Sour",
            price: 10.14,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Gourmet Aromatic Old Fashioned",
            price: 15.89,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Wine Selection",
        description:
          "New World energy meets Old World elegance in our diverse selection.",
        items: [
          {
            name: "Hearty Smoked Tempranillo",
            price: 8.86,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Traditional Fried Riesling",
            price: 11.29,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Pan-seared Chenin Blanc",
            price: 8.68,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Seasonal Herbed Vermentino",
            price: 9.2,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Aromatic Prosecco",
            price: 9.84,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Premium Mouthwatering Champagne/Sparkling Wine",
            price: 8.57,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
        ],
      },
      {
        name: "Spirits and Liqueurs",
        description:
          "From timeless classics to innovative new blends, our spirits menu is a celebration of flavor.",
        items: [
          {
            name: "Midori",
            price: 16.25,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Limoncello",
            price: 16.42,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Tequila",
            price: 17.75,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Maraschino",
            price: 15.9,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Rum",
            price: 16.57,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
];
