import { RestaurantMenu } from "@/lib/types/types";

/**
 * Menu data for The Patisserie in dubrovnik
 */
export const dubrovnikthePatisserieMenu: RestaurantMenu[] = [
  {
    title: "Main Course Menu",
    description: "Where fresh creativity meets timeless Italian inspiration",
    category: [
      {
        name: "Signature Dishes",
        description:
          "Celebrated dishes crafted with premium ingredients and exceptional care, designed to leave a lasting impression.",
        items: [
          {
            name: "Flambéed Tableside Specialty",
            price: 34.1,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Heritage Recipe Lamb Shank",
            price: 25.3,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: true,
          },
          {
            name: "Dry-Aged Tomahawk Steak",
            price: 37.01,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Restaurant's Namesake Signature Entrée",
            price: 33.97,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Executive Chef's Daily Inspiration Entrée",
            price: 35.85,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Age-Old Recipe Osso Buco with Gremolata",
            price: 26.28,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Korean BBQ Short Ribs with Kimchi Rice",
            price: 33.11,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
        ],
      },
      {
        name: "Chef's Specials",
        description:
          "Inventive dishes that explore rare ingredients, bold flavors, and progressive cooking techniques.",
        items: [
          {
            name: "Seared Foie Gras with Fig Compote",
            price: 32.6,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Locally Foraged Mushroom Selection",
            price: 28.44,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Seared Duck Breast with Cherry Reduction",
            price: 31.77,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Sustainable Seafood Tower",
            price: 37.32,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Miso-Glazed Black Cod",
            price: 34.47,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
        ],
      },
      {
        name: "Appetizers",
        description:
          "A delightful array of appetizers that highlight the best of Italian flavors—perfect for sharing or enjoying solo.",
        items: [
          {
            name: "Potstickers",
            price: 9.99,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Mini Quesadillas",
            price: 9.12,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Stuffed Avocado",
            price: 10,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Zucchini Fries",
            price: 14.97,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Mozzarella Sticks",
            price: 11,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Bruschetta",
            price: 12.88,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Samosas",
            price: 9.14,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Calamari",
            price: 12.52,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Soups",
        description:
          "A comforting range of house-made soups, from clear and delicate broths to rich, hearty bowls.",
        items: [
          {
            name: "Carrot Ginger Soup",
            price: 10.86,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Cabbage Soup",
            price: 13.34,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Egg Drop Soup",
            price: 10.07,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Vegetable Barley Soup",
            price: 7.62,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Salads",
        description:
          "Wholesome creations that blend crunch, freshness, and house-crafted dressings.",
        items: [
          {
            name: "Caesar Salad",
            price: 12.26,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Greek Salad",
            price: 10.91,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fruit Salad",
            price: 11.79,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Pasta Salad",
            price: 13.72,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Coleslaw",
            price: 13.94,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Main Courses",
        description:
          "Signature entrées crafted with precision, embodying the core of our Italian vision.",
        items: [
          {
            name: "Fresh Spicy Pho",
            price: 19.03,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "House Special Sweet Risotto",
            price: 30.89,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Hearty Stuffed Shakshuka",
            price: 21.37,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Traditional Spicy Teriyaki Chicken",
            price: 29.88,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Classic Sautéed Grilled Tofu",
            price: 19.84,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Seasonal Spicy Paella",
            price: 22.5,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "House Special Tangy Beef Burger",
            price: 22.24,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Organic Pan-seared Biryani",
            price: 21.51,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Seafood Specialties",
        description:
          "Expertly prepared seafood that highlights the natural flavors of the ocean.",
        items: [
          {
            name: "Garlic Butter Shrimp Skillet",
            price: 25.89,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Seared Tuna Steak with Sesame Crust",
            price: 26.03,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Grilled Spanish Octopus with Smoked Paprika",
            price: 22.34,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Cedar Plank Roasted Salmon",
            price: 26.51,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Linguine with Clam Sauce",
            price: 33.22,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
        ],
      },
      {
        name: "Side Dishes",
        description:
          "Flavorful companions that round out your meal with harmony and flair.",
        items: [
          {
            name: "Charred Broccolini with Garlic Oil",
            price: 5.44,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Roasted Brussels Sprouts with Balsamic Glaze",
            price: 6.34,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Warm Buttermilk Dinner Rolls",
            price: 7.88,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Grilled Zucchini and Peppers",
            price: 7.76,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Stuffed Bell Peppers with Brown Rice",
            price: 6.04,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Truffle Parmesan Fries",
            price: 8.92,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Non-Alcoholic Beverages",
        description:
          "Crafted beverages that offer a sophisticated alternative to traditional drinks.",
        items: [
          {
            name: "Milkshake",
            price: 6.09,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Iced Tea",
            price: 7.61,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Tea",
            price: 7.4,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Water",
            price: 7,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Lemonade",
            price: 6.74,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Hot Chocolate",
            price: 4.79,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
  {
    title: "Dessert Menu",
    description:
      "From classics to signatures: comforting desserts for every taste",
    category: [
      {
        name: "Baked Goods",
        description:
          "A rotating selection of baked indulgences from sweet to savory.",
        items: [
          {
            name: "Carrot Cake",
            price: 6.74,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Cupcakes",
            price: 9.82,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Tiramisu",
            price: 6.4,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Sticky Toffee Pudding",
            price: 8.26,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Strawberry Shortcake",
            price: 9.92,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Frozen Desserts",
        description:
          "A symphony of flavors and textures, our frozen desserts are a refreshing finale.",
        items: [
          {
            name: "Authentic Marinated Ice Cream",
            price: 11.39,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Homestyle Smoked Semifreddo",
            price: 11.57,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Traditional Succulent Frozen Fruit Bars",
            price: 11.85,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Tangy Frozen Yogurt",
            price: 7.08,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Handcrafted Creamy Paletas",
            price: 9.87,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
  {
    title: "Drinks Menu",
    description:
      "A select selection of wines, beers, and spirits to suit every taste",
    category: [
      {
        name: "Signature Cocktails",
        description:
          "Each cocktail is a work of art—balanced, bold, and beautifully presented.",
        items: [
          {
            name: "Bloody Mary",
            price: 12.92,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Manhattan",
            price: 12.64,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Negroni",
            price: 12.38,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Cosmopolitan",
            price: 15.65,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Mojito",
            price: 13.44,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Whiskey Sour",
            price: 11.06,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Old Fashioned",
            price: 13.5,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Wine Selection",
        description:
          "New World energy meets Old World elegance in our diverse selection.",
        items: [
          {
            name: "Hearty Savory Prosecco",
            price: 12.6,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Traditional Pan-seared Nebbiolo",
            price: 13.81,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Homestyle Stuffed Syrah/Shiraz",
            price: 9.08,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Sweet Vermentino",
            price: 11.51,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Braised Torrontés",
            price: 13.02,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Authentic Irresistible Verdicchio",
            price: 13.83,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
        ],
      },
      {
        name: "Spirits and Liqueurs",
        description:
          "Crafted for those who appreciate the finer things in life—our spirits selection.",
        items: [
          {
            name: "Gin",
            price: 10.57,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Triple Sec",
            price: 11.08,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Bénédictine",
            price: 17.54,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Cointreau",
            price: 17.69,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Vodka",
            price: 10.17,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
];
