import { Vessels } from "@/lib/interfaces/services/cruises";

export const amsterdamVessels: Vessels[] = [
  {
    name: "MV Amsterdam Explorer",
    description: "With its distinctive profile and luxurious appointments, the MV Amsterdam Explorer stands as a jewel in the Amsterdam harbor. This prestigious family cruise ship offers travelers a perfect combination of adventure and relaxation, with expert-guided excursions, world-class entertainment, and sublime culinary experiences.",
    type: "family-cruise-ship",
    capacity: 691,
    length: 238,
    width: 45,
    speed: 18,
    yearBuilt: 2010,
    homePort: {"city":"Amsterdam","country":"Netherlands","coordinates":{"latitude":52.377956,"longitude":4.89707}},
    specifications: {
      engineType: "Azimuth Thrusters",
      fuelCapacity: 5350,
      waterCapacity: 207299,
      propulsionType: "Counter-Rotating Propellers",
      hullMaterial: "Hybrid Steel-Composite",
      classification: "Russian Maritime Register of Shipping KM",
      safetyEquipment: ["Automated external defibrillators (AEDs)","Comprehensive medical facilities","Emergency position indicating radio beacons (EPIRBs)"],
      navigationEquipment: ["Autopilot systems with track control","Integrated bridge systems","Navigation data management systems"],
      communicationEquipment: ["Broadband internet throughout","Satellite communication systems"],
      entertainmentEquipment: ["Immersive simulation experiences","Children's entertainment areas","Culinary demonstration kitchens","Library and educational facilities","Dance clubs and live music venues"],
      accessibilityFeatures: ["Service animal accommodations","Roll-in showers","Elevator access to all public decks"],
      environmentalFeatures: ["Food waste digesters","Exhaust gas cleaning systems","Ballast water management technology","LED lighting throughout","Heat recovery systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false
  },
  {
    name: "PS Amsterdam Voyager",
    description: "Sailing from the picturesque port of Amsterdam, the PS Amsterdam Voyager represents a new era in cruise experiences. This remarkable mainstream cruise ship combines innovative design with thoughtful amenities, creating an atmosphere of refined elegance and warm hospitality.",
    type: "mainstream-cruise-ship",
    capacity: 2262,
    length: 552,
    width: 92,
    speed: 20,
    yearBuilt: 2007,
    homePort: {"city":"Amsterdam","country":"Netherlands","coordinates":{"latitude":52.377956,"longitude":4.89707}},
    specifications: {
      engineType: "Dual-Fuel Marine Engines",
      fuelCapacity: 25390,
      waterCapacity: 678600,
      propulsionType: "Voith Schneider Propellers",
      hullMaterial: "Hybrid Steel-Composite",
      classification: "DNV GL High Speed & Light Craft",
      safetyEquipment: ["Life jackets with integrated GPS","Advanced fire detection and suppression systems","Rescue boats and life rafts","Digital safety monitoring systems","Radar reflectors"],
      navigationEquipment: ["Navigation data management systems","Voyage data recorders (VDRs)","Echo sounders and sonar systems","Weather routing systems"],
      communicationEquipment: ["Broadband internet throughout","Emergency position-indicating radio beacons"],
      entertainmentEquipment: ["Multiple swimming pools and water features","Cinema with latest releases","Theater with Broadway-style productions","Virtual reality gaming center"],
      accessibilityFeatures: ["Accessible medical facilities","Visual alarm systems"],
      environmentalFeatures: ["Noise reduction technology to minimize impact on marine life","Optimized hull design for reduced fuel consumption","Solar panel supplementation"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false
  },
  {
    name: "MY Amsterdam Princess",
    description: "The MY Amsterdam Princess stands as a testament to luxury and innovation on the high seas. Departing from Amsterdam, this sophisticated expedition ship features immersive entertainment, wellness facilities, and exquisite cuisine prepared by internationally renowned chefs.",
    type: "expedition-ship",
    capacity: 1610,
    length: 422,
    width: 73,
    speed: 23,
    yearBuilt: 2005,
    homePort: {"city":"Amsterdam","country":"Netherlands","coordinates":{"latitude":52.377956,"longitude":4.89707}},
    specifications: {
      engineType: "Azimuth Thrusters",
      fuelCapacity: 15400,
      waterCapacity: 483000,
      propulsionType: "Cycloidal Drive",
      hullMaterial: "Marine-Grade Steel",
      classification: "American Bureau of Shipping A1",
      safetyEquipment: ["Marine evacuation systems (MES)","Life jackets with integrated GPS","Digital safety monitoring systems","Radar reflectors","Emergency escape breathing devices","Emergency position indicating radio beacons (EPIRBs)"],
      navigationEquipment: ["Global navigation satellite systems (GNSS)","Radar and automatic radar plotting aids (ARPAs)"],
      communicationEquipment: ["Maritime VHF radio systems","Ship-to-shore communication links"],
      entertainmentEquipment: ["Children's entertainment areas","Art gallery and auction facilities","Casino with table games and slot machines","Multi-purpose event spaces"],
      accessibilityFeatures: ["Roll-in showers","Visual alarm systems","Wheelchair accessible cabins"],
      environmentalFeatures: ["Recyclable material management systems","Exhaust gas cleaning systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false
  },
  {
    name: "SY Amsterdam Legend",
    description: "The SY Amsterdam Legend offers an unparalleled cruising experience from Amsterdam, combining luxury amenities with state-of-the-art navigation technology. This catamaran features spacious cabins, gourmet dining options, and entertainment venues that showcase the best of Northern Europe hospitality.",
    type: "catamaran",
    capacity: 1018,
    length: 303,
    width: 55,
    speed: 29,
    yearBuilt: 2007,
    homePort: {"city":"Amsterdam","country":"Netherlands","coordinates":{"latitude":52.377956,"longitude":4.89707}},
    specifications: {
      engineType: "Azimuth Thrusters",
      fuelCapacity: 8330,
      waterCapacity: 305400,
      propulsionType: "Conventional Shaft Propellers",
      hullMaterial: "Ice-Strengthened Steel",
      classification: "DNV GL High Speed & Light Craft",
      safetyEquipment: ["Survival craft VHF radios","Man overboard detection systems","Satellite emergency notification devices","Radar reflectors"],
      navigationEquipment: ["Doppler speed logs","Global navigation satellite systems (GNSS)","Gyrocompasses and magnetic compasses","Voyage data recorders (VDRs)"],
      communicationEquipment: ["Digital selective calling equipment","Marine radio telephony","Emergency position-indicating radio beacons"],
      entertainmentEquipment: ["Virtual reality gaming center","Library and educational facilities"],
      accessibilityFeatures: ["Roll-in showers","Accessible entertainment venues","Tactile guidance systems"],
      environmentalFeatures: ["Biodegradable hydraulic fluids","Noise reduction technology to minimize impact on marine life","Shore power connectivity","Food waste digesters"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true
  },
  {
    name: "MV Amsterdam Jewel",
    description: "The magnificent MV Amsterdam Jewel offers a perfect blend of adventure and relaxation for travelers departing from Amsterdam. This outstanding family cruise ship features panoramic ocean views, specialized dining experiences, and enriching activities that connect guests with the wonders of the Northern Europe region.",
    type: "family-cruise-ship",
    capacity: 1886,
    length: 477,
    width: 81,
    speed: 20,
    yearBuilt: 2005,
    homePort: {"city":"Amsterdam","country":"Netherlands","coordinates":{"latitude":52.377956,"longitude":4.89707}},
    specifications: {
      engineType: "Hybrid Power System",
      fuelCapacity: 19310,
      waterCapacity: 565800,
      propulsionType: "Azipod Electric Propulsion",
      hullMaterial: "Hybrid Steel-Composite",
      classification: "American Bureau of Shipping A1",
      safetyEquipment: ["Personal locator beacons","Hyperbaric treatment chambers","Searchlights and rescue equipment","Radar reflectors"],
      navigationEquipment: ["Night vision systems","Echo sounders and sonar systems","Autopilot systems with track control","Integrated bridge systems"],
      communicationEquipment: ["Emergency position-indicating radio beacons","Public address systems"],
      entertainmentEquipment: ["Immersive simulation experiences","Full-service spa and fitness center","Art gallery and auction facilities","Children's entertainment areas"],
      accessibilityFeatures: ["Transfer chairs for pool access","Elevator access to all public decks","Accessible medical facilities"],
      environmentalFeatures: ["Food waste digesters","Heat recovery systems","Solar panel supplementation"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true
  }
];
