// This file is auto-generated
    // Do not edit manually.
    // City: Bangkok
    // Generated on: 2025-06-10T03:09:08.298Z
    
    import { Vessels } from "@/lib/interfaces/services/cruises";

export const bangkokVessels: Vessels[] = [
  {
    id: "cs--explorer",
    name: "CS  Explorer",
    description: "Setting sail from the beautiful port of Bangkok, the CS  Explorer is a floating paradise designed for the discerning traveler. This transcendent zodiac equipped vessel boasts panoramic viewing decks, world-class cuisine, and personalized service that ensures an unforgettable journey.",
    type: "zodiac-equipped-vessel",
    capacity: 1251,
    length: 350,
    width: 62,
    speed: 22,
    topSpeed: 24, 
    yearBuilt: 2009,
    homePort: {"city":"Bangkok","country":"Thailand","coordinates":{"latitude":13.7563,"longitude":100.5018}},
    specifications: {
      engineType: "Azimuth Thrusters",
      fuelCapacity: 10850,
      waterCapacity: 375300,
      propulsionType: "Conventional Shaft Propellers",
      hullMaterial: "Ice-Strengthened Steel",
      classification: "DNV GL High Speed & Light Craft",
      safetyEquipment: ["Survival craft VHF radios","Satellite emergency notification devices","Marine evacuation systems (MES)","Comprehensive medical facilities","Emergency escape breathing devices"],
      navigationEquipment: ["Long-range identification and tracking (LRIT)","Automatic identification systems (AIS)","Gyrocompasses and magnetic compasses","Inland ECDIS"],
      communicationEquipment: ["Emergency position-indicating radio beacons","Public address systems"],
      entertainmentEquipment: ["Climbing walls and sports courts","Immersive simulation experiences","Dance clubs and live music venues"],
      accessibilityFeatures: ["Accessible shore excursion options","Transfer chairs for pool access"],
      environmentalFeatures: ["Shore power connectivity","Optimized hull design for reduced fuel consumption"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ss-bangkok-voyager",
    name: "SS Bangkok Voyager",
    description: "The SS Bangkok Voyager stands as a testament to luxury and innovation on the high seas. Departing from Bangkok, this sophisticated river cruise ship features immersive entertainment, wellness facilities, and exquisite cuisine prepared by internationally renowned chefs.",
    type: "river-cruise-ship",
    capacity: 858,
    length: 271,
    width: 50,
    speed: 18,
    topSpeed: 22, 
    yearBuilt: 2016,
    homePort: {"city":"Bangkok","country":"Thailand","coordinates":{"latitude":13.7563,"longitude":100.5018}},
    specifications: {
      engineType: "Azimuth Thrusters",
      fuelCapacity: 6770,
      waterCapacity: 257399,
      propulsionType: "Counter-Rotating Propellers",
      hullMaterial: "Ice-Strengthened Steel",
      classification: "DNV GL High Speed & Light Craft",
      safetyEquipment: ["Emergency escape breathing devices","Comprehensive medical facilities","Emergency position indicating radio beacons (EPIRBs)"],
      navigationEquipment: ["Inland ECDIS","Integrated bridge systems","Electronic chart display information systems (ECDIS)","Doppler speed logs"],
      communicationEquipment: ["Digital selective calling equipment","Global Maritime Distress Safety System (GMDSS)"],
      entertainmentEquipment: ["Culinary demonstration kitchens","Multi-purpose event spaces","Dance clubs and live music venues","Theater with Broadway-style productions","Casino with table games and slot machines"],
      accessibilityFeatures: ["Accessible medical facilities","Height-adjustable furniture in select cabins","Elevator access to all public decks"],
      environmentalFeatures: ["Noise reduction technology to minimize impact on marine life","Advanced water treatment systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "nx--of-the-deep",
    name: "NX  of the Deep",
    description: "The magnificent NX  of the Deep offers a perfect blend of adventure and relaxation for travelers departing from Bangkok. This outstanding family cruise ship features panoramic ocean views, specialized dining experiences, and enriching activities that connect guests with the wonders of the Thailand region.",
    type: "family-cruise-ship",
    capacity: 1214,
    length: 342,
    width: 61,
    speed: 27,
    topSpeed: 30, 
    yearBuilt: 2012,
    homePort: {"city":"Bangkok","country":"Thailand","coordinates":{"latitude":13.7563,"longitude":100.5018}},
    specifications: {
      engineType: "Azimuth Thrusters",
      fuelCapacity: 10430,
      waterCapacity: 364200,
      propulsionType: "Podded Propulsion Units",
      hullMaterial: "Marine-Grade Steel",
      classification: "RINA Green Star Plus",
      safetyEquipment: ["Hyperbaric treatment chambers","Emergency position indicating radio beacons (EPIRBs)","Advanced fire detection and suppression systems"],
      navigationEquipment: ["River radar systems","Long-range identification and tracking (LRIT)","Integrated bridge systems"],
      communicationEquipment: ["Global Maritime Distress Safety System (GMDSS)","Internal crew communication network","Broadband internet throughout"],
      entertainmentEquipment: ["Full-service spa and fitness center","Observation lounges with panoramic views","Virtual reality gaming center"],
      accessibilityFeatures: ["Service animal accommodations","Assistive listening devices","Tactile guidance systems"],
      environmentalFeatures: ["Advanced water treatment systems","Noise reduction technology to minimize impact on marine life"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "mv-the--mariner",
    name: "MV The  Mariner",
    description: "The majestic MV The  Mariner represents the pinnacle of maritime engineering and hospitality. Based in Bangkok, this exceptional zodiac equipped vessel features refined interiors, cutting-edge facilities, and carefully curated experiences that celebrate the unique culture of the Thailand region.",
    type: "zodiac-equipped-vessel",
    capacity: 1333,
    length: 366,
    width: 64,
    speed: 20,
    topSpeed: 22, 
    yearBuilt: 2018,
    homePort: {"city":"Bangkok","country":"Thailand","coordinates":{"latitude":13.7563,"longitude":100.5018}},
    specifications: {
      engineType: "LNG-Powered Engines",
      fuelCapacity: 11710,
      waterCapacity: 399900,
      propulsionType: "Counter-Rotating Propellers",
      hullMaterial: "Composite Materials",
      classification: "Bureau Veritas Star Class",
      safetyEquipment: ["Satellite emergency notification devices","Emergency escape breathing devices","Automated external defibrillators (AEDs)"],
      navigationEquipment: ["Long-range identification and tracking (LRIT)","Dynamic positioning systems","Gyrocompasses and magnetic compasses","Global navigation satellite systems (GNSS)"],
      communicationEquipment: ["Global Maritime Distress Safety System (GMDSS)","Digital selective calling equipment"],
      entertainmentEquipment: ["Observation lounges with panoramic views"],
      accessibilityFeatures: ["Hearing augmentation systems","Transfer chairs for pool access","Wheelchair accessible cabins"],
      environmentalFeatures: ["Optimized hull design for reduced fuel consumption","Advanced water treatment systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "fv--gale",
    name: "FV  Gale",
    description: "The FV  Gale invites travelers to explore the treasures of Thailand in unmatched comfort. This exceptional party cruise ship, based in Bangkok, features curated excursions, immersive cultural programs, and luxurious accommodations that ensure an unforgettable journey.",
    type: "party-cruise-ship",
    capacity: 903,
    length: 280,
    width: 52,
    speed: 25,
    topSpeed: 29, 
    yearBuilt: 2012,
    homePort: {"city":"Bangkok","country":"Thailand","coordinates":{"latitude":13.7563,"longitude":100.5018}},
    specifications: {
      engineType: "Solar-Assisted Electric",
      fuelCapacity: 7280,
      waterCapacity: 270900,
      propulsionType: "Z-Drive Propulsion",
      hullMaterial: "Ice-Strengthened Steel",
      classification: "Lloyd's Register Class 1",
      safetyEquipment: ["Personal locator beacons","Life jackets with integrated GPS","Man overboard detection systems","Emergency position indicating radio beacons (EPIRBs)","Emergency escape breathing devices"],
      navigationEquipment: ["Gyrocompasses and magnetic compasses","Dynamic positioning systems","Weather routing systems","Automatic identification systems (AIS)","River radar systems"],
      communicationEquipment: ["Internal crew communication network","Digital selective calling equipment"],
      entertainmentEquipment: ["Observation lounges with panoramic views","Dance clubs and live music venues"],
      accessibilityFeatures: ["Visual alarm systems","Wheelchair accessible cabins"],
      environmentalFeatures: ["Biodegradable hydraulic fluids","Energy-efficient appliances"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  }
];
