// This file is auto-generated
    // Do not edit manually.
    // City: Barcelona
    // Generated on: 2025-06-08T07:59:32.392Z
    
    import { Vessels } from "@/lib/interfaces/services/cruises";

export const barcelonaVessels: Vessels[] = [
{
    id: "mv--explorer",
    name: "MV  Explorer",
    description: "Combining traditional maritime charm with modern amenities, the MV  Explorer promises an extraordinary voyage from its home port of Barcelona. This impressive catamaran offers spacious accommodations, diverse dining options, and engaging activities for travelers of all ages.",
    type: "catamaran",
    capacity: 774,
    length: 254,
    width: 48,
    speed: 28,
    topSpeed: 31, 
    yearBuilt: 2008,
    homePort: {"city":"Barcelona","country":"Spain","coordinates":{"latitude":41.390205,"longitude":2.154007}},
    specifications: {
      engineType: "Azimuth Thrusters",
      fuelCapacity: 6090,
      waterCapacity: 232200,
      propulsionType: "Voith Schneider Propellers",
      hullMaterial: "Marine-Grade Steel",
      classification: "Bureau Veritas Star Class",
      safetyEquipment: ["Weather monitoring stations","Radar reflectors","Advanced fire detection and suppression systems","Digital safety monitoring systems","Marine evacuation systems (MES)","Emergency position indicating radio beacons (EPIRBs)"],
      navigationEquipment: ["Automatic identification systems (AIS)","Electronic chart display information systems (ECDIS)","Infrared camera systems","Global navigation satellite systems (GNSS)"],
      communicationEquipment: ["Broadband internet throughout","Marine radio telephony","Maritime VHF radio systems"],
      entertainmentEquipment: ["Casino with table games and slot machines","Full-service spa and fitness center"],
      accessibilityFeatures: ["Accessible medical facilities","Elevator access to all public decks"],
      environmentalFeatures: ["Ballast water management technology","Dynamic routing to optimize fuel usage","LED lighting throughout","Solar panel supplementation","Recyclable material management systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "sv-barcelona-voyager",
    name: "SV Barcelona Voyager",
    description: "The SV Barcelona Voyager offers an unparalleled cruising experience from Barcelona, combining luxury amenities with state-of-the-art navigation technology. This family cruise ship features spacious cabins, gourmet dining options, and entertainment venues that showcase the best of Catalonia hospitality.",
    type: "family-cruise-ship",
    capacity: 983,
    length: 296,
    width: 54,
    speed: 19,
    topSpeed: 21, 
    yearBuilt: 2008,
    homePort: {"city":"Barcelona","country":"Spain","coordinates":{"latitude":41.390205,"longitude":2.154007}},
    specifications: {
      engineType: "Integrated Power Systems",
      fuelCapacity: 7990,
      waterCapacity: 294900,
      propulsionType: "Water Jets",
      hullMaterial: "High-Tensile Steel Alloy",
      classification: "RINA Green Star Plus",
      safetyEquipment: ["Searchlights and rescue equipment","Weather monitoring stations","Emergency escape breathing devices","Tactical response equipment"],
      navigationEquipment: ["Radar and automatic radar plotting aids (ARPAs)","Night vision systems","Infrared camera systems"],
      communicationEquipment: ["Emergency position-indicating radio beacons","Public address systems"],
      entertainmentEquipment: ["Culinary demonstration kitchens","Cinema with latest releases"],
      accessibilityFeatures: ["Accessible medical facilities","Wheelchair accessible cabins","Tactile guidance systems","Transfer chairs for pool access"],
      environmentalFeatures: ["Advanced water treatment systems","Energy-efficient appliances","Noise reduction technology to minimize impact on marine life"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "rms--of-the-deep",
    name: "RMS  of the Deep",
    description: "With its distinctive profile and luxurious appointments, the RMS  of the Deep stands as a jewel in the Barcelona harbor. This prestigious family cruise ship offers travelers a perfect combination of adventure and relaxation, with expert-guided excursions, world-class entertainment, and sublime culinary experiences.",
    type: "family-cruise-ship",
    capacity: 1630,
    length: 426,
    width: 73,
    speed: 23,
    topSpeed: 26, 
    yearBuilt: 2019,
    homePort: {"city":"Barcelona","country":"Spain","coordinates":{"latitude":41.390205,"longitude":2.154007}},
    specifications: {
      engineType: "Gas Turbine Powerplant",
      fuelCapacity: 15540,
      waterCapacity: 489000,
      propulsionType: "Podded Propulsion Units",
      hullMaterial: "Hybrid Steel-Composite",
      classification: "Bureau Veritas Star Class",
      safetyEquipment: ["Emergency escape breathing devices","Radar reflectors","Personal locator beacons","Life jackets with integrated GPS","Searchlights and rescue equipment"],
      navigationEquipment: ["Doppler speed logs","Radar and automatic radar plotting aids (ARPAs)","Weather routing systems","Autopilot systems with track control"],
      communicationEquipment: ["Global Maritime Distress Safety System (GMDSS)"],
      entertainmentEquipment: ["Cinema with latest releases","Children's entertainment areas","Observation lounges with panoramic views"],
      accessibilityFeatures: ["Visual alarm systems","Accessible medical facilities"],
      environmentalFeatures: ["Recyclable material management systems","Solar panel supplementation"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "cs-the--mariner",
    name: "CS The  Mariner",
    description: "The majestic CS The  Mariner represents the pinnacle of maritime engineering and hospitality. Based in Barcelona, this exceptional luxury cruise ship features elegant interiors, cutting-edge facilities, and carefully curated experiences that celebrate the unique culture of the Catalonia region.",
    type: "luxury-cruise-ship",
    capacity: 465,
    length: 193,
    width: 38,
    speed: 15,
    topSpeed: 17, 
    yearBuilt: 2006,
    homePort: {"city":"Barcelona","country":"Spain","coordinates":{"latitude":41.390205,"longitude":2.154007}},
    specifications: {
      engineType: "Integrated Power Systems",
      fuelCapacity: 3660,
      waterCapacity: 139500,
      propulsionType: "Voith Schneider Propellers",
      hullMaterial: "Composite Materials",
      classification: "ClassNK NS* (Special Purpose Ship)",
      safetyEquipment: ["Weather monitoring stations","Rescue boats and life rafts","Hyperbaric treatment chambers","Comprehensive medical facilities","Man overboard detection systems"],
      navigationEquipment: ["Bridge alert management systems","Voyage data recorders (VDRs)","Automatic identification systems (AIS)","Weather routing systems"],
      communicationEquipment: ["Satellite communication systems","Emergency position-indicating radio beacons"],
      entertainmentEquipment: ["Library and educational facilities","Art gallery and auction facilities","Virtual reality gaming center"],
      accessibilityFeatures: ["Accessible medical facilities","Tactile guidance systems","Hearing augmentation systems"],
      environmentalFeatures: ["Food waste digesters","Energy-efficient appliances"]
    },
    isLuxuryVessel: true,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ly--gale",
    name: "LY  Gale",
    description: "Combining traditional maritime charm with modern amenities, the LY  Gale promises an extraordinary voyage from its home port of Barcelona. This impressive mainstream cruise ship offers spacious accommodations, diverse dining options, and engaging activities for travelers of all ages.",
    type: "mainstream-cruise-ship",
    capacity: 1760,
    length: 452,
    width: 77,
    speed: 26,
    topSpeed: 30, 
    yearBuilt: 2016,
    homePort: {"city":"Barcelona","country":"Spain","coordinates":{"latitude":41.390205,"longitude":2.154007}},
    specifications: {
      engineType: "Integrated Power Systems",
      fuelCapacity: 17400,
      waterCapacity: 528000,
      propulsionType: "Podded Propulsion Units",
      hullMaterial: "Hybrid Steel-Composite",
      classification: "China Classification Society B",
      safetyEquipment: ["Hyperbaric treatment chambers","Searchlights and rescue equipment","Advanced fire detection and suppression systems","Tactical response equipment","Rescue boats and life rafts"],
      navigationEquipment: ["Long-range identification and tracking (LRIT)","Automatic identification systems (AIS)","Echo sounders and sonar systems","River radar systems","Infrared camera systems"],
      communicationEquipment: ["Maritime VHF radio systems","Global Maritime Distress Safety System (GMDSS)"],
      entertainmentEquipment: ["Theater with Broadway-style productions","Dance clubs and live music venues","Casino with table games and slot machines"],
      accessibilityFeatures: ["Assistive listening devices","Elevator access to all public decks","Roll-in showers"],
      environmentalFeatures: ["Recyclable material management systems","LED lighting throughout","Heat recovery systems","Noise reduction technology to minimize impact on marine life"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "sy--explorer",
    name: "SY  Explorer",
    description: "The SY  Explorer offers an unparalleled cruising experience from Barcelona, combining luxury amenities with state-of-the-art navigation technology. This river cruise ship features spacious cabins, gourmet dining options, and entertainment venues that showcase the best of Catalonia hospitality.",
    type: "river-cruise-ship",
    capacity: 877,
    length: 275,
    width: 51,
    speed: 22,
    topSpeed: 25, 
    yearBuilt: 2020,
    homePort: {"city":"Barcelona","country":"Spain","coordinates":{"latitude":41.390205,"longitude":2.154007}},
    specifications: {
      engineType: "Azimuth Thrusters",
      fuelCapacity: 7010,
      waterCapacity: 263099,
      propulsionType: "Cycloidal Drive",
      hullMaterial: "Marine-Grade Steel",
      classification: "Russian Maritime Register of Shipping KM",
      safetyEquipment: ["Digital safety monitoring systems","Emergency position indicating radio beacons (EPIRBs)","Marine evacuation systems (MES)","Weather monitoring stations"],
      navigationEquipment: ["Dynamic positioning systems","Night vision systems","Global navigation satellite systems (GNSS)"],
      communicationEquipment: ["Maritime VHF radio systems","Internal crew communication network","Global Maritime Distress Safety System (GMDSS)"],
      entertainmentEquipment: ["Casino with table games and slot machines","Climbing walls and sports courts"],
      accessibilityFeatures: ["Transfer chairs for pool access","Accessible medical facilities","Accessible shore excursion options"],
      environmentalFeatures: ["Optimized hull design for reduced fuel consumption","Biodegradable hydraulic fluids","Energy-efficient appliances","Exhaust gas cleaning systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ps-barcelona-voyager",
    name: "PS Barcelona Voyager",
    description: "The magnificent PS Barcelona Voyager offers a perfect blend of adventure and relaxation for travelers departing from Barcelona. This outstanding chartered vessel features panoramic ocean views, specialized dining experiences, and enriching activities that connect guests with the wonders of the Catalonia region.",
    type: "chartered-vessel",
    capacity: 1370,
    length: 374,
    width: 66,
    speed: 16,
    topSpeed: 18, 
    yearBuilt: 2019,
    homePort: {"city":"Barcelona","country":"Spain","coordinates":{"latitude":41.390205,"longitude":2.154007}},
    specifications: {
      engineType: "LNG-Powered Engines",
      fuelCapacity: 12340,
      waterCapacity: 411000,
      propulsionType: "Podded Propulsion Units",
      hullMaterial: "High-Tensile Steel Alloy",
      classification: "China Classification Society B",
      safetyEquipment: ["Comprehensive medical facilities","Man overboard detection systems","Hyperbaric treatment chambers","Marine evacuation systems (MES)"],
      navigationEquipment: ["Integrated navigation system displays","Integrated bridge systems","Dynamic positioning systems","River radar systems"],
      communicationEquipment: ["Maritime VHF radio systems","Broadband internet throughout","Ship-to-shore communication links"],
      entertainmentEquipment: ["Climbing walls and sports courts","Full-service spa and fitness center"],
      accessibilityFeatures: ["Service animal accommodations","Accessible medical facilities","Hearing augmentation systems"],
      environmentalFeatures: ["Optimized hull design for reduced fuel consumption","Heat recovery systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "sy--of-the-deep",
    name: "SY  of the Deep",
    description: "Experience the epitome of maritime excellence aboard the SY  of the Deep, a premier zodiac equipped vessel sailing from Barcelona. With its elegant design, state-of-the-art technology, and exceptional service, every journey promises unforgettable moments and unparalleled comfort.",
    type: "zodiac-equipped-vessel",
    capacity: 548,
    length: 209,
    width: 41,
    speed: 21,
    topSpeed: 23, 
    yearBuilt: 2024,
    homePort: {"city":"Barcelona","country":"Spain","coordinates":{"latitude":41.390205,"longitude":2.154007}},
    specifications: {
      engineType: "Integrated Power Systems",
      fuelCapacity: 4280,
      waterCapacity: 164400,
      propulsionType: "Counter-Rotating Propellers",
      hullMaterial: "Reinforced Aluminum",
      classification: "Russian Maritime Register of Shipping KM",
      safetyEquipment: ["Marine evacuation systems (MES)","Advanced fire detection and suppression systems","Thermal imaging cameras","Man overboard detection systems"],
      navigationEquipment: ["Voyage data recorders (VDRs)","Integrated bridge systems","Integrated navigation system displays"],
      communicationEquipment: ["Satellite communication systems","Maritime VHF radio systems","Marine radio telephony"],
      entertainmentEquipment: ["Multi-purpose event spaces","Immersive simulation experiences","Casino with table games and slot machines","Climbing walls and sports courts"],
      accessibilityFeatures: ["Wheelchair accessible cabins","Elevator access to all public decks","Height-adjustable furniture in select cabins","Accessible shore excursion options"],
      environmentalFeatures: ["Noise reduction technology to minimize impact on marine life","LED lighting throughout"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ts--explorer",
    name: "TS  Explorer",
    description: "Combining traditional maritime charm with modern amenities, the TS  Explorer promises an extraordinary voyage from its home port of Barcelona. This impressive ocean liner offers spacious accommodations, diverse dining options, and engaging activities for travelers of all ages.",
    type: "ocean-liner",
    capacity: 1968,
    length: 493,
    width: 83,
    speed: 21,
    topSpeed: 24, 
    yearBuilt: 2023,
    homePort: {"city":"Barcelona","country":"Spain","coordinates":{"latitude":41.390205,"longitude":2.154007}},
    specifications: {
      engineType: "Azimuth Thrusters",
      fuelCapacity: 20450,
      waterCapacity: 590400,
      propulsionType: "Water Jets",
      hullMaterial: "Marine-Grade Steel",
      classification: "China Classification Society B",
      safetyEquipment: ["Radar reflectors","Personal locator beacons","Water purification systems","Survival craft VHF radios","Comprehensive medical facilities"],
      navigationEquipment: ["Integrated bridge systems","River radar systems","Autopilot systems with track control"],
      communicationEquipment: ["Satellite communication systems","Global Maritime Distress Safety System (GMDSS)"],
      entertainmentEquipment: ["Dance clubs and live music venues","Casino with table games and slot machines","Art gallery and auction facilities","Immersive simulation experiences","Climbing walls and sports courts"],
      accessibilityFeatures: ["Roll-in showers","Braille signage throughout","Elevator access to all public decks"],
      environmentalFeatures: ["Noise reduction technology to minimize impact on marine life","Recyclable material management systems","Energy-efficient appliances","Optimized hull design for reduced fuel consumption","Dynamic routing to optimize fuel usage"]
    },
    isLuxuryVessel: true,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ms-barcelona-voyager",
    name: "MS Barcelona Voyager",
    description: "The MS Barcelona Voyager stands as a testament to luxury and innovation on the high seas. Departing from Barcelona, this sophisticated chartered vessel features immersive entertainment, wellness facilities, and exquisite cuisine prepared by internationally renowned chefs.",
    type: "chartered-vessel",
    capacity: 1640,
    length: 428,
    width: 74,
    speed: 26,
    topSpeed: 30, 
    yearBuilt: 2012,
    homePort: {"city":"Barcelona","country":"Spain","coordinates":{"latitude":41.390205,"longitude":2.154007}},
    specifications: {
      engineType: "Podded Propulsion",
      fuelCapacity: 15830,
      waterCapacity: 492000,
      propulsionType: "Water Jets",
      hullMaterial: "Hybrid Steel-Composite",
      classification: "Bureau Veritas Star Class",
      safetyEquipment: ["Water purification systems","Tactical response equipment","Comprehensive medical facilities","Automated external defibrillators (AEDs)","Man overboard detection systems"],
      navigationEquipment: ["Gyrocompasses and magnetic compasses","Long-range identification and tracking (LRIT)"],
      communicationEquipment: ["Global Maritime Distress Safety System (GMDSS)","Satellite communication systems","Emergency position-indicating radio beacons"],
      entertainmentEquipment: ["Art gallery and auction facilities","Culinary demonstration kitchens","Immersive simulation experiences"],
      accessibilityFeatures: ["Elevator access to all public decks","Visual alarm systems","Transfer chairs for pool access"],
      environmentalFeatures: ["Heat recovery systems","Dynamic routing to optimize fuel usage"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "my--of-the-deep",
    name: "MY  of the Deep",
    description: "Combining traditional maritime charm with modern amenities, the MY  of the Deep promises an extraordinary voyage from its home port of Barcelona. This impressive ultra luxury cruise ship offers spacious accommodations, diverse dining options, and engaging activities for travelers of all ages.",
    type: "ultra-luxury-cruise-ship",
    capacity: 1461,
    length: 392,
    width: 68,
    speed: 18,
    topSpeed: 21, 
    yearBuilt: 2008,
    homePort: {"city":"Barcelona","country":"Spain","coordinates":{"latitude":41.390205,"longitude":2.154007}},
    specifications: {
      engineType: "Podded Propulsion",
      fuelCapacity: 13320,
      waterCapacity: 438300,
      propulsionType: "Conventional Shaft Propellers",
      hullMaterial: "Reinforced Aluminum",
      classification: "ClassNK NS* (Special Purpose Ship)",
      safetyEquipment: ["Thermal imaging cameras","Satellite emergency notification devices","Weather monitoring stations","Water purification systems"],
      navigationEquipment: ["Integrated navigation system displays","Electronic chart display information systems (ECDIS)","Automatic identification systems (AIS)"],
      communicationEquipment: ["Ship-to-shore communication links","Internal crew communication network"],
      entertainmentEquipment: ["Library and educational facilities","Immersive simulation experiences","Casino with table games and slot machines","Multi-purpose event spaces"],
      accessibilityFeatures: ["Roll-in showers","Transfer chairs for pool access"],
      environmentalFeatures: ["Exhaust gas cleaning systems","Solar panel supplementation","Marine ecosystem monitoring equipment"]
    },
    isLuxuryVessel: true,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "nx--explorer",
    name: "NX  Explorer",
    description: "The magnificent NX  Explorer offers a perfect blend of adventure and relaxation for travelers departing from Barcelona. This outstanding polar expedition ship features panoramic ocean views, specialized dining experiences, and enriching activities that connect guests with the wonders of the Catalonia region.",
    type: "polar-expedition-ship",
    capacity: 1929,
    length: 485,
    width: 82,
    speed: 20,
    topSpeed: 23, 
    yearBuilt: 2018,
    homePort: {"city":"Barcelona","country":"Spain","coordinates":{"latitude":41.390205,"longitude":2.154007}},
    specifications: {
      engineType: "Hybrid Power System",
      fuelCapacity: 19880,
      waterCapacity: 578699,
      propulsionType: "Cycloidal Drive",
      hullMaterial: "High-Tensile Steel Alloy",
      classification: "Lloyd's Register Class 1",
      safetyEquipment: ["Hyperbaric treatment chambers","Comprehensive medical facilities","Satellite emergency notification devices"],
      navigationEquipment: ["Autopilot systems with track control","Navigation data management systems","Long-range identification and tracking (LRIT)"],
      communicationEquipment: ["Global Maritime Distress Safety System (GMDSS)","Ship-to-shore communication links"],
      entertainmentEquipment: ["Theater with Broadway-style productions","Multi-purpose event spaces","Cinema with latest releases"],
      accessibilityFeatures: ["Accessible dining facilities","Tactile guidance systems"],
      environmentalFeatures: ["Food waste digesters","Exhaust gas cleaning systems","Recyclable material management systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "cs-barcelona-voyager",
    name: "CS Barcelona Voyager",
    description: "The CS Barcelona Voyager offers an unparalleled cruising experience from Barcelona, combining luxury amenities with state-of-the-art navigation technology. This catamaran features spacious cabins, gourmet dining options, and entertainment venues that showcase the best of Catalonia hospitality.",
    type: "catamaran",
    capacity: 1894,
    length: 478,
    width: 81,
    speed: 16,
    topSpeed: 19, 
    yearBuilt: 2024,
    homePort: {"city":"Barcelona","country":"Spain","coordinates":{"latitude":41.390205,"longitude":2.154007}},
    specifications: {
      engineType: "Dual-Fuel Marine Engines",
      fuelCapacity: 19350,
      waterCapacity: 568199,
      propulsionType: "Z-Drive Propulsion",
      hullMaterial: "Reinforced Aluminum",
      classification: "DNV GL High Speed & Light Craft",
      safetyEquipment: ["Survival craft VHF radios","Automated external defibrillators (AEDs)","Tactical response equipment","Personal locator beacons","Digital safety monitoring systems"],
      navigationEquipment: ["River radar systems","Night vision systems","Automatic identification systems (AIS)","Global navigation satellite systems (GNSS)"],
      communicationEquipment: ["Broadband internet throughout","Ship-to-shore communication links"],
      entertainmentEquipment: ["Immersive simulation experiences","Observation lounges with panoramic views","Dance clubs and live music venues","Multi-purpose event spaces","Virtual reality gaming center"],
      accessibilityFeatures: ["Tactile guidance systems","Service animal accommodations"],
      environmentalFeatures: ["Shore power connectivity","Ballast water management technology"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ly--of-the-deep",
    name: "LY  of the Deep",
    description: "The magnificent LY  of the Deep offers a perfect blend of adventure and relaxation for travelers departing from Barcelona. This outstanding polar expedition ship features panoramic ocean views, specialized dining experiences, and enriching activities that connect guests with the wonders of the Catalonia region.",
    type: "polar-expedition-ship",
    capacity: 1032,
    length: 306,
    width: 55,
    speed: 18,
    topSpeed: 20, 
    yearBuilt: 2021,
    homePort: {"city":"Barcelona","country":"Spain","coordinates":{"latitude":41.390205,"longitude":2.154007}},
    specifications: {
      engineType: "Hybrid Power System",
      fuelCapacity: 8410,
      waterCapacity: 309599,
      propulsionType: "Podded Propulsion Units",
      hullMaterial: "Ice-Strengthened Steel",
      classification: "RINA Green Star Plus",
      safetyEquipment: ["Water purification systems","Hyperbaric treatment chambers","Radar reflectors","Emergency escape breathing devices","Rescue boats and life rafts"],
      navigationEquipment: ["Gyrocompasses and magnetic compasses","Weather routing systems","Autopilot systems with track control","Night vision systems"],
      communicationEquipment: ["Marine radio telephony","Maritime VHF radio systems"],
      entertainmentEquipment: ["Multiple swimming pools and water features","Cinema with latest releases","Full-service spa and fitness center"],
      accessibilityFeatures: ["Braille signage throughout","Accessible medical facilities","Assistive listening devices"],
      environmentalFeatures: ["LED lighting throughout","Heat recovery systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "nx--explorer",
    name: "NX  Explorer",
    description: "With its distinctive profile and luxurious appointments, the NX  Explorer stands as a jewel in the Barcelona harbor. This prestigious catamaran offers travelers a perfect combination of adventure and relaxation, with expert-guided excursions, world-class entertainment, and sublime culinary experiences.",
    type: "catamaran",
    capacity: 795,
    length: 259,
    width: 48,
    speed: 25,
    topSpeed: 30, 
    yearBuilt: 2010,
    homePort: {"city":"Barcelona","country":"Spain","coordinates":{"latitude":41.390205,"longitude":2.154007}},
    specifications: {
      engineType: "Podded Propulsion",
      fuelCapacity: 6210,
      waterCapacity: 238500,
      propulsionType: "Conventional Shaft Propellers",
      hullMaterial: "High-Tensile Steel Alloy",
      classification: "ClassNK NS* (Special Purpose Ship)",
      safetyEquipment: ["Survival craft VHF radios","Life jackets with integrated GPS","Tactical response equipment"],
      navigationEquipment: ["Global navigation satellite systems (GNSS)","Navigation data management systems","Voyage data recorders (VDRs)","Radar and automatic radar plotting aids (ARPAs)"],
      communicationEquipment: ["Global Maritime Distress Safety System (GMDSS)","Digital selective calling equipment","Ship-to-shore communication links"],
      entertainmentEquipment: ["Culinary demonstration kitchens","Casino with table games and slot machines","Observation lounges with panoramic views","Full-service spa and fitness center","Virtual reality gaming center"],
      accessibilityFeatures: ["Transfer chairs for pool access","Wheelchair accessible cabins"],
      environmentalFeatures: ["LED lighting throughout","Advanced water treatment systems"]
    },
    isLuxuryVessel: true,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ly-barcelona-voyager",
    name: "LY Barcelona Voyager",
    description: "The LY Barcelona Voyager invites travelers to explore the treasures of Catalonia in unmatched comfort. This exceptional river cruise ship, based in Barcelona, features curated excursions, immersive cultural programs, and luxurious accommodations that ensure an unforgettable journey.",
    type: "river-cruise-ship",
    capacity: 1610,
    length: 422,
    width: 73,
    speed: 26,
    topSpeed: 31, 
    yearBuilt: 2018,
    homePort: {"city":"Barcelona","country":"Spain","coordinates":{"latitude":41.390205,"longitude":2.154007}},
    specifications: {
      engineType: "Podded Propulsion",
      fuelCapacity: 15400,
      waterCapacity: 483000,
      propulsionType: "Cycloidal Drive",
      hullMaterial: "Ice-Strengthened Steel",
      classification: "China Classification Society B",
      safetyEquipment: ["Radar reflectors","Digital safety monitoring systems","Water purification systems"],
      navigationEquipment: ["Bridge alert management systems","Navigation data management systems","River radar systems","Night vision systems"],
      communicationEquipment: ["Global Maritime Distress Safety System (GMDSS)","Marine radio telephony"],
      entertainmentEquipment: ["Theater with Broadway-style productions","Virtual reality gaming center"],
      accessibilityFeatures: ["Transfer chairs for pool access","Service animal accommodations"],
      environmentalFeatures: ["Noise reduction technology to minimize impact on marine life","Dynamic routing to optimize fuel usage","Heat recovery systems","Solar panel supplementation"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "rms--of-the-deep",
    name: "RMS  of the Deep",
    description: "Sailing from the picturesque port of Barcelona, the RMS  of the Deep represents a new era in cruise experiences. This remarkable mega yacht combines innovative design with thoughtful amenities, creating an atmosphere of refined elegance and warm hospitality.",
    type: "mega-yacht",
    capacity: 1819,
    length: 463,
    width: 79,
    speed: 23,
    topSpeed: 27, 
    yearBuilt: 2005,
    homePort: {"city":"Barcelona","country":"Spain","coordinates":{"latitude":41.390205,"longitude":2.154007}},
    specifications: {
      engineType: "Azimuth Thrusters",
      fuelCapacity: 18280,
      waterCapacity: 545699,
      propulsionType: "Counter-Rotating Propellers",
      hullMaterial: "Ice-Strengthened Steel",
      classification: "ClassNK NS* (Special Purpose Ship)",
      safetyEquipment: ["Advanced fire detection and suppression systems","Emergency escape breathing devices","Rescue boats and life rafts","Life jackets with integrated GPS"],
      navigationEquipment: ["Voyage data recorders (VDRs)","Radar and automatic radar plotting aids (ARPAs)"],
      communicationEquipment: ["Public address systems","Satellite communication systems"],
      entertainmentEquipment: ["Cinema with latest releases","Multiple swimming pools and water features","Virtual reality gaming center"],
      accessibilityFeatures: ["Height-adjustable furniture in select cabins","Accessible shore excursion options","Wheelchair accessible cabins"],
      environmentalFeatures: ["LED lighting throughout","Energy-efficient appliances"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  }
];
