// This file is auto-generated
    // Do not edit manually.
    // City: Buenos Aires
    // Generated on: 2025-06-08T07:59:32.392Z
    
    import { Vessels } from "@/lib/interfaces/services/cruises";

export const buenosAiresVessels: Vessels[] = [
{
    id: "mv--explorer",
    name: "MV  Explorer",
    description: "With its distinctive profile and luxurious appointments, the MV  Explorer stands as a jewel in the Buenos Aires harbor. This prestigious chartered vessel offers travelers a perfect combination of adventure and relaxation, with expert-guided excursions, world-class entertainment, and sublime culinary experiences.",
    type: "chartered-vessel",
    capacity: 1330,
    length: 366,
    width: 64,
    speed: 19,
    topSpeed: 22, 
    yearBuilt: 2009,
    homePort: {"city":"Buenos Aires","country":"Argentina","coordinates":{"latitude":-34.603722,"longitude":-58.381592}},
    specifications: {
      engineType: "LNG-Powered Engines",
      fuelCapacity: 11710,
      waterCapacity: 399000,
      propulsionType: "Azipod Electric Propulsion",
      hullMaterial: "Composite Materials",
      classification: "China Classification Society B",
      safetyEquipment: ["Man overboard detection systems","Tactical response equipment","Emergency position indicating radio beacons (EPIRBs)"],
      navigationEquipment: ["Radar and automatic radar plotting aids (ARPAs)","River radar systems","Weather routing systems","Infrared camera systems"],
      communicationEquipment: ["Broadband internet throughout","Internal crew communication network"],
      entertainmentEquipment: ["Culinary demonstration kitchens","Dance clubs and live music venues","Multiple swimming pools and water features"],
      accessibilityFeatures: ["Tactile guidance systems","Hearing augmentation systems","Accessible shore excursion options","Braille signage throughout"],
      environmentalFeatures: ["LED lighting throughout","Exhaust gas cleaning systems","Ballast water management technology","Marine ecosystem monitoring equipment"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "my-buenos-aires-voyager",
    name: "MY Buenos Aires Voyager",
    description: "The magnificent MY Buenos Aires Voyager offers a perfect blend of adventure and relaxation for travelers departing from Buenos Aires. This outstanding ultra luxury cruise ship features panoramic ocean views, specialized dining experiences, and enriching activities that connect guests with the wonders of the Argentina region.",
    type: "ultra-luxury-cruise-ship",
    capacity: 1584,
    length: 416,
    width: 72,
    speed: 26,
    topSpeed: 30, 
    yearBuilt: 2020,
    homePort: {"city":"Buenos Aires","country":"Argentina","coordinates":{"latitude":-34.603722,"longitude":-58.381592}},
    specifications: {
      engineType: "Dual-Fuel Marine Engines",
      fuelCapacity: 14970,
      waterCapacity: 475200,
      propulsionType: "Water Jets",
      hullMaterial: "Reinforced Aluminum",
      classification: "DNV GL High Speed & Light Craft",
      safetyEquipment: ["Weather monitoring stations","Rescue boats and life rafts","Satellite emergency notification devices","Digital safety monitoring systems","Marine evacuation systems (MES)","Personal locator beacons"],
      navigationEquipment: ["Inland ECDIS","Weather routing systems"],
      communicationEquipment: ["Broadband internet throughout","Internal crew communication network","Ship-to-shore communication links"],
      entertainmentEquipment: ["Full-service spa and fitness center","Climbing walls and sports courts"],
      accessibilityFeatures: ["Height-adjustable furniture in select cabins","Accessible dining facilities"],
      environmentalFeatures: ["Shore power connectivity","Advanced water treatment systems","Optimized hull design for reduced fuel consumption"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ly--of-the-deep",
    name: "LY  of the Deep",
    description: "The LY  of the Deep invites travelers to explore the treasures of Argentina in unmatched comfort. This exceptional party cruise ship, based in Buenos Aires, features curated excursions, immersive cultural programs, and luxurious accommodations that ensure an unforgettable journey.",
    type: "party-cruise-ship",
    capacity: 1916,
    length: 483,
    width: 82,
    speed: 28,
    topSpeed: 33, 
    yearBuilt: 2017,
    homePort: {"city":"Buenos Aires","country":"Argentina","coordinates":{"latitude":-34.603722,"longitude":-58.381592}},
    specifications: {
      engineType: "LNG-Powered Engines",
      fuelCapacity: 19800,
      waterCapacity: 574800,
      propulsionType: "Z-Drive Propulsion",
      hullMaterial: "Ice-Strengthened Steel",
      classification: "ClassNK NS* (Special Purpose Ship)",
      safetyEquipment: ["Thermal imaging cameras","Hyperbaric treatment chambers","Marine evacuation systems (MES)","Weather monitoring stations","Searchlights and rescue equipment","Rescue boats and life rafts"],
      navigationEquipment: ["Infrared camera systems","Night vision systems","Long-range identification and tracking (LRIT)","Bridge alert management systems"],
      communicationEquipment: ["Global Maritime Distress Safety System (GMDSS)","Digital selective calling equipment"],
      entertainmentEquipment: ["Climbing walls and sports courts","Observation lounges with panoramic views"],
      accessibilityFeatures: ["Assistive listening devices","Accessible dining facilities","Tactile guidance systems"],
      environmentalFeatures: ["Biodegradable hydraulic fluids"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "fv-the--mariner",
    name: "FV The  Mariner",
    description: "Sailing from the picturesque port of Buenos Aires, the FV The  Mariner represents a new era in cruise experiences. This remarkable ocean liner combines innovative design with thoughtful amenities, creating an atmosphere of refined elegance and warm hospitality.",
    type: "ocean-liner",
    capacity: 1300,
    length: 360,
    width: 64,
    speed: 20,
    topSpeed: 24, 
    yearBuilt: 2021,
    homePort: {"city":"Buenos Aires","country":"Argentina","coordinates":{"latitude":-34.603722,"longitude":-58.381592}},
    specifications: {
      engineType: "LNG-Powered Engines",
      fuelCapacity: 11520,
      waterCapacity: 390000,
      propulsionType: "Cycloidal Drive",
      hullMaterial: "Composite Materials",
      classification: "RINA Green Star Plus",
      safetyEquipment: ["Radar reflectors","Automated external defibrillators (AEDs)","Survival craft VHF radios","Rescue boats and life rafts","Life jackets with integrated GPS"],
      navigationEquipment: ["Gyrocompasses and magnetic compasses","River radar systems","Doppler speed logs"],
      communicationEquipment: ["Maritime VHF radio systems","Digital selective calling equipment"],
      entertainmentEquipment: ["Cinema with latest releases","Culinary demonstration kitchens"],
      accessibilityFeatures: ["Roll-in showers","Height-adjustable furniture in select cabins","Elevator access to all public decks","Hearing augmentation systems"],
      environmentalFeatures: ["Exhaust gas cleaning systems","LED lighting throughout","Shore power connectivity"]
    },
    isLuxuryVessel: true,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ms--gale",
    name: "MS  Gale",
    description: "Setting sail from the beautiful port of Buenos Aires, the MS  Gale is a floating paradise designed for the discerning traveler. This remarkable ice class ship boasts panoramic viewing decks, world-class cuisine, and personalized service that ensures an unforgettable journey.",
    type: "ice-class-ship",
    capacity: 738,
    length: 247,
    width: 47,
    speed: 23,
    topSpeed: 26, 
    yearBuilt: 2009,
    homePort: {"city":"Buenos Aires","country":"Argentina","coordinates":{"latitude":-34.603722,"longitude":-58.381592}},
    specifications: {
      engineType: "Azimuth Thrusters",
      fuelCapacity: 5800,
      waterCapacity: 221400,
      propulsionType: "Water Jets",
      hullMaterial: "High-Tensile Steel Alloy",
      classification: "American Bureau of Shipping A1",
      safetyEquipment: ["Emergency position indicating radio beacons (EPIRBs)","Advanced fire detection and suppression systems","Tactical response equipment","Personal locator beacons"],
      navigationEquipment: ["Infrared camera systems","Bridge alert management systems"],
      communicationEquipment: ["Marine radio telephony","Global Maritime Distress Safety System (GMDSS)"],
      entertainmentEquipment: ["Virtual reality gaming center","Climbing walls and sports courts","Cinema with latest releases"],
      accessibilityFeatures: ["Assistive listening devices","Accessible shore excursion options","Tactile guidance systems"],
      environmentalFeatures: ["LED lighting throughout","Biodegradable hydraulic fluids","Heat recovery systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "sv--explorer",
    name: "SV  Explorer",
    description: "Experience the epitome of maritime excellence aboard the SV  Explorer, a premier family cruise ship sailing from Buenos Aires. With its elegant design, state-of-the-art technology, and exceptional service, every journey promises unforgettable moments and unparalleled comfort.",
    type: "family-cruise-ship",
    capacity: 933,
    length: 286,
    width: 52,
    speed: 19,
    topSpeed: 23, 
    yearBuilt: 2010,
    homePort: {"city":"Buenos Aires","country":"Argentina","coordinates":{"latitude":-34.603722,"longitude":-58.381592}},
    specifications: {
      engineType: "Solar-Assisted Electric",
      fuelCapacity: 7430,
      waterCapacity: 279900,
      propulsionType: "Water Jets",
      hullMaterial: "Marine-Grade Steel",
      classification: "Lloyd's Register Class 1",
      safetyEquipment: ["Thermal imaging cameras","Advanced fire detection and suppression systems","Marine evacuation systems (MES)","Emergency escape breathing devices","Tactical response equipment"],
      navigationEquipment: ["Weather routing systems","Bridge alert management systems"],
      communicationEquipment: ["Satellite communication systems","Digital selective calling equipment","Marine radio telephony"],
      entertainmentEquipment: ["Immersive simulation experiences","Full-service spa and fitness center"],
      accessibilityFeatures: ["Tactile guidance systems","Hearing augmentation systems"],
      environmentalFeatures: ["Ballast water management technology","Optimized hull design for reduced fuel consumption"]
    },
    isLuxuryVessel: true,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "my-buenos-aires-voyager",
    name: "MY Buenos Aires Voyager",
    description: "Combining traditional maritime charm with modern amenities, the MY Buenos Aires Voyager promises an extraordinary voyage from its home port of Buenos Aires. This impressive ultra luxury cruise ship offers spacious accommodations, diverse dining options, and engaging activities for travelers of all ages.",
    type: "ultra-luxury-cruise-ship",
    capacity: 1084,
    length: 316,
    width: 57,
    speed: 26,
    topSpeed: 31, 
    yearBuilt: 2017,
    homePort: {"city":"Buenos Aires","country":"Argentina","coordinates":{"latitude":-34.603722,"longitude":-58.381592}},
    specifications: {
      engineType: "Podded Propulsion",
      fuelCapacity: 9000,
      waterCapacity: 325200,
      propulsionType: "Azipod Electric Propulsion",
      hullMaterial: "Composite Materials",
      classification: "ClassNK NS* (Special Purpose Ship)",
      safetyEquipment: ["Hyperbaric treatment chambers","Thermal imaging cameras","Water purification systems","Comprehensive medical facilities","Tactical response equipment","Emergency position indicating radio beacons (EPIRBs)","Digital safety monitoring systems"],
      navigationEquipment: ["Inland ECDIS","Long-range identification and tracking (LRIT)","Echo sounders and sonar systems","Dynamic positioning systems"],
      communicationEquipment: ["Broadband internet throughout","Emergency position-indicating radio beacons","Satellite communication systems"],
      entertainmentEquipment: ["Library and educational facilities","Climbing walls and sports courts","Multiple swimming pools and water features","Cinema with latest releases"],
      accessibilityFeatures: ["Roll-in showers","Hearing augmentation systems","Visual alarm systems"],
      environmentalFeatures: ["Noise reduction technology to minimize impact on marine life"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "fv--of-the-deep",
    name: "FV  of the Deep",
    description: "Sailing from the picturesque port of Buenos Aires, the FV  of the Deep represents a new era in cruise experiences. This remarkable mega yacht combines innovative design with thoughtful amenities, creating an atmosphere of refined elegance and warm hospitality.",
    type: "mega-yacht",
    capacity: 874,
    length: 274,
    width: 51,
    speed: 16,
    topSpeed: 18, 
    yearBuilt: 2011,
    homePort: {"city":"Buenos Aires","country":"Argentina","coordinates":{"latitude":-34.603722,"longitude":-58.381592}},
    specifications: {
      engineType: "Diesel-Electric Propulsion",
      fuelCapacity: 6980,
      waterCapacity: 262200,
      propulsionType: "Podded Propulsion Units",
      hullMaterial: "High-Tensile Steel Alloy",
      classification: "RINA Green Star Plus",
      safetyEquipment: ["Searchlights and rescue equipment","Personal locator beacons","Marine evacuation systems (MES)","Thermal imaging cameras","Satellite emergency notification devices"],
      navigationEquipment: ["Doppler speed logs","Integrated navigation system displays","Weather routing systems","Inland ECDIS","Bridge alert management systems"],
      communicationEquipment: ["Marine radio telephony","Maritime VHF radio systems"],
      entertainmentEquipment: ["Multiple swimming pools and water features","Library and educational facilities"],
      accessibilityFeatures: ["Accessible dining facilities","Roll-in showers","Service animal accommodations","Elevator access to all public decks"],
      environmentalFeatures: ["Marine ecosystem monitoring equipment","Energy-efficient appliances","Recyclable material management systems"]
    },
    isLuxuryVessel: true,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "rms--explorer",
    name: "RMS  Explorer",
    description: "The majestic RMS  Explorer represents the pinnacle of maritime engineering and hospitality. Based in Buenos Aires, this exceptional boutique cruise ship features elegant interiors, cutting-edge facilities, and carefully curated experiences that celebrate the unique culture of the Argentina region.",
    type: "boutique-cruise-ship",
    capacity: 1133,
    length: 326,
    width: 58,
    speed: 21,
    topSpeed: 23, 
    yearBuilt: 2006,
    homePort: {"city":"Buenos Aires","country":"Argentina","coordinates":{"latitude":-34.603722,"longitude":-58.381592}},
    specifications: {
      engineType: "Azimuth Thrusters",
      fuelCapacity: 9450,
      waterCapacity: 339900,
      propulsionType: "Podded Propulsion Units",
      hullMaterial: "Marine-Grade Steel",
      classification: "DNV GL High Speed & Light Craft",
      safetyEquipment: ["Marine evacuation systems (MES)","Digital safety monitoring systems","Emergency escape breathing devices","Hyperbaric treatment chambers","Thermal imaging cameras","Man overboard detection systems","Rescue boats and life rafts"],
      navigationEquipment: ["Autopilot systems with track control","Weather routing systems","Night vision systems"],
      communicationEquipment: ["Public address systems","Emergency position-indicating radio beacons","Digital selective calling equipment"],
      entertainmentEquipment: ["Dance clubs and live music venues","Observation lounges with panoramic views"],
      accessibilityFeatures: ["Accessible entertainment venues","Height-adjustable furniture in select cabins"],
      environmentalFeatures: ["Biodegradable hydraulic fluids","Dynamic routing to optimize fuel usage","Shore power connectivity"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "nx-buenos-aires-voyager",
    name: "NX Buenos Aires Voyager",
    description: "The NX Buenos Aires Voyager invites travelers to explore the treasures of Argentina in unmatched comfort. This exceptional party cruise ship, based in Buenos Aires, features curated excursions, immersive cultural programs, and luxurious accommodations that ensure an unforgettable journey.",
    type: "party-cruise-ship",
    capacity: 964,
    length: 292,
    width: 53,
    speed: 22,
    topSpeed: 24, 
    yearBuilt: 2024,
    homePort: {"city":"Buenos Aires","country":"Argentina","coordinates":{"latitude":-34.603722,"longitude":-58.381592}},
    specifications: {
      engineType: "Podded Propulsion",
      fuelCapacity: 7730,
      waterCapacity: 289200,
      propulsionType: "Conventional Shaft Propellers",
      hullMaterial: "Composite Materials",
      classification: "Russian Maritime Register of Shipping KM",
      safetyEquipment: ["Hyperbaric treatment chambers","Life jackets with integrated GPS","Weather monitoring stations","Automated external defibrillators (AEDs)"],
      navigationEquipment: ["Integrated navigation system displays","Global navigation satellite systems (GNSS)"],
      communicationEquipment: ["Global Maritime Distress Safety System (GMDSS)","Emergency position-indicating radio beacons","Broadband internet throughout"],
      entertainmentEquipment: ["Multiple swimming pools and water features","Virtual reality gaming center","Climbing walls and sports courts","Library and educational facilities"],
      accessibilityFeatures: ["Roll-in showers","Wheelchair accessible cabins"],
      environmentalFeatures: ["Energy-efficient appliances","Marine ecosystem monitoring equipment","Food waste digesters","Advanced water treatment systems"]
    },
    isLuxuryVessel: true,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "hms--of-the-deep",
    name: "HMS  of the Deep",
    description: "The magnificent HMS  of the Deep offers a perfect blend of adventure and relaxation for travelers departing from Buenos Aires. This outstanding polar expedition ship features panoramic ocean views, specialized dining experiences, and enriching activities that connect guests with the wonders of the Argentina region.",
    type: "polar-expedition-ship",
    capacity: 1328,
    length: 365,
    width: 64,
    speed: 18,
    topSpeed: 21, 
    yearBuilt: 2016,
    homePort: {"city":"Buenos Aires","country":"Argentina","coordinates":{"latitude":-34.603722,"longitude":-58.381592}},
    specifications: {
      engineType: "LNG-Powered Engines",
      fuelCapacity: 11680,
      waterCapacity: 398400,
      propulsionType: "Counter-Rotating Propellers",
      hullMaterial: "Reinforced Aluminum",
      classification: "ClassNK NS* (Special Purpose Ship)",
      safetyEquipment: ["Hyperbaric treatment chambers","Searchlights and rescue equipment","Personal locator beacons","Thermal imaging cameras"],
      navigationEquipment: ["Integrated navigation system displays","Bridge alert management systems","Infrared camera systems","Automatic identification systems (AIS)","Echo sounders and sonar systems"],
      communicationEquipment: ["Marine radio telephony","Public address systems"],
      entertainmentEquipment: ["Culinary demonstration kitchens","Observation lounges with panoramic views","Immersive simulation experiences"],
      accessibilityFeatures: ["Wheelchair accessible cabins","Accessible dining facilities","Visual alarm systems"],
      environmentalFeatures: ["Food waste digesters","Marine ecosystem monitoring equipment","Biodegradable hydraulic fluids","Solar panel supplementation"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ly--explorer",
    name: "LY  Explorer",
    description: "Sailing from the picturesque port of Buenos Aires, the LY  Explorer represents a new era in cruise experiences. This remarkable river cruise ship combines innovative design with thoughtful amenities, creating an atmosphere of refined elegance and warm hospitality.",
    type: "river-cruise-ship",
    capacity: 882,
    length: 276,
    width: 51,
    speed: 16,
    topSpeed: 19, 
    yearBuilt: 2019,
    homePort: {"city":"Buenos Aires","country":"Argentina","coordinates":{"latitude":-34.603722,"longitude":-58.381592}},
    specifications: {
      engineType: "Integrated Power Systems",
      fuelCapacity: 7030,
      waterCapacity: 264599,
      propulsionType: "Voith Schneider Propellers",
      hullMaterial: "Reinforced Aluminum",
      classification: "Lloyd's Register Class 1",
      safetyEquipment: ["Survival craft VHF radios","Searchlights and rescue equipment","Emergency position indicating radio beacons (EPIRBs)","Marine evacuation systems (MES)","Hyperbaric treatment chambers"],
      navigationEquipment: ["Infrared camera systems","Weather routing systems","Integrated navigation system displays","Bridge alert management systems","Integrated bridge systems"],
      communicationEquipment: ["Broadband internet throughout","Global Maritime Distress Safety System (GMDSS)","Emergency position-indicating radio beacons"],
      entertainmentEquipment: ["Casino with table games and slot machines","Observation lounges with panoramic views","Immersive simulation experiences","Culinary demonstration kitchens"],
      accessibilityFeatures: ["Accessible entertainment venues","Transfer chairs for pool access","Service animal accommodations","Wheelchair accessible cabins"],
      environmentalFeatures: ["Recyclable material management systems","Advanced water treatment systems","Food waste digesters","Heat recovery systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "rv-buenos-aires-voyager",
    name: "RV Buenos Aires Voyager",
    description: "The magnificent RV Buenos Aires Voyager offers a perfect blend of adventure and relaxation for travelers departing from Buenos Aires. This outstanding mainstream cruise ship features panoramic ocean views, specialized dining experiences, and enriching activities that connect guests with the wonders of the Argentina region.",
    type: "mainstream-cruise-ship",
    capacity: 1858,
    length: 471,
    width: 80,
    speed: 29,
    topSpeed: 33, 
    yearBuilt: 2008,
    homePort: {"city":"Buenos Aires","country":"Argentina","coordinates":{"latitude":-34.603722,"longitude":-58.381592}},
    specifications: {
      engineType: "Hybrid Power System",
      fuelCapacity: 18840,
      waterCapacity: 557400,
      propulsionType: "Cycloidal Drive",
      hullMaterial: "High-Tensile Steel Alloy",
      classification: "Lloyd's Register Class 1",
      safetyEquipment: ["Rescue boats and life rafts","Man overboard detection systems","Weather monitoring stations","Satellite emergency notification devices","Water purification systems","Radar reflectors"],
      navigationEquipment: ["Echo sounders and sonar systems","Doppler speed logs"],
      communicationEquipment: ["Satellite communication systems","Emergency position-indicating radio beacons"],
      entertainmentEquipment: ["Virtual reality gaming center","Multiple swimming pools and water features","Theater with Broadway-style productions","Multi-purpose event spaces","Observation lounges with panoramic views"],
      accessibilityFeatures: ["Braille signage throughout","Tactile guidance systems"],
      environmentalFeatures: ["Dynamic routing to optimize fuel usage","Energy-efficient appliances"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "sy--of-the-deep",
    name: "SY  of the Deep",
    description: "The magnificent SY  of the Deep offers a perfect blend of adventure and relaxation for travelers departing from Buenos Aires. This outstanding polar expedition ship features panoramic ocean views, specialized dining experiences, and enriching activities that connect guests with the wonders of the Argentina region.",
    type: "polar-expedition-ship",
    capacity: 582,
    length: 216,
    width: 42,
    speed: 29,
    topSpeed: 33, 
    yearBuilt: 2013,
    homePort: {"city":"Buenos Aires","country":"Argentina","coordinates":{"latitude":-34.603722,"longitude":-58.381592}},
    specifications: {
      engineType: "Podded Propulsion",
      fuelCapacity: 4530,
      waterCapacity: 174600,
      propulsionType: "Z-Drive Propulsion",
      hullMaterial: "Marine-Grade Steel",
      classification: "ClassNK NS* (Special Purpose Ship)",
      safetyEquipment: ["Water purification systems","Hyperbaric treatment chambers"],
      navigationEquipment: ["Long-range identification and tracking (LRIT)","Navigation data management systems","Autopilot systems with track control"],
      communicationEquipment: ["Satellite communication systems","Maritime VHF radio systems"],
      entertainmentEquipment: ["Library and educational facilities","Multiple swimming pools and water features","Dance clubs and live music venues"],
      accessibilityFeatures: ["Braille signage throughout","Hearing augmentation systems","Accessible entertainment venues","Visual alarm systems"],
      environmentalFeatures: ["Biodegradable hydraulic fluids","Exhaust gas cleaning systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "rms--explorer",
    name: "RMS  Explorer",
    description: "Combining traditional maritime charm with modern amenities, the RMS  Explorer promises an extraordinary voyage from its home port of Buenos Aires. This impressive resort style ship offers spacious accommodations, diverse dining options, and engaging activities for travelers of all ages.",
    type: "resort-style-ship",
    capacity: 845,
    length: 269,
    width: 50,
    speed: 27,
    topSpeed: 30, 
    yearBuilt: 2024,
    homePort: {"city":"Buenos Aires","country":"Argentina","coordinates":{"latitude":-34.603722,"longitude":-58.381592}},
    specifications: {
      engineType: "Hybrid Power System",
      fuelCapacity: 6720,
      waterCapacity: 253500,
      propulsionType: "Podded Propulsion Units",
      hullMaterial: "High-Tensile Steel Alloy",
      classification: "Russian Maritime Register of Shipping KM",
      safetyEquipment: ["Automated external defibrillators (AEDs)","Radar reflectors","Emergency escape breathing devices","Rescue boats and life rafts","Life jackets with integrated GPS"],
      navigationEquipment: ["Long-range identification and tracking (LRIT)","Global navigation satellite systems (GNSS)","River radar systems"],
      communicationEquipment: ["Satellite communication systems","Maritime VHF radio systems"],
      entertainmentEquipment: ["Casino with table games and slot machines","Theater with Broadway-style productions"],
      accessibilityFeatures: ["Elevator access to all public decks","Accessible entertainment venues","Braille signage throughout"],
      environmentalFeatures: ["Food waste digesters","Dynamic routing to optimize fuel usage"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "nb-buenos-aires-voyager",
    name: "NB Buenos Aires Voyager",
    description: "Setting sail from the beautiful port of Buenos Aires, the NB Buenos Aires Voyager is a floating paradise designed for the discerning traveler. This remarkable family cruise ship boasts panoramic viewing decks, world-class cuisine, and personalized service that ensures an unforgettable journey.",
    type: "family-cruise-ship",
    capacity: 1626,
    length: 425,
    width: 73,
    speed: 19,
    topSpeed: 22, 
    yearBuilt: 2020,
    homePort: {"city":"Buenos Aires","country":"Argentina","coordinates":{"latitude":-34.603722,"longitude":-58.381592}},
    specifications: {
      engineType: "Gas Turbine Powerplant",
      fuelCapacity: 15510,
      waterCapacity: 487799,
      propulsionType: "Voith Schneider Propellers",
      hullMaterial: "Composite Materials",
      classification: "DNV GL High Speed & Light Craft",
      safetyEquipment: ["Rescue boats and life rafts","Radar reflectors","Tactical response equipment","Personal locator beacons"],
      navigationEquipment: ["Echo sounders and sonar systems","Doppler speed logs","Long-range identification and tracking (LRIT)"],
      communicationEquipment: ["Ship-to-shore communication links"],
      entertainmentEquipment: ["Multi-purpose event spaces","Dance clubs and live music venues"],
      accessibilityFeatures: ["Visual alarm systems","Braille signage throughout"],
      environmentalFeatures: ["Biodegradable hydraulic fluids"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "fv--of-the-deep",
    name: "FV  of the Deep",
    description: "The FV  of the Deep invites travelers to explore the treasures of Argentina in unmatched comfort. This exceptional expedition ship, based in Buenos Aires, features curated excursions, immersive cultural programs, and luxurious accommodations that ensure an unforgettable journey.",
    type: "expedition-ship",
    capacity: 1714,
    length: 442,
    width: 76,
    speed: 26,
    topSpeed: 30, 
    yearBuilt: 2024,
    homePort: {"city":"Buenos Aires","country":"Argentina","coordinates":{"latitude":-34.603722,"longitude":-58.381592}},
    specifications: {
      engineType: "LNG-Powered Engines",
      fuelCapacity: 16790,
      waterCapacity: 514199,
      propulsionType: "Cycloidal Drive",
      hullMaterial: "Reinforced Aluminum",
      classification: "DNV GL High Speed & Light Craft",
      safetyEquipment: ["Emergency escape breathing devices","Searchlights and rescue equipment","Water purification systems","Automated external defibrillators (AEDs)","Tactical response equipment","Satellite emergency notification devices"],
      navigationEquipment: ["Automatic identification systems (AIS)","Integrated navigation system displays"],
      communicationEquipment: ["Emergency position-indicating radio beacons","Internal crew communication network"],
      entertainmentEquipment: ["Art gallery and auction facilities","Casino with table games and slot machines"],
      accessibilityFeatures: ["Assistive listening devices","Accessible medical facilities"],
      environmentalFeatures: ["Solar panel supplementation","Recyclable material management systems","Marine ecosystem monitoring equipment","Energy-efficient appliances"]
    },
    isLuxuryVessel: true,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  }
];
