// This file is auto-generated
    // Do not edit manually.
    // City: Dubrovnik
    // Generated on: 2025-06-10T08:14:15.034Z
    
    import { Vessels } from "@/lib/interfaces/services/cruises";

export const dubrovnikVessels: Vessels[] = [
{
    id: "my--explorer",
    name: "MY  Explorer",
    description: "The MY  Explorer invites travelers to explore the treasures of Croatian Coast in unmatched comfort. This exceptional chartered vessel, based in Dubrovnik, features curated excursions, immersive cultural programs, and luxurious accommodations that ensure an unforgettable journey.",
    type: "chartered-vessel",
    capacity: 1222,
    length: 344,
    width: 61,
    speed: 21,
    topSpeed: 23, 
    yearBuilt: 2019,
    homePort: {"city":"Dubrovnik","country":"Croatia","coordinates":{"latitude":0,"longitude":0}},
    specifications: {
      engineType: "Integrated Power Systems",
      fuelCapacity: 10490,
      waterCapacity: 366599,
      propulsionType: "Z-Drive Propulsion",
      hullMaterial: "Reinforced Aluminum",
      classification: "RINA Green Star Plus",
      safetyEquipment: ["Thermal imaging cameras","Hyperbaric treatment chambers","Satellite emergency notification devices","Water purification systems"],
      navigationEquipment: ["Global navigation satellite systems (GNSS)","Inland ECDIS","River radar systems","Bridge alert management systems"],
      communicationEquipment: ["Digital selective calling equipment","Global Maritime Distress Safety System (GMDSS)","Broadband internet throughout"],
      entertainmentEquipment: ["Cinema with latest releases","Casino with table games and slot machines","Children's entertainment areas"],
      accessibilityFeatures: ["Service animal accommodations","Wheelchair accessible cabins"],
      environmentalFeatures: ["Biodegradable hydraulic fluids","Marine ecosystem monitoring equipment","Optimized hull design for reduced fuel consumption"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ly-dubrovnik-voyager",
    name: "LY Dubrovnik Voyager",
    description: "Combining traditional maritime charm with modern amenities, the LY Dubrovnik Voyager promises an extraordinary voyage from its home port of Dubrovnik. This impressive adults only ship offers spacious accommodations, diverse dining options, and engaging activities for travelers of all ages.",
    type: "adults-only-ship",
    capacity: 1955,
    length: 491,
    width: 83,
    speed: 17,
    topSpeed: 20, 
    yearBuilt: 2014,
    homePort: {"city":"Dubrovnik","country":"Croatia","coordinates":{"latitude":0,"longitude":0}},
    specifications: {
      engineType: "Azimuth Thrusters",
      fuelCapacity: 20370,
      waterCapacity: 586500,
      propulsionType: "Conventional Shaft Propellers",
      hullMaterial: "Marine-Grade Steel",
      classification: "DNV GL High Speed & Light Craft",
      safetyEquipment: ["Emergency escape breathing devices","Tactical response equipment","Marine evacuation systems (MES)"],
      navigationEquipment: ["Weather routing systems","Doppler speed logs","Long-range identification and tracking (LRIT)","Radar and automatic radar plotting aids (ARPAs)","Autopilot systems with track control"],
      communicationEquipment: ["Digital selective calling equipment","Internal crew communication network"],
      entertainmentEquipment: ["Theater with Broadway-style productions","Immersive simulation experiences"],
      accessibilityFeatures: ["Accessible entertainment venues","Accessible dining facilities"],
      environmentalFeatures: ["Shore power connectivity","Solar panel supplementation","Ballast water management technology","Heat recovery systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "nb--of-the-deep",
    name: "NB  of the Deep",
    description: "The NB  of the Deep stands as a testament to luxury and innovation on the high seas. Departing from Dubrovnik, this sophisticated family cruise ship features immersive entertainment, wellness facilities, and exquisite cuisine prepared by internationally renowned chefs.",
    type: "family-cruise-ship",
    capacity: 1907,
    length: 481,
    width: 82,
    speed: 27,
    topSpeed: 32, 
    yearBuilt: 2010,
    homePort: {"city":"Dubrovnik","country":"Croatia","coordinates":{"latitude":0,"longitude":0}},
    specifications: {
      engineType: "Integrated Power Systems",
      fuelCapacity: 19720,
      waterCapacity: 572100,
      propulsionType: "Cycloidal Drive",
      hullMaterial: "Hybrid Steel-Composite",
      classification: "Lloyd's Register Class 1",
      safetyEquipment: ["Survival craft VHF radios","Personal locator beacons","Automated external defibrillators (AEDs)","Advanced fire detection and suppression systems","Water purification systems"],
      navigationEquipment: ["Autopilot systems with track control","Night vision systems","Doppler speed logs"],
      communicationEquipment: ["Internal crew communication network","Broadband internet throughout","Public address systems"],
      entertainmentEquipment: ["Casino with table games and slot machines","Culinary demonstration kitchens","Library and educational facilities","Immersive simulation experiences","Multiple swimming pools and water features"],
      accessibilityFeatures: ["Accessible shore excursion options","Wheelchair accessible cabins","Accessible entertainment venues","Service animal accommodations"],
      environmentalFeatures: ["Food waste digesters","Solar panel supplementation","Marine ecosystem monitoring equipment","Advanced water treatment systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "fv-the--mariner",
    name: "FV The  Mariner",
    description: "The FV The  Mariner stands as a testament to luxury and innovation on the high seas. Departing from Dubrovnik, this sophisticated mid size cruise ship features immersive entertainment, wellness facilities, and exquisite cuisine prepared by internationally renowned chefs.",
    type: "mid-size-cruise-ship",
    capacity: 1828,
    length: 465,
    width: 79,
    speed: 27,
    topSpeed: 30, 
    yearBuilt: 2016,
    homePort: {"city":"Dubrovnik","country":"Croatia","coordinates":{"latitude":0,"longitude":0}},
    specifications: {
      engineType: "Diesel-Electric Propulsion",
      fuelCapacity: 18360,
      waterCapacity: 548400,
      propulsionType: "Azipod Electric Propulsion",
      hullMaterial: "Composite Materials",
      classification: "DNV GL High Speed & Light Craft",
      safetyEquipment: ["Weather monitoring stations","Thermal imaging cameras","Digital safety monitoring systems","Personal locator beacons","Survival craft VHF radios"],
      navigationEquipment: ["Long-range identification and tracking (LRIT)","Global navigation satellite systems (GNSS)","Dynamic positioning systems","Bridge alert management systems"],
      communicationEquipment: ["Maritime VHF radio systems","Satellite communication systems"],
      entertainmentEquipment: ["Dance clubs and live music venues","Children's entertainment areas","Culinary demonstration kitchens","Library and educational facilities"],
      accessibilityFeatures: ["Accessible medical facilities","Braille signage throughout","Accessible shore excursion options","Hearing augmentation systems"],
      environmentalFeatures: ["Solar panel supplementation","Ballast water management technology"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "nb--gale",
    name: "NB  Gale",
    description: "With its distinctive profile and luxurious appointments, the NB  Gale stands as a jewel in the Dubrovnik harbor. This prestigious party cruise ship offers travelers a perfect combination of adventure and relaxation, with expert-guided excursions, world-class entertainment, and sublime culinary experiences.",
    type: "party-cruise-ship",
    capacity: 1205,
    length: 341,
    width: 61,
    speed: 26,
    topSpeed: 31, 
    yearBuilt: 2012,
    homePort: {"city":"Dubrovnik","country":"Croatia","coordinates":{"latitude":0,"longitude":0}},
    specifications: {
      engineType: "Dual-Fuel Marine Engines",
      fuelCapacity: 10400,
      waterCapacity: 361500,
      propulsionType: "Voith Schneider Propellers",
      hullMaterial: "Ice-Strengthened Steel",
      classification: "China Classification Society B",
      safetyEquipment: ["Thermal imaging cameras","Personal locator beacons","Rescue boats and life rafts","Life jackets with integrated GPS","Survival craft VHF radios"],
      navigationEquipment: ["Echo sounders and sonar systems","Automatic identification systems (AIS)"],
      communicationEquipment: ["Global Maritime Distress Safety System (GMDSS)","Internal crew communication network"],
      entertainmentEquipment: ["Climbing walls and sports courts","Full-service spa and fitness center","Library and educational facilities","Casino with table games and slot machines"],
      accessibilityFeatures: ["Hearing augmentation systems"],
      environmentalFeatures: ["Dynamic routing to optimize fuel usage","Noise reduction technology to minimize impact on marine life","Food waste digesters","Biodegradable hydraulic fluids"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "nb--explorer",
    name: "NB  Explorer",
    description: "The NB  Explorer offers an unparalleled cruising experience from Dubrovnik, combining luxury amenities with state-of-the-art navigation technology. This boutique cruise ship features spacious cabins, gourmet dining options, and entertainment venues that showcase the best of Croatian Coast hospitality.",
    type: "boutique-cruise-ship",
    capacity: 1580,
    length: 416,
    width: 72,
    speed: 25,
    topSpeed: 29, 
    yearBuilt: 2005,
    homePort: {"city":"Dubrovnik","country":"Croatia","coordinates":{"latitude":0,"longitude":0}},
    specifications: {
      engineType: "Gas Turbine Powerplant",
      fuelCapacity: 14970,
      waterCapacity: 474000,
      propulsionType: "Water Jets",
      hullMaterial: "Reinforced Aluminum",
      classification: "Bureau Veritas Star Class",
      safetyEquipment: ["Emergency escape breathing devices","Advanced fire detection and suppression systems","Weather monitoring stations","Personal locator beacons"],
      navigationEquipment: ["Automatic identification systems (AIS)","Echo sounders and sonar systems","Long-range identification and tracking (LRIT)","Radar and automatic radar plotting aids (ARPAs)"],
      communicationEquipment: ["Maritime VHF radio systems","Marine radio telephony"],
      entertainmentEquipment: ["Dance clubs and live music venues","Virtual reality gaming center","Immersive simulation experiences"],
      accessibilityFeatures: ["Tactile guidance systems","Accessible dining facilities"],
      environmentalFeatures: ["Optimized hull design for reduced fuel consumption","LED lighting throughout","Heat recovery systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "sv-dubrovnik-voyager",
    name: "SV Dubrovnik Voyager",
    description: "With its distinctive profile and luxurious appointments, the SV Dubrovnik Voyager stands as a jewel in the Dubrovnik harbor. This prestigious mid size cruise ship offers travelers a perfect combination of adventure and relaxation, with expert-guided excursions, world-class entertainment, and sublime culinary experiences.",
    type: "mid-size-cruise-ship",
    capacity: 998,
    length: 299,
    width: 54,
    speed: 25,
    topSpeed: 29, 
    yearBuilt: 2020,
    homePort: {"city":"Dubrovnik","country":"Croatia","coordinates":{"latitude":0,"longitude":0}},
    specifications: {
      engineType: "Hybrid Power System",
      fuelCapacity: 8070,
      waterCapacity: 299400,
      propulsionType: "Z-Drive Propulsion",
      hullMaterial: "High-Tensile Steel Alloy",
      classification: "RINA Green Star Plus",
      safetyEquipment: ["Thermal imaging cameras","Tactical response equipment","Radar reflectors","Man overboard detection systems","Weather monitoring stations","Automated external defibrillators (AEDs)","Satellite emergency notification devices"],
      navigationEquipment: ["Weather routing systems","Voyage data recorders (VDRs)","River radar systems"],
      communicationEquipment: ["Internal crew communication network","Maritime VHF radio systems"],
      entertainmentEquipment: ["Library and educational facilities","Cinema with latest releases","Virtual reality gaming center"],
      accessibilityFeatures: ["Wheelchair accessible cabins","Height-adjustable furniture in select cabins"],
      environmentalFeatures: ["Ballast water management technology","Shore power connectivity","Solar panel supplementation"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "cs--of-the-deep",
    name: "CS  of the Deep",
    description: "Experience the epitome of maritime excellence aboard the CS  of the Deep, a premier adults only ship sailing from Dubrovnik. With its elegant design, state-of-the-art technology, and exceptional service, every journey promises unforgettable moments and unparalleled comfort.",
    type: "adults-only-ship",
    capacity: 1198,
    length: 339,
    width: 60,
    speed: 29,
    topSpeed: 34, 
    yearBuilt: 2013,
    homePort: {"city":"Dubrovnik","country":"Croatia","coordinates":{"latitude":0,"longitude":0}},
    specifications: {
      engineType: "Azimuth Thrusters",
      fuelCapacity: 10170,
      waterCapacity: 359400,
      propulsionType: "Cycloidal Drive",
      hullMaterial: "Composite Materials",
      classification: "ClassNK NS* (Special Purpose Ship)",
      safetyEquipment: ["Life jackets with integrated GPS","Advanced fire detection and suppression systems","Survival craft VHF radios","Digital safety monitoring systems","Marine evacuation systems (MES)","Emergency position indicating radio beacons (EPIRBs)"],
      navigationEquipment: ["Global navigation satellite systems (GNSS)","Navigation data management systems","River radar systems"],
      communicationEquipment: ["Broadband internet throughout","Maritime VHF radio systems"],
      entertainmentEquipment: ["Observation lounges with panoramic views","Dance clubs and live music venues","Immersive simulation experiences","Multiple swimming pools and water features"],
      accessibilityFeatures: ["Accessible medical facilities","Roll-in showers","Hearing augmentation systems","Height-adjustable furniture in select cabins"],
      environmentalFeatures: ["Shore power connectivity","Heat recovery systems","Dynamic routing to optimize fuel usage"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "rv-the--mariner",
    name: "RV The  Mariner",
    description: "Experience the epitome of maritime excellence aboard the RV The  Mariner, a premier resort style ship sailing from Dubrovnik. With its elegant design, state-of-the-art technology, and exceptional service, every journey promises unforgettable moments and unparalleled comfort.",
    type: "resort-style-ship",
    capacity: 753,
    length: 250,
    width: 47,
    speed: 16,
    topSpeed: 19, 
    yearBuilt: 2010,
    homePort: {"city":"Dubrovnik","country":"Croatia","coordinates":{"latitude":0,"longitude":0}},
    specifications: {
      engineType: "LNG-Powered Engines",
      fuelCapacity: 5870,
      waterCapacity: 225900,
      propulsionType: "Azipod Electric Propulsion",
      hullMaterial: "Reinforced Aluminum",
      classification: "DNV GL High Speed & Light Craft",
      safetyEquipment: ["Weather monitoring stations","Digital safety monitoring systems","Marine evacuation systems (MES)","Thermal imaging cameras","Hyperbaric treatment chambers"],
      navigationEquipment: ["Global navigation satellite systems (GNSS)","Bridge alert management systems","Automatic identification systems (AIS)","Autopilot systems with track control"],
      communicationEquipment: ["Ship-to-shore communication links","Marine radio telephony"],
      entertainmentEquipment: ["Full-service spa and fitness center","Dance clubs and live music venues","Observation lounges with panoramic views"],
      accessibilityFeatures: ["Service animal accommodations","Accessible shore excursion options","Roll-in showers"],
      environmentalFeatures: ["Energy-efficient appliances","Solar panel supplementation","Advanced water treatment systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "fv--gale",
    name: "FV  Gale",
    description: "Combining traditional maritime charm with modern amenities, the FV  Gale promises an extraordinary voyage from its home port of Dubrovnik. This impressive mega yacht offers spacious accommodations, diverse dining options, and engaging activities for travelers of all ages.",
    type: "mega-yacht",
    capacity: 1647,
    length: 429,
    width: 74,
    speed: 25,
    topSpeed: 30, 
    yearBuilt: 2012,
    homePort: {"city":"Dubrovnik","country":"Croatia","coordinates":{"latitude":0,"longitude":0}},
    specifications: {
      engineType: "Dual-Fuel Marine Engines",
      fuelCapacity: 15870,
      waterCapacity: 494099,
      propulsionType: "Counter-Rotating Propellers",
      hullMaterial: "Marine-Grade Steel",
      classification: "RINA Green Star Plus",
      safetyEquipment: ["Comprehensive medical facilities","Tactical response equipment","Emergency position indicating radio beacons (EPIRBs)","Survival craft VHF radios","Weather monitoring stations","Hyperbaric treatment chambers"],
      navigationEquipment: ["Echo sounders and sonar systems","Long-range identification and tracking (LRIT)","Radar and automatic radar plotting aids (ARPAs)","Automatic identification systems (AIS)"],
      communicationEquipment: ["Public address systems","Broadband internet throughout"],
      entertainmentEquipment: ["Cinema with latest releases","Art gallery and auction facilities"],
      accessibilityFeatures: ["Elevator access to all public decks","Service animal accommodations"],
      environmentalFeatures: ["Exhaust gas cleaning systems","Ballast water management technology","Heat recovery systems","Dynamic routing to optimize fuel usage"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  }
];
