import { Vessels } from "@/lib/interfaces/services/cruises";

export const fortLauderdaleVessels: Vessels[] = [
  {
    name: "RV Fort Lauderdale Explorer",
    description:
      "The RV Fort Lauderdale Explorer invites travelers to explore the treasures of Caribbean in unmatched comfort. This exceptional mainstream cruise ship, based in Fort Lauderdale, features curated excursions, immersive cultural programs, and luxurious accommodations that ensure an unforgettable journey.",
    type: "mainstream-cruise-ship",
    capacity: 1475,
    length: 395,
    width: 69,
    speed: 16,
    yearBuilt: 2008,
    homePort: {
      city: "Fort Lauderdale",
      country: "United States",
      coordinates: { latitude: 26.122439, longitude: -80.137317 },
    },
    specifications: {
      engineType: "Gas Turbine Powerplant",
      fuelCapacity: 13620,
      waterCapacity: 442500,
      propulsionType: "Podded Propulsion Units",
      hullMaterial: "High-Tensile Steel Alloy",
      classification: "China Classification Society B",
      safetyEquipment: [
        "Personal locator beacons",
        "Emergency position indicating radio beacons (EPIRBs)",
        "Automated external defibrillators (AEDs)",
        "Rescue boats and life rafts",
      ],
      navigationEquipment: [
        "Electronic chart display information systems (ECDIS)",
        "Voyage data recorders (VDRs)",
        "River radar systems",
      ],
      communicationEquipment: [
        "Public address systems",
        "Satellite communication systems",
        "Internal crew communication network",
      ],
      entertainmentEquipment: [
        "Art gallery and auction facilities",
        "Immersive simulation experiences",
        "Library and educational facilities",
      ],
      accessibilityFeatures: [
        "Hearing augmentation systems",
        "Height-adjustable furniture in select cabins",
      ],
      environmentalFeatures: [
        "Dynamic routing to optimize fuel usage",
        "Heat recovery systems",
        "Ballast water management technology",
      ],
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
  },
  {
    name: "MS Fort Lauderdale Voyager",
    description:
      "The MS Fort Lauderdale Voyager invites travelers to explore the treasures of Caribbean in unmatched comfort. This exceptional chartered vessel, based in Fort Lauderdale, features curated excursions, immersive cultural programs, and luxurious accommodations that ensure an unforgettable journey.",
    type: "chartered-vessel",
    capacity: 839,
    length: 267,
    width: 50,
    speed: 25,
    yearBuilt: 2024,
    homePort: {
      city: "Fort Lauderdale",
      country: "United States",
      coordinates: { latitude: 26.122439, longitude: -80.137317 },
    },
    specifications: {
      engineType: "Hybrid Power System",
      fuelCapacity: 6670,
      waterCapacity: 251700,
      propulsionType: "Azipod Electric Propulsion",
      hullMaterial: "Reinforced Aluminum",
      classification: "RINA Green Star Plus",
      safetyEquipment: [
        "Automated external defibrillators (AEDs)",
        "Rescue boats and life rafts",
        "Searchlights and rescue equipment",
      ],
      navigationEquipment: [
        "Global navigation satellite systems (GNSS)",
        "Radar and automatic radar plotting aids (ARPAs)",
      ],
      communicationEquipment: [
        "Maritime VHF radio systems",
        "Internal crew communication network",
      ],
      entertainmentEquipment: [
        "Dance clubs and live music venues",
        "Immersive simulation experiences",
        "Cinema with latest releases",
      ],
      accessibilityFeatures: [
        "Service animal accommodations",
        "Elevator access to all public decks",
      ],
      environmentalFeatures: [
        "Optimized hull design for reduced fuel consumption",
        "LED lighting throughout",
        "Solar panel supplementation",
        "Dynamic routing to optimize fuel usage",
        "Exhaust gas cleaning systems",
      ],
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
  },
  {
    name: "PS Fort Lauderdale Princess",
    description:
      "The magnificent PS Fort Lauderdale Princess offers a perfect blend of adventure and relaxation for travelers departing from Fort Lauderdale. This outstanding catamaran features panoramic ocean views, specialized dining experiences, and enriching activities that connect guests with the wonders of the Caribbean region.",
    type: "catamaran",
    capacity: 691,
    length: 238,
    width: 45,
    speed: 15,
    yearBuilt: 2022,
    homePort: {
      city: "Fort Lauderdale",
      country: "United States",
      coordinates: { latitude: 26.122439, longitude: -80.137317 },
    },
    specifications: {
      engineType: "LNG-Powered Engines",
      fuelCapacity: 5350,
      waterCapacity: 207299,
      propulsionType: "Water Jets",
      hullMaterial: "Reinforced Aluminum",
      classification: "ClassNK NS* (Special Purpose Ship)",
      safetyEquipment: [
        "Radar reflectors",
        "Personal locator beacons",
        "Thermal imaging cameras",
        "Rescue boats and life rafts",
        "Searchlights and rescue equipment",
      ],
      navigationEquipment: [
        "Integrated bridge systems",
        "Integrated navigation system displays",
        "River radar systems",
        "Global navigation satellite systems (GNSS)",
      ],
      communicationEquipment: [
        "Digital selective calling equipment",
        "Maritime VHF radio systems",
      ],
      entertainmentEquipment: [
        "Cinema with latest releases",
        "Climbing walls and sports courts",
        "Culinary demonstration kitchens",
        "Multi-purpose event spaces",
      ],
      accessibilityFeatures: [
        "Tactile guidance systems",
        "Service animal accommodations",
        "Accessible medical facilities",
      ],
      environmentalFeatures: [
        "Food waste digesters",
        "Ballast water management technology",
      ],
    },
    isLuxuryVessel: true,
    isPetFriendly: false,
  },
  {
    name: "TS Fort Lauderdale Legend",
    description:
      "The majestic TS Fort Lauderdale Legend represents the pinnacle of maritime engineering and hospitality. Based in Fort Lauderdale, this exceptional mainstream cruise ship features elegant interiors, cutting-edge facilities, and carefully curated experiences that celebrate the unique culture of the Caribbean region.",
    type: "mainstream-cruise-ship",
    capacity: 2394,
    length: 578,
    width: 96,
    speed: 28,
    yearBuilt: 2011,
    homePort: {
      city: "Fort Lauderdale",
      country: "United States",
      coordinates: { latitude: 26.122439, longitude: -80.137317 },
    },
    specifications: {
      engineType: "LNG-Powered Engines",
      fuelCapacity: 27740,
      waterCapacity: 718199,
      propulsionType: "Water Jets",
      hullMaterial: "Hybrid Steel-Composite",
      classification: "RINA Green Star Plus",
      safetyEquipment: [
        "Comprehensive medical facilities",
        "Rescue boats and life rafts",
        "Man overboard detection systems",
      ],
      navigationEquipment: [
        "Voyage data recorders (VDRs)",
        "Long-range identification and tracking (LRIT)",
        "Electronic chart display information systems (ECDIS)",
        "Gyrocompasses and magnetic compasses",
        "Integrated navigation system displays",
      ],
      communicationEquipment: [
        "Broadband internet throughout",
        "Satellite communication systems",
      ],
      entertainmentEquipment: [
        "Immersive simulation experiences",
        "Children's entertainment areas",
      ],
      accessibilityFeatures: [
        "Height-adjustable furniture in select cabins",
        "Braille signage throughout",
      ],
      environmentalFeatures: [
        "Ballast water management technology",
        "Exhaust gas cleaning systems",
      ],
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
  },
  {
    name: "RMS Fort Lauderdale Jewel",
    description:
      "Combining traditional maritime charm with modern amenities, the RMS Fort Lauderdale Jewel promises an extraordinary voyage from its home port of Fort Lauderdale. This impressive mega yacht offers spacious accommodations, diverse dining options, and engaging activities for travelers of all ages.",
    type: "mega-yacht",
    capacity: 1523,
    length: 404,
    width: 70,
    speed: 15,
    yearBuilt: 2023,
    homePort: {
      city: "Fort Lauderdale",
      country: "United States",
      coordinates: { latitude: 26.122439, longitude: -80.137317 },
    },
    specifications: {
      engineType: "Gas Turbine Powerplant",
      fuelCapacity: 14140,
      waterCapacity: 456900,
      propulsionType: "Cycloidal Drive",
      hullMaterial: "Ice-Strengthened Steel",
      classification: "Russian Maritime Register of Shipping KM",
      safetyEquipment: [
        "Survival craft VHF radios",
        "Personal locator beacons",
        "Satellite emergency notification devices",
        "Hyperbaric treatment chambers",
        "Automated external defibrillators (AEDs)",
      ],
      navigationEquipment: [
        "Radar and automatic radar plotting aids (ARPAs)",
        "Integrated navigation system displays",
        "Night vision systems",
        "River radar systems",
        "Voyage data recorders (VDRs)",
      ],
      communicationEquipment: [
        "Ship-to-shore communication links",
        "Public address systems",
        "Broadband internet throughout",
      ],
      entertainmentEquipment: [
        "Multiple swimming pools and water features",
        "Cinema with latest releases",
        "Theater with Broadway-style productions",
      ],
      accessibilityFeatures: [
        "Wheelchair accessible cabins",
        "Assistive listening devices",
      ],
      environmentalFeatures: [
        "Biodegradable hydraulic fluids",
        "Exhaust gas cleaning systems",
      ],
    },
    isLuxuryVessel: true,
    isPetFriendly: false,
  },
];
