// This file is auto-generated
    // Do not edit manually.
    // City: George Town
    // Generated on: 2025-06-10T03:09:08.299Z
    
    import { Vessels } from "@/lib/interfaces/services/cruises";

export const georgeTownVessels: Vessels[] = [
  {
    id: "cs--explorer",
    name: "CS  Explorer",
    description: "The CS  Explorer stands as a testament to luxury and innovation on the high seas. Departing from George Town, this sophisticated luxury cruise ship features immersive entertainment, wellness facilities, and exquisite cuisine prepared by internationally renowned chefs.",
    type: "luxury-cruise-ship",
    capacity: 839,
    length: 267,
    width: 50,
    speed: 28,
    topSpeed: 31, 
    yearBuilt: 2024,
    homePort: {"city":"George Town","country":"Cayman Islands","coordinates":{"latitude":19.2855,"longitude":-81.2546}},
    specifications: {
      engineType: "Hybrid Power System",
      fuelCapacity: 6670,
      waterCapacity: 251700,
      propulsionType: "Cycloidal Drive",
      hullMaterial: "Reinforced Aluminum",
      classification: "Russian Maritime Register of Shipping KM",
      safetyEquipment: ["Automated external defibrillators (AEDs)","Searchlights and rescue equipment"],
      navigationEquipment: ["Integrated navigation system displays","Automatic identification systems (AIS)","Long-range identification and tracking (LRIT)"],
      communicationEquipment: ["Broadband internet throughout","Maritime VHF radio systems","Satellite communication systems"],
      entertainmentEquipment: ["Theater with Broadway-style productions","Children's entertainment areas","Culinary demonstration kitchens","Art gallery and auction facilities","Observation lounges with panoramic views"],
      accessibilityFeatures: ["Braille signage throughout","Elevator access to all public decks","Accessible entertainment venues"],
      environmentalFeatures: ["Advanced water treatment systems","Solar panel supplementation","Shore power connectivity","Ballast water management technology"]
    },
    isLuxuryVessel: true,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "mv-george-town-voyager",
    name: "MV George Town Voyager",
    description: "Sailing from the picturesque port of George Town, the MV George Town Voyager represents a new era in cruise experiences. This remarkable adults only ship combines innovative design with thoughtful amenities, creating an atmosphere of refined elegance and warm hospitality.",
    type: "adults-only-ship",
    capacity: 1142,
    length: 328,
    width: 59,
    speed: 26,
    topSpeed: 30, 
    yearBuilt: 2010,
    homePort: {"city":"George Town","country":"Cayman Islands","coordinates":{"latitude":19.2855,"longitude":-81.2546}},
    specifications: {
      engineType: "Solar-Assisted Electric",
      fuelCapacity: 9670,
      waterCapacity: 342599,
      propulsionType: "Azipod Electric Propulsion",
      hullMaterial: "Marine-Grade Steel",
      classification: "Lloyd's Register Class 1",
      safetyEquipment: ["Thermal imaging cameras","Satellite emergency notification devices","Advanced fire detection and suppression systems","Hyperbaric treatment chambers","Marine evacuation systems (MES)"],
      navigationEquipment: ["Autopilot systems with track control","Echo sounders and sonar systems"],
      communicationEquipment: ["Emergency position-indicating radio beacons","Marine radio telephony","Digital selective calling equipment"],
      entertainmentEquipment: ["Culinary demonstration kitchens","Dance clubs and live music venues","Library and educational facilities","Full-service spa and fitness center","Children's entertainment areas"],
      accessibilityFeatures: ["Transfer chairs for pool access","Service animal accommodations"],
      environmentalFeatures: ["Ballast water management technology","Heat recovery systems","Dynamic routing to optimize fuel usage","Exhaust gas cleaning systems"]
    },
    isLuxuryVessel: true,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "cs--of-the-deep",
    name: "CS  of the Deep",
    description: "The CS  of the Deep offers an unparalleled cruising experience from George Town, combining luxury amenities with state-of-the-art navigation technology. This polar expedition ship features spacious cabins, gourmet dining options, and entertainment venues that showcase the best of Cayman Islands hospitality.",
    type: "polar-expedition-ship",
    capacity: 691,
    length: 238,
    width: 45,
    speed: 23,
    topSpeed: 26, 
    yearBuilt: 2019,
    homePort: {"city":"George Town","country":"Cayman Islands","coordinates":{"latitude":19.2855,"longitude":-81.2546}},
    specifications: {
      engineType: "Gas Turbine Powerplant",
      fuelCapacity: 5350,
      waterCapacity: 207299,
      propulsionType: "Voith Schneider Propellers",
      hullMaterial: "Hybrid Steel-Composite",
      classification: "RINA Green Star Plus",
      safetyEquipment: ["Marine evacuation systems (MES)","Digital safety monitoring systems","Thermal imaging cameras","Automated external defibrillators (AEDs)"],
      navigationEquipment: ["Integrated bridge systems","Autopilot systems with track control","Automatic identification systems (AIS)","Dynamic positioning systems","Weather routing systems"],
      communicationEquipment: ["Marine radio telephony","Global Maritime Distress Safety System (GMDSS)"],
      entertainmentEquipment: ["Library and educational facilities","Theater with Broadway-style productions"],
      accessibilityFeatures: ["Accessible dining facilities","Braille signage throughout","Accessible shore excursion options","Roll-in showers"],
      environmentalFeatures: ["Shore power connectivity","Solar panel supplementation"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "nx-the--mariner",
    name: "NX The  Mariner",
    description: "Setting sail from the beautiful port of George Town, the NX The  Mariner is a floating paradise designed for the discerning traveler. This sublime short hop ferry boasts panoramic viewing decks, world-class cuisine, and personalized service that ensures an unforgettable journey.",
    type: "short-hop-ferry",
    capacity: 1483,
    length: 396,
    width: 69,
    speed: 17,
    topSpeed: 19, 
    yearBuilt: 2023,
    homePort: {"city":"George Town","country":"Cayman Islands","coordinates":{"latitude":19.2855,"longitude":-81.2546}},
    specifications: {
      engineType: "Podded Propulsion",
      fuelCapacity: 13660,
      waterCapacity: 444900,
      propulsionType: "Counter-Rotating Propellers",
      hullMaterial: "High-Tensile Steel Alloy",
      classification: "Russian Maritime Register of Shipping KM",
      safetyEquipment: ["Life jackets with integrated GPS","Water purification systems","Weather monitoring stations","Marine evacuation systems (MES)","Digital safety monitoring systems","Man overboard detection systems"],
      navigationEquipment: ["Gyrocompasses and magnetic compasses","Automatic identification systems (AIS)"],
      communicationEquipment: ["Ship-to-shore communication links","Maritime VHF radio systems","Marine radio telephony"],
      entertainmentEquipment: ["Children's entertainment areas","Art gallery and auction facilities","Multiple swimming pools and water features","Virtual reality gaming center"],
      accessibilityFeatures: ["Transfer chairs for pool access","Height-adjustable furniture in select cabins"],
      environmentalFeatures: ["Food waste digesters","Advanced water treatment systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "rv--gale",
    name: "RV  Gale",
    description: "With its distinctive profile and luxurious appointments, the RV  Gale stands as a jewel in the George Town harbor. This prestigious catamaran offers travelers a perfect combination of adventure and relaxation, with expert-guided excursions, world-class entertainment, and sublime culinary experiences.",
    type: "catamaran",
    capacity: 1413,
    length: 382,
    width: 67,
    speed: 26,
    topSpeed: 29, 
    yearBuilt: 2024,
    homePort: {"city":"George Town","country":"Cayman Islands","coordinates":{"latitude":19.2855,"longitude":-81.2546}},
    specifications: {
      engineType: "Dual-Fuel Marine Engines",
      fuelCapacity: 12790,
      waterCapacity: 423900,
      propulsionType: "Water Jets",
      hullMaterial: "Composite Materials",
      classification: "Bureau Veritas Star Class",
      safetyEquipment: ["Satellite emergency notification devices","Hyperbaric treatment chambers","Man overboard detection systems","Survival craft VHF radios"],
      navigationEquipment: ["Dynamic positioning systems","Radar and automatic radar plotting aids (ARPAs)","Night vision systems"],
      communicationEquipment: ["Broadband internet throughout","Ship-to-shore communication links"],
      entertainmentEquipment: ["Art gallery and auction facilities","Theater with Broadway-style productions","Children's entertainment areas","Multiple swimming pools and water features","Dance clubs and live music venues"],
      accessibilityFeatures: ["Service animal accommodations","Elevator access to all public decks","Accessible medical facilities","Tactile guidance systems"],
      environmentalFeatures: ["Food waste digesters","Noise reduction technology to minimize impact on marine life","Recyclable material management systems","Energy-efficient appliances","Ballast water management technology"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  }
];
