// This file is auto-generated
    // Do not edit manually.
    // City: Istanbul
    // Generated on: 2025-06-10T08:14:15.036Z
    
    import { Vessels } from "@/lib/interfaces/services/cruises";

export const istanbulVessels: Vessels[] = [
{
    id: "mv--explorer",
    name: "MV  Explorer",
    description: "The MV  Explorer offers an unparalleled cruising experience from Istanbul, combining luxury amenities with state-of-the-art navigation technology. This mega yacht features spacious cabins, gourmet dining options, and entertainment venues that showcase the best of Turkey hospitality.",
    type: "mega-yacht",
    capacity: 1868,
    length: 473,
    width: 80,
    speed: 28,
    topSpeed: 32, 
    yearBuilt: 2011,
    homePort: {"city":"Istanbul","country":"Turkey","coordinates":{"latitude":0,"longitude":0}},
    specifications: {
      engineType: "Podded Propulsion",
      fuelCapacity: 18920,
      waterCapacity: 560400,
      propulsionType: "Conventional Shaft Propellers",
      hullMaterial: "Reinforced Aluminum",
      classification: "American Bureau of Shipping A1",
      safetyEquipment: ["Personal locator beacons","Emergency position indicating radio beacons (EPIRBs)","Man overboard detection systems","Thermal imaging cameras"],
      navigationEquipment: ["Night vision systems","Integrated navigation system displays","Weather routing systems","Global navigation satellite systems (GNSS)"],
      communicationEquipment: ["Emergency position-indicating radio beacons","Maritime VHF radio systems","Marine radio telephony"],
      entertainmentEquipment: ["Climbing walls and sports courts","Art gallery and auction facilities"],
      accessibilityFeatures: ["Accessible entertainment venues","Transfer chairs for pool access","Braille signage throughout","Hearing augmentation systems"],
      environmentalFeatures: ["Heat recovery systems","Marine ecosystem monitoring equipment","Recyclable material management systems","Dynamic routing to optimize fuel usage"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "rms-istanbul-voyager",
    name: "RMS Istanbul Voyager",
    description: "The RMS Istanbul Voyager invites travelers to explore the treasures of Turkey in unmatched comfort. This exceptional luxury cruise ship, based in Istanbul, features curated excursions, immersive cultural programs, and luxurious accommodations that ensure an unforgettable journey.",
    type: "luxury-cruise-ship",
    capacity: 898,
    length: 279,
    width: 51,
    speed: 28,
    topSpeed: 32, 
    yearBuilt: 2007,
    homePort: {"city":"Istanbul","country":"Turkey","coordinates":{"latitude":0,"longitude":0}},
    specifications: {
      engineType: "Azimuth Thrusters",
      fuelCapacity: 7110,
      waterCapacity: 269400,
      propulsionType: "Cycloidal Drive",
      hullMaterial: "Marine-Grade Steel",
      classification: "DNV GL High Speed & Light Craft",
      safetyEquipment: ["Digital safety monitoring systems","Personal locator beacons","Tactical response equipment","Hyperbaric treatment chambers","Comprehensive medical facilities"],
      navigationEquipment: ["Weather routing systems","Long-range identification and tracking (LRIT)"],
      communicationEquipment: ["Internal crew communication network","Broadband internet throughout"],
      entertainmentEquipment: ["Library and educational facilities","Observation lounges with panoramic views","Casino with table games and slot machines","Multiple swimming pools and water features"],
      accessibilityFeatures: ["Accessible entertainment venues","Roll-in showers"],
      environmentalFeatures: ["Energy-efficient appliances","Food waste digesters","Ballast water management technology"]
    },
    isLuxuryVessel: true,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "my--of-the-deep",
    name: "MY  of the Deep",
    description: "The MY  of the Deep stands as a testament to luxury and innovation on the high seas. Departing from Istanbul, this sophisticated polar expedition ship features immersive entertainment, wellness facilities, and exquisite cuisine prepared by internationally renowned chefs.",
    type: "polar-expedition-ship",
    capacity: 1993,
    length: 498,
    width: 84,
    speed: 18,
    topSpeed: 20, 
    yearBuilt: 2013,
    homePort: {"city":"Istanbul","country":"Turkey","coordinates":{"latitude":0,"longitude":0}},
    specifications: {
      engineType: "LNG-Powered Engines",
      fuelCapacity: 20910,
      waterCapacity: 597900,
      propulsionType: "Counter-Rotating Propellers",
      hullMaterial: "Marine-Grade Steel",
      classification: "China Classification Society B",
      safetyEquipment: ["Thermal imaging cameras","Man overboard detection systems","Automated external defibrillators (AEDs)","Advanced fire detection and suppression systems","Marine evacuation systems (MES)","Emergency position indicating radio beacons (EPIRBs)","Hyperbaric treatment chambers"],
      navigationEquipment: ["Dynamic positioning systems","Integrated bridge systems"],
      communicationEquipment: ["Internal crew communication network","Emergency position-indicating radio beacons"],
      entertainmentEquipment: ["Art gallery and auction facilities","Dance clubs and live music venues","Culinary demonstration kitchens","Children's entertainment areas"],
      accessibilityFeatures: ["Height-adjustable furniture in select cabins","Visual alarm systems"],
      environmentalFeatures: ["Noise reduction technology to minimize impact on marine life","Advanced water treatment systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "fv-the--mariner",
    name: "FV The  Mariner",
    description: "The majestic FV The  Mariner represents the pinnacle of maritime engineering and hospitality. Based in Istanbul, this exceptional river cruise ship features lavish interiors, cutting-edge facilities, and carefully curated experiences that celebrate the unique culture of the Turkey region.",
    type: "river-cruise-ship",
    capacity: 1039,
    length: 307,
    width: 56,
    speed: 26,
    topSpeed: 29, 
    yearBuilt: 2012,
    homePort: {"city":"Istanbul","country":"Turkey","coordinates":{"latitude":0,"longitude":0}},
    specifications: {
      engineType: "Podded Propulsion",
      fuelCapacity: 8590,
      waterCapacity: 311700,
      propulsionType: "Counter-Rotating Propellers",
      hullMaterial: "Marine-Grade Steel",
      classification: "China Classification Society B",
      safetyEquipment: ["Satellite emergency notification devices","Radar reflectors","Automated external defibrillators (AEDs)","Man overboard detection systems"],
      navigationEquipment: ["Navigation data management systems","Gyrocompasses and magnetic compasses","Inland ECDIS"],
      communicationEquipment: ["Public address systems","Broadband internet throughout"],
      entertainmentEquipment: ["Full-service spa and fitness center","Multiple swimming pools and water features","Children's entertainment areas"],
      accessibilityFeatures: ["Assistive listening devices","Braille signage throughout","Transfer chairs for pool access"],
      environmentalFeatures: ["Solar panel supplementation","Shore power connectivity","Marine ecosystem monitoring equipment","Optimized hull design for reduced fuel consumption","LED lighting throughout"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "fv--gale",
    name: "FV  Gale",
    description: "Experience the epitome of maritime excellence aboard the FV  Gale, a premier chartered vessel sailing from Istanbul. With its elegant design, state-of-the-art technology, and exceptional service, every journey promises unforgettable moments and unparalleled comfort.",
    type: "chartered-vessel",
    capacity: 1052,
    length: 310,
    width: 56,
    speed: 28,
    topSpeed: 32, 
    yearBuilt: 2009,
    homePort: {"city":"Istanbul","country":"Turkey","coordinates":{"latitude":0,"longitude":0}},
    specifications: {
      engineType: "Diesel-Electric Propulsion",
      fuelCapacity: 8680,
      waterCapacity: 315599,
      propulsionType: "Counter-Rotating Propellers",
      hullMaterial: "Hybrid Steel-Composite",
      classification: "Lloyd's Register Class 1",
      safetyEquipment: ["Emergency position indicating radio beacons (EPIRBs)","Hyperbaric treatment chambers","Tactical response equipment","Comprehensive medical facilities"],
      navigationEquipment: ["Weather routing systems","Integrated navigation system displays","Night vision systems","Gyrocompasses and magnetic compasses"],
      communicationEquipment: ["Ship-to-shore communication links","Maritime VHF radio systems"],
      entertainmentEquipment: ["Dance clubs and live music venues","Multi-purpose event spaces","Climbing walls and sports courts","Observation lounges with panoramic views"],
      accessibilityFeatures: ["Accessible dining facilities","Height-adjustable furniture in select cabins","Roll-in showers"],
      environmentalFeatures: ["Recyclable material management systems","Energy-efficient appliances"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "cs--explorer",
    name: "CS  Explorer",
    description: "The magnificent CS  Explorer offers a perfect blend of adventure and relaxation for travelers departing from Istanbul. This outstanding adults only ship features panoramic ocean views, specialized dining experiences, and enriching activities that connect guests with the wonders of the Turkey region.",
    type: "adults-only-ship",
    capacity: 1278,
    length: 355,
    width: 63,
    speed: 20,
    topSpeed: 22, 
    yearBuilt: 2012,
    homePort: {"city":"Istanbul","country":"Turkey","coordinates":{"latitude":0,"longitude":0}},
    specifications: {
      engineType: "Podded Propulsion",
      fuelCapacity: 11180,
      waterCapacity: 383400,
      propulsionType: "Z-Drive Propulsion",
      hullMaterial: "Ice-Strengthened Steel",
      classification: "RINA Green Star Plus",
      safetyEquipment: ["Marine evacuation systems (MES)","Survival craft VHF radios","Hyperbaric treatment chambers"],
      navigationEquipment: ["Electronic chart display information systems (ECDIS)","Navigation data management systems"],
      communicationEquipment: ["Maritime VHF radio systems","Satellite communication systems"],
      entertainmentEquipment: ["Climbing walls and sports courts","Cinema with latest releases","Culinary demonstration kitchens"],
      accessibilityFeatures: ["Roll-in showers","Transfer chairs for pool access"],
      environmentalFeatures: ["Solar panel supplementation","Energy-efficient appliances","Marine ecosystem monitoring equipment","Exhaust gas cleaning systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "my-istanbul-voyager",
    name: "MY Istanbul Voyager",
    description: "The magnificent MY Istanbul Voyager offers a perfect blend of adventure and relaxation for travelers departing from Istanbul. This outstanding chartered vessel features panoramic ocean views, specialized dining experiences, and enriching activities that connect guests with the wonders of the Turkey region.",
    type: "chartered-vessel",
    capacity: 682,
    length: 236,
    width: 45,
    speed: 27,
    topSpeed: 31, 
    yearBuilt: 2018,
    homePort: {"city":"Istanbul","country":"Turkey","coordinates":{"latitude":0,"longitude":0}},
    specifications: {
      engineType: "Integrated Power Systems",
      fuelCapacity: 5310,
      waterCapacity: 204600,
      propulsionType: "Voith Schneider Propellers",
      hullMaterial: "Hybrid Steel-Composite",
      classification: "RINA Green Star Plus",
      safetyEquipment: ["Automated external defibrillators (AEDs)","Thermal imaging cameras","Radar reflectors","Survival craft VHF radios","Advanced fire detection and suppression systems"],
      navigationEquipment: ["Electronic chart display information systems (ECDIS)","Integrated bridge systems"],
      communicationEquipment: ["Broadband internet throughout","Internal crew communication network","Public address systems"],
      entertainmentEquipment: ["Art gallery and auction facilities","Library and educational facilities","Observation lounges with panoramic views"],
      accessibilityFeatures: ["Tactile guidance systems","Assistive listening devices","Service animal accommodations","Height-adjustable furniture in select cabins"],
      environmentalFeatures: ["Heat recovery systems","Optimized hull design for reduced fuel consumption","Solar panel supplementation","Exhaust gas cleaning systems","Ballast water management technology"]
    },
    isLuxuryVessel: true,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "rv--of-the-deep",
    name: "RV  of the Deep",
    description: "Experience the epitome of maritime excellence aboard the RV  of the Deep, a premier luxury cruise ship sailing from Istanbul. With its elegant design, state-of-the-art technology, and exceptional service, every journey promises unforgettable moments and unparalleled comfort.",
    type: "luxury-cruise-ship",
    capacity: 442,
    length: 188,
    width: 38,
    speed: 28,
    topSpeed: 33, 
    yearBuilt: 2017,
    homePort: {"city":"Istanbul","country":"Turkey","coordinates":{"latitude":0,"longitude":0}},
    specifications: {
      engineType: "Diesel-Electric Propulsion",
      fuelCapacity: 3570,
      waterCapacity: 132600,
      propulsionType: "Counter-Rotating Propellers",
      hullMaterial: "Ice-Strengthened Steel",
      classification: "China Classification Society B",
      safetyEquipment: ["Weather monitoring stations","Comprehensive medical facilities","Radar reflectors","Water purification systems","Searchlights and rescue equipment"],
      navigationEquipment: ["Doppler speed logs","Inland ECDIS"],
      communicationEquipment: ["Public address systems","Marine radio telephony"],
      entertainmentEquipment: ["Immersive simulation experiences","Multiple swimming pools and water features","Multi-purpose event spaces","Library and educational facilities"],
      accessibilityFeatures: ["Braille signage throughout","Assistive listening devices","Accessible shore excursion options"],
      environmentalFeatures: ["Food waste digesters","Exhaust gas cleaning systems","Ballast water management technology","Biodegradable hydraulic fluids","Heat recovery systems"]
    },
    isLuxuryVessel: true,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "fv-the--mariner",
    name: "FV The  Mariner",
    description: "Experience the epitome of maritime excellence aboard the FV The  Mariner, a premier resort style ship sailing from Istanbul. With its elegant design, state-of-the-art technology, and exceptional service, every journey promises unforgettable moments and unparalleled comfort.",
    type: "resort-style-ship",
    capacity: 1729,
    length: 445,
    width: 76,
    speed: 16,
    topSpeed: 18, 
    yearBuilt: 2014,
    homePort: {"city":"Istanbul","country":"Turkey","coordinates":{"latitude":0,"longitude":0}},
    specifications: {
      engineType: "LNG-Powered Engines",
      fuelCapacity: 16910,
      waterCapacity: 518699,
      propulsionType: "Z-Drive Propulsion",
      hullMaterial: "Hybrid Steel-Composite",
      classification: "DNV GL High Speed & Light Craft",
      safetyEquipment: ["Personal locator beacons","Emergency escape breathing devices","Digital safety monitoring systems"],
      navigationEquipment: ["Dynamic positioning systems","Night vision systems"],
      communicationEquipment: ["Marine radio telephony","Global Maritime Distress Safety System (GMDSS)"],
      entertainmentEquipment: ["Cinema with latest releases","Immersive simulation experiences","Multiple swimming pools and water features"],
      accessibilityFeatures: ["Braille signage throughout","Transfer chairs for pool access"],
      environmentalFeatures: ["Biodegradable hydraulic fluids","Optimized hull design for reduced fuel consumption","Dynamic routing to optimize fuel usage"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "sv--gale",
    name: "SV  Gale",
    description: "The SV  Gale offers an unparalleled cruising experience from Istanbul, combining luxury amenities with state-of-the-art navigation technology. This small ocean ship features spacious cabins, gourmet dining options, and entertainment venues that showcase the best of Turkey hospitality.",
    type: "small-ocean-ship",
    capacity: 1988,
    length: 497,
    width: 84,
    speed: 15,
    topSpeed: 17, 
    yearBuilt: 2012,
    homePort: {"city":"Istanbul","country":"Turkey","coordinates":{"latitude":0,"longitude":0}},
    specifications: {
      engineType: "Hybrid Power System",
      fuelCapacity: 20870,
      waterCapacity: 596400,
      propulsionType: "Conventional Shaft Propellers",
      hullMaterial: "Composite Materials",
      classification: "Russian Maritime Register of Shipping KM",
      safetyEquipment: ["Radar reflectors","Thermal imaging cameras","Comprehensive medical facilities"],
      navigationEquipment: ["Automatic identification systems (AIS)","Doppler speed logs"],
      communicationEquipment: ["Emergency position-indicating radio beacons","Maritime VHF radio systems","Marine radio telephony"],
      entertainmentEquipment: ["Casino with table games and slot machines","Art gallery and auction facilities","Cinema with latest releases"],
      accessibilityFeatures: ["Height-adjustable furniture in select cabins","Elevator access to all public decks","Service animal accommodations","Hearing augmentation systems"],
      environmentalFeatures: ["Noise reduction technology to minimize impact on marine life","Recyclable material management systems","Solar panel supplementation"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  }
];
