// This file is auto-generated
    // Do not edit manually.
    // City: Lisbon
    // Generated on: 2025-06-08T07:59:32.395Z
    
    import { Vessels } from "@/lib/interfaces/services/cruises";

export const lisbonVessels: Vessels[] = [
{
    id: "rms--explorer",
    name: "RMS  Explorer",
    description: "Sailing from the picturesque port of Lisbon, the RMS  Explorer represents a new era in cruise experiences. This remarkable eco friendly hybrid ship combines innovative design with thoughtful amenities, creating an atmosphere of refined elegance and warm hospitality.",
    type: "eco-friendly-hybrid-ship",
    capacity: 1379,
    length: 375,
    width: 66,
    speed: 27,
    topSpeed: 31, 
    yearBuilt: 2015,
    homePort: {"city":"Lisbon","country":"Portugal","coordinates":{"latitude":38.7169,"longitude":-9.1399}},
    specifications: {
      engineType: "Integrated Power Systems",
      fuelCapacity: 12370,
      waterCapacity: 413700,
      propulsionType: "Cycloidal Drive",
      hullMaterial: "Ice-Strengthened Steel",
      classification: "Lloyd's Register Class 1",
      safetyEquipment: ["Digital safety monitoring systems","Hyperbaric treatment chambers","Personal locator beacons","Satellite emergency notification devices","Emergency position indicating radio beacons (EPIRBs)","Automated external defibrillators (AEDs)"],
      navigationEquipment: ["Integrated navigation system displays","Infrared camera systems","Doppler speed logs","Navigation data management systems","Global navigation satellite systems (GNSS)"],
      communicationEquipment: ["Satellite communication systems","Emergency position-indicating radio beacons"],
      entertainmentEquipment: ["Culinary demonstration kitchens","Library and educational facilities"],
      accessibilityFeatures: ["Assistive listening devices","Roll-in showers","Hearing augmentation systems"],
      environmentalFeatures: ["Solar panel supplementation","Ballast water management technology","Shore power connectivity"]
    },
    isLuxuryVessel: true,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ps-lisbon-voyager",
    name: "PS Lisbon Voyager",
    description: "Sailing from the picturesque port of Lisbon, the PS Lisbon Voyager represents a new era in cruise experiences. This remarkable polar expedition ship combines innovative design with thoughtful amenities, creating an atmosphere of refined elegance and warm hospitality.",
    type: "polar-expedition-ship",
    capacity: 535,
    length: 207,
    width: 41,
    speed: 19,
    topSpeed: 21, 
    yearBuilt: 2006,
    homePort: {"city":"Lisbon","country":"Portugal","coordinates":{"latitude":38.7169,"longitude":-9.1399}},
    specifications: {
      engineType: "Azimuth Thrusters",
      fuelCapacity: 4240,
      waterCapacity: 160500,
      propulsionType: "Water Jets",
      hullMaterial: "High-Tensile Steel Alloy",
      classification: "Bureau Veritas Star Class",
      safetyEquipment: ["Water purification systems","Radar reflectors","Marine evacuation systems (MES)","Thermal imaging cameras","Personal locator beacons"],
      navigationEquipment: ["Night vision systems","Long-range identification and tracking (LRIT)","Autopilot systems with track control"],
      communicationEquipment: ["Ship-to-shore communication links","Broadband internet throughout","Internal crew communication network"],
      entertainmentEquipment: ["Observation lounges with panoramic views","Immersive simulation experiences"],
      accessibilityFeatures: ["Assistive listening devices","Accessible dining facilities"],
      environmentalFeatures: ["Exhaust gas cleaning systems","Shore power connectivity","Marine ecosystem monitoring equipment","Energy-efficient appliances","LED lighting throughout"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "sy--of-the-deep",
    name: "SY  of the Deep",
    description: "The SY  of the Deep stands as a testament to luxury and innovation on the high seas. Departing from Lisbon, this sophisticated party cruise ship features immersive entertainment, wellness facilities, and exquisite cuisine prepared by internationally renowned chefs.",
    type: "party-cruise-ship",
    capacity: 1676,
    length: 435,
    width: 75,
    speed: 18,
    topSpeed: 20, 
    yearBuilt: 2014,
    homePort: {"city":"Lisbon","country":"Portugal","coordinates":{"latitude":38.7169,"longitude":-9.1399}},
    specifications: {
      engineType: "LNG-Powered Engines",
      fuelCapacity: 16310,
      waterCapacity: 502799,
      propulsionType: "Cycloidal Drive",
      hullMaterial: "Marine-Grade Steel",
      classification: "American Bureau of Shipping A1",
      safetyEquipment: ["Digital safety monitoring systems","Thermal imaging cameras","Radar reflectors"],
      navigationEquipment: ["Gyrocompasses and magnetic compasses","Navigation data management systems","Voyage data recorders (VDRs)"],
      communicationEquipment: ["Internal crew communication network","Ship-to-shore communication links","Broadband internet throughout"],
      entertainmentEquipment: ["Climbing walls and sports courts","Library and educational facilities"],
      accessibilityFeatures: ["Elevator access to all public decks","Braille signage throughout","Accessible medical facilities","Visual alarm systems"],
      environmentalFeatures: ["Energy-efficient appliances","Ballast water management technology","Heat recovery systems","Optimized hull design for reduced fuel consumption"]
    },
    isLuxuryVessel: true,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "rv-the--mariner",
    name: "RV The  Mariner",
    description: "Setting sail from the beautiful port of Lisbon, the RV The  Mariner is a floating paradise designed for the discerning traveler. This remarkable eco friendly hybrid ship boasts panoramic viewing decks, world-class cuisine, and personalized service that ensures an unforgettable journey.",
    type: "eco-friendly-hybrid-ship",
    capacity: 1550,
    length: 410,
    width: 71,
    speed: 17,
    topSpeed: 19, 
    yearBuilt: 2005,
    homePort: {"city":"Lisbon","country":"Portugal","coordinates":{"latitude":38.7169,"longitude":-9.1399}},
    specifications: {
      engineType: "Podded Propulsion",
      fuelCapacity: 14550,
      waterCapacity: 465000,
      propulsionType: "Cycloidal Drive",
      hullMaterial: "Hybrid Steel-Composite",
      classification: "ClassNK NS* (Special Purpose Ship)",
      safetyEquipment: ["Weather monitoring stations","Tactical response equipment","Man overboard detection systems","Satellite emergency notification devices","Radar reflectors"],
      navigationEquipment: ["Autopilot systems with track control","Automatic identification systems (AIS)","Electronic chart display information systems (ECDIS)","Weather routing systems"],
      communicationEquipment: ["Digital selective calling equipment","Public address systems"],
      entertainmentEquipment: ["Climbing walls and sports courts","Observation lounges with panoramic views"],
      accessibilityFeatures: ["Accessible shore excursion options","Wheelchair accessible cabins","Braille signage throughout"],
      environmentalFeatures: ["Energy-efficient appliances","LED lighting throughout","Advanced water treatment systems","Exhaust gas cleaning systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ss--gale",
    name: "SS  Gale",
    description: "With its distinctive profile and luxurious appointments, the SS  Gale stands as a jewel in the Lisbon harbor. This prestigious ultra luxury cruise ship offers travelers a perfect combination of adventure and relaxation, with expert-guided excursions, world-class entertainment, and sublime culinary experiences.",
    type: "ultra-luxury-cruise-ship",
    capacity: 1145,
    length: 329,
    width: 59,
    speed: 15,
    topSpeed: 18, 
    yearBuilt: 2023,
    homePort: {"city":"Lisbon","country":"Portugal","coordinates":{"latitude":38.7169,"longitude":-9.1399}},
    specifications: {
      engineType: "Dual-Fuel Marine Engines",
      fuelCapacity: 9700,
      waterCapacity: 343500,
      propulsionType: "Water Jets",
      hullMaterial: "Ice-Strengthened Steel",
      classification: "American Bureau of Shipping A1",
      safetyEquipment: ["Survival craft VHF radios","Weather monitoring stations","Marine evacuation systems (MES)","Rescue boats and life rafts","Emergency position indicating radio beacons (EPIRBs)","Hyperbaric treatment chambers"],
      navigationEquipment: ["Inland ECDIS","Weather routing systems"],
      communicationEquipment: ["Public address systems","Ship-to-shore communication links","Marine radio telephony"],
      entertainmentEquipment: ["Multiple swimming pools and water features","Immersive simulation experiences","Climbing walls and sports courts","Full-service spa and fitness center"],
      accessibilityFeatures: ["Height-adjustable furniture in select cabins","Elevator access to all public decks","Visual alarm systems"],
      environmentalFeatures: ["LED lighting throughout","Energy-efficient appliances","Dynamic routing to optimize fuel usage","Shore power connectivity"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "fv--explorer",
    name: "FV  Explorer",
    description: "The majestic FV  Explorer represents the pinnacle of maritime engineering and hospitality. Based in Lisbon, this exceptional ice class ship features elegant interiors, cutting-edge facilities, and carefully curated experiences that celebrate the unique culture of the Portugal region.",
    type: "ice-class-ship",
    capacity: 615,
    length: 223,
    width: 43,
    speed: 26,
    topSpeed: 31, 
    yearBuilt: 2015,
    homePort: {"city":"Lisbon","country":"Portugal","coordinates":{"latitude":38.7169,"longitude":-9.1399}},
    specifications: {
      engineType: "Podded Propulsion",
      fuelCapacity: 4790,
      waterCapacity: 184500,
      propulsionType: "Conventional Shaft Propellers",
      hullMaterial: "Marine-Grade Steel",
      classification: "Lloyd's Register Class 1",
      safetyEquipment: ["Rescue boats and life rafts","Thermal imaging cameras","Comprehensive medical facilities"],
      navigationEquipment: ["Autopilot systems with track control","Integrated bridge systems","Radar and automatic radar plotting aids (ARPAs)"],
      communicationEquipment: ["Satellite communication systems","Digital selective calling equipment"],
      entertainmentEquipment: ["Immersive simulation experiences","Full-service spa and fitness center"],
      accessibilityFeatures: ["Roll-in showers","Accessible shore excursion options"],
      environmentalFeatures: ["Noise reduction technology to minimize impact on marine life","LED lighting throughout","Energy-efficient appliances","Biodegradable hydraulic fluids","Ballast water management technology"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "fv-lisbon-voyager",
    name: "FV Lisbon Voyager",
    description: "Setting sail from the beautiful port of Lisbon, the FV Lisbon Voyager is a floating paradise designed for the discerning traveler. This remarkable river cruise ship boasts panoramic viewing decks, world-class cuisine, and personalized service that ensures an unforgettable journey.",
    type: "river-cruise-ship",
    capacity: 1212,
    length: 342,
    width: 61,
    speed: 28,
    topSpeed: 32, 
    yearBuilt: 2023,
    homePort: {"city":"Lisbon","country":"Portugal","coordinates":{"latitude":38.7169,"longitude":-9.1399}},
    specifications: {
      engineType: "Azimuth Thrusters",
      fuelCapacity: 10430,
      waterCapacity: 363599,
      propulsionType: "Conventional Shaft Propellers",
      hullMaterial: "Ice-Strengthened Steel",
      classification: "RINA Green Star Plus",
      safetyEquipment: ["Tactical response equipment","Thermal imaging cameras","Searchlights and rescue equipment","Marine evacuation systems (MES)"],
      navigationEquipment: ["Global navigation satellite systems (GNSS)","River radar systems","Bridge alert management systems"],
      communicationEquipment: ["Marine radio telephony","Public address systems"],
      entertainmentEquipment: ["Climbing walls and sports courts","Art gallery and auction facilities","Children's entertainment areas","Immersive simulation experiences"],
      accessibilityFeatures: ["Wheelchair accessible cabins","Accessible dining facilities"],
      environmentalFeatures: ["Advanced water treatment systems","LED lighting throughout","Marine ecosystem monitoring equipment"]
    },
    isLuxuryVessel: true,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ps--of-the-deep",
    name: "PS  of the Deep",
    description: "The PS  of the Deep stands as a testament to luxury and innovation on the high seas. Departing from Lisbon, this sophisticated small ocean ship features immersive entertainment, wellness facilities, and exquisite cuisine prepared by internationally renowned chefs.",
    type: "small-ocean-ship",
    capacity: 602,
    length: 220,
    width: 43,
    speed: 21,
    topSpeed: 24, 
    yearBuilt: 2020,
    homePort: {"city":"Lisbon","country":"Portugal","coordinates":{"latitude":38.7169,"longitude":-9.1399}},
    specifications: {
      engineType: "Dual-Fuel Marine Engines",
      fuelCapacity: 4730,
      waterCapacity: 180600,
      propulsionType: "Counter-Rotating Propellers",
      hullMaterial: "Reinforced Aluminum",
      classification: "Lloyd's Register Class 1",
      safetyEquipment: ["Life jackets with integrated GPS","Advanced fire detection and suppression systems","Man overboard detection systems","Emergency position indicating radio beacons (EPIRBs)","Survival craft VHF radios","Tactical response equipment"],
      navigationEquipment: ["Gyrocompasses and magnetic compasses","Electronic chart display information systems (ECDIS)","Voyage data recorders (VDRs)"],
      communicationEquipment: ["Public address systems"],
      entertainmentEquipment: ["Observation lounges with panoramic views","Casino with table games and slot machines","Multiple swimming pools and water features"],
      accessibilityFeatures: ["Visual alarm systems","Accessible shore excursion options","Elevator access to all public decks"],
      environmentalFeatures: ["Biodegradable hydraulic fluids","LED lighting throughout","Noise reduction technology to minimize impact on marine life"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "mv--explorer",
    name: "MV  Explorer",
    description: "The MV  Explorer offers an unparalleled cruising experience from Lisbon, combining luxury amenities with state-of-the-art navigation technology. This eco friendly hybrid ship features spacious cabins, gourmet dining options, and entertainment venues that showcase the best of Portugal hospitality.",
    type: "eco-friendly-hybrid-ship",
    capacity: 1162,
    length: 332,
    width: 59,
    speed: 21,
    topSpeed: 24, 
    yearBuilt: 2005,
    homePort: {"city":"Lisbon","country":"Portugal","coordinates":{"latitude":38.7169,"longitude":-9.1399}},
    specifications: {
      engineType: "Azimuth Thrusters",
      fuelCapacity: 9790,
      waterCapacity: 348599,
      propulsionType: "Conventional Shaft Propellers",
      hullMaterial: "High-Tensile Steel Alloy",
      classification: "Bureau Veritas Star Class",
      safetyEquipment: ["Water purification systems","Emergency escape breathing devices","Comprehensive medical facilities","Rescue boats and life rafts","Life jackets with integrated GPS","Searchlights and rescue equipment"],
      navigationEquipment: ["River radar systems","Weather routing systems","Electronic chart display information systems (ECDIS)","Autopilot systems with track control"],
      communicationEquipment: ["Emergency position-indicating radio beacons","Marine radio telephony"],
      entertainmentEquipment: ["Observation lounges with panoramic views","Virtual reality gaming center"],
      accessibilityFeatures: ["Transfer chairs for pool access","Tactile guidance systems","Roll-in showers"],
      environmentalFeatures: ["Advanced water treatment systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "sy-lisbon-voyager",
    name: "SY Lisbon Voyager",
    description: "Sailing from the picturesque port of Lisbon, the SY Lisbon Voyager represents a new era in cruise experiences. This remarkable mainstream cruise ship combines innovative design with thoughtful amenities, creating an atmosphere of refined elegance and warm hospitality.",
    type: "mainstream-cruise-ship",
    capacity: 2703,
    length: 640,
    width: 106,
    speed: 20,
    topSpeed: 23, 
    yearBuilt: 2020,
    homePort: {"city":"Lisbon","country":"Portugal","coordinates":{"latitude":38.7169,"longitude":-9.1399}},
    specifications: {
      engineType: "Azimuth Thrusters",
      fuelCapacity: 33920,
      waterCapacity: 810900,
      propulsionType: "Podded Propulsion Units",
      hullMaterial: "Composite Materials",
      classification: "American Bureau of Shipping A1",
      safetyEquipment: ["Radar reflectors","Satellite emergency notification devices","Comprehensive medical facilities"],
      navigationEquipment: ["Dynamic positioning systems","Global navigation satellite systems (GNSS)","Doppler speed logs","Navigation data management systems","Autopilot systems with track control"],
      communicationEquipment: ["Maritime VHF radio systems","Broadband internet throughout"],
      entertainmentEquipment: ["Children's entertainment areas","Cinema with latest releases"],
      accessibilityFeatures: ["Accessible medical facilities","Service animal accommodations"],
      environmentalFeatures: ["Advanced water treatment systems"]
    },
    isLuxuryVessel: true,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ss--of-the-deep",
    name: "SS  of the Deep",
    description: "The majestic SS  of the Deep represents the pinnacle of maritime engineering and hospitality. Based in Lisbon, this exceptional small ocean ship features elegant interiors, cutting-edge facilities, and carefully curated experiences that celebrate the unique culture of the Portugal region.",
    type: "small-ocean-ship",
    capacity: 1224,
    length: 344,
    width: 61,
    speed: 23,
    topSpeed: 26, 
    yearBuilt: 2008,
    homePort: {"city":"Lisbon","country":"Portugal","coordinates":{"latitude":38.7169,"longitude":-9.1399}},
    specifications: {
      engineType: "Diesel-Electric Propulsion",
      fuelCapacity: 10490,
      waterCapacity: 367200,
      propulsionType: "Cycloidal Drive",
      hullMaterial: "Composite Materials",
      classification: "Bureau Veritas Star Class",
      safetyEquipment: ["Emergency position indicating radio beacons (EPIRBs)","Thermal imaging cameras","Marine evacuation systems (MES)"],
      navigationEquipment: ["Integrated navigation system displays","Echo sounders and sonar systems"],
      communicationEquipment: ["Public address systems","Satellite communication systems"],
      entertainmentEquipment: ["Multi-purpose event spaces","Multiple swimming pools and water features","Theater with Broadway-style productions"],
      accessibilityFeatures: ["Elevator access to all public decks","Service animal accommodations","Visual alarm systems","Accessible shore excursion options"],
      environmentalFeatures: ["Energy-efficient appliances","Noise reduction technology to minimize impact on marine life","Advanced water treatment systems","Biodegradable hydraulic fluids"]
    },
    isLuxuryVessel: true,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ps--explorer",
    name: "PS  Explorer",
    description: "The majestic PS  Explorer represents the pinnacle of maritime engineering and hospitality. Based in Lisbon, this exceptional polar expedition ship features elegant interiors, cutting-edge facilities, and carefully curated experiences that celebrate the unique culture of the Portugal region.",
    type: "polar-expedition-ship",
    capacity: 506,
    length: 201,
    width: 40,
    speed: 22,
    topSpeed: 26, 
    yearBuilt: 2015,
    homePort: {"city":"Lisbon","country":"Portugal","coordinates":{"latitude":38.7169,"longitude":-9.1399}},
    specifications: {
      engineType: "Hybrid Power System",
      fuelCapacity: 4020,
      waterCapacity: 151799,
      propulsionType: "Azipod Electric Propulsion",
      hullMaterial: "Ice-Strengthened Steel",
      classification: "China Classification Society B",
      safetyEquipment: ["Comprehensive medical facilities","Water purification systems","Man overboard detection systems","Hyperbaric treatment chambers"],
      navigationEquipment: ["Voyage data recorders (VDRs)","Radar and automatic radar plotting aids (ARPAs)","Weather routing systems"],
      communicationEquipment: ["Ship-to-shore communication links"],
      entertainmentEquipment: ["Cinema with latest releases","Climbing walls and sports courts","Observation lounges with panoramic views"],
      accessibilityFeatures: ["Service animal accommodations","Braille signage throughout"],
      environmentalFeatures: ["Optimized hull design for reduced fuel consumption","Energy-efficient appliances","Shore power connectivity"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "rms-lisbon-voyager",
    name: "RMS Lisbon Voyager",
    description: "With its distinctive profile and luxurious appointments, the RMS Lisbon Voyager stands as a jewel in the Lisbon harbor. This prestigious eco friendly hybrid ship offers travelers a perfect combination of adventure and relaxation, with expert-guided excursions, world-class entertainment, and sublime culinary experiences.",
    type: "eco-friendly-hybrid-ship",
    capacity: 1987,
    length: 497,
    width: 84,
    speed: 15,
    topSpeed: 18, 
    yearBuilt: 2013,
    homePort: {"city":"Lisbon","country":"Portugal","coordinates":{"latitude":38.7169,"longitude":-9.1399}},
    specifications: {
      engineType: "Azimuth Thrusters",
      fuelCapacity: 20870,
      waterCapacity: 596100,
      propulsionType: "Counter-Rotating Propellers",
      hullMaterial: "Ice-Strengthened Steel",
      classification: "Russian Maritime Register of Shipping KM",
      safetyEquipment: ["Satellite emergency notification devices","Radar reflectors","Advanced fire detection and suppression systems","Man overboard detection systems"],
      navigationEquipment: ["Integrated bridge systems","Night vision systems","Long-range identification and tracking (LRIT)","Echo sounders and sonar systems","Inland ECDIS"],
      communicationEquipment: ["Internal crew communication network","Digital selective calling equipment","Global Maritime Distress Safety System (GMDSS)"],
      entertainmentEquipment: ["Observation lounges with panoramic views","Virtual reality gaming center"],
      accessibilityFeatures: ["Transfer chairs for pool access","Accessible entertainment venues","Accessible medical facilities","Wheelchair accessible cabins"],
      environmentalFeatures: ["Recyclable material management systems","Heat recovery systems","Marine ecosystem monitoring equipment","Solar panel supplementation"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "my--of-the-deep",
    name: "MY  of the Deep",
    description: "Combining traditional maritime charm with modern amenities, the MY  of the Deep promises an extraordinary voyage from its home port of Lisbon. This impressive ocean liner offers spacious accommodations, diverse dining options, and engaging activities for travelers of all ages.",
    type: "ocean-liner",
    capacity: 1839,
    length: 467,
    width: 80,
    speed: 26,
    topSpeed: 30, 
    yearBuilt: 2008,
    homePort: {"city":"Lisbon","country":"Portugal","coordinates":{"latitude":38.7169,"longitude":-9.1399}},
    specifications: {
      engineType: "LNG-Powered Engines",
      fuelCapacity: 18680,
      waterCapacity: 551699,
      propulsionType: "Water Jets",
      hullMaterial: "Reinforced Aluminum",
      classification: "Russian Maritime Register of Shipping KM",
      safetyEquipment: ["Radar reflectors","Digital safety monitoring systems","Emergency position indicating radio beacons (EPIRBs)","Survival craft VHF radios","Marine evacuation systems (MES)","Rescue boats and life rafts","Water purification systems"],
      navigationEquipment: ["Global navigation satellite systems (GNSS)","Bridge alert management systems","Gyrocompasses and magnetic compasses"],
      communicationEquipment: ["Digital selective calling equipment","Ship-to-shore communication links"],
      entertainmentEquipment: ["Theater with Broadway-style productions","Cinema with latest releases","Virtual reality gaming center"],
      accessibilityFeatures: ["Assistive listening devices","Wheelchair accessible cabins","Hearing augmentation systems","Accessible medical facilities"],
      environmentalFeatures: ["Advanced water treatment systems","Marine ecosystem monitoring equipment","Ballast water management technology","Optimized hull design for reduced fuel consumption"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "sv--explorer",
    name: "SV  Explorer",
    description: "The magnificent SV  Explorer offers a perfect blend of adventure and relaxation for travelers departing from Lisbon. This outstanding short hop ferry features panoramic ocean views, specialized dining experiences, and enriching activities that connect guests with the wonders of the Portugal region.",
    type: "short-hop-ferry",
    capacity: 1984,
    length: 496,
    width: 84,
    speed: 19,
    topSpeed: 21, 
    yearBuilt: 2010,
    homePort: {"city":"Lisbon","country":"Portugal","coordinates":{"latitude":38.7169,"longitude":-9.1399}},
    specifications: {
      engineType: "LNG-Powered Engines",
      fuelCapacity: 20830,
      waterCapacity: 595199,
      propulsionType: "Azipod Electric Propulsion",
      hullMaterial: "Ice-Strengthened Steel",
      classification: "ClassNK NS* (Special Purpose Ship)",
      safetyEquipment: ["Comprehensive medical facilities","Digital safety monitoring systems","Searchlights and rescue equipment"],
      navigationEquipment: ["Dynamic positioning systems","Night vision systems","Global navigation satellite systems (GNSS)"],
      communicationEquipment: ["Emergency position-indicating radio beacons","Digital selective calling equipment","Marine radio telephony"],
      entertainmentEquipment: ["Casino with table games and slot machines","Culinary demonstration kitchens","Immersive simulation experiences","Virtual reality gaming center"],
      accessibilityFeatures: ["Braille signage throughout","Accessible medical facilities","Accessible dining facilities","Accessible entertainment venues"],
      environmentalFeatures: ["Recyclable material management systems","Food waste digesters"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "sv-lisbon-voyager",
    name: "SV Lisbon Voyager",
    description: "With its distinctive profile and luxurious appointments, the SV Lisbon Voyager stands as a jewel in the Lisbon harbor. This prestigious superyacht offers travelers a perfect combination of adventure and relaxation, with expert-guided excursions, world-class entertainment, and sublime culinary experiences.",
    type: "superyacht",
    capacity: 886,
    length: 277,
    width: 51,
    speed: 28,
    topSpeed: 31, 
    yearBuilt: 2012,
    homePort: {"city":"Lisbon","country":"Portugal","coordinates":{"latitude":38.7169,"longitude":-9.1399}},
    specifications: {
      engineType: "Azimuth Thrusters",
      fuelCapacity: 7060,
      waterCapacity: 265800,
      propulsionType: "Conventional Shaft Propellers",
      hullMaterial: "Composite Materials",
      classification: "China Classification Society B",
      safetyEquipment: ["Rescue boats and life rafts","Advanced fire detection and suppression systems","Thermal imaging cameras"],
      navigationEquipment: ["Navigation data management systems","Voyage data recorders (VDRs)","Integrated navigation system displays","Electronic chart display information systems (ECDIS)"],
      communicationEquipment: ["Internal crew communication network","Broadband internet throughout","Marine radio telephony"],
      entertainmentEquipment: ["Theater with Broadway-style productions","Multi-purpose event spaces","Virtual reality gaming center","Culinary demonstration kitchens"],
      accessibilityFeatures: ["Height-adjustable furniture in select cabins","Tactile guidance systems"],
      environmentalFeatures: ["Optimized hull design for reduced fuel consumption","Exhaust gas cleaning systems","Energy-efficient appliances"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ms--of-the-deep",
    name: "MS  of the Deep",
    description: "The MS  of the Deep stands as a testament to luxury and innovation on the high seas. Departing from Lisbon, this sophisticated eco friendly hybrid ship features immersive entertainment, wellness facilities, and exquisite cuisine prepared by internationally renowned chefs.",
    type: "eco-friendly-hybrid-ship",
    capacity: 1064,
    length: 312,
    width: 56,
    speed: 21,
    topSpeed: 25, 
    yearBuilt: 2005,
    homePort: {"city":"Lisbon","country":"Portugal","coordinates":{"latitude":38.7169,"longitude":-9.1399}},
    specifications: {
      engineType: "Dual-Fuel Marine Engines",
      fuelCapacity: 8730,
      waterCapacity: 319200,
      propulsionType: "Cycloidal Drive",
      hullMaterial: "Composite Materials",
      classification: "RINA Green Star Plus",
      safetyEquipment: ["Automated external defibrillators (AEDs)","Tactical response equipment","Rescue boats and life rafts","Hyperbaric treatment chambers"],
      navigationEquipment: ["Integrated navigation system displays","Infrared camera systems","Automatic identification systems (AIS)","Inland ECDIS"],
      communicationEquipment: ["Global Maritime Distress Safety System (GMDSS)","Satellite communication systems"],
      entertainmentEquipment: ["Art gallery and auction facilities","Theater with Broadway-style productions","Casino with table games and slot machines"],
      accessibilityFeatures: ["Roll-in showers","Assistive listening devices","Transfer chairs for pool access"],
      environmentalFeatures: ["Marine ecosystem monitoring equipment","Ballast water management technology","LED lighting throughout","Energy-efficient appliances","Exhaust gas cleaning systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  }
];
