// This file is auto-generated
    // Do not edit manually.
    // City: London
    // Generated on: 2025-06-08T07:59:32.395Z
    
    import { Vessels } from "@/lib/interfaces/services/cruises";

export const londonVessels: Vessels[] = [
{
    id: "ms--explorer",
    name: "MS  Explorer",
    description: "The majestic MS  Explorer represents the pinnacle of maritime engineering and hospitality. Based in London, this exceptional short hop ferry features elegant interiors, cutting-edge facilities, and carefully curated experiences that celebrate the unique culture of the England region.",
    type: "short-hop-ferry",
    capacity: 962,
    length: 292,
    width: 53,
    speed: 20,
    topSpeed: 22, 
    yearBuilt: 2021,
    homePort: {"city":"London","country":"United Kingdom","coordinates":{"latitude":51.5074,"longitude":-0.1278}},
    specifications: {
      engineType: "Hybrid Power System",
      fuelCapacity: 7730,
      waterCapacity: 288599,
      propulsionType: "Cycloidal Drive",
      hullMaterial: "Marine-Grade Steel",
      classification: "ClassNK NS* (Special Purpose Ship)",
      safetyEquipment: ["Emergency escape breathing devices","Marine evacuation systems (MES)","Personal locator beacons"],
      navigationEquipment: ["Electronic chart display information systems (ECDIS)","Navigation data management systems","Gyrocompasses and magnetic compasses"],
      communicationEquipment: ["Global Maritime Distress Safety System (GMDSS)","Broadband internet throughout"],
      entertainmentEquipment: ["Full-service spa and fitness center","Immersive simulation experiences"],
      accessibilityFeatures: ["Accessible dining facilities","Service animal accommodations","Hearing augmentation systems"],
      environmentalFeatures: ["Exhaust gas cleaning systems","Marine ecosystem monitoring equipment","Ballast water management technology","Heat recovery systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "mv-london-voyager",
    name: "MV London Voyager",
    description: "The MV London Voyager invites travelers to explore the treasures of England in unmatched comfort. This exceptional short hop ferry, based in London, features curated excursions, immersive cultural programs, and luxurious accommodations that ensure an unforgettable journey.",
    type: "short-hop-ferry",
    capacity: 1731,
    length: 446,
    width: 76,
    speed: 28,
    topSpeed: 31, 
    yearBuilt: 2024,
    homePort: {"city":"London","country":"United Kingdom","coordinates":{"latitude":51.5074,"longitude":-0.1278}},
    specifications: {
      engineType: "Integrated Power Systems",
      fuelCapacity: 16940,
      waterCapacity: 519299,
      propulsionType: "Voith Schneider Propellers",
      hullMaterial: "Marine-Grade Steel",
      classification: "Bureau Veritas Star Class",
      safetyEquipment: ["Marine evacuation systems (MES)","Personal locator beacons","Thermal imaging cameras","Radar reflectors"],
      navigationEquipment: ["Bridge alert management systems","Weather routing systems"],
      communicationEquipment: ["Global Maritime Distress Safety System (GMDSS)","Public address systems"],
      entertainmentEquipment: ["Multi-purpose event spaces","Observation lounges with panoramic views","Virtual reality gaming center","Library and educational facilities"],
      accessibilityFeatures: ["Accessible entertainment venues","Service animal accommodations"],
      environmentalFeatures: ["Recyclable material management systems","Energy-efficient appliances","Exhaust gas cleaning systems","LED lighting throughout"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "hms--of-the-deep",
    name: "HMS  of the Deep",
    description: "Sailing from the picturesque port of London, the HMS  of the Deep represents a new era in cruise experiences. This remarkable river cruise ship combines innovative design with thoughtful amenities, creating an atmosphere of refined elegance and warm hospitality.",
    type: "river-cruise-ship",
    capacity: 1402,
    length: 380,
    width: 67,
    speed: 18,
    topSpeed: 20, 
    yearBuilt: 2018,
    homePort: {"city":"London","country":"United Kingdom","coordinates":{"latitude":51.5074,"longitude":-0.1278}},
    specifications: {
      engineType: "Dual-Fuel Marine Engines",
      fuelCapacity: 12730,
      waterCapacity: 420599,
      propulsionType: "Azipod Electric Propulsion",
      hullMaterial: "Composite Materials",
      classification: "China Classification Society B",
      safetyEquipment: ["Water purification systems","Emergency position indicating radio beacons (EPIRBs)","Digital safety monitoring systems","Searchlights and rescue equipment"],
      navigationEquipment: ["Autopilot systems with track control","Weather routing systems","Inland ECDIS"],
      communicationEquipment: ["Emergency position-indicating radio beacons","Global Maritime Distress Safety System (GMDSS)"],
      entertainmentEquipment: ["Virtual reality gaming center","Casino with table games and slot machines"],
      accessibilityFeatures: ["Accessible entertainment venues","Visual alarm systems","Tactile guidance systems"],
      environmentalFeatures: ["Ballast water management technology","Food waste digesters","LED lighting throughout","Shore power connectivity","Solar panel supplementation"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ms-the--mariner",
    name: "MS The  Mariner",
    description: "The MS The  Mariner stands as a testament to luxury and innovation on the high seas. Departing from London, this sophisticated luxury cruise ship features immersive entertainment, wellness facilities, and exquisite cuisine prepared by internationally renowned chefs.",
    type: "luxury-cruise-ship",
    capacity: 653,
    length: 230,
    width: 44,
    speed: 19,
    topSpeed: 22, 
    yearBuilt: 2010,
    homePort: {"city":"London","country":"United Kingdom","coordinates":{"latitude":51.5074,"longitude":-0.1278}},
    specifications: {
      engineType: "Integrated Power Systems",
      fuelCapacity: 5060,
      waterCapacity: 195900,
      propulsionType: "Counter-Rotating Propellers",
      hullMaterial: "Ice-Strengthened Steel",
      classification: "Russian Maritime Register of Shipping KM",
      safetyEquipment: ["Man overboard detection systems","Emergency escape breathing devices","Weather monitoring stations"],
      navigationEquipment: ["Long-range identification and tracking (LRIT)","Doppler speed logs"],
      communicationEquipment: ["Satellite communication systems","Internal crew communication network","Digital selective calling equipment"],
      entertainmentEquipment: ["Dance clubs and live music venues","Full-service spa and fitness center","Art gallery and auction facilities"],
      accessibilityFeatures: ["Service animal accommodations","Hearing augmentation systems","Roll-in showers"],
      environmentalFeatures: ["Exhaust gas cleaning systems","Biodegradable hydraulic fluids","Optimized hull design for reduced fuel consumption"]
    },
    isLuxuryVessel: true,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ts--gale",
    name: "TS  Gale",
    description: "With its distinctive profile and luxurious appointments, the TS  Gale stands as a jewel in the London harbor. This prestigious family cruise ship offers travelers a perfect combination of adventure and relaxation, with expert-guided excursions, world-class entertainment, and sublime culinary experiences.",
    type: "family-cruise-ship",
    capacity: 1571,
    length: 414,
    width: 72,
    speed: 16,
    topSpeed: 19, 
    yearBuilt: 2016,
    homePort: {"city":"London","country":"United Kingdom","coordinates":{"latitude":51.5074,"longitude":-0.1278}},
    specifications: {
      engineType: "Diesel-Electric Propulsion",
      fuelCapacity: 14900,
      waterCapacity: 471299,
      propulsionType: "Conventional Shaft Propellers",
      hullMaterial: "Marine-Grade Steel",
      classification: "Lloyd's Register Class 1",
      safetyEquipment: ["Weather monitoring stations","Searchlights and rescue equipment","Water purification systems","Radar reflectors","Comprehensive medical facilities","Thermal imaging cameras"],
      navigationEquipment: ["Autopilot systems with track control","River radar systems"],
      communicationEquipment: ["Marine radio telephony","Global Maritime Distress Safety System (GMDSS)","Internal crew communication network"],
      entertainmentEquipment: ["Multi-purpose event spaces","Observation lounges with panoramic views"],
      accessibilityFeatures: ["Roll-in showers","Hearing augmentation systems","Elevator access to all public decks"],
      environmentalFeatures: ["Dynamic routing to optimize fuel usage","Solar panel supplementation","Shore power connectivity"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ts--explorer",
    name: "TS  Explorer",
    description: "Sailing from the picturesque port of London, the TS  Explorer represents a new era in cruise experiences. This remarkable resort style ship combines innovative design with thoughtful amenities, creating an atmosphere of refined elegance and warm hospitality.",
    type: "resort-style-ship",
    capacity: 1311,
    length: 362,
    width: 64,
    speed: 24,
    topSpeed: 28, 
    yearBuilt: 2011,
    homePort: {"city":"London","country":"United Kingdom","coordinates":{"latitude":51.5074,"longitude":-0.1278}},
    specifications: {
      engineType: "Azimuth Thrusters",
      fuelCapacity: 11580,
      waterCapacity: 393300,
      propulsionType: "Voith Schneider Propellers",
      hullMaterial: "Composite Materials",
      classification: "Lloyd's Register Class 1",
      safetyEquipment: ["Life jackets with integrated GPS","Searchlights and rescue equipment","Marine evacuation systems (MES)"],
      navigationEquipment: ["Global navigation satellite systems (GNSS)","Autopilot systems with track control"],
      communicationEquipment: ["Broadband internet throughout","Emergency position-indicating radio beacons"],
      entertainmentEquipment: ["Art gallery and auction facilities","Full-service spa and fitness center","Multiple swimming pools and water features"],
      accessibilityFeatures: ["Accessible shore excursion options","Wheelchair accessible cabins","Roll-in showers"],
      environmentalFeatures: ["Energy-efficient appliances","Advanced water treatment systems","Exhaust gas cleaning systems","Biodegradable hydraulic fluids"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ts-london-voyager",
    name: "TS London Voyager",
    description: "The TS London Voyager invites travelers to explore the treasures of England in unmatched comfort. This exceptional resort style ship, based in London, features curated excursions, immersive cultural programs, and luxurious accommodations that ensure an unforgettable journey.",
    type: "resort-style-ship",
    capacity: 728,
    length: 245,
    width: 46,
    speed: 19,
    topSpeed: 21, 
    yearBuilt: 2022,
    homePort: {"city":"London","country":"United Kingdom","coordinates":{"latitude":51.5074,"longitude":-0.1278}},
    specifications: {
      engineType: "Integrated Power Systems",
      fuelCapacity: 5630,
      waterCapacity: 218400,
      propulsionType: "Counter-Rotating Propellers",
      hullMaterial: "Marine-Grade Steel",
      classification: "Lloyd's Register Class 1",
      safetyEquipment: ["Emergency escape breathing devices","Digital safety monitoring systems","Man overboard detection systems","Advanced fire detection and suppression systems","Weather monitoring stations"],
      navigationEquipment: ["Inland ECDIS","Long-range identification and tracking (LRIT)","Echo sounders and sonar systems","Autopilot systems with track control"],
      communicationEquipment: ["Global Maritime Distress Safety System (GMDSS)","Satellite communication systems","Broadband internet throughout"],
      entertainmentEquipment: ["Dance clubs and live music venues","Multiple swimming pools and water features"],
      accessibilityFeatures: ["Transfer chairs for pool access","Accessible dining facilities","Hearing augmentation systems"],
      environmentalFeatures: ["Noise reduction technology to minimize impact on marine life","Optimized hull design for reduced fuel consumption","Biodegradable hydraulic fluids"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ms--of-the-deep",
    name: "MS  of the Deep",
    description: "The MS  of the Deep offers an unparalleled cruising experience from London, combining luxury amenities with state-of-the-art navigation technology. This luxury cruise ship features spacious cabins, gourmet dining options, and entertainment venues that showcase the best of England hospitality.",
    type: "luxury-cruise-ship",
    capacity: 891,
    length: 278,
    width: 51,
    speed: 29,
    topSpeed: 34, 
    yearBuilt: 2009,
    homePort: {"city":"London","country":"United Kingdom","coordinates":{"latitude":51.5074,"longitude":-0.1278}},
    specifications: {
      engineType: "Hybrid Power System",
      fuelCapacity: 7080,
      waterCapacity: 267300,
      propulsionType: "Counter-Rotating Propellers",
      hullMaterial: "Hybrid Steel-Composite",
      classification: "Bureau Veritas Star Class",
      safetyEquipment: ["Radar reflectors","Automated external defibrillators (AEDs)","Marine evacuation systems (MES)","Searchlights and rescue equipment","Man overboard detection systems","Emergency position indicating radio beacons (EPIRBs)"],
      navigationEquipment: ["Integrated navigation system displays","Automatic identification systems (AIS)","Dynamic positioning systems"],
      communicationEquipment: ["Global Maritime Distress Safety System (GMDSS)","Emergency position-indicating radio beacons","Broadband internet throughout"],
      entertainmentEquipment: ["Children's entertainment areas","Immersive simulation experiences","Dance clubs and live music venues","Full-service spa and fitness center","Library and educational facilities"],
      accessibilityFeatures: ["Visual alarm systems","Accessible entertainment venues","Service animal accommodations","Braille signage throughout"],
      environmentalFeatures: ["Marine ecosystem monitoring equipment","Exhaust gas cleaning systems","Solar panel supplementation"]
    },
    isLuxuryVessel: true,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ts--explorer",
    name: "TS  Explorer",
    description: "The majestic TS  Explorer represents the pinnacle of maritime engineering and hospitality. Based in London, this exceptional adults only ship features elegant interiors, cutting-edge facilities, and carefully curated experiences that celebrate the unique culture of the England region.",
    type: "adults-only-ship",
    capacity: 1427,
    length: 385,
    width: 67,
    speed: 19,
    topSpeed: 22, 
    yearBuilt: 2013,
    homePort: {"city":"London","country":"United Kingdom","coordinates":{"latitude":51.5074,"longitude":-0.1278}},
    specifications: {
      engineType: "Gas Turbine Powerplant",
      fuelCapacity: 12890,
      waterCapacity: 428099,
      propulsionType: "Cycloidal Drive",
      hullMaterial: "Reinforced Aluminum",
      classification: "Russian Maritime Register of Shipping KM",
      safetyEquipment: ["Personal locator beacons","Water purification systems","Marine evacuation systems (MES)","Searchlights and rescue equipment","Emergency position indicating radio beacons (EPIRBs)"],
      navigationEquipment: ["Infrared camera systems","Weather routing systems","Inland ECDIS","Night vision systems"],
      communicationEquipment: ["Maritime VHF radio systems","Emergency position-indicating radio beacons","Ship-to-shore communication links"],
      entertainmentEquipment: ["Theater with Broadway-style productions","Dance clubs and live music venues","Climbing walls and sports courts","Multiple swimming pools and water features","Casino with table games and slot machines"],
      accessibilityFeatures: ["Accessible dining facilities","Braille signage throughout","Hearing augmentation systems","Accessible shore excursion options"],
      environmentalFeatures: ["Optimized hull design for reduced fuel consumption","Marine ecosystem monitoring equipment","Advanced water treatment systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ts-london-voyager",
    name: "TS London Voyager",
    description: "Experience the epitome of maritime excellence aboard the TS London Voyager, a premier family cruise ship sailing from London. With its elegant design, state-of-the-art technology, and exceptional service, every journey promises unforgettable moments and unparalleled comfort.",
    type: "family-cruise-ship",
    capacity: 1237,
    length: 347,
    width: 62,
    speed: 20,
    topSpeed: 24, 
    yearBuilt: 2014,
    homePort: {"city":"London","country":"United Kingdom","coordinates":{"latitude":51.5074,"longitude":-0.1278}},
    specifications: {
      engineType: "Azimuth Thrusters",
      fuelCapacity: 10750,
      waterCapacity: 371099,
      propulsionType: "Conventional Shaft Propellers",
      hullMaterial: "High-Tensile Steel Alloy",
      classification: "China Classification Society B",
      safetyEquipment: ["Radar reflectors","Man overboard detection systems","Emergency escape breathing devices","Life jackets with integrated GPS","Comprehensive medical facilities","Personal locator beacons"],
      navigationEquipment: ["Weather routing systems","Echo sounders and sonar systems","Long-range identification and tracking (LRIT)","Infrared camera systems"],
      communicationEquipment: ["Internal crew communication network"],
      entertainmentEquipment: ["Virtual reality gaming center","Children's entertainment areas","Multi-purpose event spaces","Climbing walls and sports courts"],
      accessibilityFeatures: ["Service animal accommodations","Wheelchair accessible cabins","Accessible dining facilities","Visual alarm systems"],
      environmentalFeatures: ["LED lighting throughout","Heat recovery systems","Dynamic routing to optimize fuel usage"]
    },
    isLuxuryVessel: true,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "nx--of-the-deep",
    name: "NX  of the Deep",
    description: "The NX  of the Deep invites travelers to explore the treasures of England in unmatched comfort. This exceptional family cruise ship, based in London, features curated excursions, immersive cultural programs, and luxurious accommodations that ensure an unforgettable journey.",
    type: "family-cruise-ship",
    capacity: 652,
    length: 230,
    width: 44,
    speed: 15,
    topSpeed: 17, 
    yearBuilt: 2014,
    homePort: {"city":"London","country":"United Kingdom","coordinates":{"latitude":51.5074,"longitude":-0.1278}},
    specifications: {
      engineType: "Solar-Assisted Electric",
      fuelCapacity: 5060,
      waterCapacity: 195600,
      propulsionType: "Cycloidal Drive",
      hullMaterial: "Composite Materials",
      classification: "Lloyd's Register Class 1",
      safetyEquipment: ["Rescue boats and life rafts","Radar reflectors","Life jackets with integrated GPS","Digital safety monitoring systems"],
      navigationEquipment: ["Autopilot systems with track control","Night vision systems"],
      communicationEquipment: ["Satellite communication systems","Emergency position-indicating radio beacons","Public address systems"],
      entertainmentEquipment: ["Art gallery and auction facilities","Dance clubs and live music venues"],
      accessibilityFeatures: ["Roll-in showers","Elevator access to all public decks"],
      environmentalFeatures: ["Energy-efficient appliances","Marine ecosystem monitoring equipment","Heat recovery systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "hms--explorer",
    name: "HMS  Explorer",
    description: "Combining traditional maritime charm with modern amenities, the HMS  Explorer promises an extraordinary voyage from its home port of London. This impressive polar expedition ship offers spacious accommodations, diverse dining options, and engaging activities for travelers of all ages.",
    type: "polar-expedition-ship",
    capacity: 613,
    length: 222,
    width: 43,
    speed: 25,
    topSpeed: 30, 
    yearBuilt: 2017,
    homePort: {"city":"London","country":"United Kingdom","coordinates":{"latitude":51.5074,"longitude":-0.1278}},
    specifications: {
      engineType: "LNG-Powered Engines",
      fuelCapacity: 4770,
      waterCapacity: 183900,
      propulsionType: "Z-Drive Propulsion",
      hullMaterial: "Hybrid Steel-Composite",
      classification: "China Classification Society B",
      safetyEquipment: ["Comprehensive medical facilities","Hyperbaric treatment chambers","Man overboard detection systems","Radar reflectors","Water purification systems"],
      navigationEquipment: ["Radar and automatic radar plotting aids (ARPAs)","Autopilot systems with track control","Night vision systems","Bridge alert management systems"],
      communicationEquipment: ["Ship-to-shore communication links","Internal crew communication network"],
      entertainmentEquipment: ["Climbing walls and sports courts","Multiple swimming pools and water features"],
      accessibilityFeatures: ["Visual alarm systems","Braille signage throughout"],
      environmentalFeatures: ["Heat recovery systems","Biodegradable hydraulic fluids","Ballast water management technology","Noise reduction technology to minimize impact on marine life","LED lighting throughout"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "cs-london-voyager",
    name: "CS London Voyager",
    description: "The majestic CS London Voyager represents the pinnacle of maritime engineering and hospitality. Based in London, this exceptional catamaran features elegant interiors, cutting-edge facilities, and carefully curated experiences that celebrate the unique culture of the England region.",
    type: "catamaran",
    capacity: 1945,
    length: 489,
    width: 83,
    speed: 19,
    topSpeed: 22, 
    yearBuilt: 2006,
    homePort: {"city":"London","country":"United Kingdom","coordinates":{"latitude":51.5074,"longitude":-0.1278}},
    specifications: {
      engineType: "Diesel-Electric Propulsion",
      fuelCapacity: 20290,
      waterCapacity: 583500,
      propulsionType: "Water Jets",
      hullMaterial: "Hybrid Steel-Composite",
      classification: "DNV GL High Speed & Light Craft",
      safetyEquipment: ["Automated external defibrillators (AEDs)","Rescue boats and life rafts","Emergency escape breathing devices","Comprehensive medical facilities"],
      navigationEquipment: ["Radar and automatic radar plotting aids (ARPAs)","Autopilot systems with track control"],
      communicationEquipment: ["Marine radio telephony","Internal crew communication network","Maritime VHF radio systems"],
      entertainmentEquipment: ["Art gallery and auction facilities","Virtual reality gaming center"],
      accessibilityFeatures: ["Accessible entertainment venues","Braille signage throughout","Height-adjustable furniture in select cabins","Service animal accommodations"],
      environmentalFeatures: ["Noise reduction technology to minimize impact on marine life","Biodegradable hydraulic fluids"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ps--of-the-deep",
    name: "PS  of the Deep",
    description: "Combining traditional maritime charm with modern amenities, the PS  of the Deep promises an extraordinary voyage from its home port of London. This impressive ice class ship offers spacious accommodations, diverse dining options, and engaging activities for travelers of all ages.",
    type: "ice-class-ship",
    capacity: 1278,
    length: 355,
    width: 63,
    speed: 24,
    topSpeed: 28, 
    yearBuilt: 2014,
    homePort: {"city":"London","country":"United Kingdom","coordinates":{"latitude":51.5074,"longitude":-0.1278}},
    specifications: {
      engineType: "Solar-Assisted Electric",
      fuelCapacity: 11180,
      waterCapacity: 383400,
      propulsionType: "Conventional Shaft Propellers",
      hullMaterial: "High-Tensile Steel Alloy",
      classification: "ClassNK NS* (Special Purpose Ship)",
      safetyEquipment: ["Rescue boats and life rafts","Satellite emergency notification devices","Advanced fire detection and suppression systems"],
      navigationEquipment: ["Automatic identification systems (AIS)","Integrated bridge systems","Night vision systems"],
      communicationEquipment: ["Digital selective calling equipment","Marine radio telephony"],
      entertainmentEquipment: ["Multiple swimming pools and water features","Library and educational facilities","Children's entertainment areas"],
      accessibilityFeatures: ["Roll-in showers","Visual alarm systems","Accessible dining facilities","Service animal accommodations"],
      environmentalFeatures: ["Noise reduction technology to minimize impact on marine life","Heat recovery systems","Shore power connectivity","Marine ecosystem monitoring equipment"]
    },
    isLuxuryVessel: true,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "nb--explorer",
    name: "NB  Explorer",
    description: "Setting sail from the beautiful port of London, the NB  Explorer is a floating paradise designed for the discerning traveler. This remarkable boutique cruise ship boasts panoramic viewing decks, world-class cuisine, and personalized service that ensures an unforgettable journey.",
    type: "boutique-cruise-ship",
    capacity: 1829,
    length: 465,
    width: 79,
    speed: 19,
    topSpeed: 22, 
    yearBuilt: 2005,
    homePort: {"city":"London","country":"United Kingdom","coordinates":{"latitude":51.5074,"longitude":-0.1278}},
    specifications: {
      engineType: "Gas Turbine Powerplant",
      fuelCapacity: 18360,
      waterCapacity: 548699,
      propulsionType: "Water Jets",
      hullMaterial: "High-Tensile Steel Alloy",
      classification: "ClassNK NS* (Special Purpose Ship)",
      safetyEquipment: ["Survival craft VHF radios","Weather monitoring stations","Man overboard detection systems"],
      navigationEquipment: ["Night vision systems","Infrared camera systems","Echo sounders and sonar systems","Navigation data management systems","Weather routing systems"],
      communicationEquipment: ["Marine radio telephony","Public address systems","Satellite communication systems"],
      entertainmentEquipment: ["Multiple swimming pools and water features","Culinary demonstration kitchens","Dance clubs and live music venues"],
      accessibilityFeatures: ["Height-adjustable furniture in select cabins","Visual alarm systems"],
      environmentalFeatures: ["Optimized hull design for reduced fuel consumption","Advanced water treatment systems","Shore power connectivity","Noise reduction technology to minimize impact on marine life","Heat recovery systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "hms-london-voyager",
    name: "HMS London Voyager",
    description: "Setting sail from the beautiful port of London, the HMS London Voyager is a floating paradise designed for the discerning traveler. This remarkable small ocean ship boasts panoramic viewing decks, world-class cuisine, and personalized service that ensures an unforgettable journey.",
    type: "small-ocean-ship",
    capacity: 973,
    length: 294,
    width: 54,
    speed: 24,
    topSpeed: 28, 
    yearBuilt: 2016,
    homePort: {"city":"London","country":"United Kingdom","coordinates":{"latitude":51.5074,"longitude":-0.1278}},
    specifications: {
      engineType: "Hybrid Power System",
      fuelCapacity: 7930,
      waterCapacity: 291900,
      propulsionType: "Podded Propulsion Units",
      hullMaterial: "Composite Materials",
      classification: "Bureau Veritas Star Class",
      safetyEquipment: ["Survival craft VHF radios","Personal locator beacons","Emergency escape breathing devices"],
      navigationEquipment: ["Dynamic positioning systems","Navigation data management systems","Echo sounders and sonar systems"],
      communicationEquipment: ["Emergency position-indicating radio beacons","Broadband internet throughout"],
      entertainmentEquipment: ["Climbing walls and sports courts","Theater with Broadway-style productions"],
      accessibilityFeatures: ["Accessible shore excursion options","Elevator access to all public decks","Transfer chairs for pool access"],
      environmentalFeatures: ["Marine ecosystem monitoring equipment","Advanced water treatment systems","Optimized hull design for reduced fuel consumption"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "sv--of-the-deep",
    name: "SV  of the Deep",
    description: "Sailing from the picturesque port of London, the SV  of the Deep represents a new era in cruise experiences. This remarkable family cruise ship combines innovative design with thoughtful amenities, creating an atmosphere of refined elegance and warm hospitality.",
    type: "family-cruise-ship",
    capacity: 1687,
    length: 437,
    width: 75,
    speed: 27,
    topSpeed: 30, 
    yearBuilt: 2020,
    homePort: {"city":"London","country":"United Kingdom","coordinates":{"latitude":51.5074,"longitude":-0.1278}},
    specifications: {
      engineType: "Azimuth Thrusters",
      fuelCapacity: 16380,
      waterCapacity: 506099,
      propulsionType: "Conventional Shaft Propellers",
      hullMaterial: "Composite Materials",
      classification: "China Classification Society B",
      safetyEquipment: ["Digital safety monitoring systems","Marine evacuation systems (MES)","Hyperbaric treatment chambers"],
      navigationEquipment: ["Echo sounders and sonar systems","Long-range identification and tracking (LRIT)","Autopilot systems with track control","Infrared camera systems"],
      communicationEquipment: ["Maritime VHF radio systems","Ship-to-shore communication links"],
      entertainmentEquipment: ["Climbing walls and sports courts","Culinary demonstration kitchens"],
      accessibilityFeatures: ["Visual alarm systems","Height-adjustable furniture in select cabins","Accessible entertainment venues"],
      environmentalFeatures: ["Shore power connectivity","Food waste digesters"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  }
];
