// This file is auto-generated
    // Do not edit manually.
    // City: Melbourne
    // Generated on: 2025-06-10T03:09:08.301Z
    
    import { Vessels } from "@/lib/interfaces/services/cruises";

export const melbourneVessels: Vessels[] = [
  {
    id: "ps--explorer",
    name: "PS  Explorer",
    description: "The majestic PS  Explorer represents the pinnacle of maritime engineering and hospitality. Based in Melbourne, this exceptional family cruise ship features divine interiors, cutting-edge facilities, and carefully curated experiences that celebrate the unique culture of the Australia region.",
    type: "family-cruise-ship",
    capacity: 724,
    length: 244,
    width: 46,
    speed: 16,
    topSpeed: 19, 
    yearBuilt: 2013,
    homePort: {"city":"Melbourne","country":"Australia","coordinates":{"latitude":-37.8136,"longitude":144.9631}},
    specifications: {
      engineType: "Integrated Power Systems",
      fuelCapacity: 5610,
      waterCapacity: 217200,
      propulsionType: "Cycloidal Drive",
      hullMaterial: "Composite Materials",
      classification: "American Bureau of Shipping A1",
      safetyEquipment: ["Weather monitoring stations","Tactical response equipment","Advanced fire detection and suppression systems","Automated external defibrillators (AEDs)","Personal locator beacons"],
      navigationEquipment: ["Bridge alert management systems","Weather routing systems","Automatic identification systems (AIS)","River radar systems"],
      communicationEquipment: ["Public address systems","Emergency position-indicating radio beacons","Internal crew communication network"],
      entertainmentEquipment: ["Children's entertainment areas","Dance clubs and live music venues","Art gallery and auction facilities","Casino with table games and slot machines"],
      accessibilityFeatures: ["Transfer chairs for pool access","Wheelchair accessible cabins","Accessible dining facilities","Service animal accommodations"],
      environmentalFeatures: ["Heat recovery systems","Food waste digesters","Shore power connectivity"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "sy-melbourne-voyager",
    name: "SY Melbourne Voyager",
    description: "Experience the epitome of maritime excellence aboard the SY Melbourne Voyager, a premier adults only ship sailing from Melbourne. With its elegant design, state-of-the-art technology, and exceptional service, every journey promises unforgettable moments and unparalleled comfort.",
    type: "adults-only-ship",
    capacity: 1992,
    length: 498,
    width: 84,
    speed: 15,
    topSpeed: 18, 
    yearBuilt: 2023,
    homePort: {"city":"Melbourne","country":"Australia","coordinates":{"latitude":-37.8136,"longitude":144.9631}},
    specifications: {
      engineType: "Solar-Assisted Electric",
      fuelCapacity: 20910,
      waterCapacity: 597600,
      propulsionType: "Azipod Electric Propulsion",
      hullMaterial: "High-Tensile Steel Alloy",
      classification: "DNV GL High Speed & Light Craft",
      safetyEquipment: ["Radar reflectors","Marine evacuation systems (MES)","Tactical response equipment","Water purification systems","Emergency position indicating radio beacons (EPIRBs)","Automated external defibrillators (AEDs)"],
      navigationEquipment: ["Long-range identification and tracking (LRIT)","Night vision systems","Navigation data management systems"],
      communicationEquipment: ["Digital selective calling equipment","Satellite communication systems"],
      entertainmentEquipment: ["Full-service spa and fitness center","Library and educational facilities","Art gallery and auction facilities","Multi-purpose event spaces"],
      accessibilityFeatures: ["Accessible medical facilities","Height-adjustable furniture in select cabins","Wheelchair accessible cabins"],
      environmentalFeatures: ["Energy-efficient appliances","Recyclable material management systems","Optimized hull design for reduced fuel consumption"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "nb--of-the-deep",
    name: "NB  of the Deep",
    description: "Sailing from the picturesque port of Melbourne, the NB  of the Deep represents a new era in cruise experiences. This remarkable mid size cruise ship combines innovative design with thoughtful amenities, creating an atmosphere of refined elegance and warm hospitality.",
    type: "mid-size-cruise-ship",
    capacity: 1734,
    length: 446,
    width: 76,
    speed: 18,
    topSpeed: 21, 
    yearBuilt: 2017,
    homePort: {"city":"Melbourne","country":"Australia","coordinates":{"latitude":-37.8136,"longitude":144.9631}},
    specifications: {
      engineType: "Podded Propulsion",
      fuelCapacity: 16940,
      waterCapacity: 520199,
      propulsionType: "Voith Schneider Propellers",
      hullMaterial: "Ice-Strengthened Steel",
      classification: "Bureau Veritas Star Class",
      safetyEquipment: ["Radar reflectors","Automated external defibrillators (AEDs)","Comprehensive medical facilities","Life jackets with integrated GPS","Emergency escape breathing devices","Man overboard detection systems","Marine evacuation systems (MES)"],
      navigationEquipment: ["Echo sounders and sonar systems","Infrared camera systems","River radar systems"],
      communicationEquipment: ["Digital selective calling equipment","Satellite communication systems","Maritime VHF radio systems"],
      entertainmentEquipment: ["Casino with table games and slot machines","Cinema with latest releases","Observation lounges with panoramic views"],
      accessibilityFeatures: ["Elevator access to all public decks","Tactile guidance systems","Assistive listening devices"],
      environmentalFeatures: ["Energy-efficient appliances","Solar panel supplementation"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ss-the--mariner",
    name: "SS The  Mariner",
    description: "The majestic SS The  Mariner represents the pinnacle of maritime engineering and hospitality. Based in Melbourne, this exceptional catamaran features unforgettable interiors, cutting-edge facilities, and carefully curated experiences that celebrate the unique culture of the Australia region.",
    type: "catamaran",
    capacity: 968,
    length: 293,
    width: 53,
    speed: 17,
    topSpeed: 20, 
    yearBuilt: 2006,
    homePort: {"city":"Melbourne","country":"Australia","coordinates":{"latitude":-37.8136,"longitude":144.9631}},
    specifications: {
      engineType: "Azimuth Thrusters",
      fuelCapacity: 7760,
      waterCapacity: 290400,
      propulsionType: "Z-Drive Propulsion",
      hullMaterial: "High-Tensile Steel Alloy",
      classification: "Russian Maritime Register of Shipping KM",
      safetyEquipment: ["Marine evacuation systems (MES)","Personal locator beacons","Emergency escape breathing devices","Man overboard detection systems","Tactical response equipment","Survival craft VHF radios"],
      navigationEquipment: ["Radar and automatic radar plotting aids (ARPAs)","Global navigation satellite systems (GNSS)","Electronic chart display information systems (ECDIS)","River radar systems","Gyrocompasses and magnetic compasses"],
      communicationEquipment: ["Marine radio telephony","Broadband internet throughout"],
      entertainmentEquipment: ["Immersive simulation experiences","Dance clubs and live music venues","Theater with Broadway-style productions","Children's entertainment areas","Full-service spa and fitness center"],
      accessibilityFeatures: ["Visual alarm systems","Transfer chairs for pool access","Accessible medical facilities"],
      environmentalFeatures: ["Optimized hull design for reduced fuel consumption","Solar panel supplementation","LED lighting throughout","Shore power connectivity"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "rv--gale",
    name: "RV  Gale",
    description: "The RV  Gale stands as a testament to luxury and innovation on the high seas. Departing from Melbourne, this sophisticated polar expedition ship features immersive entertainment, wellness facilities, and exquisite cuisine prepared by internationally renowned chefs.",
    type: "polar-expedition-ship",
    capacity: 1971,
    length: 494,
    width: 84,
    speed: 24,
    topSpeed: 27, 
    yearBuilt: 2020,
    homePort: {"city":"Melbourne","country":"Australia","coordinates":{"latitude":-37.8136,"longitude":144.9631}},
    specifications: {
      engineType: "Azimuth Thrusters",
      fuelCapacity: 20740,
      waterCapacity: 591300,
      propulsionType: "Z-Drive Propulsion",
      hullMaterial: "Marine-Grade Steel",
      classification: "Lloyd's Register Class 1",
      safetyEquipment: ["Life jackets with integrated GPS","Hyperbaric treatment chambers","Emergency position indicating radio beacons (EPIRBs)","Advanced fire detection and suppression systems","Thermal imaging cameras"],
      navigationEquipment: ["Automatic identification systems (AIS)","Integrated bridge systems","Gyrocompasses and magnetic compasses","Infrared camera systems"],
      communicationEquipment: ["Satellite communication systems","Global Maritime Distress Safety System (GMDSS)"],
      entertainmentEquipment: ["Immersive simulation experiences","Theater with Broadway-style productions","Virtual reality gaming center"],
      accessibilityFeatures: ["Height-adjustable furniture in select cabins","Visual alarm systems","Elevator access to all public decks","Hearing augmentation systems"],
      environmentalFeatures: ["Biodegradable hydraulic fluids","Heat recovery systems","Optimized hull design for reduced fuel consumption","Dynamic routing to optimize fuel usage"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  }
];
