// This file is auto-generated
    // Do not edit manually.
    // City: Montevideo
    // Generated on: 2025-06-08T07:59:32.396Z
    
    import { Vessels } from "@/lib/interfaces/services/cruises";

export const montevideoVessels: Vessels[] = [
{
    id: "ms--explorer",
    name: "MS  Explorer",
    description: "The MS  Explorer offers an unparalleled cruising experience from Montevideo, combining luxury amenities with state-of-the-art navigation technology. This mid size cruise ship features spacious cabins, gourmet dining options, and entertainment venues that showcase the best of Uruguay hospitality.",
    type: "mid-size-cruise-ship",
    capacity: 795,
    length: 259,
    width: 48,
    speed: 16,
    topSpeed: 18, 
    yearBuilt: 2011,
    homePort: {"city":"Montevideo","country":"Uruguay","coordinates":{"latitude":-34.9011,"longitude":-56.1645}},
    specifications: {
      engineType: "LNG-Powered Engines",
      fuelCapacity: 6210,
      waterCapacity: 238500,
      propulsionType: "Conventional Shaft Propellers",
      hullMaterial: "Composite Materials",
      classification: "Lloyd's Register Class 1",
      safetyEquipment: ["Searchlights and rescue equipment","Hyperbaric treatment chambers","Emergency position indicating radio beacons (EPIRBs)","Life jackets with integrated GPS","Man overboard detection systems"],
      navigationEquipment: ["Integrated navigation system displays","Echo sounders and sonar systems","River radar systems","Global navigation satellite systems (GNSS)"],
      communicationEquipment: ["Satellite communication systems"],
      entertainmentEquipment: ["Theater with Broadway-style productions","Library and educational facilities"],
      accessibilityFeatures: ["Accessible dining facilities","Visual alarm systems"],
      environmentalFeatures: ["Solar panel supplementation","Optimized hull design for reduced fuel consumption","Heat recovery systems","Dynamic routing to optimize fuel usage","Food waste digesters"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "my-montevideo-voyager",
    name: "MY Montevideo Voyager",
    description: "Experience the epitome of maritime excellence aboard the MY Montevideo Voyager, a premier river cruise ship sailing from Montevideo. With its elegant design, state-of-the-art technology, and exceptional service, every journey promises unforgettable moments and unparalleled comfort.",
    type: "river-cruise-ship",
    capacity: 1502,
    length: 400,
    width: 70,
    speed: 29,
    topSpeed: 34, 
    yearBuilt: 2007,
    homePort: {"city":"Montevideo","country":"Uruguay","coordinates":{"latitude":-34.9011,"longitude":-56.1645}},
    specifications: {
      engineType: "Gas Turbine Powerplant",
      fuelCapacity: 14000,
      waterCapacity: 450599,
      propulsionType: "Azipod Electric Propulsion",
      hullMaterial: "High-Tensile Steel Alloy",
      classification: "RINA Green Star Plus",
      safetyEquipment: ["Comprehensive medical facilities","Life jackets with integrated GPS","Searchlights and rescue equipment","Water purification systems"],
      navigationEquipment: ["Voyage data recorders (VDRs)","Global navigation satellite systems (GNSS)","River radar systems","Echo sounders and sonar systems"],
      communicationEquipment: ["Internal crew communication network","Emergency position-indicating radio beacons","Broadband internet throughout"],
      entertainmentEquipment: ["Library and educational facilities","Multiple swimming pools and water features","Casino with table games and slot machines","Art gallery and auction facilities","Dance clubs and live music venues"],
      accessibilityFeatures: ["Visual alarm systems"],
      environmentalFeatures: ["Recyclable material management systems","Energy-efficient appliances","Ballast water management technology"]
    },
    isLuxuryVessel: true,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "rms--of-the-deep",
    name: "RMS  of the Deep",
    description: "The RMS  of the Deep invites travelers to explore the treasures of Uruguay in unmatched comfort. This exceptional superyacht, based in Montevideo, features curated excursions, immersive cultural programs, and luxurious accommodations that ensure an unforgettable journey.",
    type: "superyacht",
    capacity: 873,
    length: 274,
    width: 51,
    speed: 22,
    topSpeed: 26, 
    yearBuilt: 2019,
    homePort: {"city":"Montevideo","country":"Uruguay","coordinates":{"latitude":-34.9011,"longitude":-56.1645}},
    specifications: {
      engineType: "Dual-Fuel Marine Engines",
      fuelCapacity: 6980,
      waterCapacity: 261899,
      propulsionType: "Podded Propulsion Units",
      hullMaterial: "Ice-Strengthened Steel",
      classification: "Lloyd's Register Class 1",
      safetyEquipment: ["Hyperbaric treatment chambers","Personal locator beacons","Emergency position indicating radio beacons (EPIRBs)","Tactical response equipment","Radar reflectors"],
      navigationEquipment: ["Infrared camera systems","Doppler speed logs"],
      communicationEquipment: ["Emergency position-indicating radio beacons","Internal crew communication network","Global Maritime Distress Safety System (GMDSS)"],
      entertainmentEquipment: ["Theater with Broadway-style productions","Dance clubs and live music venues","Observation lounges with panoramic views","Virtual reality gaming center"],
      accessibilityFeatures: ["Hearing augmentation systems","Braille signage throughout","Service animal accommodations","Tactile guidance systems"],
      environmentalFeatures: ["Energy-efficient appliances","Food waste digesters","Ballast water management technology"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ts-the--mariner",
    name: "TS The  Mariner",
    description: "The majestic TS The  Mariner represents the pinnacle of maritime engineering and hospitality. Based in Montevideo, this exceptional catamaran features elegant interiors, cutting-edge facilities, and carefully curated experiences that celebrate the unique culture of the Uruguay region.",
    type: "catamaran",
    capacity: 1880,
    length: 476,
    width: 81,
    speed: 20,
    topSpeed: 24, 
    yearBuilt: 2008,
    homePort: {"city":"Montevideo","country":"Uruguay","coordinates":{"latitude":-34.9011,"longitude":-56.1645}},
    specifications: {
      engineType: "Dual-Fuel Marine Engines",
      fuelCapacity: 19270,
      waterCapacity: 564000,
      propulsionType: "Counter-Rotating Propellers",
      hullMaterial: "High-Tensile Steel Alloy",
      classification: "Lloyd's Register Class 1",
      safetyEquipment: ["Survival craft VHF radios","Digital safety monitoring systems","Thermal imaging cameras","Rescue boats and life rafts"],
      navigationEquipment: ["Weather routing systems","Voyage data recorders (VDRs)"],
      communicationEquipment: ["Digital selective calling equipment","Satellite communication systems","Broadband internet throughout"],
      entertainmentEquipment: ["Immersive simulation experiences","Climbing walls and sports courts"],
      accessibilityFeatures: ["Wheelchair accessible cabins","Accessible entertainment venues","Accessible dining facilities"],
      environmentalFeatures: ["Solar panel supplementation","Exhaust gas cleaning systems","Advanced water treatment systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "rms--gale",
    name: "RMS  Gale",
    description: "Experience the epitome of maritime excellence aboard the RMS  Gale, a premier adults only ship sailing from Montevideo. With its elegant design, state-of-the-art technology, and exceptional service, every journey promises unforgettable moments and unparalleled comfort.",
    type: "adults-only-ship",
    capacity: 603,
    length: 220,
    width: 43,
    speed: 21,
    topSpeed: 24, 
    yearBuilt: 2020,
    homePort: {"city":"Montevideo","country":"Uruguay","coordinates":{"latitude":-34.9011,"longitude":-56.1645}},
    specifications: {
      engineType: "Solar-Assisted Electric",
      fuelCapacity: 4730,
      waterCapacity: 180900,
      propulsionType: "Water Jets",
      hullMaterial: "Composite Materials",
      classification: "DNV GL High Speed & Light Craft",
      safetyEquipment: ["Comprehensive medical facilities","Thermal imaging cameras","Tactical response equipment","Rescue boats and life rafts"],
      navigationEquipment: ["Integrated bridge systems","Bridge alert management systems","Echo sounders and sonar systems"],
      communicationEquipment: ["Public address systems","Global Maritime Distress Safety System (GMDSS)","Emergency position-indicating radio beacons"],
      entertainmentEquipment: ["Library and educational facilities","Observation lounges with panoramic views"],
      accessibilityFeatures: ["Height-adjustable furniture in select cabins"],
      environmentalFeatures: ["Energy-efficient appliances","Noise reduction technology to minimize impact on marine life"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "nb--explorer",
    name: "NB  Explorer",
    description: "With its distinctive profile and luxurious appointments, the NB  Explorer stands as a jewel in the Montevideo harbor. This prestigious mid size cruise ship offers travelers a perfect combination of adventure and relaxation, with expert-guided excursions, world-class entertainment, and sublime culinary experiences.",
    type: "mid-size-cruise-ship",
    capacity: 711,
    length: 242,
    width: 46,
    speed: 22,
    topSpeed: 25, 
    yearBuilt: 2021,
    homePort: {"city":"Montevideo","country":"Uruguay","coordinates":{"latitude":-34.9011,"longitude":-56.1645}},
    specifications: {
      engineType: "Podded Propulsion",
      fuelCapacity: 5560,
      waterCapacity: 213299,
      propulsionType: "Cycloidal Drive",
      hullMaterial: "Ice-Strengthened Steel",
      classification: "China Classification Society B",
      safetyEquipment: ["Searchlights and rescue equipment","Marine evacuation systems (MES)","Emergency escape breathing devices","Advanced fire detection and suppression systems","Weather monitoring stations","Personal locator beacons"],
      navigationEquipment: ["Global navigation satellite systems (GNSS)","Integrated navigation system displays","Infrared camera systems"],
      communicationEquipment: ["Marine radio telephony","Digital selective calling equipment","Satellite communication systems"],
      entertainmentEquipment: ["Full-service spa and fitness center","Culinary demonstration kitchens","Dance clubs and live music venues","Multi-purpose event spaces"],
      accessibilityFeatures: ["Braille signage throughout","Assistive listening devices"],
      environmentalFeatures: ["Recyclable material management systems","Food waste digesters","Marine ecosystem monitoring equipment"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "sv-montevideo-voyager",
    name: "SV Montevideo Voyager",
    description: "The majestic SV Montevideo Voyager represents the pinnacle of maritime engineering and hospitality. Based in Montevideo, this exceptional mainstream cruise ship features elegant interiors, cutting-edge facilities, and carefully curated experiences that celebrate the unique culture of the Uruguay region.",
    type: "mainstream-cruise-ship",
    capacity: 1345,
    length: 369,
    width: 65,
    speed: 19,
    topSpeed: 22, 
    yearBuilt: 2010,
    homePort: {"city":"Montevideo","country":"Uruguay","coordinates":{"latitude":-34.9011,"longitude":-56.1645}},
    specifications: {
      engineType: "Azimuth Thrusters",
      fuelCapacity: 11990,
      waterCapacity: 403500,
      propulsionType: "Counter-Rotating Propellers",
      hullMaterial: "Marine-Grade Steel",
      classification: "Bureau Veritas Star Class",
      safetyEquipment: ["Emergency escape breathing devices","Man overboard detection systems","Radar reflectors","Life jackets with integrated GPS"],
      navigationEquipment: ["Dynamic positioning systems","Long-range identification and tracking (LRIT)","Gyrocompasses and magnetic compasses","Echo sounders and sonar systems","Voyage data recorders (VDRs)"],
      communicationEquipment: ["Marine radio telephony","Satellite communication systems","Broadband internet throughout"],
      entertainmentEquipment: ["Theater with Broadway-style productions","Climbing walls and sports courts"],
      accessibilityFeatures: ["Tactile guidance systems","Roll-in showers"],
      environmentalFeatures: ["Food waste digesters","Exhaust gas cleaning systems","Heat recovery systems","Advanced water treatment systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ss--of-the-deep",
    name: "SS  of the Deep",
    description: "Setting sail from the beautiful port of Montevideo, the SS  of the Deep is a floating paradise designed for the discerning traveler. This remarkable adults only ship boasts panoramic viewing decks, world-class cuisine, and personalized service that ensures an unforgettable journey.",
    type: "adults-only-ship",
    capacity: 561,
    length: 212,
    width: 41,
    speed: 15,
    topSpeed: 17, 
    yearBuilt: 2015,
    homePort: {"city":"Montevideo","country":"Uruguay","coordinates":{"latitude":-34.9011,"longitude":-56.1645}},
    specifications: {
      engineType: "Solar-Assisted Electric",
      fuelCapacity: 4340,
      waterCapacity: 168299,
      propulsionType: "Voith Schneider Propellers",
      hullMaterial: "Marine-Grade Steel",
      classification: "American Bureau of Shipping A1",
      safetyEquipment: ["Man overboard detection systems","Searchlights and rescue equipment","Life jackets with integrated GPS"],
      navigationEquipment: ["Echo sounders and sonar systems","Integrated navigation system displays"],
      communicationEquipment: ["Digital selective calling equipment","Global Maritime Distress Safety System (GMDSS)"],
      entertainmentEquipment: ["Theater with Broadway-style productions","Full-service spa and fitness center","Multiple swimming pools and water features","Immersive simulation experiences","Art gallery and auction facilities"],
      accessibilityFeatures: ["Height-adjustable furniture in select cabins","Assistive listening devices","Accessible dining facilities"],
      environmentalFeatures: ["Optimized hull design for reduced fuel consumption","Biodegradable hydraulic fluids","Food waste digesters"]
    },
    isLuxuryVessel: true,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "cs--explorer",
    name: "CS  Explorer",
    description: "Sailing from the picturesque port of Montevideo, the CS  Explorer represents a new era in cruise experiences. This remarkable chartered vessel combines innovative design with thoughtful amenities, creating an atmosphere of refined elegance and warm hospitality.",
    type: "chartered-vessel",
    capacity: 1968,
    length: 493,
    width: 83,
    speed: 26,
    topSpeed: 29, 
    yearBuilt: 2009,
    homePort: {"city":"Montevideo","country":"Uruguay","coordinates":{"latitude":-34.9011,"longitude":-56.1645}},
    specifications: {
      engineType: "Integrated Power Systems",
      fuelCapacity: 20450,
      waterCapacity: 590400,
      propulsionType: "Z-Drive Propulsion",
      hullMaterial: "Ice-Strengthened Steel",
      classification: "Russian Maritime Register of Shipping KM",
      safetyEquipment: ["Hyperbaric treatment chambers","Life jackets with integrated GPS","Comprehensive medical facilities","Tactical response equipment","Automated external defibrillators (AEDs)"],
      navigationEquipment: ["Night vision systems","Inland ECDIS","Global navigation satellite systems (GNSS)","Autopilot systems with track control"],
      communicationEquipment: ["Global Maritime Distress Safety System (GMDSS)","Satellite communication systems"],
      entertainmentEquipment: ["Dance clubs and live music venues","Theater with Broadway-style productions","Multi-purpose event spaces","Library and educational facilities","Casino with table games and slot machines"],
      accessibilityFeatures: ["Tactile guidance systems","Accessible entertainment venues","Transfer chairs for pool access","Braille signage throughout"],
      environmentalFeatures: ["Optimized hull design for reduced fuel consumption","Energy-efficient appliances","Dynamic routing to optimize fuel usage","Advanced water treatment systems","Marine ecosystem monitoring equipment"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "my-montevideo-voyager",
    name: "MY Montevideo Voyager",
    description: "Sailing from the picturesque port of Montevideo, the MY Montevideo Voyager represents a new era in cruise experiences. This remarkable mega yacht combines innovative design with thoughtful amenities, creating an atmosphere of refined elegance and warm hospitality.",
    type: "mega-yacht",
    capacity: 1521,
    length: 404,
    width: 70,
    speed: 15,
    topSpeed: 18, 
    yearBuilt: 2008,
    homePort: {"city":"Montevideo","country":"Uruguay","coordinates":{"latitude":-34.9011,"longitude":-56.1645}},
    specifications: {
      engineType: "Hybrid Power System",
      fuelCapacity: 14140,
      waterCapacity: 456300,
      propulsionType: "Conventional Shaft Propellers",
      hullMaterial: "Hybrid Steel-Composite",
      classification: "Lloyd's Register Class 1",
      safetyEquipment: ["Hyperbaric treatment chambers","Man overboard detection systems","Water purification systems","Survival craft VHF radios","Life jackets with integrated GPS","Emergency escape breathing devices"],
      navigationEquipment: ["Doppler speed logs","Automatic identification systems (AIS)","Radar and automatic radar plotting aids (ARPAs)","Echo sounders and sonar systems"],
      communicationEquipment: ["Maritime VHF radio systems","Ship-to-shore communication links","Marine radio telephony"],
      entertainmentEquipment: ["Theater with Broadway-style productions","Multiple swimming pools and water features","Casino with table games and slot machines","Full-service spa and fitness center","Culinary demonstration kitchens"],
      accessibilityFeatures: ["Roll-in showers","Wheelchair accessible cabins"],
      environmentalFeatures: ["Recyclable material management systems","Marine ecosystem monitoring equipment","Exhaust gas cleaning systems","Food waste digesters","Dynamic routing to optimize fuel usage"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "hms--of-the-deep",
    name: "HMS  of the Deep",
    description: "The HMS  of the Deep offers an unparalleled cruising experience from Montevideo, combining luxury amenities with state-of-the-art navigation technology. This short hop ferry features spacious cabins, gourmet dining options, and entertainment venues that showcase the best of Uruguay hospitality.",
    type: "short-hop-ferry",
    capacity: 1359,
    length: 371,
    width: 65,
    speed: 15,
    topSpeed: 17, 
    yearBuilt: 2010,
    homePort: {"city":"Montevideo","country":"Uruguay","coordinates":{"latitude":-34.9011,"longitude":-56.1645}},
    specifications: {
      engineType: "Integrated Power Systems",
      fuelCapacity: 12050,
      waterCapacity: 407700,
      propulsionType: "Counter-Rotating Propellers",
      hullMaterial: "Hybrid Steel-Composite",
      classification: "American Bureau of Shipping A1",
      safetyEquipment: ["Water purification systems","Emergency position indicating radio beacons (EPIRBs)","Weather monitoring stations"],
      navigationEquipment: ["Navigation data management systems","Integrated bridge systems"],
      communicationEquipment: ["Marine radio telephony","Global Maritime Distress Safety System (GMDSS)","Public address systems"],
      entertainmentEquipment: ["Cinema with latest releases","Children's entertainment areas","Virtual reality gaming center","Immersive simulation experiences"],
      accessibilityFeatures: ["Accessible shore excursion options","Height-adjustable furniture in select cabins","Accessible medical facilities"],
      environmentalFeatures: ["Ballast water management technology","Food waste digesters","Marine ecosystem monitoring equipment","Noise reduction technology to minimize impact on marine life"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "sy--explorer",
    name: "SY  Explorer",
    description: "The majestic SY  Explorer represents the pinnacle of maritime engineering and hospitality. Based in Montevideo, this exceptional resort style ship features elegant interiors, cutting-edge facilities, and carefully curated experiences that celebrate the unique culture of the Uruguay region.",
    type: "resort-style-ship",
    capacity: 1541,
    length: 408,
    width: 71,
    speed: 18,
    topSpeed: 21, 
    yearBuilt: 2020,
    homePort: {"city":"Montevideo","country":"Uruguay","coordinates":{"latitude":-34.9011,"longitude":-56.1645}},
    specifications: {
      engineType: "Diesel-Electric Propulsion",
      fuelCapacity: 14480,
      waterCapacity: 462299,
      propulsionType: "Counter-Rotating Propellers",
      hullMaterial: "Reinforced Aluminum",
      classification: "ClassNK NS* (Special Purpose Ship)",
      safetyEquipment: ["Emergency position indicating radio beacons (EPIRBs)","Survival craft VHF radios","Water purification systems","Tactical response equipment","Automated external defibrillators (AEDs)","Weather monitoring stations","Comprehensive medical facilities"],
      navigationEquipment: ["Voyage data recorders (VDRs)","Global navigation satellite systems (GNSS)"],
      communicationEquipment: ["Broadband internet throughout","Satellite communication systems"],
      entertainmentEquipment: ["Culinary demonstration kitchens","Children's entertainment areas","Art gallery and auction facilities"],
      accessibilityFeatures: ["Accessible dining facilities","Hearing augmentation systems"],
      environmentalFeatures: ["Food waste digesters","Shore power connectivity","Advanced water treatment systems","Exhaust gas cleaning systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "mv-montevideo-voyager",
    name: "MV Montevideo Voyager",
    description: "The MV Montevideo Voyager stands as a testament to luxury and innovation on the high seas. Departing from Montevideo, this sophisticated small ocean ship features immersive entertainment, wellness facilities, and exquisite cuisine prepared by internationally renowned chefs.",
    type: "small-ocean-ship",
    capacity: 1369,
    length: 373,
    width: 65,
    speed: 19,
    topSpeed: 22, 
    yearBuilt: 2021,
    homePort: {"city":"Montevideo","country":"Uruguay","coordinates":{"latitude":-34.9011,"longitude":-56.1645}},
    specifications: {
      engineType: "Diesel-Electric Propulsion",
      fuelCapacity: 12120,
      waterCapacity: 410700,
      propulsionType: "Z-Drive Propulsion",
      hullMaterial: "Hybrid Steel-Composite",
      classification: "China Classification Society B",
      safetyEquipment: ["Survival craft VHF radios","Satellite emergency notification devices","Tactical response equipment","Thermal imaging cameras"],
      navigationEquipment: ["Infrared camera systems","River radar systems","Integrated bridge systems","Integrated navigation system displays"],
      communicationEquipment: ["Satellite communication systems"],
      entertainmentEquipment: ["Observation lounges with panoramic views","Dance clubs and live music venues","Casino with table games and slot machines"],
      accessibilityFeatures: ["Accessible medical facilities","Accessible dining facilities","Hearing augmentation systems","Service animal accommodations"],
      environmentalFeatures: ["Noise reduction technology to minimize impact on marine life","Shore power connectivity","LED lighting throughout"]
    },
    isLuxuryVessel: true,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "mv--of-the-deep",
    name: "MV  of the Deep",
    description: "Setting sail from the beautiful port of Montevideo, the MV  of the Deep is a floating paradise designed for the discerning traveler. This remarkable catamaran boasts panoramic viewing decks, world-class cuisine, and personalized service that ensures an unforgettable journey.",
    type: "catamaran",
    capacity: 587,
    length: 217,
    width: 42,
    speed: 15,
    topSpeed: 17, 
    yearBuilt: 2007,
    homePort: {"city":"Montevideo","country":"Uruguay","coordinates":{"latitude":-34.9011,"longitude":-56.1645}},
    specifications: {
      engineType: "Podded Propulsion",
      fuelCapacity: 4550,
      waterCapacity: 176100,
      propulsionType: "Voith Schneider Propellers",
      hullMaterial: "Reinforced Aluminum",
      classification: "Russian Maritime Register of Shipping KM",
      safetyEquipment: ["Thermal imaging cameras","Personal locator beacons","Emergency position indicating radio beacons (EPIRBs)"],
      navigationEquipment: ["Long-range identification and tracking (LRIT)","Electronic chart display information systems (ECDIS)","Infrared camera systems","Gyrocompasses and magnetic compasses"],
      communicationEquipment: ["Maritime VHF radio systems","Emergency position-indicating radio beacons","Global Maritime Distress Safety System (GMDSS)"],
      entertainmentEquipment: ["Virtual reality gaming center","Theater with Broadway-style productions"],
      accessibilityFeatures: ["Accessible entertainment venues","Accessible dining facilities","Tactile guidance systems"],
      environmentalFeatures: ["Heat recovery systems","Solar panel supplementation","Marine ecosystem monitoring equipment"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "fv--explorer",
    name: "FV  Explorer",
    description: "Combining traditional maritime charm with modern amenities, the FV  Explorer promises an extraordinary voyage from its home port of Montevideo. This impressive small ocean ship offers spacious accommodations, diverse dining options, and engaging activities for travelers of all ages.",
    type: "small-ocean-ship",
    capacity: 887,
    length: 277,
    width: 51,
    speed: 17,
    topSpeed: 20, 
    yearBuilt: 2020,
    homePort: {"city":"Montevideo","country":"Uruguay","coordinates":{"latitude":-34.9011,"longitude":-56.1645}},
    specifications: {
      engineType: "Podded Propulsion",
      fuelCapacity: 7060,
      waterCapacity: 266099,
      propulsionType: "Voith Schneider Propellers",
      hullMaterial: "Hybrid Steel-Composite",
      classification: "RINA Green Star Plus",
      safetyEquipment: ["Man overboard detection systems","Survival craft VHF radios","Comprehensive medical facilities","Personal locator beacons","Hyperbaric treatment chambers","Water purification systems"],
      navigationEquipment: ["Gyrocompasses and magnetic compasses","Electronic chart display information systems (ECDIS)","Global navigation satellite systems (GNSS)","Integrated bridge systems"],
      communicationEquipment: ["Internal crew communication network","Public address systems"],
      entertainmentEquipment: ["Observation lounges with panoramic views","Climbing walls and sports courts","Theater with Broadway-style productions","Culinary demonstration kitchens"],
      accessibilityFeatures: ["Service animal accommodations","Hearing augmentation systems","Accessible dining facilities","Accessible entertainment venues"],
      environmentalFeatures: ["Noise reduction technology to minimize impact on marine life","Biodegradable hydraulic fluids","Exhaust gas cleaning systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "hms-montevideo-voyager",
    name: "HMS Montevideo Voyager",
    description: "The majestic HMS Montevideo Voyager represents the pinnacle of maritime engineering and hospitality. Based in Montevideo, this exceptional resort style ship features elegant interiors, cutting-edge facilities, and carefully curated experiences that celebrate the unique culture of the Uruguay region.",
    type: "resort-style-ship",
    capacity: 1092,
    length: 318,
    width: 57,
    speed: 22,
    topSpeed: 26, 
    yearBuilt: 2022,
    homePort: {"city":"Montevideo","country":"Uruguay","coordinates":{"latitude":-34.9011,"longitude":-56.1645}},
    specifications: {
      engineType: "Integrated Power Systems",
      fuelCapacity: 9060,
      waterCapacity: 327599,
      propulsionType: "Azipod Electric Propulsion",
      hullMaterial: "Hybrid Steel-Composite",
      classification: "China Classification Society B",
      safetyEquipment: ["Personal locator beacons","Advanced fire detection and suppression systems","Satellite emergency notification devices","Survival craft VHF radios","Rescue boats and life rafts"],
      navigationEquipment: ["Automatic identification systems (AIS)","Global navigation satellite systems (GNSS)","Infrared camera systems","Electronic chart display information systems (ECDIS)"],
      communicationEquipment: ["Marine radio telephony","Satellite communication systems"],
      entertainmentEquipment: ["Multiple swimming pools and water features","Climbing walls and sports courts","Immersive simulation experiences","Full-service spa and fitness center"],
      accessibilityFeatures: ["Visual alarm systems","Elevator access to all public decks"],
      environmentalFeatures: ["Recyclable material management systems","Advanced water treatment systems","Biodegradable hydraulic fluids","Optimized hull design for reduced fuel consumption"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "my--of-the-deep",
    name: "MY  of the Deep",
    description: "Experience the epitome of maritime excellence aboard the MY  of the Deep, a premier eco friendly hybrid ship sailing from Montevideo. With its elegant design, state-of-the-art technology, and exceptional service, every journey promises unforgettable moments and unparalleled comfort.",
    type: "eco-friendly-hybrid-ship",
    capacity: 1878,
    length: 475,
    width: 81,
    speed: 21,
    topSpeed: 25, 
    yearBuilt: 2017,
    homePort: {"city":"Montevideo","country":"Uruguay","coordinates":{"latitude":-34.9011,"longitude":-56.1645}},
    specifications: {
      engineType: "Gas Turbine Powerplant",
      fuelCapacity: 19230,
      waterCapacity: 563400,
      propulsionType: "Water Jets",
      hullMaterial: "Marine-Grade Steel",
      classification: "RINA Green Star Plus",
      safetyEquipment: ["Emergency escape breathing devices","Satellite emergency notification devices"],
      navigationEquipment: ["Radar and automatic radar plotting aids (ARPAs)","Electronic chart display information systems (ECDIS)"],
      communicationEquipment: ["Digital selective calling equipment","Internal crew communication network"],
      entertainmentEquipment: ["Multiple swimming pools and water features","Cinema with latest releases","Full-service spa and fitness center","Climbing walls and sports courts"],
      accessibilityFeatures: ["Roll-in showers","Service animal accommodations"],
      environmentalFeatures: ["Exhaust gas cleaning systems","Shore power connectivity","LED lighting throughout","Heat recovery systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  }
];
