// This file is auto-generated
    // Do not edit manually.
    // City: Oslo
    // Generated on: 2025-06-08T07:59:32.397Z
    
    import { Vessels } from "@/lib/interfaces/services/cruises";

export const osloVessels: Vessels[] = [
{
    id: "rv--explorer",
    name: "RV  Explorer",
    description: "Sailing from the picturesque port of Oslo, the RV  Explorer represents a new era in cruise experiences. This remarkable boutique cruise ship combines innovative design with thoughtful amenities, creating an atmosphere of refined elegance and warm hospitality.",
    type: "boutique-cruise-ship",
    capacity: 950,
    length: 290,
    width: 53,
    speed: 22,
    topSpeed: 26, 
    yearBuilt: 2011,
    homePort: {"city":"Oslo","country":"Norway","coordinates":{"latitude":59.9139,"longitude":10.7522}},
    specifications: {
      engineType: "Diesel-Electric Propulsion",
      fuelCapacity: 7680,
      waterCapacity: 285000,
      propulsionType: "Z-Drive Propulsion",
      hullMaterial: "Ice-Strengthened Steel",
      classification: "Lloyd's Register Class 1",
      safetyEquipment: ["Searchlights and rescue equipment","Man overboard detection systems","Radar reflectors","Survival craft VHF radios","Emergency escape breathing devices","Weather monitoring stations"],
      navigationEquipment: ["Electronic chart display information systems (ECDIS)","Voyage data recorders (VDRs)","Global navigation satellite systems (GNSS)"],
      communicationEquipment: ["Broadband internet throughout","Global Maritime Distress Safety System (GMDSS)"],
      entertainmentEquipment: ["Casino with table games and slot machines","Immersive simulation experiences"],
      accessibilityFeatures: ["Assistive listening devices","Height-adjustable furniture in select cabins","Braille signage throughout"],
      environmentalFeatures: ["Optimized hull design for reduced fuel consumption","Heat recovery systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "fv-oslo-voyager",
    name: "FV Oslo Voyager",
    description: "The magnificent FV Oslo Voyager offers a perfect blend of adventure and relaxation for travelers departing from Oslo. This outstanding adults only ship features panoramic ocean views, specialized dining experiences, and enriching activities that connect guests with the wonders of the Norway region.",
    type: "adults-only-ship",
    capacity: 658,
    length: 231,
    width: 44,
    speed: 25,
    topSpeed: 29, 
    yearBuilt: 2022,
    homePort: {"city":"Oslo","country":"Norway","coordinates":{"latitude":59.9139,"longitude":10.7522}},
    specifications: {
      engineType: "Azimuth Thrusters",
      fuelCapacity: 5080,
      waterCapacity: 197400,
      propulsionType: "Z-Drive Propulsion",
      hullMaterial: "Ice-Strengthened Steel",
      classification: "ClassNK NS* (Special Purpose Ship)",
      safetyEquipment: ["Survival craft VHF radios","Tactical response equipment","Searchlights and rescue equipment","Life jackets with integrated GPS"],
      navigationEquipment: ["Radar and automatic radar plotting aids (ARPAs)","Inland ECDIS"],
      communicationEquipment: ["Internal crew communication network","Public address systems","Emergency position-indicating radio beacons"],
      entertainmentEquipment: ["Culinary demonstration kitchens","Art gallery and auction facilities","Climbing walls and sports courts"],
      accessibilityFeatures: ["Height-adjustable furniture in select cabins","Braille signage throughout"],
      environmentalFeatures: ["Solar panel supplementation","Energy-efficient appliances","Exhaust gas cleaning systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "sv--of-the-deep",
    name: "SV  of the Deep",
    description: "The majestic SV  of the Deep represents the pinnacle of maritime engineering and hospitality. Based in Oslo, this exceptional catamaran features elegant interiors, cutting-edge facilities, and carefully curated experiences that celebrate the unique culture of the Norway region.",
    type: "catamaran",
    capacity: 1970,
    length: 494,
    width: 84,
    speed: 19,
    topSpeed: 22, 
    yearBuilt: 2013,
    homePort: {"city":"Oslo","country":"Norway","coordinates":{"latitude":59.9139,"longitude":10.7522}},
    specifications: {
      engineType: "LNG-Powered Engines",
      fuelCapacity: 20740,
      waterCapacity: 591000,
      propulsionType: "Azipod Electric Propulsion",
      hullMaterial: "Ice-Strengthened Steel",
      classification: "Lloyd's Register Class 1",
      safetyEquipment: ["Man overboard detection systems","Marine evacuation systems (MES)","Rescue boats and life rafts","Thermal imaging cameras"],
      navigationEquipment: ["River radar systems","Long-range identification and tracking (LRIT)","Voyage data recorders (VDRs)","Navigation data management systems"],
      communicationEquipment: ["Broadband internet throughout","Public address systems"],
      entertainmentEquipment: ["Theater with Broadway-style productions","Full-service spa and fitness center","Art gallery and auction facilities"],
      accessibilityFeatures: ["Assistive listening devices","Height-adjustable furniture in select cabins"],
      environmentalFeatures: ["Dynamic routing to optimize fuel usage","Marine ecosystem monitoring equipment"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "hms-the--mariner",
    name: "HMS The  Mariner",
    description: "The magnificent HMS The  Mariner offers a perfect blend of adventure and relaxation for travelers departing from Oslo. This outstanding polar expedition ship features panoramic ocean views, specialized dining experiences, and enriching activities that connect guests with the wonders of the Norway region.",
    type: "polar-expedition-ship",
    capacity: 1685,
    length: 437,
    width: 75,
    speed: 21,
    topSpeed: 23, 
    yearBuilt: 2014,
    homePort: {"city":"Oslo","country":"Norway","coordinates":{"latitude":59.9139,"longitude":10.7522}},
    specifications: {
      engineType: "Azimuth Thrusters",
      fuelCapacity: 16380,
      waterCapacity: 505500,
      propulsionType: "Cycloidal Drive",
      hullMaterial: "High-Tensile Steel Alloy",
      classification: "American Bureau of Shipping A1",
      safetyEquipment: ["Survival craft VHF radios","Radar reflectors","Tactical response equipment","Hyperbaric treatment chambers","Water purification systems"],
      navigationEquipment: ["Radar and automatic radar plotting aids (ARPAs)"],
      communicationEquipment: ["Broadband internet throughout","Marine radio telephony"],
      entertainmentEquipment: ["Library and educational facilities","Climbing walls and sports courts","Multiple swimming pools and water features","Children's entertainment areas"],
      accessibilityFeatures: ["Height-adjustable furniture in select cabins","Transfer chairs for pool access","Wheelchair accessible cabins","Tactile guidance systems"],
      environmentalFeatures: ["Food waste digesters","Heat recovery systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "cs--gale",
    name: "CS  Gale",
    description: "The CS  Gale stands as a testament to luxury and innovation on the high seas. Departing from Oslo, this sophisticated short hop ferry features immersive entertainment, wellness facilities, and exquisite cuisine prepared by internationally renowned chefs.",
    type: "short-hop-ferry",
    capacity: 795,
    length: 259,
    width: 48,
    speed: 27,
    topSpeed: 32, 
    yearBuilt: 2019,
    homePort: {"city":"Oslo","country":"Norway","coordinates":{"latitude":59.9139,"longitude":10.7522}},
    specifications: {
      engineType: "Gas Turbine Powerplant",
      fuelCapacity: 6210,
      waterCapacity: 238500,
      propulsionType: "Conventional Shaft Propellers",
      hullMaterial: "Ice-Strengthened Steel",
      classification: "China Classification Society B",
      safetyEquipment: ["Satellite emergency notification devices","Life jackets with integrated GPS","Hyperbaric treatment chambers","Weather monitoring stations","Emergency position indicating radio beacons (EPIRBs)"],
      navigationEquipment: ["Automatic identification systems (AIS)","Long-range identification and tracking (LRIT)"],
      communicationEquipment: ["Ship-to-shore communication links","Internal crew communication network","Emergency position-indicating radio beacons"],
      entertainmentEquipment: ["Immersive simulation experiences","Culinary demonstration kitchens"],
      accessibilityFeatures: ["Hearing augmentation systems","Accessible shore excursion options","Accessible dining facilities","Tactile guidance systems"],
      environmentalFeatures: ["Dynamic routing to optimize fuel usage","Marine ecosystem monitoring equipment","Noise reduction technology to minimize impact on marine life"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ts--explorer",
    name: "TS  Explorer",
    description: "The majestic TS  Explorer represents the pinnacle of maritime engineering and hospitality. Based in Oslo, this exceptional ultra luxury cruise ship features elegant interiors, cutting-edge facilities, and carefully curated experiences that celebrate the unique culture of the Norway region.",
    type: "ultra-luxury-cruise-ship",
    capacity: 848,
    length: 269,
    width: 50,
    speed: 19,
    topSpeed: 21, 
    yearBuilt: 2011,
    homePort: {"city":"Oslo","country":"Norway","coordinates":{"latitude":59.9139,"longitude":10.7522}},
    specifications: {
      engineType: "LNG-Powered Engines",
      fuelCapacity: 6720,
      waterCapacity: 254399,
      propulsionType: "Z-Drive Propulsion",
      hullMaterial: "High-Tensile Steel Alloy",
      classification: "American Bureau of Shipping A1",
      safetyEquipment: ["Radar reflectors","Searchlights and rescue equipment","Water purification systems","Thermal imaging cameras","Man overboard detection systems"],
      navigationEquipment: ["Inland ECDIS","Electronic chart display information systems (ECDIS)"],
      communicationEquipment: ["Global Maritime Distress Safety System (GMDSS)","Internal crew communication network"],
      entertainmentEquipment: ["Library and educational facilities","Virtual reality gaming center","Multiple swimming pools and water features"],
      accessibilityFeatures: ["Accessible dining facilities","Braille signage throughout","Hearing augmentation systems","Assistive listening devices"],
      environmentalFeatures: ["Optimized hull design for reduced fuel consumption","Heat recovery systems","Shore power connectivity","Ballast water management technology"]
    },
    isLuxuryVessel: true,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ps-oslo-voyager",
    name: "PS Oslo Voyager",
    description: "Sailing from the picturesque port of Oslo, the PS Oslo Voyager represents a new era in cruise experiences. This remarkable party cruise ship combines innovative design with thoughtful amenities, creating an atmosphere of refined elegance and warm hospitality.",
    type: "party-cruise-ship",
    capacity: 1827,
    length: 465,
    width: 79,
    speed: 18,
    topSpeed: 22, 
    yearBuilt: 2017,
    homePort: {"city":"Oslo","country":"Norway","coordinates":{"latitude":59.9139,"longitude":10.7522}},
    specifications: {
      engineType: "Solar-Assisted Electric",
      fuelCapacity: 18360,
      waterCapacity: 548100,
      propulsionType: "Podded Propulsion Units",
      hullMaterial: "Composite Materials",
      classification: "Russian Maritime Register of Shipping KM",
      safetyEquipment: ["Comprehensive medical facilities","Satellite emergency notification devices","Searchlights and rescue equipment","Marine evacuation systems (MES)","Tactical response equipment","Thermal imaging cameras"],
      navigationEquipment: ["Voyage data recorders (VDRs)","Night vision systems","Weather routing systems"],
      communicationEquipment: ["Ship-to-shore communication links","Marine radio telephony"],
      entertainmentEquipment: ["Art gallery and auction facilities","Children's entertainment areas"],
      accessibilityFeatures: ["Accessible entertainment venues","Service animal accommodations"],
      environmentalFeatures: ["Recyclable material management systems","Optimized hull design for reduced fuel consumption"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "sv--of-the-deep",
    name: "SV  of the Deep",
    description: "The magnificent SV  of the Deep offers a perfect blend of adventure and relaxation for travelers departing from Oslo. This outstanding boutique cruise ship features panoramic ocean views, specialized dining experiences, and enriching activities that connect guests with the wonders of the Norway region.",
    type: "boutique-cruise-ship",
    capacity: 1259,
    length: 351,
    width: 62,
    speed: 29,
    topSpeed: 33, 
    yearBuilt: 2018,
    homePort: {"city":"Oslo","country":"Norway","coordinates":{"latitude":59.9139,"longitude":10.7522}},
    specifications: {
      engineType: "Hybrid Power System",
      fuelCapacity: 10880,
      waterCapacity: 377700,
      propulsionType: "Z-Drive Propulsion",
      hullMaterial: "High-Tensile Steel Alloy",
      classification: "American Bureau of Shipping A1",
      safetyEquipment: ["Hyperbaric treatment chambers","Digital safety monitoring systems","Searchlights and rescue equipment","Emergency position indicating radio beacons (EPIRBs)","Weather monitoring stations"],
      navigationEquipment: ["Bridge alert management systems","Electronic chart display information systems (ECDIS)","Integrated bridge systems","Navigation data management systems"],
      communicationEquipment: ["Digital selective calling equipment","Maritime VHF radio systems"],
      entertainmentEquipment: ["Multi-purpose event spaces","Cinema with latest releases"],
      accessibilityFeatures: ["Transfer chairs for pool access","Accessible shore excursion options","Height-adjustable furniture in select cabins"],
      environmentalFeatures: ["Solar panel supplementation","Dynamic routing to optimize fuel usage"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "mv--explorer",
    name: "MV  Explorer",
    description: "With its distinctive profile and luxurious appointments, the MV  Explorer stands as a jewel in the Oslo harbor. This prestigious boutique cruise ship offers travelers a perfect combination of adventure and relaxation, with expert-guided excursions, world-class entertainment, and sublime culinary experiences.",
    type: "boutique-cruise-ship",
    capacity: 875,
    length: 275,
    width: 51,
    speed: 26,
    topSpeed: 29, 
    yearBuilt: 2017,
    homePort: {"city":"Oslo","country":"Norway","coordinates":{"latitude":59.9139,"longitude":10.7522}},
    specifications: {
      engineType: "Dual-Fuel Marine Engines",
      fuelCapacity: 7010,
      waterCapacity: 262500,
      propulsionType: "Z-Drive Propulsion",
      hullMaterial: "Ice-Strengthened Steel",
      classification: "Bureau Veritas Star Class",
      safetyEquipment: ["Marine evacuation systems (MES)","Personal locator beacons","Satellite emergency notification devices","Radar reflectors","Survival craft VHF radios"],
      navigationEquipment: ["Inland ECDIS","Echo sounders and sonar systems","Voyage data recorders (VDRs)","Integrated bridge systems"],
      communicationEquipment: ["Digital selective calling equipment","Marine radio telephony","Global Maritime Distress Safety System (GMDSS)"],
      entertainmentEquipment: ["Dance clubs and live music venues","Culinary demonstration kitchens","Multiple swimming pools and water features","Library and educational facilities"],
      accessibilityFeatures: ["Braille signage throughout","Transfer chairs for pool access","Accessible entertainment venues"],
      environmentalFeatures: ["Solar panel supplementation","Biodegradable hydraulic fluids","Energy-efficient appliances","Marine ecosystem monitoring equipment"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ms-oslo-voyager",
    name: "MS Oslo Voyager",
    description: "The MS Oslo Voyager invites travelers to explore the treasures of Norway in unmatched comfort. This exceptional adults only ship, based in Oslo, features curated excursions, immersive cultural programs, and luxurious accommodations that ensure an unforgettable journey.",
    type: "adults-only-ship",
    capacity: 1382,
    length: 376,
    width: 66,
    speed: 24,
    topSpeed: 27, 
    yearBuilt: 2017,
    homePort: {"city":"Oslo","country":"Norway","coordinates":{"latitude":59.9139,"longitude":10.7522}},
    specifications: {
      engineType: "Integrated Power Systems",
      fuelCapacity: 12400,
      waterCapacity: 414599,
      propulsionType: "Podded Propulsion Units",
      hullMaterial: "Marine-Grade Steel",
      classification: "China Classification Society B",
      safetyEquipment: ["Digital safety monitoring systems","Weather monitoring stations","Rescue boats and life rafts","Advanced fire detection and suppression systems","Radar reflectors"],
      navigationEquipment: ["Echo sounders and sonar systems","Electronic chart display information systems (ECDIS)","Autopilot systems with track control"],
      communicationEquipment: ["Global Maritime Distress Safety System (GMDSS)","Digital selective calling equipment"],
      entertainmentEquipment: ["Full-service spa and fitness center","Observation lounges with panoramic views"],
      accessibilityFeatures: ["Roll-in showers","Hearing augmentation systems"],
      environmentalFeatures: ["Noise reduction technology to minimize impact on marine life","Dynamic routing to optimize fuel usage"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "fv--of-the-deep",
    name: "FV  of the Deep",
    description: "Sailing from the picturesque port of Oslo, the FV  of the Deep represents a new era in cruise experiences. This remarkable mid size cruise ship combines innovative design with thoughtful amenities, creating an atmosphere of refined elegance and warm hospitality.",
    type: "mid-size-cruise-ship",
    capacity: 861,
    length: 272,
    width: 50,
    speed: 27,
    topSpeed: 30, 
    yearBuilt: 2005,
    homePort: {"city":"Oslo","country":"Norway","coordinates":{"latitude":59.9139,"longitude":10.7522}},
    specifications: {
      engineType: "Solar-Assisted Electric",
      fuelCapacity: 6800,
      waterCapacity: 258300,
      propulsionType: "Azipod Electric Propulsion",
      hullMaterial: "Hybrid Steel-Composite",
      classification: "Bureau Veritas Star Class",
      safetyEquipment: ["Emergency position indicating radio beacons (EPIRBs)","Personal locator beacons","Thermal imaging cameras","Radar reflectors"],
      navigationEquipment: ["Global navigation satellite systems (GNSS)","River radar systems","Automatic identification systems (AIS)","Echo sounders and sonar systems"],
      communicationEquipment: ["Global Maritime Distress Safety System (GMDSS)","Emergency position-indicating radio beacons"],
      entertainmentEquipment: ["Culinary demonstration kitchens","Full-service spa and fitness center","Cinema with latest releases","Immersive simulation experiences"],
      accessibilityFeatures: ["Accessible medical facilities","Hearing augmentation systems","Transfer chairs for pool access"],
      environmentalFeatures: ["Biodegradable hydraulic fluids","Heat recovery systems","Recyclable material management systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "my--explorer",
    name: "MY  Explorer",
    description: "The magnificent MY  Explorer offers a perfect blend of adventure and relaxation for travelers departing from Oslo. This outstanding resort style ship features panoramic ocean views, specialized dining experiences, and enriching activities that connect guests with the wonders of the Norway region.",
    type: "resort-style-ship",
    capacity: 1547,
    length: 409,
    width: 71,
    speed: 24,
    topSpeed: 28, 
    yearBuilt: 2006,
    homePort: {"city":"Oslo","country":"Norway","coordinates":{"latitude":59.9139,"longitude":10.7522}},
    specifications: {
      engineType: "Podded Propulsion",
      fuelCapacity: 14510,
      waterCapacity: 464099,
      propulsionType: "Cycloidal Drive",
      hullMaterial: "Ice-Strengthened Steel",
      classification: "China Classification Society B",
      safetyEquipment: ["Advanced fire detection and suppression systems","Weather monitoring stations","Thermal imaging cameras","Survival craft VHF radios","Personal locator beacons"],
      navigationEquipment: ["Long-range identification and tracking (LRIT)","Integrated bridge systems"],
      communicationEquipment: ["Global Maritime Distress Safety System (GMDSS)","Digital selective calling equipment","Public address systems"],
      entertainmentEquipment: ["Climbing walls and sports courts","Cinema with latest releases","Virtual reality gaming center","Art gallery and auction facilities"],
      accessibilityFeatures: ["Accessible shore excursion options","Wheelchair accessible cabins"],
      environmentalFeatures: ["Dynamic routing to optimize fuel usage","Optimized hull design for reduced fuel consumption"]
    },
    isLuxuryVessel: true,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "my-oslo-voyager",
    name: "MY Oslo Voyager",
    description: "With its distinctive profile and luxurious appointments, the MY Oslo Voyager stands as a jewel in the Oslo harbor. This prestigious small ocean ship offers travelers a perfect combination of adventure and relaxation, with expert-guided excursions, world-class entertainment, and sublime culinary experiences.",
    type: "small-ocean-ship",
    capacity: 1463,
    length: 392,
    width: 68,
    speed: 16,
    topSpeed: 18, 
    yearBuilt: 2013,
    homePort: {"city":"Oslo","country":"Norway","coordinates":{"latitude":59.9139,"longitude":10.7522}},
    specifications: {
      engineType: "Integrated Power Systems",
      fuelCapacity: 13320,
      waterCapacity: 438900,
      propulsionType: "Conventional Shaft Propellers",
      hullMaterial: "Ice-Strengthened Steel",
      classification: "Lloyd's Register Class 1",
      safetyEquipment: ["Hyperbaric treatment chambers","Marine evacuation systems (MES)","Advanced fire detection and suppression systems","Searchlights and rescue equipment","Water purification systems","Rescue boats and life rafts"],
      navigationEquipment: ["River radar systems","Infrared camera systems","Night vision systems","Dynamic positioning systems"],
      communicationEquipment: ["Broadband internet throughout","Public address systems","Emergency position-indicating radio beacons"],
      entertainmentEquipment: ["Theater with Broadway-style productions","Virtual reality gaming center","Immersive simulation experiences","Observation lounges with panoramic views"],
      accessibilityFeatures: ["Hearing augmentation systems"],
      environmentalFeatures: ["Heat recovery systems","Solar panel supplementation"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "hms--of-the-deep",
    name: "HMS  of the Deep",
    description: "The majestic HMS  of the Deep represents the pinnacle of maritime engineering and hospitality. Based in Oslo, this exceptional ultra luxury cruise ship features elegant interiors, cutting-edge facilities, and carefully curated experiences that celebrate the unique culture of the Norway region.",
    type: "ultra-luxury-cruise-ship",
    capacity: 1654,
    length: 430,
    width: 74,
    speed: 23,
    topSpeed: 27, 
    yearBuilt: 2021,
    homePort: {"city":"Oslo","country":"Norway","coordinates":{"latitude":59.9139,"longitude":10.7522}},
    specifications: {
      engineType: "Integrated Power Systems",
      fuelCapacity: 15910,
      waterCapacity: 496200,
      propulsionType: "Voith Schneider Propellers",
      hullMaterial: "Composite Materials",
      classification: "RINA Green Star Plus",
      safetyEquipment: ["Marine evacuation systems (MES)","Automated external defibrillators (AEDs)","Tactical response equipment","Comprehensive medical facilities","Hyperbaric treatment chambers"],
      navigationEquipment: ["Autopilot systems with track control","Bridge alert management systems","Inland ECDIS","Automatic identification systems (AIS)"],
      communicationEquipment: ["Maritime VHF radio systems","Satellite communication systems","Marine radio telephony"],
      entertainmentEquipment: ["Theater with Broadway-style productions","Casino with table games and slot machines","Climbing walls and sports courts"],
      accessibilityFeatures: ["Tactile guidance systems","Transfer chairs for pool access","Accessible entertainment venues","Accessible dining facilities"],
      environmentalFeatures: ["Food waste digesters","Noise reduction technology to minimize impact on marine life","Energy-efficient appliances"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "sv--explorer",
    name: "SV  Explorer",
    description: "The SV  Explorer stands as a testament to luxury and innovation on the high seas. Departing from Oslo, this sophisticated resort style ship features immersive entertainment, wellness facilities, and exquisite cuisine prepared by internationally renowned chefs.",
    type: "resort-style-ship",
    capacity: 1181,
    length: 336,
    width: 60,
    speed: 22,
    topSpeed: 24, 
    yearBuilt: 2017,
    homePort: {"city":"Oslo","country":"Norway","coordinates":{"latitude":59.9139,"longitude":10.7522}},
    specifications: {
      engineType: "Podded Propulsion",
      fuelCapacity: 10080,
      waterCapacity: 354300,
      propulsionType: "Z-Drive Propulsion",
      hullMaterial: "High-Tensile Steel Alloy",
      classification: "American Bureau of Shipping A1",
      safetyEquipment: ["Emergency position indicating radio beacons (EPIRBs)","Man overboard detection systems","Marine evacuation systems (MES)","Radar reflectors","Satellite emergency notification devices"],
      navigationEquipment: ["Radar and automatic radar plotting aids (ARPAs)","Weather routing systems","Integrated navigation system displays","Doppler speed logs"],
      communicationEquipment: ["Marine radio telephony","Satellite communication systems","Ship-to-shore communication links"],
      entertainmentEquipment: ["Full-service spa and fitness center","Observation lounges with panoramic views","Theater with Broadway-style productions"],
      accessibilityFeatures: ["Wheelchair accessible cabins","Service animal accommodations"],
      environmentalFeatures: ["Dynamic routing to optimize fuel usage"]
    },
    isLuxuryVessel: true,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "hms-oslo-voyager",
    name: "HMS Oslo Voyager",
    description: "Experience the epitome of maritime excellence aboard the HMS Oslo Voyager, a premier zodiac equipped vessel sailing from Oslo. With its elegant design, state-of-the-art technology, and exceptional service, every journey promises unforgettable moments and unparalleled comfort.",
    type: "zodiac-equipped-vessel",
    capacity: 913,
    length: 282,
    width: 52,
    speed: 18,
    topSpeed: 21, 
    yearBuilt: 2019,
    homePort: {"city":"Oslo","country":"Norway","coordinates":{"latitude":59.9139,"longitude":10.7522}},
    specifications: {
      engineType: "Gas Turbine Powerplant",
      fuelCapacity: 7330,
      waterCapacity: 273900,
      propulsionType: "Azipod Electric Propulsion",
      hullMaterial: "Marine-Grade Steel",
      classification: "DNV GL High Speed & Light Craft",
      safetyEquipment: ["Marine evacuation systems (MES)","Comprehensive medical facilities","Life jackets with integrated GPS","Emergency position indicating radio beacons (EPIRBs)","Survival craft VHF radios"],
      navigationEquipment: ["Integrated bridge systems","Echo sounders and sonar systems","River radar systems","Dynamic positioning systems"],
      communicationEquipment: ["Broadband internet throughout","Emergency position-indicating radio beacons"],
      entertainmentEquipment: ["Full-service spa and fitness center","Casino with table games and slot machines","Immersive simulation experiences","Art gallery and auction facilities"],
      accessibilityFeatures: ["Height-adjustable furniture in select cabins","Accessible shore excursion options","Accessible dining facilities","Wheelchair accessible cabins"],
      environmentalFeatures: ["Biodegradable hydraulic fluids","Dynamic routing to optimize fuel usage","Shore power connectivity","Solar panel supplementation"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "nx--of-the-deep",
    name: "NX  of the Deep",
    description: "The NX  of the Deep offers an unparalleled cruising experience from Oslo, combining luxury amenities with state-of-the-art navigation technology. This small ocean ship features spacious cabins, gourmet dining options, and entertainment venues that showcase the best of Norway hospitality.",
    type: "small-ocean-ship",
    capacity: 666,
    length: 233,
    width: 44,
    speed: 22,
    topSpeed: 25, 
    yearBuilt: 2017,
    homePort: {"city":"Oslo","country":"Norway","coordinates":{"latitude":59.9139,"longitude":10.7522}},
    specifications: {
      engineType: "Azimuth Thrusters",
      fuelCapacity: 5120,
      waterCapacity: 199799,
      propulsionType: "Podded Propulsion Units",
      hullMaterial: "Marine-Grade Steel",
      classification: "ClassNK NS* (Special Purpose Ship)",
      safetyEquipment: ["Life jackets with integrated GPS","Radar reflectors","Comprehensive medical facilities","Personal locator beacons","Water purification systems","Emergency escape breathing devices","Weather monitoring stations"],
      navigationEquipment: ["Autopilot systems with track control","Global navigation satellite systems (GNSS)","Integrated bridge systems"],
      communicationEquipment: ["Emergency position-indicating radio beacons","Global Maritime Distress Safety System (GMDSS)"],
      entertainmentEquipment: ["Children's entertainment areas","Immersive simulation experiences","Art gallery and auction facilities"],
      accessibilityFeatures: ["Accessible dining facilities","Height-adjustable furniture in select cabins","Assistive listening devices"],
      environmentalFeatures: ["Recyclable material management systems","Shore power connectivity","Noise reduction technology to minimize impact on marine life"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  }
];
