// This file is auto-generated
    // Do not edit manually.
    // City: Quebec City
    // Generated on: 2025-06-08T07:59:32.397Z
    
    import { Vessels } from "@/lib/interfaces/services/cruises";

export const quebecCityVessels: Vessels[] = [
{
    id: "fv--explorer",
    name: "FV  Explorer",
    description: "The majestic FV  Explorer represents the pinnacle of maritime engineering and hospitality. Based in Quebec City, this exceptional polar expedition ship features elegant interiors, cutting-edge facilities, and carefully curated experiences that celebrate the unique culture of the Quebec region.",
    type: "polar-expedition-ship",
    capacity: 1918,
    length: 483,
    width: 82,
    speed: 27,
    topSpeed: 32, 
    yearBuilt: 2014,
    homePort: {"city":"Quebec City","country":"Canada","coordinates":{"latitude":46.8139,"longitude":-71.2082}},
    specifications: {
      engineType: "Integrated Power Systems",
      fuelCapacity: 19800,
      waterCapacity: 575400,
      propulsionType: "Cycloidal Drive",
      hullMaterial: "High-Tensile Steel Alloy",
      classification: "ClassNK NS* (Special Purpose Ship)",
      safetyEquipment: ["Comprehensive medical facilities","Rescue boats and life rafts","Hyperbaric treatment chambers","Weather monitoring stations"],
      navigationEquipment: ["Weather routing systems","Bridge alert management systems","Global navigation satellite systems (GNSS)","Voyage data recorders (VDRs)"],
      communicationEquipment: ["Broadband internet throughout","Marine radio telephony"],
      entertainmentEquipment: ["Library and educational facilities","Casino with table games and slot machines","Dance clubs and live music venues","Cinema with latest releases"],
      accessibilityFeatures: ["Transfer chairs for pool access","Service animal accommodations"],
      environmentalFeatures: ["Ballast water management technology","Noise reduction technology to minimize impact on marine life","Recyclable material management systems","Shore power connectivity"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "rv-quebec-city-voyager",
    name: "RV Quebec City Voyager",
    description: "Experience the epitome of maritime excellence aboard the RV Quebec City Voyager, a premier zodiac equipped vessel sailing from Quebec City. With its elegant design, state-of-the-art technology, and exceptional service, every journey promises unforgettable moments and unparalleled comfort.",
    type: "zodiac-equipped-vessel",
    capacity: 1215,
    length: 343,
    width: 61,
    speed: 17,
    topSpeed: 20, 
    yearBuilt: 2015,
    homePort: {"city":"Quebec City","country":"Canada","coordinates":{"latitude":46.8139,"longitude":-71.2082}},
    specifications: {
      engineType: "LNG-Powered Engines",
      fuelCapacity: 10460,
      waterCapacity: 364500,
      propulsionType: "Counter-Rotating Propellers",
      hullMaterial: "Hybrid Steel-Composite",
      classification: "Russian Maritime Register of Shipping KM",
      safetyEquipment: ["Satellite emergency notification devices","Thermal imaging cameras","Rescue boats and life rafts","Personal locator beacons","Man overboard detection systems","Emergency position indicating radio beacons (EPIRBs)"],
      navigationEquipment: ["Dynamic positioning systems","River radar systems","Weather routing systems","Echo sounders and sonar systems","Infrared camera systems"],
      communicationEquipment: ["Satellite communication systems","Maritime VHF radio systems","Marine radio telephony"],
      entertainmentEquipment: ["Theater with Broadway-style productions","Art gallery and auction facilities"],
      accessibilityFeatures: ["Tactile guidance systems","Wheelchair accessible cabins"],
      environmentalFeatures: ["Recyclable material management systems","Advanced water treatment systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ts--of-the-deep",
    name: "TS  of the Deep",
    description: "Combining traditional maritime charm with modern amenities, the TS  of the Deep promises an extraordinary voyage from its home port of Quebec City. This impressive polar expedition ship offers spacious accommodations, diverse dining options, and engaging activities for travelers of all ages.",
    type: "polar-expedition-ship",
    capacity: 1318,
    length: 363,
    width: 64,
    speed: 17,
    topSpeed: 20, 
    yearBuilt: 2009,
    homePort: {"city":"Quebec City","country":"Canada","coordinates":{"latitude":46.8139,"longitude":-71.2082}},
    specifications: {
      engineType: "Integrated Power Systems",
      fuelCapacity: 11610,
      waterCapacity: 395400,
      propulsionType: "Podded Propulsion Units",
      hullMaterial: "Composite Materials",
      classification: "Lloyd's Register Class 1",
      safetyEquipment: ["Comprehensive medical facilities","Thermal imaging cameras","Survival craft VHF radios","Personal locator beacons","Marine evacuation systems (MES)"],
      navigationEquipment: ["River radar systems","Gyrocompasses and magnetic compasses","Electronic chart display information systems (ECDIS)","Voyage data recorders (VDRs)"],
      communicationEquipment: ["Digital selective calling equipment","Satellite communication systems"],
      entertainmentEquipment: ["Climbing walls and sports courts","Library and educational facilities","Theater with Broadway-style productions","Multi-purpose event spaces"],
      accessibilityFeatures: ["Hearing augmentation systems","Assistive listening devices","Accessible shore excursion options","Tactile guidance systems"],
      environmentalFeatures: ["Optimized hull design for reduced fuel consumption","Ballast water management technology"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "mv-the--mariner",
    name: "MV The  Mariner",
    description: "The MV The  Mariner stands as a testament to luxury and innovation on the high seas. Departing from Quebec City, this sophisticated mid size cruise ship features immersive entertainment, wellness facilities, and exquisite cuisine prepared by internationally renowned chefs.",
    type: "mid-size-cruise-ship",
    capacity: 738,
    length: 247,
    width: 47,
    speed: 27,
    topSpeed: 32, 
    yearBuilt: 2021,
    homePort: {"city":"Quebec City","country":"Canada","coordinates":{"latitude":46.8139,"longitude":-71.2082}},
    specifications: {
      engineType: "Diesel-Electric Propulsion",
      fuelCapacity: 5800,
      waterCapacity: 221400,
      propulsionType: "Podded Propulsion Units",
      hullMaterial: "Hybrid Steel-Composite",
      classification: "RINA Green Star Plus",
      safetyEquipment: ["Satellite emergency notification devices","Life jackets with integrated GPS","Emergency position indicating radio beacons (EPIRBs)"],
      navigationEquipment: ["Dynamic positioning systems","Automatic identification systems (AIS)"],
      communicationEquipment: ["Maritime VHF radio systems","Emergency position-indicating radio beacons"],
      entertainmentEquipment: ["Full-service spa and fitness center","Cinema with latest releases","Theater with Broadway-style productions"],
      accessibilityFeatures: ["Accessible medical facilities","Accessible entertainment venues","Hearing augmentation systems"],
      environmentalFeatures: ["Heat recovery systems","Energy-efficient appliances"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "hms--gale",
    name: "HMS  Gale",
    description: "With its distinctive profile and luxurious appointments, the HMS  Gale stands as a jewel in the Quebec City harbor. This prestigious short hop ferry offers travelers a perfect combination of adventure and relaxation, with expert-guided excursions, world-class entertainment, and sublime culinary experiences.",
    type: "short-hop-ferry",
    capacity: 1736,
    length: 447,
    width: 77,
    speed: 29,
    topSpeed: 35, 
    yearBuilt: 2020,
    homePort: {"city":"Quebec City","country":"Canada","coordinates":{"latitude":46.8139,"longitude":-71.2082}},
    specifications: {
      engineType: "Integrated Power Systems",
      fuelCapacity: 17200,
      waterCapacity: 520799,
      propulsionType: "Conventional Shaft Propellers",
      hullMaterial: "High-Tensile Steel Alloy",
      classification: "DNV GL High Speed & Light Craft",
      safetyEquipment: ["Automated external defibrillators (AEDs)","Tactical response equipment","Emergency position indicating radio beacons (EPIRBs)","Rescue boats and life rafts","Radar reflectors","Life jackets with integrated GPS"],
      navigationEquipment: ["Bridge alert management systems","Night vision systems"],
      communicationEquipment: ["Maritime VHF radio systems","Public address systems"],
      entertainmentEquipment: ["Climbing walls and sports courts","Theater with Broadway-style productions"],
      accessibilityFeatures: ["Elevator access to all public decks","Wheelchair accessible cabins"],
      environmentalFeatures: ["LED lighting throughout","Energy-efficient appliances","Solar panel supplementation"]
    },
    isLuxuryVessel: true,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "nx--explorer",
    name: "NX  Explorer",
    description: "The majestic NX  Explorer represents the pinnacle of maritime engineering and hospitality. Based in Quebec City, this exceptional eco friendly hybrid ship features elegant interiors, cutting-edge facilities, and carefully curated experiences that celebrate the unique culture of the Quebec region.",
    type: "eco-friendly-hybrid-ship",
    capacity: 964,
    length: 292,
    width: 53,
    speed: 22,
    topSpeed: 24, 
    yearBuilt: 2014,
    homePort: {"city":"Quebec City","country":"Canada","coordinates":{"latitude":46.8139,"longitude":-71.2082}},
    specifications: {
      engineType: "Dual-Fuel Marine Engines",
      fuelCapacity: 7730,
      waterCapacity: 289200,
      propulsionType: "Voith Schneider Propellers",
      hullMaterial: "Marine-Grade Steel",
      classification: "ClassNK NS* (Special Purpose Ship)",
      safetyEquipment: ["Searchlights and rescue equipment","Thermal imaging cameras","Emergency position indicating radio beacons (EPIRBs)","Survival craft VHF radios"],
      navigationEquipment: ["Autopilot systems with track control","Bridge alert management systems","Integrated navigation system displays"],
      communicationEquipment: ["Internal crew communication network","Broadband internet throughout"],
      entertainmentEquipment: ["Dance clubs and live music venues","Full-service spa and fitness center"],
      accessibilityFeatures: ["Hearing augmentation systems","Assistive listening devices","Tactile guidance systems"],
      environmentalFeatures: ["LED lighting throughout","Solar panel supplementation"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "mv-quebec-city-voyager",
    name: "MV Quebec City Voyager",
    description: "The MV Quebec City Voyager stands as a testament to luxury and innovation on the high seas. Departing from Quebec City, this sophisticated mega yacht features immersive entertainment, wellness facilities, and exquisite cuisine prepared by internationally renowned chefs.",
    type: "mega-yacht",
    capacity: 836,
    length: 267,
    width: 50,
    speed: 27,
    topSpeed: 30, 
    yearBuilt: 2009,
    homePort: {"city":"Quebec City","country":"Canada","coordinates":{"latitude":46.8139,"longitude":-71.2082}},
    specifications: {
      engineType: "Podded Propulsion",
      fuelCapacity: 6670,
      waterCapacity: 250799,
      propulsionType: "Conventional Shaft Propellers",
      hullMaterial: "Marine-Grade Steel",
      classification: "Lloyd's Register Class 1",
      safetyEquipment: ["Marine evacuation systems (MES)","Man overboard detection systems","Searchlights and rescue equipment","Comprehensive medical facilities","Life jackets with integrated GPS"],
      navigationEquipment: ["River radar systems","Radar and automatic radar plotting aids (ARPAs)","Bridge alert management systems"],
      communicationEquipment: ["Satellite communication systems","Broadband internet throughout"],
      entertainmentEquipment: ["Multi-purpose event spaces","Children's entertainment areas"],
      accessibilityFeatures: ["Transfer chairs for pool access","Elevator access to all public decks"],
      environmentalFeatures: ["Marine ecosystem monitoring equipment","Solar panel supplementation","Dynamic routing to optimize fuel usage"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "cs--of-the-deep",
    name: "CS  of the Deep",
    description: "The CS  of the Deep offers an unparalleled cruising experience from Quebec City, combining luxury amenities with state-of-the-art navigation technology. This party cruise ship features spacious cabins, gourmet dining options, and entertainment venues that showcase the best of Quebec hospitality.",
    type: "party-cruise-ship",
    capacity: 1233,
    length: 346,
    width: 61,
    speed: 24,
    topSpeed: 26, 
    yearBuilt: 2013,
    homePort: {"city":"Quebec City","country":"Canada","coordinates":{"latitude":46.8139,"longitude":-71.2082}},
    specifications: {
      engineType: "Hybrid Power System",
      fuelCapacity: 10550,
      waterCapacity: 369900,
      propulsionType: "Voith Schneider Propellers",
      hullMaterial: "Composite Materials",
      classification: "Lloyd's Register Class 1",
      safetyEquipment: ["Digital safety monitoring systems","Rescue boats and life rafts","Personal locator beacons","Survival craft VHF radios","Man overboard detection systems"],
      navigationEquipment: ["Voyage data recorders (VDRs)","Autopilot systems with track control","Weather routing systems","Gyrocompasses and magnetic compasses"],
      communicationEquipment: ["Marine radio telephony","Internal crew communication network","Satellite communication systems"],
      entertainmentEquipment: ["Library and educational facilities","Casino with table games and slot machines","Multi-purpose event spaces"],
      accessibilityFeatures: ["Accessible dining facilities","Height-adjustable furniture in select cabins"],
      environmentalFeatures: ["Optimized hull design for reduced fuel consumption","Exhaust gas cleaning systems","Recyclable material management systems","Food waste digesters"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "rms--explorer",
    name: "RMS  Explorer",
    description: "The RMS  Explorer invites travelers to explore the treasures of Quebec in unmatched comfort. This exceptional mid size cruise ship, based in Quebec City, features curated excursions, immersive cultural programs, and luxurious accommodations that ensure an unforgettable journey.",
    type: "mid-size-cruise-ship",
    capacity: 1744,
    length: 448,
    width: 77,
    speed: 18,
    topSpeed: 21, 
    yearBuilt: 2024,
    homePort: {"city":"Quebec City","country":"Canada","coordinates":{"latitude":46.8139,"longitude":-71.2082}},
    specifications: {
      engineType: "Azimuth Thrusters",
      fuelCapacity: 17240,
      waterCapacity: 523199,
      propulsionType: "Cycloidal Drive",
      hullMaterial: "Marine-Grade Steel",
      classification: "American Bureau of Shipping A1",
      safetyEquipment: ["Searchlights and rescue equipment","Water purification systems","Emergency escape breathing devices","Hyperbaric treatment chambers","Personal locator beacons"],
      navigationEquipment: ["Autopilot systems with track control","Night vision systems","Infrared camera systems","Integrated bridge systems","Inland ECDIS"],
      communicationEquipment: ["Maritime VHF radio systems","Global Maritime Distress Safety System (GMDSS)"],
      entertainmentEquipment: ["Theater with Broadway-style productions","Immersive simulation experiences"],
      accessibilityFeatures: ["Visual alarm systems","Wheelchair accessible cabins","Tactile guidance systems"],
      environmentalFeatures: ["Recyclable material management systems","LED lighting throughout"]
    },
    isLuxuryVessel: true,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "sy-quebec-city-voyager",
    name: "SY Quebec City Voyager",
    description: "Setting sail from the beautiful port of Quebec City, the SY Quebec City Voyager is a floating paradise designed for the discerning traveler. This remarkable river cruise ship boasts panoramic viewing decks, world-class cuisine, and personalized service that ensures an unforgettable journey.",
    type: "river-cruise-ship",
    capacity: 1021,
    length: 304,
    width: 55,
    speed: 29,
    topSpeed: 33, 
    yearBuilt: 2010,
    homePort: {"city":"Quebec City","country":"Canada","coordinates":{"latitude":46.8139,"longitude":-71.2082}},
    specifications: {
      engineType: "Podded Propulsion",
      fuelCapacity: 8360,
      waterCapacity: 306300,
      propulsionType: "Voith Schneider Propellers",
      hullMaterial: "Ice-Strengthened Steel",
      classification: "China Classification Society B",
      safetyEquipment: ["Personal locator beacons","Automated external defibrillators (AEDs)","Hyperbaric treatment chambers"],
      navigationEquipment: ["Long-range identification and tracking (LRIT)","Infrared camera systems","Night vision systems"],
      communicationEquipment: ["Global Maritime Distress Safety System (GMDSS)","Public address systems"],
      entertainmentEquipment: ["Full-service spa and fitness center","Art gallery and auction facilities","Observation lounges with panoramic views"],
      accessibilityFeatures: ["Elevator access to all public decks","Accessible medical facilities"],
      environmentalFeatures: ["Shore power connectivity","Dynamic routing to optimize fuel usage"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "rms--of-the-deep",
    name: "RMS  of the Deep",
    description: "The RMS  of the Deep invites travelers to explore the treasures of Quebec in unmatched comfort. This exceptional resort style ship, based in Quebec City, features curated excursions, immersive cultural programs, and luxurious accommodations that ensure an unforgettable journey.",
    type: "resort-style-ship",
    capacity: 1868,
    length: 473,
    width: 80,
    speed: 25,
    topSpeed: 28, 
    yearBuilt: 2007,
    homePort: {"city":"Quebec City","country":"Canada","coordinates":{"latitude":46.8139,"longitude":-71.2082}},
    specifications: {
      engineType: "Gas Turbine Powerplant",
      fuelCapacity: 18920,
      waterCapacity: 560400,
      propulsionType: "Counter-Rotating Propellers",
      hullMaterial: "Composite Materials",
      classification: "Bureau Veritas Star Class",
      safetyEquipment: ["Emergency position indicating radio beacons (EPIRBs)","Automated external defibrillators (AEDs)","Emergency escape breathing devices","Marine evacuation systems (MES)","Searchlights and rescue equipment","Thermal imaging cameras"],
      navigationEquipment: ["Doppler speed logs","Navigation data management systems","Global navigation satellite systems (GNSS)","Gyrocompasses and magnetic compasses"],
      communicationEquipment: ["Public address systems","Satellite communication systems"],
      entertainmentEquipment: ["Climbing walls and sports courts","Library and educational facilities","Virtual reality gaming center"],
      accessibilityFeatures: ["Visual alarm systems","Tactile guidance systems"],
      environmentalFeatures: ["Ballast water management technology","Advanced water treatment systems","Exhaust gas cleaning systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "mv--explorer",
    name: "MV  Explorer",
    description: "The magnificent MV  Explorer offers a perfect blend of adventure and relaxation for travelers departing from Quebec City. This outstanding expedition ship features panoramic ocean views, specialized dining experiences, and enriching activities that connect guests with the wonders of the Quebec region.",
    type: "expedition-ship",
    capacity: 630,
    length: 226,
    width: 43,
    speed: 28,
    topSpeed: 31, 
    yearBuilt: 2014,
    homePort: {"city":"Quebec City","country":"Canada","coordinates":{"latitude":46.8139,"longitude":-71.2082}},
    specifications: {
      engineType: "Solar-Assisted Electric",
      fuelCapacity: 4850,
      waterCapacity: 189000,
      propulsionType: "Voith Schneider Propellers",
      hullMaterial: "Hybrid Steel-Composite",
      classification: "Lloyd's Register Class 1",
      safetyEquipment: ["Comprehensive medical facilities","Personal locator beacons","Weather monitoring stations","Man overboard detection systems","Tactical response equipment"],
      navigationEquipment: ["Dynamic positioning systems","Autopilot systems with track control","Inland ECDIS"],
      communicationEquipment: ["Maritime VHF radio systems","Global Maritime Distress Safety System (GMDSS)"],
      entertainmentEquipment: ["Culinary demonstration kitchens","Casino with table games and slot machines"],
      accessibilityFeatures: ["Height-adjustable furniture in select cabins","Accessible medical facilities"],
      environmentalFeatures: ["Heat recovery systems","Dynamic routing to optimize fuel usage","Advanced water treatment systems","Marine ecosystem monitoring equipment"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "nx-quebec-city-voyager",
    name: "NX Quebec City Voyager",
    description: "The majestic NX Quebec City Voyager represents the pinnacle of maritime engineering and hospitality. Based in Quebec City, this exceptional mid size cruise ship features elegant interiors, cutting-edge facilities, and carefully curated experiences that celebrate the unique culture of the Quebec region.",
    type: "mid-size-cruise-ship",
    capacity: 1941,
    length: 488,
    width: 83,
    speed: 22,
    topSpeed: 24, 
    yearBuilt: 2006,
    homePort: {"city":"Quebec City","country":"Canada","coordinates":{"latitude":46.8139,"longitude":-71.2082}},
    specifications: {
      engineType: "LNG-Powered Engines",
      fuelCapacity: 20250,
      waterCapacity: 582300,
      propulsionType: "Water Jets",
      hullMaterial: "Reinforced Aluminum",
      classification: "RINA Green Star Plus",
      safetyEquipment: ["Comprehensive medical facilities","Rescue boats and life rafts","Emergency escape breathing devices"],
      navigationEquipment: ["Electronic chart display information systems (ECDIS)","Long-range identification and tracking (LRIT)","Voyage data recorders (VDRs)"],
      communicationEquipment: ["Digital selective calling equipment","Internal crew communication network","Maritime VHF radio systems"],
      entertainmentEquipment: ["Full-service spa and fitness center","Art gallery and auction facilities","Culinary demonstration kitchens"],
      accessibilityFeatures: ["Tactile guidance systems","Braille signage throughout","Hearing augmentation systems"],
      environmentalFeatures: ["Heat recovery systems","Shore power connectivity","Food waste digesters"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ly--of-the-deep",
    name: "LY  of the Deep",
    description: "Experience the epitome of maritime excellence aboard the LY  of the Deep, a premier mega yacht sailing from Quebec City. With its elegant design, state-of-the-art technology, and exceptional service, every journey promises unforgettable moments and unparalleled comfort.",
    type: "mega-yacht",
    capacity: 1055,
    length: 311,
    width: 56,
    speed: 15,
    topSpeed: 18, 
    yearBuilt: 2015,
    homePort: {"city":"Quebec City","country":"Canada","coordinates":{"latitude":46.8139,"longitude":-71.2082}},
    specifications: {
      engineType: "Solar-Assisted Electric",
      fuelCapacity: 8700,
      waterCapacity: 316500,
      propulsionType: "Z-Drive Propulsion",
      hullMaterial: "Marine-Grade Steel",
      classification: "DNV GL High Speed & Light Craft",
      safetyEquipment: ["Weather monitoring stations","Satellite emergency notification devices","Hyperbaric treatment chambers","Emergency escape breathing devices","Digital safety monitoring systems","Rescue boats and life rafts"],
      navigationEquipment: ["Autopilot systems with track control","Night vision systems","Electronic chart display information systems (ECDIS)","Integrated navigation system displays"],
      communicationEquipment: ["Public address systems"],
      entertainmentEquipment: ["Children's entertainment areas","Library and educational facilities"],
      accessibilityFeatures: ["Hearing augmentation systems","Service animal accommodations","Wheelchair accessible cabins","Transfer chairs for pool access"],
      environmentalFeatures: ["Food waste digesters","Marine ecosystem monitoring equipment","Energy-efficient appliances"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "cs--explorer",
    name: "CS  Explorer",
    description: "The magnificent CS  Explorer offers a perfect blend of adventure and relaxation for travelers departing from Quebec City. This outstanding expedition ship features panoramic ocean views, specialized dining experiences, and enriching activities that connect guests with the wonders of the Quebec region.",
    type: "expedition-ship",
    capacity: 1509,
    length: 401,
    width: 70,
    speed: 19,
    topSpeed: 21, 
    yearBuilt: 2016,
    homePort: {"city":"Quebec City","country":"Canada","coordinates":{"latitude":46.8139,"longitude":-71.2082}},
    specifications: {
      engineType: "Diesel-Electric Propulsion",
      fuelCapacity: 14030,
      waterCapacity: 452700,
      propulsionType: "Counter-Rotating Propellers",
      hullMaterial: "Reinforced Aluminum",
      classification: "Bureau Veritas Star Class",
      safetyEquipment: ["Thermal imaging cameras","Advanced fire detection and suppression systems","Weather monitoring stations","Radar reflectors"],
      navigationEquipment: ["Global navigation satellite systems (GNSS)","Gyrocompasses and magnetic compasses","River radar systems"],
      communicationEquipment: ["Public address systems","Broadband internet throughout","Emergency position-indicating radio beacons"],
      entertainmentEquipment: ["Observation lounges with panoramic views","Art gallery and auction facilities","Climbing walls and sports courts","Children's entertainment areas","Full-service spa and fitness center"],
      accessibilityFeatures: ["Accessible dining facilities","Assistive listening devices","Height-adjustable furniture in select cabins"],
      environmentalFeatures: ["Optimized hull design for reduced fuel consumption","Biodegradable hydraulic fluids"]
    },
    isLuxuryVessel: true,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "sv-quebec-city-voyager",
    name: "SV Quebec City Voyager",
    description: "Sailing from the picturesque port of Quebec City, the SV Quebec City Voyager represents a new era in cruise experiences. This remarkable superyacht combines innovative design with thoughtful amenities, creating an atmosphere of refined elegance and warm hospitality.",
    type: "superyacht",
    capacity: 1906,
    length: 481,
    width: 82,
    speed: 28,
    topSpeed: 31, 
    yearBuilt: 2013,
    homePort: {"city":"Quebec City","country":"Canada","coordinates":{"latitude":46.8139,"longitude":-71.2082}},
    specifications: {
      engineType: "Podded Propulsion",
      fuelCapacity: 19720,
      waterCapacity: 571800,
      propulsionType: "Cycloidal Drive",
      hullMaterial: "Composite Materials",
      classification: "Bureau Veritas Star Class",
      safetyEquipment: ["Emergency position indicating radio beacons (EPIRBs)","Searchlights and rescue equipment","Tactical response equipment","Weather monitoring stations","Personal locator beacons","Automated external defibrillators (AEDs)"],
      navigationEquipment: ["Global navigation satellite systems (GNSS)","Dynamic positioning systems","Inland ECDIS","Doppler speed logs"],
      communicationEquipment: ["Satellite communication systems","Broadband internet throughout"],
      entertainmentEquipment: ["Virtual reality gaming center","Climbing walls and sports courts","Observation lounges with panoramic views","Culinary demonstration kitchens"],
      accessibilityFeatures: ["Braille signage throughout","Accessible entertainment venues","Hearing augmentation systems"],
      environmentalFeatures: ["Food waste digesters","Solar panel supplementation"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "sy--of-the-deep",
    name: "SY  of the Deep",
    description: "Combining traditional maritime charm with modern amenities, the SY  of the Deep promises an extraordinary voyage from its home port of Quebec City. This impressive expedition ship offers spacious accommodations, diverse dining options, and engaging activities for travelers of all ages.",
    type: "expedition-ship",
    capacity: 1870,
    length: 474,
    width: 81,
    speed: 17,
    topSpeed: 19, 
    yearBuilt: 2015,
    homePort: {"city":"Quebec City","country":"Canada","coordinates":{"latitude":46.8139,"longitude":-71.2082}},
    specifications: {
      engineType: "Dual-Fuel Marine Engines",
      fuelCapacity: 19190,
      waterCapacity: 561000,
      propulsionType: "Podded Propulsion Units",
      hullMaterial: "Marine-Grade Steel",
      classification: "ClassNK NS* (Special Purpose Ship)",
      safetyEquipment: ["Tactical response equipment","Emergency escape breathing devices","Survival craft VHF radios","Comprehensive medical facilities"],
      navigationEquipment: ["Doppler speed logs","Weather routing systems"],
      communicationEquipment: ["Ship-to-shore communication links","Internal crew communication network"],
      entertainmentEquipment: ["Art gallery and auction facilities","Casino with table games and slot machines","Virtual reality gaming center"],
      accessibilityFeatures: ["Accessible entertainment venues","Accessible dining facilities","Tactile guidance systems","Accessible shore excursion options"],
      environmentalFeatures: ["Dynamic routing to optimize fuel usage","Marine ecosystem monitoring equipment"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  }
];
