// This file is auto-generated
    // Do not edit manually.
    // City: San Francisco
    // Generated on: 2025-06-10T08:14:15.040Z
    
    import { Vessels } from "@/lib/interfaces/services/cruises";

export const sanFranciscoVessels: Vessels[] = [
{
    id: "my--explorer",
    name: "MY  Explorer",
    description: "The MY  Explorer stands as a testament to luxury and innovation on the high seas. Departing from San Francisco, this sophisticated superyacht features immersive entertainment, wellness facilities, and exquisite cuisine prepared by internationally renowned chefs.",
    type: "superyacht",
    capacity: 995,
    length: 299,
    width: 54,
    speed: 15,
    topSpeed: 17, 
    yearBuilt: 2005,
    homePort: {"city":"San Francisco","country":"United States","coordinates":{"latitude":0,"longitude":0}},
    specifications: {
      engineType: "Solar-Assisted Electric",
      fuelCapacity: 8070,
      waterCapacity: 298500,
      propulsionType: "Conventional Shaft Propellers",
      hullMaterial: "Marine-Grade Steel",
      classification: "DNV GL High Speed & Light Craft",
      safetyEquipment: ["Weather monitoring stations","Personal locator beacons"],
      navigationEquipment: ["Electronic chart display information systems (ECDIS)","Automatic identification systems (AIS)"],
      communicationEquipment: ["Marine radio telephony","Emergency position-indicating radio beacons","Digital selective calling equipment"],
      entertainmentEquipment: ["Climbing walls and sports courts","Children's entertainment areas","Immersive simulation experiences","Multi-purpose event spaces"],
      accessibilityFeatures: ["Elevator access to all public decks","Tactile guidance systems"],
      environmentalFeatures: ["Shore power connectivity","Food waste digesters","LED lighting throughout"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ts-san-francisco-voyager",
    name: "TS San Francisco Voyager",
    description: "The majestic TS San Francisco Voyager represents the pinnacle of maritime engineering and hospitality. Based in San Francisco, this exceptional zodiac equipped vessel features deluxe interiors, cutting-edge facilities, and carefully curated experiences that celebrate the unique culture of the California region.",
    type: "zodiac-equipped-vessel",
    capacity: 1514,
    length: 402,
    width: 70,
    speed: 28,
    topSpeed: 33, 
    yearBuilt: 2007,
    homePort: {"city":"San Francisco","country":"United States","coordinates":{"latitude":0,"longitude":0}},
    specifications: {
      engineType: "Gas Turbine Powerplant",
      fuelCapacity: 14070,
      waterCapacity: 454200,
      propulsionType: "Voith Schneider Propellers",
      hullMaterial: "Composite Materials",
      classification: "American Bureau of Shipping A1",
      safetyEquipment: ["Digital safety monitoring systems","Marine evacuation systems (MES)","Personal locator beacons","Survival craft VHF radios","Tactical response equipment"],
      navigationEquipment: ["Weather routing systems","River radar systems","Long-range identification and tracking (LRIT)","Doppler speed logs","Autopilot systems with track control"],
      communicationEquipment: ["Satellite communication systems","Maritime VHF radio systems","Global Maritime Distress Safety System (GMDSS)"],
      entertainmentEquipment: ["Culinary demonstration kitchens","Multiple swimming pools and water features","Library and educational facilities","Art gallery and auction facilities"],
      accessibilityFeatures: ["Elevator access to all public decks","Accessible entertainment venues","Assistive listening devices","Service animal accommodations"],
      environmentalFeatures: ["Food waste digesters","LED lighting throughout","Recyclable material management systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "rms--of-the-deep",
    name: "RMS  of the Deep",
    description: "With its distinctive profile and luxurious appointments, the RMS  of the Deep stands as a jewel in the San Francisco harbor. This prestigious river cruise ship offers travelers a perfect combination of adventure and relaxation, with expert-guided excursions, world-class entertainment, and sublime culinary experiences.",
    type: "river-cruise-ship",
    capacity: 1143,
    length: 328,
    width: 59,
    speed: 25,
    topSpeed: 30, 
    yearBuilt: 2023,
    homePort: {"city":"San Francisco","country":"United States","coordinates":{"latitude":0,"longitude":0}},
    specifications: {
      engineType: "Hybrid Power System",
      fuelCapacity: 9670,
      waterCapacity: 342900,
      propulsionType: "Counter-Rotating Propellers",
      hullMaterial: "Composite Materials",
      classification: "Lloyd's Register Class 1",
      safetyEquipment: ["Thermal imaging cameras","Weather monitoring stations","Marine evacuation systems (MES)","Emergency escape breathing devices"],
      navigationEquipment: ["Dynamic positioning systems","Integrated navigation system displays","River radar systems","Electronic chart display information systems (ECDIS)"],
      communicationEquipment: ["Satellite communication systems","Digital selective calling equipment","Public address systems"],
      entertainmentEquipment: ["Casino with table games and slot machines","Culinary demonstration kitchens","Observation lounges with panoramic views","Theater with Broadway-style productions"],
      accessibilityFeatures: ["Accessible shore excursion options","Elevator access to all public decks","Roll-in showers"],
      environmentalFeatures: ["Ballast water management technology","Food waste digesters","Optimized hull design for reduced fuel consumption","Shore power connectivity"]
    },
    isLuxuryVessel: true,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "mv-the--mariner",
    name: "MV The  Mariner",
    description: "The majestic MV The  Mariner represents the pinnacle of maritime engineering and hospitality. Based in San Francisco, this exceptional chartered vessel features radiating interiors, cutting-edge facilities, and carefully curated experiences that celebrate the unique culture of the California region.",
    type: "chartered-vessel",
    capacity: 1839,
    length: 467,
    width: 80,
    speed: 18,
    topSpeed: 20, 
    yearBuilt: 2011,
    homePort: {"city":"San Francisco","country":"United States","coordinates":{"latitude":0,"longitude":0}},
    specifications: {
      engineType: "Gas Turbine Powerplant",
      fuelCapacity: 18680,
      waterCapacity: 551699,
      propulsionType: "Conventional Shaft Propellers",
      hullMaterial: "Composite Materials",
      classification: "Lloyd's Register Class 1",
      safetyEquipment: ["Digital safety monitoring systems","Comprehensive medical facilities"],
      navigationEquipment: ["Infrared camera systems","Electronic chart display information systems (ECDIS)"],
      communicationEquipment: ["Marine radio telephony","Digital selective calling equipment","Global Maritime Distress Safety System (GMDSS)"],
      entertainmentEquipment: ["Observation lounges with panoramic views","Climbing walls and sports courts"],
      accessibilityFeatures: ["Transfer chairs for pool access","Height-adjustable furniture in select cabins","Accessible dining facilities","Assistive listening devices"],
      environmentalFeatures: ["Energy-efficient appliances","Advanced water treatment systems","Noise reduction technology to minimize impact on marine life","Heat recovery systems"]
    },
    isLuxuryVessel: true,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "nb--gale",
    name: "NB  Gale",
    description: "The magnificent NB  Gale offers a perfect blend of adventure and relaxation for travelers departing from San Francisco. This outstanding luxury cruise ship features panoramic ocean views, specialized dining experiences, and enriching activities that connect guests with the wonders of the California region.",
    type: "luxury-cruise-ship",
    capacity: 286,
    length: 157,
    width: 33,
    speed: 21,
    topSpeed: 24, 
    yearBuilt: 2010,
    homePort: {"city":"San Francisco","country":"United States","coordinates":{"latitude":0,"longitude":0}},
    specifications: {
      engineType: "Solar-Assisted Electric",
      fuelCapacity: 2590,
      waterCapacity: 85800,
      propulsionType: "Z-Drive Propulsion",
      hullMaterial: "Ice-Strengthened Steel",
      classification: "RINA Green Star Plus",
      safetyEquipment: ["Comprehensive medical facilities","Radar reflectors","Personal locator beacons","Digital safety monitoring systems","Rescue boats and life rafts"],
      navigationEquipment: ["Radar and automatic radar plotting aids (ARPAs)","Dynamic positioning systems"],
      communicationEquipment: ["Satellite communication systems","Broadband internet throughout","Emergency position-indicating radio beacons"],
      entertainmentEquipment: ["Theater with Broadway-style productions","Art gallery and auction facilities"],
      accessibilityFeatures: ["Wheelchair accessible cabins","Roll-in showers"],
      environmentalFeatures: ["Biodegradable hydraulic fluids","LED lighting throughout","Exhaust gas cleaning systems"]
    },
    isLuxuryVessel: true,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ps--explorer",
    name: "PS  Explorer",
    description: "Sailing from the picturesque port of San Francisco, the PS  Explorer represents a new era in cruise experiences. This remarkable family cruise ship combines innovative design with thoughtful amenities, creating an atmosphere of refined elegance and warm hospitality.",
    type: "family-cruise-ship",
    capacity: 1618,
    length: 423,
    width: 73,
    speed: 16,
    topSpeed: 19, 
    yearBuilt: 2012,
    homePort: {"city":"San Francisco","country":"United States","coordinates":{"latitude":0,"longitude":0}},
    specifications: {
      engineType: "Azimuth Thrusters",
      fuelCapacity: 15430,
      waterCapacity: 485400,
      propulsionType: "Z-Drive Propulsion",
      hullMaterial: "Composite Materials",
      classification: "DNV GL High Speed & Light Craft",
      safetyEquipment: ["Personal locator beacons","Tactical response equipment","Rescue boats and life rafts","Advanced fire detection and suppression systems","Satellite emergency notification devices"],
      navigationEquipment: ["Automatic identification systems (AIS)","Night vision systems","Weather routing systems"],
      communicationEquipment: ["Internal crew communication network","Broadband internet throughout","Marine radio telephony"],
      entertainmentEquipment: ["Observation lounges with panoramic views","Immersive simulation experiences","Art gallery and auction facilities"],
      accessibilityFeatures: ["Height-adjustable furniture in select cabins","Wheelchair accessible cabins","Assistive listening devices"],
      environmentalFeatures: ["Biodegradable hydraulic fluids","Food waste digesters","Advanced water treatment systems","Marine ecosystem monitoring equipment","LED lighting throughout"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "sy-san-francisco-voyager",
    name: "SY San Francisco Voyager",
    description: "The SY San Francisco Voyager stands as a testament to luxury and innovation on the high seas. Departing from San Francisco, this sophisticated expedition ship features immersive entertainment, wellness facilities, and exquisite cuisine prepared by internationally renowned chefs.",
    type: "expedition-ship",
    capacity: 1938,
    length: 487,
    width: 83,
    speed: 20,
    topSpeed: 23, 
    yearBuilt: 2009,
    homePort: {"city":"San Francisco","country":"United States","coordinates":{"latitude":0,"longitude":0}},
    specifications: {
      engineType: "Dual-Fuel Marine Engines",
      fuelCapacity: 20210,
      waterCapacity: 581400,
      propulsionType: "Azipod Electric Propulsion",
      hullMaterial: "Reinforced Aluminum",
      classification: "ClassNK NS* (Special Purpose Ship)",
      safetyEquipment: ["Weather monitoring stations","Automated external defibrillators (AEDs)","Hyperbaric treatment chambers"],
      navigationEquipment: ["River radar systems","Integrated navigation system displays","Navigation data management systems"],
      communicationEquipment: ["Global Maritime Distress Safety System (GMDSS)","Broadband internet throughout"],
      entertainmentEquipment: ["Observation lounges with panoramic views"],
      accessibilityFeatures: ["Roll-in showers","Accessible medical facilities","Elevator access to all public decks"],
      environmentalFeatures: ["Advanced water treatment systems","Recyclable material management systems","Solar panel supplementation","Food waste digesters"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ms--of-the-deep",
    name: "MS  of the Deep",
    description: "Sailing from the picturesque port of San Francisco, the MS  of the Deep represents a new era in cruise experiences. This remarkable luxury cruise ship combines innovative design with thoughtful amenities, creating an atmosphere of refined elegance and warm hospitality.",
    type: "luxury-cruise-ship",
    capacity: 255,
    length: 151,
    width: 32,
    speed: 19,
    topSpeed: 21, 
    yearBuilt: 2005,
    homePort: {"city":"San Francisco","country":"United States","coordinates":{"latitude":0,"longitude":0}},
    specifications: {
      engineType: "Solar-Assisted Electric",
      fuelCapacity: 2410,
      waterCapacity: 76500,
      propulsionType: "Water Jets",
      hullMaterial: "Marine-Grade Steel",
      classification: "Russian Maritime Register of Shipping KM",
      safetyEquipment: ["Advanced fire detection and suppression systems","Comprehensive medical facilities","Satellite emergency notification devices","Emergency position indicating radio beacons (EPIRBs)"],
      navigationEquipment: ["Integrated navigation system displays","Global navigation satellite systems (GNSS)","Dynamic positioning systems"],
      communicationEquipment: ["Digital selective calling equipment","Emergency position-indicating radio beacons"],
      entertainmentEquipment: ["Cinema with latest releases","Children's entertainment areas","Immersive simulation experiences","Observation lounges with panoramic views"],
      accessibilityFeatures: ["Elevator access to all public decks","Braille signage throughout"],
      environmentalFeatures: ["Heat recovery systems","Shore power connectivity","Advanced water treatment systems"]
    },
    isLuxuryVessel: true,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "sv-the--mariner",
    name: "SV The  Mariner",
    description: "Experience the epitome of maritime excellence aboard the SV The  Mariner, a premier river cruise ship sailing from San Francisco. With its elegant design, state-of-the-art technology, and exceptional service, every journey promises unforgettable moments and unparalleled comfort.",
    type: "river-cruise-ship",
    capacity: 1539,
    length: 407,
    width: 71,
    speed: 29,
    topSpeed: 32, 
    yearBuilt: 2011,
    homePort: {"city":"San Francisco","country":"United States","coordinates":{"latitude":0,"longitude":0}},
    specifications: {
      engineType: "Podded Propulsion",
      fuelCapacity: 14440,
      waterCapacity: 461700,
      propulsionType: "Azipod Electric Propulsion",
      hullMaterial: "Reinforced Aluminum",
      classification: "China Classification Society B",
      safetyEquipment: ["Emergency escape breathing devices","Tactical response equipment","Rescue boats and life rafts","Thermal imaging cameras"],
      navigationEquipment: ["Navigation data management systems","Gyrocompasses and magnetic compasses"],
      communicationEquipment: ["Satellite communication systems","Public address systems"],
      entertainmentEquipment: ["Children's entertainment areas","Multi-purpose event spaces"],
      accessibilityFeatures: ["Wheelchair accessible cabins","Transfer chairs for pool access","Accessible medical facilities"],
      environmentalFeatures: ["Heat recovery systems","Recyclable material management systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "fv--gale",
    name: "FV  Gale",
    description: "The FV  Gale offers an unparalleled cruising experience from San Francisco, combining luxury amenities with state-of-the-art navigation technology. This expedition ship features spacious cabins, gourmet dining options, and entertainment venues that showcase the best of California hospitality.",
    type: "expedition-ship",
    capacity: 1277,
    length: 355,
    width: 63,
    speed: 18,
    topSpeed: 20, 
    yearBuilt: 2008,
    homePort: {"city":"San Francisco","country":"United States","coordinates":{"latitude":0,"longitude":0}},
    specifications: {
      engineType: "LNG-Powered Engines",
      fuelCapacity: 11180,
      waterCapacity: 383099,
      propulsionType: "Voith Schneider Propellers",
      hullMaterial: "Ice-Strengthened Steel",
      classification: "ClassNK NS* (Special Purpose Ship)",
      safetyEquipment: ["Advanced fire detection and suppression systems","Tactical response equipment","Personal locator beacons","Comprehensive medical facilities","Thermal imaging cameras","Hyperbaric treatment chambers","Rescue boats and life rafts"],
      navigationEquipment: ["Integrated bridge systems","Navigation data management systems","Dynamic positioning systems","Infrared camera systems"],
      communicationEquipment: ["Internal crew communication network","Ship-to-shore communication links","Maritime VHF radio systems"],
      entertainmentEquipment: ["Climbing walls and sports courts","Cinema with latest releases","Virtual reality gaming center"],
      accessibilityFeatures: ["Service animal accommodations","Visual alarm systems","Accessible entertainment venues"],
      environmentalFeatures: ["Noise reduction technology to minimize impact on marine life","Heat recovery systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  }
];
