// This file is auto-generated
    // Do not edit manually.
    // City: Shanghai
    // Generated on: 2025-06-10T03:09:08.304Z
    
    import { Vessels } from "@/lib/interfaces/services/cruises";

export const shanghaiVessels: Vessels[] = [
  {
    id: "cs--explorer",
    name: "CS  Explorer",
    description: "Combining traditional maritime charm with modern amenities, the CS  Explorer promises an extraordinary voyage from its home port of Shanghai. This impressive chartered vessel offers spacious accommodations, diverse dining options, and engaging activities for travelers of all ages.",
    type: "chartered-vessel",
    capacity: 1148,
    length: 329,
    width: 59,
    speed: 18,
    topSpeed: 21, 
    yearBuilt: 2009,
    homePort: {"city":"Shanghai","country":"China","coordinates":{"latitude":31.2304,"longitude":121.4737}},
    specifications: {
      engineType: "Solar-Assisted Electric",
      fuelCapacity: 9700,
      waterCapacity: 344400,
      propulsionType: "Podded Propulsion Units",
      hullMaterial: "Ice-Strengthened Steel",
      classification: "RINA Green Star Plus",
      safetyEquipment: ["Personal locator beacons","Weather monitoring stations","Advanced fire detection and suppression systems","Emergency escape breathing devices"],
      navigationEquipment: ["Night vision systems","Bridge alert management systems"],
      communicationEquipment: ["Ship-to-shore communication links"],
      entertainmentEquipment: ["Virtual reality gaming center","Dance clubs and live music venues","Library and educational facilities"],
      accessibilityFeatures: ["Accessible entertainment venues","Tactile guidance systems"],
      environmentalFeatures: ["Heat recovery systems","Marine ecosystem monitoring equipment","Advanced water treatment systems","Dynamic routing to optimize fuel usage"]
    },
    isLuxuryVessel: true,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "nx-shanghai-voyager",
    name: "NX Shanghai Voyager",
    description: "Combining traditional maritime charm with modern amenities, the NX Shanghai Voyager promises an extraordinary voyage from its home port of Shanghai. This impressive ice class ship offers spacious accommodations, diverse dining options, and engaging activities for travelers of all ages.",
    type: "ice-class-ship",
    capacity: 1815,
    length: 463,
    width: 79,
    speed: 15,
    topSpeed: 17, 
    yearBuilt: 2008,
    homePort: {"city":"Shanghai","country":"China","coordinates":{"latitude":31.2304,"longitude":121.4737}},
    specifications: {
      engineType: "Dual-Fuel Marine Engines",
      fuelCapacity: 18280,
      waterCapacity: 544500,
      propulsionType: "Conventional Shaft Propellers",
      hullMaterial: "Hybrid Steel-Composite",
      classification: "RINA Green Star Plus",
      safetyEquipment: ["Searchlights and rescue equipment","Survival craft VHF radios","Thermal imaging cameras"],
      navigationEquipment: ["Integrated navigation system displays","Integrated bridge systems","Inland ECDIS","Voyage data recorders (VDRs)","Autopilot systems with track control"],
      communicationEquipment: ["Ship-to-shore communication links","Emergency position-indicating radio beacons","Maritime VHF radio systems"],
      entertainmentEquipment: ["Virtual reality gaming center","Full-service spa and fitness center"],
      accessibilityFeatures: ["Transfer chairs for pool access","Roll-in showers"],
      environmentalFeatures: ["Shore power connectivity","Recyclable material management systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ms--of-the-deep",
    name: "MS  of the Deep",
    description: "With its distinctive profile and luxurious appointments, the MS  of the Deep stands as a jewel in the Shanghai harbor. This prestigious catamaran offers travelers a perfect combination of adventure and relaxation, with expert-guided excursions, world-class entertainment, and sublime culinary experiences.",
    type: "catamaran",
    capacity: 1865,
    length: 473,
    width: 80,
    speed: 20,
    topSpeed: 23, 
    yearBuilt: 2015,
    homePort: {"city":"Shanghai","country":"China","coordinates":{"latitude":31.2304,"longitude":121.4737}},
    specifications: {
      engineType: "Podded Propulsion",
      fuelCapacity: 18920,
      waterCapacity: 559500,
      propulsionType: "Conventional Shaft Propellers",
      hullMaterial: "High-Tensile Steel Alloy",
      classification: "ClassNK NS* (Special Purpose Ship)",
      safetyEquipment: ["Hyperbaric treatment chambers","Radar reflectors","Life jackets with integrated GPS","Rescue boats and life rafts","Emergency escape breathing devices","Survival craft VHF radios"],
      navigationEquipment: ["Doppler speed logs","Integrated navigation system displays","Long-range identification and tracking (LRIT)","River radar systems"],
      communicationEquipment: ["Marine radio telephony","Maritime VHF radio systems","Satellite communication systems"],
      entertainmentEquipment: ["Casino with table games and slot machines","Art gallery and auction facilities"],
      accessibilityFeatures: ["Elevator access to all public decks","Height-adjustable furniture in select cabins"],
      environmentalFeatures: ["Recyclable material management systems","Optimized hull design for reduced fuel consumption","Energy-efficient appliances"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "mv-the--mariner",
    name: "MV The  Mariner",
    description: "The majestic MV The  Mariner represents the pinnacle of maritime engineering and hospitality. Based in Shanghai, this exceptional family cruise ship features timeless interiors, cutting-edge facilities, and carefully curated experiences that celebrate the unique culture of the China region.",
    type: "family-cruise-ship",
    capacity: 1268,
    length: 353,
    width: 62,
    speed: 28,
    topSpeed: 33, 
    yearBuilt: 2016,
    homePort: {"city":"Shanghai","country":"China","coordinates":{"latitude":31.2304,"longitude":121.4737}},
    specifications: {
      engineType: "Dual-Fuel Marine Engines",
      fuelCapacity: 10940,
      waterCapacity: 380400,
      propulsionType: "Azipod Electric Propulsion",
      hullMaterial: "Marine-Grade Steel",
      classification: "RINA Green Star Plus",
      safetyEquipment: ["Satellite emergency notification devices","Tactical response equipment","Weather monitoring stations","Man overboard detection systems"],
      navigationEquipment: ["Long-range identification and tracking (LRIT)","Doppler speed logs"],
      communicationEquipment: ["Broadband internet throughout","Satellite communication systems","Marine radio telephony"],
      entertainmentEquipment: ["Art gallery and auction facilities","Theater with Broadway-style productions"],
      accessibilityFeatures: ["Assistive listening devices","Accessible medical facilities"],
      environmentalFeatures: ["Marine ecosystem monitoring equipment","Ballast water management technology","Noise reduction technology to minimize impact on marine life","Exhaust gas cleaning systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "nb--gale",
    name: "NB  Gale",
    description: "The majestic NB  Gale represents the pinnacle of maritime engineering and hospitality. Based in Shanghai, this exceptional family cruise ship features unforgettable interiors, cutting-edge facilities, and carefully curated experiences that celebrate the unique culture of the China region.",
    type: "family-cruise-ship",
    capacity: 1382,
    length: 376,
    width: 66,
    speed: 15,
    topSpeed: 18, 
    yearBuilt: 2014,
    homePort: {"city":"Shanghai","country":"China","coordinates":{"latitude":31.2304,"longitude":121.4737}},
    specifications: {
      engineType: "Dual-Fuel Marine Engines",
      fuelCapacity: 12400,
      waterCapacity: 414599,
      propulsionType: "Voith Schneider Propellers",
      hullMaterial: "Composite Materials",
      classification: "Lloyd's Register Class 1",
      safetyEquipment: ["Advanced fire detection and suppression systems","Emergency position indicating radio beacons (EPIRBs)","Marine evacuation systems (MES)","Digital safety monitoring systems","Rescue boats and life rafts"],
      navigationEquipment: ["Global navigation satellite systems (GNSS)","Echo sounders and sonar systems"],
      communicationEquipment: ["Broadband internet throughout","Ship-to-shore communication links","Public address systems"],
      entertainmentEquipment: ["Dance clubs and live music venues","Cinema with latest releases","Immersive simulation experiences"],
      accessibilityFeatures: ["Accessible entertainment venues","Braille signage throughout","Hearing augmentation systems"],
      environmentalFeatures: ["Marine ecosystem monitoring equipment","LED lighting throughout"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  }
];
