// This file is auto-generated
    // Do not edit manually.
    // City: Sydney
    // Generated on: 2025-06-08T07:59:32.400Z
    
    import { Vessels } from "@/lib/interfaces/services/cruises";

export const sydneyVessels: Vessels[] = [
{
    id: "mv--explorer",
    name: "MV  Explorer",
    description: "With its distinctive profile and luxurious appointments, the MV  Explorer stands as a jewel in the Sydney harbor. This prestigious mainstream cruise ship offers travelers a perfect combination of adventure and relaxation, with expert-guided excursions, world-class entertainment, and sublime culinary experiences.",
    type: "mainstream-cruise-ship",
    capacity: 2021,
    length: 504,
    width: 85,
    speed: 19,
    topSpeed: 22, 
    yearBuilt: 2019,
    homePort: {"city":"Sydney","country":"Australia","coordinates":{"latitude":-33.8688,"longitude":151.2093}},
    specifications: {
      engineType: "Gas Turbine Powerplant",
      fuelCapacity: 21420,
      waterCapacity: 606300,
      propulsionType: "Conventional Shaft Propellers",
      hullMaterial: "High-Tensile Steel Alloy",
      classification: "DNV GL High Speed & Light Craft",
      safetyEquipment: ["Searchlights and rescue equipment","Emergency position indicating radio beacons (EPIRBs)","Satellite emergency notification devices","Tactical response equipment","Advanced fire detection and suppression systems"],
      navigationEquipment: ["Automatic identification systems (AIS)","Night vision systems","River radar systems","Infrared camera systems"],
      communicationEquipment: ["Marine radio telephony","Emergency position-indicating radio beacons"],
      entertainmentEquipment: ["Multiple swimming pools and water features","Full-service spa and fitness center","Cinema with latest releases","Multi-purpose event spaces","Casino with table games and slot machines"],
      accessibilityFeatures: ["Accessible medical facilities","Transfer chairs for pool access"],
      environmentalFeatures: ["Noise reduction technology to minimize impact on marine life","Food waste digesters","Optimized hull design for reduced fuel consumption"]
    },
    isLuxuryVessel: true,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ps-sydney-voyager",
    name: "PS Sydney Voyager",
    description: "Experience the epitome of maritime excellence aboard the PS Sydney Voyager, a premier luxury cruise ship sailing from Sydney. With its elegant design, state-of-the-art technology, and exceptional service, every journey promises unforgettable moments and unparalleled comfort.",
    type: "luxury-cruise-ship",
    capacity: 857,
    length: 271,
    width: 50,
    speed: 26,
    topSpeed: 29, 
    yearBuilt: 2007,
    homePort: {"city":"Sydney","country":"Australia","coordinates":{"latitude":-33.8688,"longitude":151.2093}},
    specifications: {
      engineType: "Gas Turbine Powerplant",
      fuelCapacity: 6770,
      waterCapacity: 257099,
      propulsionType: "Counter-Rotating Propellers",
      hullMaterial: "High-Tensile Steel Alloy",
      classification: "Bureau Veritas Star Class",
      safetyEquipment: ["Hyperbaric treatment chambers","Advanced fire detection and suppression systems","Emergency escape breathing devices","Digital safety monitoring systems","Automated external defibrillators (AEDs)","Searchlights and rescue equipment"],
      navigationEquipment: ["Weather routing systems","Voyage data recorders (VDRs)","Navigation data management systems"],
      communicationEquipment: ["Marine radio telephony","Global Maritime Distress Safety System (GMDSS)"],
      entertainmentEquipment: ["Library and educational facilities"],
      accessibilityFeatures: ["Tactile guidance systems","Assistive listening devices"],
      environmentalFeatures: ["Heat recovery systems","Recyclable material management systems"]
    },
    isLuxuryVessel: true,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "nx--of-the-deep",
    name: "NX  of the Deep",
    description: "Setting sail from the beautiful port of Sydney, the NX  of the Deep is a floating paradise designed for the discerning traveler. This remarkable expedition ship boasts panoramic viewing decks, world-class cuisine, and personalized service that ensures an unforgettable journey.",
    type: "expedition-ship",
    capacity: 1551,
    length: 410,
    width: 71,
    speed: 27,
    topSpeed: 31, 
    yearBuilt: 2008,
    homePort: {"city":"Sydney","country":"Australia","coordinates":{"latitude":-33.8688,"longitude":151.2093}},
    specifications: {
      engineType: "Azimuth Thrusters",
      fuelCapacity: 14550,
      waterCapacity: 465299,
      propulsionType: "Voith Schneider Propellers",
      hullMaterial: "Composite Materials",
      classification: "American Bureau of Shipping A1",
      safetyEquipment: ["Emergency escape breathing devices","Survival craft VHF radios","Rescue boats and life rafts","Comprehensive medical facilities"],
      navigationEquipment: ["Radar and automatic radar plotting aids (ARPAs)","Integrated bridge systems"],
      communicationEquipment: ["Maritime VHF radio systems"],
      entertainmentEquipment: ["Casino with table games and slot machines","Full-service spa and fitness center"],
      accessibilityFeatures: ["Assistive listening devices","Hearing augmentation systems"],
      environmentalFeatures: ["Food waste digesters","Heat recovery systems","Advanced water treatment systems"]
    },
    isLuxuryVessel: true,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "fv-the--mariner",
    name: "FV The  Mariner",
    description: "The FV The  Mariner offers an unparalleled cruising experience from Sydney, combining luxury amenities with state-of-the-art navigation technology. This party cruise ship features spacious cabins, gourmet dining options, and entertainment venues that showcase the best of Australia hospitality.",
    type: "party-cruise-ship",
    capacity: 1975,
    length: 495,
    width: 84,
    speed: 16,
    topSpeed: 18, 
    yearBuilt: 2014,
    homePort: {"city":"Sydney","country":"Australia","coordinates":{"latitude":-33.8688,"longitude":151.2093}},
    specifications: {
      engineType: "Hybrid Power System",
      fuelCapacity: 20790,
      waterCapacity: 592500,
      propulsionType: "Conventional Shaft Propellers",
      hullMaterial: "High-Tensile Steel Alloy",
      classification: "China Classification Society B",
      safetyEquipment: ["Life jackets with integrated GPS","Satellite emergency notification devices","Emergency escape breathing devices","Weather monitoring stations","Emergency position indicating radio beacons (EPIRBs)","Digital safety monitoring systems"],
      navigationEquipment: ["Infrared camera systems","Global navigation satellite systems (GNSS)"],
      communicationEquipment: ["Emergency position-indicating radio beacons","Marine radio telephony"],
      entertainmentEquipment: ["Immersive simulation experiences","Dance clubs and live music venues","Observation lounges with panoramic views","Theater with Broadway-style productions"],
      accessibilityFeatures: ["Accessible dining facilities","Tactile guidance systems","Hearing augmentation systems"],
      environmentalFeatures: ["LED lighting throughout","Heat recovery systems","Solar panel supplementation"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "my--gale",
    name: "MY  Gale",
    description: "Experience the epitome of maritime excellence aboard the MY  Gale, a premier mega yacht sailing from Sydney. With its elegant design, state-of-the-art technology, and exceptional service, every journey promises unforgettable moments and unparalleled comfort.",
    type: "mega-yacht",
    capacity: 1532,
    length: 406,
    width: 70,
    speed: 20,
    topSpeed: 23, 
    yearBuilt: 2011,
    homePort: {"city":"Sydney","country":"Australia","coordinates":{"latitude":-33.8688,"longitude":151.2093}},
    specifications: {
      engineType: "Podded Propulsion",
      fuelCapacity: 14210,
      waterCapacity: 459599,
      propulsionType: "Water Jets",
      hullMaterial: "Reinforced Aluminum",
      classification: "ClassNK NS* (Special Purpose Ship)",
      safetyEquipment: ["Weather monitoring stations","Radar reflectors","Comprehensive medical facilities"],
      navigationEquipment: ["Integrated bridge systems","Integrated navigation system displays"],
      communicationEquipment: ["Broadband internet throughout","Satellite communication systems","Internal crew communication network"],
      entertainmentEquipment: ["Culinary demonstration kitchens","Climbing walls and sports courts","Full-service spa and fitness center"],
      accessibilityFeatures: ["Roll-in showers","Accessible dining facilities"],
      environmentalFeatures: ["Dynamic routing to optimize fuel usage","Shore power connectivity","Advanced water treatment systems","Heat recovery systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "sv--explorer",
    name: "SV  Explorer",
    description: "The majestic SV  Explorer represents the pinnacle of maritime engineering and hospitality. Based in Sydney, this exceptional boutique cruise ship features elegant interiors, cutting-edge facilities, and carefully curated experiences that celebrate the unique culture of the Australia region.",
    type: "boutique-cruise-ship",
    capacity: 1373,
    length: 374,
    width: 66,
    speed: 28,
    topSpeed: 33, 
    yearBuilt: 2011,
    homePort: {"city":"Sydney","country":"Australia","coordinates":{"latitude":-33.8688,"longitude":151.2093}},
    specifications: {
      engineType: "Integrated Power Systems",
      fuelCapacity: 12340,
      waterCapacity: 411900,
      propulsionType: "Water Jets",
      hullMaterial: "Reinforced Aluminum",
      classification: "American Bureau of Shipping A1",
      safetyEquipment: ["Personal locator beacons","Automated external defibrillators (AEDs)","Life jackets with integrated GPS","Rescue boats and life rafts","Weather monitoring stations"],
      navigationEquipment: ["Echo sounders and sonar systems","Automatic identification systems (AIS)"],
      communicationEquipment: ["Internal crew communication network","Emergency position-indicating radio beacons","Global Maritime Distress Safety System (GMDSS)"],
      entertainmentEquipment: ["Climbing walls and sports courts","Observation lounges with panoramic views"],
      accessibilityFeatures: ["Tactile guidance systems","Visual alarm systems"],
      environmentalFeatures: ["Recyclable material management systems","Ballast water management technology","Dynamic routing to optimize fuel usage","Shore power connectivity"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ly-sydney-voyager",
    name: "LY Sydney Voyager",
    description: "Combining traditional maritime charm with modern amenities, the LY Sydney Voyager promises an extraordinary voyage from its home port of Sydney. This impressive superyacht offers spacious accommodations, diverse dining options, and engaging activities for travelers of all ages.",
    type: "superyacht",
    capacity: 1969,
    length: 493,
    width: 83,
    speed: 22,
    topSpeed: 24, 
    yearBuilt: 2018,
    homePort: {"city":"Sydney","country":"Australia","coordinates":{"latitude":-33.8688,"longitude":151.2093}},
    specifications: {
      engineType: "Dual-Fuel Marine Engines",
      fuelCapacity: 20450,
      waterCapacity: 590699,
      propulsionType: "Voith Schneider Propellers",
      hullMaterial: "Composite Materials",
      classification: "American Bureau of Shipping A1",
      safetyEquipment: ["Thermal imaging cameras","Hyperbaric treatment chambers","Advanced fire detection and suppression systems","Emergency escape breathing devices","Rescue boats and life rafts"],
      navigationEquipment: ["Autopilot systems with track control","Echo sounders and sonar systems"],
      communicationEquipment: ["Satellite communication systems","Maritime VHF radio systems"],
      entertainmentEquipment: ["Library and educational facilities","Theater with Broadway-style productions"],
      accessibilityFeatures: ["Wheelchair accessible cabins","Accessible shore excursion options"],
      environmentalFeatures: ["LED lighting throughout","Optimized hull design for reduced fuel consumption","Solar panel supplementation","Biodegradable hydraulic fluids"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "nb--of-the-deep",
    name: "NB  of the Deep",
    description: "Setting sail from the beautiful port of Sydney, the NB  of the Deep is a floating paradise designed for the discerning traveler. This remarkable ultra luxury cruise ship boasts panoramic viewing decks, world-class cuisine, and personalized service that ensures an unforgettable journey.",
    type: "ultra-luxury-cruise-ship",
    capacity: 1186,
    length: 337,
    width: 60,
    speed: 21,
    topSpeed: 24, 
    yearBuilt: 2020,
    homePort: {"city":"Sydney","country":"Australia","coordinates":{"latitude":-33.8688,"longitude":151.2093}},
    specifications: {
      engineType: "Hybrid Power System",
      fuelCapacity: 10110,
      waterCapacity: 355800,
      propulsionType: "Water Jets",
      hullMaterial: "Hybrid Steel-Composite",
      classification: "RINA Green Star Plus",
      safetyEquipment: ["Radar reflectors","Digital safety monitoring systems","Weather monitoring stations","Survival craft VHF radios","Emergency escape breathing devices","Satellite emergency notification devices","Comprehensive medical facilities"],
      navigationEquipment: ["Automatic identification systems (AIS)","Weather routing systems","Gyrocompasses and magnetic compasses","Long-range identification and tracking (LRIT)","Inland ECDIS"],
      communicationEquipment: ["Maritime VHF radio systems","Emergency position-indicating radio beacons"],
      entertainmentEquipment: ["Dance clubs and live music venues","Children's entertainment areas","Art gallery and auction facilities","Immersive simulation experiences","Casino with table games and slot machines"],
      accessibilityFeatures: ["Accessible shore excursion options","Accessible entertainment venues"],
      environmentalFeatures: ["Exhaust gas cleaning systems","Shore power connectivity","Heat recovery systems","Energy-efficient appliances","Advanced water treatment systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "cs--explorer",
    name: "CS  Explorer",
    description: "Sailing from the picturesque port of Sydney, the CS  Explorer represents a new era in cruise experiences. This remarkable chartered vessel combines innovative design with thoughtful amenities, creating an atmosphere of refined elegance and warm hospitality.",
    type: "chartered-vessel",
    capacity: 1645,
    length: 429,
    width: 74,
    speed: 28,
    topSpeed: 31, 
    yearBuilt: 2012,
    homePort: {"city":"Sydney","country":"Australia","coordinates":{"latitude":-33.8688,"longitude":151.2093}},
    specifications: {
      engineType: "Solar-Assisted Electric",
      fuelCapacity: 15870,
      waterCapacity: 493500,
      propulsionType: "Water Jets",
      hullMaterial: "Ice-Strengthened Steel",
      classification: "American Bureau of Shipping A1",
      safetyEquipment: ["Satellite emergency notification devices","Radar reflectors"],
      navigationEquipment: ["River radar systems","Echo sounders and sonar systems"],
      communicationEquipment: ["Digital selective calling equipment","Internal crew communication network","Marine radio telephony"],
      entertainmentEquipment: ["Virtual reality gaming center","Full-service spa and fitness center"],
      accessibilityFeatures: ["Visual alarm systems","Braille signage throughout","Roll-in showers","Tactile guidance systems"],
      environmentalFeatures: ["Noise reduction technology to minimize impact on marine life","Heat recovery systems","Biodegradable hydraulic fluids"]
    },
    isLuxuryVessel: true,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ps-sydney-voyager",
    name: "PS Sydney Voyager",
    description: "Setting sail from the beautiful port of Sydney, the PS Sydney Voyager is a floating paradise designed for the discerning traveler. This remarkable river cruise ship boasts panoramic viewing decks, world-class cuisine, and personalized service that ensures an unforgettable journey.",
    type: "river-cruise-ship",
    capacity: 926,
    length: 285,
    width: 52,
    speed: 15,
    topSpeed: 17, 
    yearBuilt: 2015,
    homePort: {"city":"Sydney","country":"Australia","coordinates":{"latitude":-33.8688,"longitude":151.2093}},
    specifications: {
      engineType: "Diesel-Electric Propulsion",
      fuelCapacity: 7410,
      waterCapacity: 277800,
      propulsionType: "Z-Drive Propulsion",
      hullMaterial: "Marine-Grade Steel",
      classification: "Russian Maritime Register of Shipping KM",
      safetyEquipment: ["Tactical response equipment","Personal locator beacons","Advanced fire detection and suppression systems"],
      navigationEquipment: ["Electronic chart display information systems (ECDIS)","Gyrocompasses and magnetic compasses","Dynamic positioning systems"],
      communicationEquipment: ["Maritime VHF radio systems","Global Maritime Distress Safety System (GMDSS)"],
      entertainmentEquipment: ["Art gallery and auction facilities","Children's entertainment areas","Full-service spa and fitness center","Cinema with latest releases"],
      accessibilityFeatures: ["Accessible shore excursion options","Elevator access to all public decks","Service animal accommodations","Accessible medical facilities"],
      environmentalFeatures: ["Ballast water management technology","Solar panel supplementation","Exhaust gas cleaning systems","Noise reduction technology to minimize impact on marine life"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "rv--of-the-deep",
    name: "RV  of the Deep",
    description: "Setting sail from the beautiful port of Sydney, the RV  of the Deep is a floating paradise designed for the discerning traveler. This remarkable short hop ferry boasts panoramic viewing decks, world-class cuisine, and personalized service that ensures an unforgettable journey.",
    type: "short-hop-ferry",
    capacity: 933,
    length: 286,
    width: 52,
    speed: 21,
    topSpeed: 23, 
    yearBuilt: 2021,
    homePort: {"city":"Sydney","country":"Australia","coordinates":{"latitude":-33.8688,"longitude":151.2093}},
    specifications: {
      engineType: "Azimuth Thrusters",
      fuelCapacity: 7430,
      waterCapacity: 279900,
      propulsionType: "Water Jets",
      hullMaterial: "Reinforced Aluminum",
      classification: "ClassNK NS* (Special Purpose Ship)",
      safetyEquipment: ["Water purification systems","Digital safety monitoring systems","Emergency escape breathing devices"],
      navigationEquipment: ["Doppler speed logs","Long-range identification and tracking (LRIT)"],
      communicationEquipment: ["Public address systems","Emergency position-indicating radio beacons"],
      entertainmentEquipment: ["Immersive simulation experiences","Climbing walls and sports courts","Observation lounges with panoramic views","Theater with Broadway-style productions"],
      accessibilityFeatures: ["Assistive listening devices","Visual alarm systems","Service animal accommodations","Accessible entertainment venues"],
      environmentalFeatures: ["Advanced water treatment systems","Noise reduction technology to minimize impact on marine life"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "nb--explorer",
    name: "NB  Explorer",
    description: "The magnificent NB  Explorer offers a perfect blend of adventure and relaxation for travelers departing from Sydney. This outstanding adults only ship features panoramic ocean views, specialized dining experiences, and enriching activities that connect guests with the wonders of the Australia region.",
    type: "adults-only-ship",
    capacity: 741,
    length: 248,
    width: 47,
    speed: 15,
    topSpeed: 17, 
    yearBuilt: 2006,
    homePort: {"city":"Sydney","country":"Australia","coordinates":{"latitude":-33.8688,"longitude":151.2093}},
    specifications: {
      engineType: "LNG-Powered Engines",
      fuelCapacity: 5820,
      waterCapacity: 222299,
      propulsionType: "Voith Schneider Propellers",
      hullMaterial: "Marine-Grade Steel",
      classification: "Bureau Veritas Star Class",
      safetyEquipment: ["Searchlights and rescue equipment","Advanced fire detection and suppression systems","Rescue boats and life rafts"],
      navigationEquipment: ["Autopilot systems with track control","Doppler speed logs"],
      communicationEquipment: ["Digital selective calling equipment","Internal crew communication network"],
      entertainmentEquipment: ["Observation lounges with panoramic views","Multi-purpose event spaces"],
      accessibilityFeatures: ["Braille signage throughout","Wheelchair accessible cabins","Roll-in showers"],
      environmentalFeatures: ["LED lighting throughout","Solar panel supplementation","Shore power connectivity","Food waste digesters"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "sy-sydney-voyager",
    name: "SY Sydney Voyager",
    description: "The SY Sydney Voyager offers an unparalleled cruising experience from Sydney, combining luxury amenities with state-of-the-art navigation technology. This mega yacht features spacious cabins, gourmet dining options, and entertainment venues that showcase the best of Australia hospitality.",
    type: "mega-yacht",
    capacity: 1349,
    length: 369,
    width: 65,
    speed: 20,
    topSpeed: 22, 
    yearBuilt: 2015,
    homePort: {"city":"Sydney","country":"Australia","coordinates":{"latitude":-33.8688,"longitude":151.2093}},
    specifications: {
      engineType: "Integrated Power Systems",
      fuelCapacity: 11990,
      waterCapacity: 404700,
      propulsionType: "Voith Schneider Propellers",
      hullMaterial: "High-Tensile Steel Alloy",
      classification: "Lloyd's Register Class 1",
      safetyEquipment: ["Life jackets with integrated GPS","Advanced fire detection and suppression systems","Weather monitoring stations","Hyperbaric treatment chambers","Searchlights and rescue equipment","Man overboard detection systems"],
      navigationEquipment: ["Integrated navigation system displays","Automatic identification systems (AIS)","Global navigation satellite systems (GNSS)","Radar and automatic radar plotting aids (ARPAs)","Night vision systems"],
      communicationEquipment: ["Emergency position-indicating radio beacons","Public address systems","Internal crew communication network"],
      entertainmentEquipment: ["Children's entertainment areas","Full-service spa and fitness center"],
      accessibilityFeatures: ["Assistive listening devices","Tactile guidance systems"],
      environmentalFeatures: ["Advanced water treatment systems","Food waste digesters","Solar panel supplementation"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "cs--of-the-deep",
    name: "CS  of the Deep",
    description: "With its distinctive profile and luxurious appointments, the CS  of the Deep stands as a jewel in the Sydney harbor. This prestigious short hop ferry offers travelers a perfect combination of adventure and relaxation, with expert-guided excursions, world-class entertainment, and sublime culinary experiences.",
    type: "short-hop-ferry",
    capacity: 552,
    length: 210,
    width: 41,
    speed: 15,
    topSpeed: 18, 
    yearBuilt: 2013,
    homePort: {"city":"Sydney","country":"Australia","coordinates":{"latitude":-33.8688,"longitude":151.2093}},
    specifications: {
      engineType: "LNG-Powered Engines",
      fuelCapacity: 4300,
      waterCapacity: 165600,
      propulsionType: "Cycloidal Drive",
      hullMaterial: "Marine-Grade Steel",
      classification: "Lloyd's Register Class 1",
      safetyEquipment: ["Water purification systems","Weather monitoring stations","Digital safety monitoring systems","Satellite emergency notification devices"],
      navigationEquipment: ["Bridge alert management systems","Integrated navigation system displays","Electronic chart display information systems (ECDIS)"],
      communicationEquipment: ["Satellite communication systems","Internal crew communication network","Digital selective calling equipment"],
      entertainmentEquipment: ["Climbing walls and sports courts","Multi-purpose event spaces","Culinary demonstration kitchens","Theater with Broadway-style productions"],
      accessibilityFeatures: ["Service animal accommodations","Accessible shore excursion options"],
      environmentalFeatures: ["Noise reduction technology to minimize impact on marine life","Food waste digesters","Biodegradable hydraulic fluids"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "nx--explorer",
    name: "NX  Explorer",
    description: "The NX  Explorer stands as a testament to luxury and innovation on the high seas. Departing from Sydney, this sophisticated mega yacht features immersive entertainment, wellness facilities, and exquisite cuisine prepared by internationally renowned chefs.",
    type: "mega-yacht",
    capacity: 1258,
    length: 351,
    width: 62,
    speed: 27,
    topSpeed: 32, 
    yearBuilt: 2006,
    homePort: {"city":"Sydney","country":"Australia","coordinates":{"latitude":-33.8688,"longitude":151.2093}},
    specifications: {
      engineType: "Hybrid Power System",
      fuelCapacity: 10880,
      waterCapacity: 377400,
      propulsionType: "Water Jets",
      hullMaterial: "Hybrid Steel-Composite",
      classification: "Bureau Veritas Star Class",
      safetyEquipment: ["Survival craft VHF radios","Emergency escape breathing devices","Automated external defibrillators (AEDs)","Satellite emergency notification devices"],
      navigationEquipment: ["Weather routing systems","Doppler speed logs","Automatic identification systems (AIS)","Echo sounders and sonar systems"],
      communicationEquipment: ["Emergency position-indicating radio beacons","Public address systems","Global Maritime Distress Safety System (GMDSS)"],
      entertainmentEquipment: ["Cinema with latest releases","Art gallery and auction facilities","Culinary demonstration kitchens","Observation lounges with panoramic views"],
      accessibilityFeatures: ["Elevator access to all public decks","Tactile guidance systems","Hearing augmentation systems"],
      environmentalFeatures: ["Advanced water treatment systems","Heat recovery systems","Food waste digesters","Exhaust gas cleaning systems"]
    },
    isLuxuryVessel: true,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "rv-sydney-voyager",
    name: "RV Sydney Voyager",
    description: "Setting sail from the beautiful port of Sydney, the RV Sydney Voyager is a floating paradise designed for the discerning traveler. This remarkable mainstream cruise ship boasts panoramic viewing decks, world-class cuisine, and personalized service that ensures an unforgettable journey.",
    type: "mainstream-cruise-ship",
    capacity: 2124,
    length: 524,
    width: 88,
    speed: 17,
    topSpeed: 20, 
    yearBuilt: 2010,
    homePort: {"city":"Sydney","country":"Australia","coordinates":{"latitude":-33.8688,"longitude":151.2093}},
    specifications: {
      engineType: "Solar-Assisted Electric",
      fuelCapacity: 23050,
      waterCapacity: 637199,
      propulsionType: "Water Jets",
      hullMaterial: "High-Tensile Steel Alloy",
      classification: "China Classification Society B",
      safetyEquipment: ["Advanced fire detection and suppression systems","Automated external defibrillators (AEDs)","Life jackets with integrated GPS","Hyperbaric treatment chambers","Man overboard detection systems","Tactical response equipment","Water purification systems"],
      navigationEquipment: ["Autopilot systems with track control","Inland ECDIS","Integrated bridge systems"],
      communicationEquipment: ["Satellite communication systems","Public address systems"],
      entertainmentEquipment: ["Library and educational facilities","Children's entertainment areas"],
      accessibilityFeatures: ["Service animal accommodations","Hearing augmentation systems"],
      environmentalFeatures: ["Dynamic routing to optimize fuel usage","Marine ecosystem monitoring equipment"]
    },
    isLuxuryVessel: true,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "cs--of-the-deep",
    name: "CS  of the Deep",
    description: "Combining traditional maritime charm with modern amenities, the CS  of the Deep promises an extraordinary voyage from its home port of Sydney. This impressive mid size cruise ship offers spacious accommodations, diverse dining options, and engaging activities for travelers of all ages.",
    type: "mid-size-cruise-ship",
    capacity: 1408,
    length: 381,
    width: 67,
    speed: 24,
    topSpeed: 27, 
    yearBuilt: 2012,
    homePort: {"city":"Sydney","country":"Australia","coordinates":{"latitude":-33.8688,"longitude":151.2093}},
    specifications: {
      engineType: "Solar-Assisted Electric",
      fuelCapacity: 12760,
      waterCapacity: 422400,
      propulsionType: "Podded Propulsion Units",
      hullMaterial: "High-Tensile Steel Alloy",
      classification: "RINA Green Star Plus",
      safetyEquipment: ["Survival craft VHF radios","Automated external defibrillators (AEDs)","Life jackets with integrated GPS"],
      navigationEquipment: ["Global navigation satellite systems (GNSS)","Echo sounders and sonar systems","River radar systems","Dynamic positioning systems"],
      communicationEquipment: ["Satellite communication systems","Digital selective calling equipment"],
      entertainmentEquipment: ["Cinema with latest releases","Multi-purpose event spaces"],
      accessibilityFeatures: ["Tactile guidance systems","Braille signage throughout"],
      environmentalFeatures: ["Recyclable material management systems","LED lighting throughout","Biodegradable hydraulic fluids","Advanced water treatment systems","Marine ecosystem monitoring equipment"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  }
];
