// This file is auto-generated
    // Do not edit manually.
    // City: Tampa
    // Generated on: 2025-06-08T07:59:32.400Z
    
    import { Vessels } from "@/lib/interfaces/services/cruises";

export const tampaVessels: Vessels[] = [
{
    id: "my--explorer",
    name: "MY  Explorer",
    description: "Sailing from the picturesque port of Tampa, the MY  Explorer represents a new era in cruise experiences. This remarkable party cruise ship combines innovative design with thoughtful amenities, creating an atmosphere of refined elegance and warm hospitality.",
    type: "party-cruise-ship",
    capacity: 1187,
    length: 337,
    width: 60,
    speed: 16,
    topSpeed: 18, 
    yearBuilt: 2021,
    homePort: {"city":"Tampa","country":"United States","coordinates":{"latitude":27.9506,"longitude":-82.4572}},
    specifications: {
      engineType: "Hybrid Power System",
      fuelCapacity: 10110,
      waterCapacity: 356099,
      propulsionType: "Voith Schneider Propellers",
      hullMaterial: "High-Tensile Steel Alloy",
      classification: "Russian Maritime Register of Shipping KM",
      safetyEquipment: ["Life jackets with integrated GPS","Automated external defibrillators (AEDs)","Survival craft VHF radios","Thermal imaging cameras","Advanced fire detection and suppression systems","Searchlights and rescue equipment","Marine evacuation systems (MES)"],
      navigationEquipment: ["Radar and automatic radar plotting aids (ARPAs)","Automatic identification systems (AIS)","Inland ECDIS","Navigation data management systems"],
      communicationEquipment: ["Ship-to-shore communication links"],
      entertainmentEquipment: ["Art gallery and auction facilities","Full-service spa and fitness center","Observation lounges with panoramic views"],
      accessibilityFeatures: ["Roll-in showers","Accessible medical facilities"],
      environmentalFeatures: ["Biodegradable hydraulic fluids","Dynamic routing to optimize fuel usage","LED lighting throughout","Recyclable material management systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "sv-tampa-voyager",
    name: "SV Tampa Voyager",
    description: "The SV Tampa Voyager invites travelers to explore the treasures of Florida in unmatched comfort. This exceptional party cruise ship, based in Tampa, features curated excursions, immersive cultural programs, and luxurious accommodations that ensure an unforgettable journey.",
    type: "party-cruise-ship",
    capacity: 1412,
    length: 382,
    width: 67,
    speed: 23,
    topSpeed: 28, 
    yearBuilt: 2011,
    homePort: {"city":"Tampa","country":"United States","coordinates":{"latitude":27.9506,"longitude":-82.4572}},
    specifications: {
      engineType: "Diesel-Electric Propulsion",
      fuelCapacity: 12790,
      waterCapacity: 423599,
      propulsionType: "Z-Drive Propulsion",
      hullMaterial: "Composite Materials",
      classification: "DNV GL High Speed & Light Craft",
      safetyEquipment: ["Tactical response equipment","Weather monitoring stations","Rescue boats and life rafts","Man overboard detection systems","Comprehensive medical facilities","Automated external defibrillators (AEDs)"],
      navigationEquipment: ["Infrared camera systems","Voyage data recorders (VDRs)"],
      communicationEquipment: ["Digital selective calling equipment","Internal crew communication network"],
      entertainmentEquipment: ["Immersive simulation experiences","Cinema with latest releases","Multiple swimming pools and water features"],
      accessibilityFeatures: ["Accessible medical facilities","Wheelchair accessible cabins"],
      environmentalFeatures: ["Shore power connectivity","Optimized hull design for reduced fuel consumption","Solar panel supplementation","Dynamic routing to optimize fuel usage"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ss--of-the-deep",
    name: "SS  of the Deep",
    description: "With its distinctive profile and luxurious appointments, the SS  of the Deep stands as a jewel in the Tampa harbor. This prestigious mid size cruise ship offers travelers a perfect combination of adventure and relaxation, with expert-guided excursions, world-class entertainment, and sublime culinary experiences.",
    type: "mid-size-cruise-ship",
    capacity: 955,
    length: 291,
    width: 53,
    speed: 21,
    topSpeed: 23, 
    yearBuilt: 2013,
    homePort: {"city":"Tampa","country":"United States","coordinates":{"latitude":27.9506,"longitude":-82.4572}},
    specifications: {
      engineType: "Hybrid Power System",
      fuelCapacity: 7710,
      waterCapacity: 286500,
      propulsionType: "Cycloidal Drive",
      hullMaterial: "Hybrid Steel-Composite",
      classification: "American Bureau of Shipping A1",
      safetyEquipment: ["Searchlights and rescue equipment","Comprehensive medical facilities","Automated external defibrillators (AEDs)"],
      navigationEquipment: ["Echo sounders and sonar systems","Inland ECDIS","Infrared camera systems"],
      communicationEquipment: ["Satellite communication systems","Digital selective calling equipment","Public address systems"],
      entertainmentEquipment: ["Multiple swimming pools and water features","Children's entertainment areas","Virtual reality gaming center"],
      accessibilityFeatures: ["Accessible medical facilities"],
      environmentalFeatures: ["Exhaust gas cleaning systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "sv-the--mariner",
    name: "SV The  Mariner",
    description: "Combining traditional maritime charm with modern amenities, the SV The  Mariner promises an extraordinary voyage from its home port of Tampa. This impressive short hop ferry offers spacious accommodations, diverse dining options, and engaging activities for travelers of all ages.",
    type: "short-hop-ferry",
    capacity: 1564,
    length: 412,
    width: 71,
    speed: 18,
    topSpeed: 21, 
    yearBuilt: 2018,
    homePort: {"city":"Tampa","country":"United States","coordinates":{"latitude":27.9506,"longitude":-82.4572}},
    specifications: {
      engineType: "Solar-Assisted Electric",
      fuelCapacity: 14620,
      waterCapacity: 469200,
      propulsionType: "Podded Propulsion Units",
      hullMaterial: "Ice-Strengthened Steel",
      classification: "China Classification Society B",
      safetyEquipment: ["Emergency position indicating radio beacons (EPIRBs)","Emergency escape breathing devices","Advanced fire detection and suppression systems","Personal locator beacons"],
      navigationEquipment: ["River radar systems","Radar and automatic radar plotting aids (ARPAs)","Infrared camera systems"],
      communicationEquipment: ["Digital selective calling equipment","Public address systems","Satellite communication systems"],
      entertainmentEquipment: ["Casino with table games and slot machines","Cinema with latest releases","Multiple swimming pools and water features"],
      accessibilityFeatures: ["Roll-in showers","Hearing augmentation systems","Accessible shore excursion options","Accessible dining facilities"],
      environmentalFeatures: ["Noise reduction technology to minimize impact on marine life","Energy-efficient appliances"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "nb--gale",
    name: "NB  Gale",
    description: "Sailing from the picturesque port of Tampa, the NB  Gale represents a new era in cruise experiences. This remarkable ocean liner combines innovative design with thoughtful amenities, creating an atmosphere of refined elegance and warm hospitality.",
    type: "ocean-liner",
    capacity: 1833,
    length: 466,
    width: 79,
    speed: 19,
    topSpeed: 22, 
    yearBuilt: 2022,
    homePort: {"city":"Tampa","country":"United States","coordinates":{"latitude":27.9506,"longitude":-82.4572}},
    specifications: {
      engineType: "LNG-Powered Engines",
      fuelCapacity: 18400,
      waterCapacity: 549900,
      propulsionType: "Conventional Shaft Propellers",
      hullMaterial: "High-Tensile Steel Alloy",
      classification: "Russian Maritime Register of Shipping KM",
      safetyEquipment: ["Weather monitoring stations","Emergency position indicating radio beacons (EPIRBs)","Digital safety monitoring systems","Life jackets with integrated GPS","Marine evacuation systems (MES)","Emergency escape breathing devices"],
      navigationEquipment: ["Integrated navigation system displays","Autopilot systems with track control","Voyage data recorders (VDRs)","Electronic chart display information systems (ECDIS)","Echo sounders and sonar systems"],
      communicationEquipment: ["Global Maritime Distress Safety System (GMDSS)","Marine radio telephony"],
      entertainmentEquipment: ["Virtual reality gaming center","Art gallery and auction facilities","Observation lounges with panoramic views","Cinema with latest releases"],
      accessibilityFeatures: ["Service animal accommodations","Wheelchair accessible cabins","Transfer chairs for pool access","Elevator access to all public decks"],
      environmentalFeatures: ["LED lighting throughout","Advanced water treatment systems","Optimized hull design for reduced fuel consumption","Ballast water management technology"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ms--explorer",
    name: "MS  Explorer",
    description: "With its distinctive profile and luxurious appointments, the MS  Explorer stands as a jewel in the Tampa harbor. This prestigious boutique cruise ship offers travelers a perfect combination of adventure and relaxation, with expert-guided excursions, world-class entertainment, and sublime culinary experiences.",
    type: "boutique-cruise-ship",
    capacity: 1408,
    length: 381,
    width: 67,
    speed: 20,
    topSpeed: 23, 
    yearBuilt: 2010,
    homePort: {"city":"Tampa","country":"United States","coordinates":{"latitude":27.9506,"longitude":-82.4572}},
    specifications: {
      engineType: "LNG-Powered Engines",
      fuelCapacity: 12760,
      waterCapacity: 422400,
      propulsionType: "Podded Propulsion Units",
      hullMaterial: "Hybrid Steel-Composite",
      classification: "Bureau Veritas Star Class",
      safetyEquipment: ["Advanced fire detection and suppression systems","Marine evacuation systems (MES)","Hyperbaric treatment chambers","Satellite emergency notification devices","Emergency position indicating radio beacons (EPIRBs)","Rescue boats and life rafts"],
      navigationEquipment: ["Automatic identification systems (AIS)","Night vision systems","Integrated navigation system displays"],
      communicationEquipment: ["Maritime VHF radio systems"],
      entertainmentEquipment: ["Multiple swimming pools and water features","Climbing walls and sports courts","Full-service spa and fitness center"],
      accessibilityFeatures: ["Accessible entertainment venues","Height-adjustable furniture in select cabins","Accessible shore excursion options","Service animal accommodations"],
      environmentalFeatures: ["Noise reduction technology to minimize impact on marine life","Heat recovery systems","Optimized hull design for reduced fuel consumption","Solar panel supplementation","Dynamic routing to optimize fuel usage"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "rv-tampa-voyager",
    name: "RV Tampa Voyager",
    description: "The RV Tampa Voyager invites travelers to explore the treasures of Florida in unmatched comfort. This exceptional zodiac equipped vessel, based in Tampa, features curated excursions, immersive cultural programs, and luxurious accommodations that ensure an unforgettable journey.",
    type: "zodiac-equipped-vessel",
    capacity: 1517,
    length: 403,
    width: 70,
    speed: 23,
    topSpeed: 26, 
    yearBuilt: 2015,
    homePort: {"city":"Tampa","country":"United States","coordinates":{"latitude":27.9506,"longitude":-82.4572}},
    specifications: {
      engineType: "Hybrid Power System",
      fuelCapacity: 14100,
      waterCapacity: 455099,
      propulsionType: "Z-Drive Propulsion",
      hullMaterial: "Marine-Grade Steel",
      classification: "Lloyd's Register Class 1",
      safetyEquipment: ["Radar reflectors","Automated external defibrillators (AEDs)","Emergency position indicating radio beacons (EPIRBs)"],
      navigationEquipment: ["Electronic chart display information systems (ECDIS)","Autopilot systems with track control","Navigation data management systems"],
      communicationEquipment: ["Emergency position-indicating radio beacons","Maritime VHF radio systems","Digital selective calling equipment"],
      entertainmentEquipment: ["Climbing walls and sports courts","Immersive simulation experiences","Casino with table games and slot machines","Culinary demonstration kitchens"],
      accessibilityFeatures: ["Accessible entertainment venues","Transfer chairs for pool access","Height-adjustable furniture in select cabins"],
      environmentalFeatures: ["Exhaust gas cleaning systems","Energy-efficient appliances","Dynamic routing to optimize fuel usage","Advanced water treatment systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "my--of-the-deep",
    name: "MY  of the Deep",
    description: "The majestic MY  of the Deep represents the pinnacle of maritime engineering and hospitality. Based in Tampa, this exceptional chartered vessel features elegant interiors, cutting-edge facilities, and carefully curated experiences that celebrate the unique culture of the Florida region.",
    type: "chartered-vessel",
    capacity: 1287,
    length: 357,
    width: 63,
    speed: 15,
    topSpeed: 18, 
    yearBuilt: 2015,
    homePort: {"city":"Tampa","country":"United States","coordinates":{"latitude":27.9506,"longitude":-82.4572}},
    specifications: {
      engineType: "Dual-Fuel Marine Engines",
      fuelCapacity: 11240,
      waterCapacity: 386099,
      propulsionType: "Conventional Shaft Propellers",
      hullMaterial: "Composite Materials",
      classification: "ClassNK NS* (Special Purpose Ship)",
      safetyEquipment: ["Survival craft VHF radios","Automated external defibrillators (AEDs)","Life jackets with integrated GPS","Radar reflectors","Rescue boats and life rafts","Advanced fire detection and suppression systems","Satellite emergency notification devices"],
      navigationEquipment: ["Autopilot systems with track control","Dynamic positioning systems"],
      communicationEquipment: ["Digital selective calling equipment","Internal crew communication network"],
      entertainmentEquipment: ["Virtual reality gaming center","Casino with table games and slot machines","Art gallery and auction facilities","Library and educational facilities"],
      accessibilityFeatures: ["Accessible entertainment venues","Service animal accommodations","Accessible shore excursion options"],
      environmentalFeatures: ["Exhaust gas cleaning systems","Marine ecosystem monitoring equipment","Ballast water management technology"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "mv--explorer",
    name: "MV  Explorer",
    description: "The MV  Explorer stands as a testament to luxury and innovation on the high seas. Departing from Tampa, this sophisticated adults only ship features immersive entertainment, wellness facilities, and exquisite cuisine prepared by internationally renowned chefs.",
    type: "adults-only-ship",
    capacity: 1397,
    length: 379,
    width: 66,
    speed: 27,
    topSpeed: 32, 
    yearBuilt: 2011,
    homePort: {"city":"Tampa","country":"United States","coordinates":{"latitude":27.9506,"longitude":-82.4572}},
    specifications: {
      engineType: "Gas Turbine Powerplant",
      fuelCapacity: 12500,
      waterCapacity: 419099,
      propulsionType: "Cycloidal Drive",
      hullMaterial: "Reinforced Aluminum",
      classification: "ClassNK NS* (Special Purpose Ship)",
      safetyEquipment: ["Searchlights and rescue equipment","Man overboard detection systems","Thermal imaging cameras","Digital safety monitoring systems","Satellite emergency notification devices","Water purification systems","Hyperbaric treatment chambers"],
      navigationEquipment: ["Autopilot systems with track control","Navigation data management systems","Integrated bridge systems"],
      communicationEquipment: ["Broadband internet throughout","Internal crew communication network"],
      entertainmentEquipment: ["Casino with table games and slot machines","Dance clubs and live music venues","Art gallery and auction facilities","Multiple swimming pools and water features"],
      accessibilityFeatures: ["Accessible shore excursion options","Roll-in showers","Accessible dining facilities","Accessible medical facilities"],
      environmentalFeatures: ["Exhaust gas cleaning systems","LED lighting throughout"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "my-tampa-voyager",
    name: "MY Tampa Voyager",
    description: "With its distinctive profile and luxurious appointments, the MY Tampa Voyager stands as a jewel in the Tampa harbor. This prestigious river cruise ship offers travelers a perfect combination of adventure and relaxation, with expert-guided excursions, world-class entertainment, and sublime culinary experiences.",
    type: "river-cruise-ship",
    capacity: 521,
    length: 204,
    width: 40,
    speed: 29,
    topSpeed: 33, 
    yearBuilt: 2015,
    homePort: {"city":"Tampa","country":"United States","coordinates":{"latitude":27.9506,"longitude":-82.4572}},
    specifications: {
      engineType: "Podded Propulsion",
      fuelCapacity: 4080,
      waterCapacity: 156299,
      propulsionType: "Water Jets",
      hullMaterial: "Reinforced Aluminum",
      classification: "Bureau Veritas Star Class",
      safetyEquipment: ["Weather monitoring stations","Advanced fire detection and suppression systems"],
      navigationEquipment: ["Automatic identification systems (AIS)","Navigation data management systems","Electronic chart display information systems (ECDIS)"],
      communicationEquipment: ["Public address systems","Marine radio telephony"],
      entertainmentEquipment: ["Culinary demonstration kitchens","Immersive simulation experiences","Casino with table games and slot machines","Children's entertainment areas","Theater with Broadway-style productions"],
      accessibilityFeatures: ["Accessible dining facilities","Transfer chairs for pool access","Roll-in showers"],
      environmentalFeatures: ["Optimized hull design for reduced fuel consumption","Noise reduction technology to minimize impact on marine life","Ballast water management technology","Solar panel supplementation"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "hms--of-the-deep",
    name: "HMS  of the Deep",
    description: "The majestic HMS  of the Deep represents the pinnacle of maritime engineering and hospitality. Based in Tampa, this exceptional ice class ship features elegant interiors, cutting-edge facilities, and carefully curated experiences that celebrate the unique culture of the Florida region.",
    type: "ice-class-ship",
    capacity: 1005,
    length: 301,
    width: 55,
    speed: 28,
    topSpeed: 33, 
    yearBuilt: 2019,
    homePort: {"city":"Tampa","country":"United States","coordinates":{"latitude":27.9506,"longitude":-82.4572}},
    specifications: {
      engineType: "Podded Propulsion",
      fuelCapacity: 8270,
      waterCapacity: 301500,
      propulsionType: "Conventional Shaft Propellers",
      hullMaterial: "Reinforced Aluminum",
      classification: "American Bureau of Shipping A1",
      safetyEquipment: ["Hyperbaric treatment chambers","Tactical response equipment","Emergency escape breathing devices","Searchlights and rescue equipment","Comprehensive medical facilities","Personal locator beacons"],
      navigationEquipment: ["Autopilot systems with track control","Radar and automatic radar plotting aids (ARPAs)"],
      communicationEquipment: ["Satellite communication systems","Emergency position-indicating radio beacons"],
      entertainmentEquipment: ["Dance clubs and live music venues","Observation lounges with panoramic views","Children's entertainment areas","Full-service spa and fitness center"],
      accessibilityFeatures: ["Service animal accommodations","Accessible entertainment venues","Braille signage throughout"],
      environmentalFeatures: ["Recyclable material management systems","Heat recovery systems","Energy-efficient appliances","Dynamic routing to optimize fuel usage"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ts--explorer",
    name: "TS  Explorer",
    description: "The majestic TS  Explorer represents the pinnacle of maritime engineering and hospitality. Based in Tampa, this exceptional ocean liner features elegant interiors, cutting-edge facilities, and carefully curated experiences that celebrate the unique culture of the Florida region.",
    type: "ocean-liner",
    capacity: 1472,
    length: 394,
    width: 69,
    speed: 27,
    topSpeed: 30, 
    yearBuilt: 2020,
    homePort: {"city":"Tampa","country":"United States","coordinates":{"latitude":27.9506,"longitude":-82.4572}},
    specifications: {
      engineType: "Diesel-Electric Propulsion",
      fuelCapacity: 13590,
      waterCapacity: 441599,
      propulsionType: "Conventional Shaft Propellers",
      hullMaterial: "High-Tensile Steel Alloy",
      classification: "China Classification Society B",
      safetyEquipment: ["Thermal imaging cameras","Marine evacuation systems (MES)","Comprehensive medical facilities","Automated external defibrillators (AEDs)","Life jackets with integrated GPS"],
      navigationEquipment: ["Autopilot systems with track control","Automatic identification systems (AIS)","Bridge alert management systems","Navigation data management systems","Voyage data recorders (VDRs)"],
      communicationEquipment: ["Public address systems","Digital selective calling equipment"],
      entertainmentEquipment: ["Casino with table games and slot machines","Cinema with latest releases","Multiple swimming pools and water features","Children's entertainment areas","Culinary demonstration kitchens"],
      accessibilityFeatures: ["Braille signage throughout","Assistive listening devices","Roll-in showers"],
      environmentalFeatures: ["Solar panel supplementation","Optimized hull design for reduced fuel consumption","Recyclable material management systems"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ly-tampa-voyager",
    name: "LY Tampa Voyager",
    description: "The LY Tampa Voyager stands as a testament to luxury and innovation on the high seas. Departing from Tampa, this sophisticated superyacht features immersive entertainment, wellness facilities, and exquisite cuisine prepared by internationally renowned chefs.",
    type: "superyacht",
    capacity: 1282,
    length: 356,
    width: 63,
    speed: 26,
    topSpeed: 29, 
    yearBuilt: 2020,
    homePort: {"city":"Tampa","country":"United States","coordinates":{"latitude":27.9506,"longitude":-82.4572}},
    specifications: {
      engineType: "Podded Propulsion",
      fuelCapacity: 11210,
      waterCapacity: 384599,
      propulsionType: "Conventional Shaft Propellers",
      hullMaterial: "Marine-Grade Steel",
      classification: "Bureau Veritas Star Class",
      safetyEquipment: ["Satellite emergency notification devices","Weather monitoring stations","Searchlights and rescue equipment"],
      navigationEquipment: ["Navigation data management systems","Automatic identification systems (AIS)"],
      communicationEquipment: ["Broadband internet throughout","Global Maritime Distress Safety System (GMDSS)","Satellite communication systems"],
      entertainmentEquipment: ["Cinema with latest releases"],
      accessibilityFeatures: ["Service animal accommodations","Assistive listening devices","Accessible entertainment venues"],
      environmentalFeatures: ["Marine ecosystem monitoring equipment","Biodegradable hydraulic fluids","Food waste digesters"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ps--of-the-deep",
    name: "PS  of the Deep",
    description: "Experience the epitome of maritime excellence aboard the PS  of the Deep, a premier river cruise ship sailing from Tampa. With its elegant design, state-of-the-art technology, and exceptional service, every journey promises unforgettable moments and unparalleled comfort.",
    type: "river-cruise-ship",
    capacity: 1230,
    length: 346,
    width: 61,
    speed: 18,
    topSpeed: 20, 
    yearBuilt: 2021,
    homePort: {"city":"Tampa","country":"United States","coordinates":{"latitude":27.9506,"longitude":-82.4572}},
    specifications: {
      engineType: "Hybrid Power System",
      fuelCapacity: 10550,
      waterCapacity: 369000,
      propulsionType: "Cycloidal Drive",
      hullMaterial: "High-Tensile Steel Alloy",
      classification: "Russian Maritime Register of Shipping KM",
      safetyEquipment: ["Emergency escape breathing devices","Survival craft VHF radios","Digital safety monitoring systems","Water purification systems","Advanced fire detection and suppression systems"],
      navigationEquipment: ["Inland ECDIS","Dynamic positioning systems","Weather routing systems","Long-range identification and tracking (LRIT)","Global navigation satellite systems (GNSS)"],
      communicationEquipment: ["Internal crew communication network","Public address systems","Marine radio telephony"],
      entertainmentEquipment: ["Immersive simulation experiences","Climbing walls and sports courts"],
      accessibilityFeatures: ["Tactile guidance systems","Assistive listening devices"],
      environmentalFeatures: ["Noise reduction technology to minimize impact on marine life","Marine ecosystem monitoring equipment","Dynamic routing to optimize fuel usage","Exhaust gas cleaning systems","Optimized hull design for reduced fuel consumption"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "sy--explorer",
    name: "SY  Explorer",
    description: "Experience the epitome of maritime excellence aboard the SY  Explorer, a premier polar expedition ship sailing from Tampa. With its elegant design, state-of-the-art technology, and exceptional service, every journey promises unforgettable moments and unparalleled comfort.",
    type: "polar-expedition-ship",
    capacity: 1323,
    length: 364,
    width: 64,
    speed: 16,
    topSpeed: 19, 
    yearBuilt: 2015,
    homePort: {"city":"Tampa","country":"United States","coordinates":{"latitude":27.9506,"longitude":-82.4572}},
    specifications: {
      engineType: "Diesel-Electric Propulsion",
      fuelCapacity: 11640,
      waterCapacity: 396900,
      propulsionType: "Podded Propulsion Units",
      hullMaterial: "Marine-Grade Steel",
      classification: "ClassNK NS* (Special Purpose Ship)",
      safetyEquipment: ["Comprehensive medical facilities","Searchlights and rescue equipment","Life jackets with integrated GPS"],
      navigationEquipment: ["Radar and automatic radar plotting aids (ARPAs)","Autopilot systems with track control"],
      communicationEquipment: ["Satellite communication systems","Broadband internet throughout","Public address systems"],
      entertainmentEquipment: ["Observation lounges with panoramic views","Multiple swimming pools and water features"],
      accessibilityFeatures: ["Hearing augmentation systems","Transfer chairs for pool access"],
      environmentalFeatures: ["Optimized hull design for reduced fuel consumption","Dynamic routing to optimize fuel usage","Exhaust gas cleaning systems","Ballast water management technology","Solar panel supplementation"]
    },
    isLuxuryVessel: false,
    isPetFriendly: true,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "sy-tampa-voyager",
    name: "SY Tampa Voyager",
    description: "The SY Tampa Voyager stands as a testament to luxury and innovation on the high seas. Departing from Tampa, this sophisticated catamaran features immersive entertainment, wellness facilities, and exquisite cuisine prepared by internationally renowned chefs.",
    type: "catamaran",
    capacity: 809,
    length: 261,
    width: 49,
    speed: 18,
    topSpeed: 21, 
    yearBuilt: 2023,
    homePort: {"city":"Tampa","country":"United States","coordinates":{"latitude":27.9506,"longitude":-82.4572}},
    specifications: {
      engineType: "Azimuth Thrusters",
      fuelCapacity: 6390,
      waterCapacity: 242700,
      propulsionType: "Cycloidal Drive",
      hullMaterial: "Ice-Strengthened Steel",
      classification: "RINA Green Star Plus",
      safetyEquipment: ["Advanced fire detection and suppression systems","Emergency escape breathing devices","Satellite emergency notification devices"],
      navigationEquipment: ["Long-range identification and tracking (LRIT)","Automatic identification systems (AIS)","Radar and automatic radar plotting aids (ARPAs)","Voyage data recorders (VDRs)","Autopilot systems with track control"],
      communicationEquipment: ["Emergency position-indicating radio beacons","Ship-to-shore communication links"],
      entertainmentEquipment: ["Theater with Broadway-style productions","Library and educational facilities","Observation lounges with panoramic views","Multi-purpose event spaces"],
      accessibilityFeatures: ["Roll-in showers","Elevator access to all public decks","Braille signage throughout"],
      environmentalFeatures: ["Noise reduction technology to minimize impact on marine life","Ballast water management technology","Optimized hull design for reduced fuel consumption","Shore power connectivity"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  },
  {
    id: "ss--of-the-deep",
    name: "SS  of the Deep",
    description: "Experience the epitome of maritime excellence aboard the SS  of the Deep, a premier mid size cruise ship sailing from Tampa. With its elegant design, state-of-the-art technology, and exceptional service, every journey promises unforgettable moments and unparalleled comfort.",
    type: "mid-size-cruise-ship",
    capacity: 1132,
    length: 326,
    width: 58,
    speed: 29,
    topSpeed: 33, 
    yearBuilt: 2005,
    homePort: {"city":"Tampa","country":"United States","coordinates":{"latitude":27.9506,"longitude":-82.4572}},
    specifications: {
      engineType: "Diesel-Electric Propulsion",
      fuelCapacity: 9450,
      waterCapacity: 339599,
      propulsionType: "Water Jets",
      hullMaterial: "Reinforced Aluminum",
      classification: "ClassNK NS* (Special Purpose Ship)",
      safetyEquipment: ["Satellite emergency notification devices","Weather monitoring stations","Advanced fire detection and suppression systems","Digital safety monitoring systems"],
      navigationEquipment: ["Integrated bridge systems","Navigation data management systems"],
      communicationEquipment: ["Marine radio telephony","Emergency position-indicating radio beacons"],
      entertainmentEquipment: ["Immersive simulation experiences","Multiple swimming pools and water features","Art gallery and auction facilities"],
      accessibilityFeatures: ["Braille signage throughout","Accessible entertainment venues","Wheelchair accessible cabins","Hearing augmentation systems"],
      environmentalFeatures: ["Noise reduction technology to minimize impact on marine life","Marine ecosystem monitoring equipment"]
    },
    isLuxuryVessel: false,
    isPetFriendly: false,
    imageUrl: "/images/vessels/default-vessel.jpg"
  }
];
