import { RestaurantMenu } from "@/lib/types/types";

/**
 * Menu data for Royal Craft in st-thomas
 */
export const stThomasroyalCraftMenu: RestaurantMenu[] = [
  {
    title: "Main Course Menu",
    description:
      "Taste the depth of Mediterranean culture through our delicious preparations",
    category: [
      {
        name: "Signature Dishes",
        description:
          "Inspired by nature, mood, and season—our chef’s ever-evolving vision on a plate.",
        items: [
          {
            name: "Legendary Prime Rib",
            price: 24.79,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "24-Hour Braised Short Ribs",
            price: 35.08,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Restaurant's Namesake Signature Entrée",
            price: 27.22,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Captain's Favorite Seafood Tower",
            price: 37.75,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Japanese A5 Wagyu with Ponzu Butter",
            price: 28.95,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Wood-Fired Peking Duck with Plum Sauce",
            price: 26.5,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Charcoal Grilled Iberico Pork",
            price: 30.53,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: false,
            isKosher: false,
          },
        ],
      },
      {
        name: "Chef's Specials",
        description:
          "Unique culinary compositions that rotate frequently to keep each visit fresh and surprising.",
        items: [
          {
            name: "Authentic Grilled Volcanic Stone-Cooked Specialty",
            price: 28.13,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Authentic Zesty Slow-Roasted Prime Rib",
            price: 30.37,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: true,
          },
          {
            name: "Homestyle Hearty Seasonal Truffle Risotto",
            price: 30.1,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Homestyle Grilled Tableside Flambé Preparation",
            price: 36.9,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: false,
            isKosher: true,
          },
          {
            name: "Deluxe Savory Grilled Venison with Juniper Berry Sauce",
            price: 25.28,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
        ],
      },
      {
        name: "Appetizers",
        description:
          "A tempting assortment of beginning bites to pair with your first drink.",
        items: [
          {
            name: "Onion Rings",
            price: 9.03,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Bruschetta",
            price: 11.19,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Dumplings",
            price: 11.93,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deviled Eggs",
            price: 11.43,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Tempura",
            price: 8.94,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Spring Rolls",
            price: 12.14,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Crostini",
            price: 14.62,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Mezze Platter",
            price: 12.29,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Soups",
        description:
          "From light broths to hearty stews, our soups are a comforting embrace in every spoonful.",
        items: [
          {
            name: "Mushroom Soup",
            price: 12.09,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Gumbo",
            price: 12.7,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Italian Wedding Soup",
            price: 11.12,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Miso Soup",
            price: 7.74,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Salads",
        description:
          "Lively salads combining texture, temperature, and taste for a refreshing start or light meal.",
        items: [
          {
            name: "Fruit Salad",
            price: 15.89,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Nicoise Salad",
            price: 11.21,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Watermelon Feta Salad",
            price: 13.99,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Cobb Salad",
            price: 10.92,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Lentil and Feta Salad",
            price: 12.98,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Main Courses",
        description:
          "Crafted with passion and precision, our mains are designed to impress.",
        items: [
          {
            name: "Pizza",
            price: 18.24,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Lentil Stew",
            price: 20.86,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Spaghetti Bolognese",
            price: 23.83,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Coq au Vin",
            price: 24.59,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Thai Curry",
            price: 22.42,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Salmon",
            price: 29.53,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Stir-fry",
            price: 19.94,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Moussaka",
            price: 27.5,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Seafood Specialties",
        description:
          "A celebration of the sea, featuring seasonal catches and artisanal techniques.",
        items: [
          {
            name: "Fresh Spiced New England Lobster Roll",
            price: 34.07,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "House Special Roasted Grilled Lobster with Lemon Butter",
            price: 34.1,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Traditional Fried Prawn Curry in Coconut Masala",
            price: 22.78,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Gourmet Enticing Cajun Shrimp and Grits",
            price: 33.05,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Traditional Spicy Linguine with Clam Sauce",
            price: 22.5,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
        ],
      },
      {
        name: "Side Dishes",
        description:
          "Crafted to enhance your meal, these sides are a celebration of Mediterranean flavors.",
        items: [
          {
            name: "Roasted Root Vegetables",
            price: 6.13,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Crispy Beer-Battered Onion Rings",
            price: 8.05,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Soft Polenta with Parmesan",
            price: 7.21,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Roasted Brussels Sprouts with Balsamic Glaze",
            price: 6.83,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Maple-Glazed Baby Carrots",
            price: 7.49,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Baked Idaho Potato with Sour Cream",
            price: 8.02,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Non-Alcoholic Beverages",
        description:
          "Refreshing selections ranging from house-made sodas to premium juices.",
        items: [
          {
            name: "Iced Tea",
            price: 7.74,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Smoothie",
            price: 7.61,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Soda",
            price: 7.83,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Milkshake",
            price: 7.32,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Lemonade",
            price: 6.06,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Tea",
            price: 7.44,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
  {
    title: "Dessert Menu",
    description: "Elevate your evening with our crowd-pleasing dessert course",
    category: [
      {
        name: "Baked Goods",
        description:
          "Warm, fragrant creations baked fresh daily with premium ingredients.",
        items: [
          {
            name: "Homestyle Zingy Cannoli",
            price: 6.87,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Hearty Braised Cobbler",
            price: 10.37,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Grilled Muffins",
            price: 6.61,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Gourmet Exquisite Crumb Cake",
            price: 10.68,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Premium Flaky Scones",
            price: 10.66,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Frozen Desserts",
        description:
          "Classic frozen favorites reimagined with gourmet flair and fresh ingredients.",
        items: [
          {
            name: "Frozen Pie",
            price: 11.69,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Paletas",
            price: 7.16,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Frozen Pudding",
            price: 8.23,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Frozen Mousse",
            price: 7.59,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Ice Cream Cake",
            price: 7.57,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
  {
    title: "Drinks Menu",
    description: "From wines to spirits: fine choices for every palate",
    category: [
      {
        name: "Signature Cocktails",
        description:
          "Elevate your evening with our signature cocktails, each a unique expression of flavor.",
        items: [
          {
            name: "House Special Enticing Mai Tai",
            price: 10.42,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Spicy Martini",
            price: 13.89,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Tender Cosmopolitan",
            price: 14.57,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Handcrafted Steamed Mojito",
            price: 10.48,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Gourmet Juicy Manhattan",
            price: 13.36,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Homestyle Crispy Whiskey Sour",
            price: 11.97,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Zesty Margarita",
            price: 12.51,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Wine Selection",
        description:
          "New World energy meets Old World elegance in our diverse selection.",
        items: [
          {
            name: "Authentic Satisfying Riesling",
            price: 13.59,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Sweet Champagne/Sparkling Wine",
            price: 12.09,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: true,
          },
          {
            name: "Homestyle Grilled Fiano",
            price: 11.92,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Herbed Nebbiolo",
            price: 12.62,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Classic Grilled Pinot Grigio",
            price: 10.26,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Organic Tangy Merlot",
            price: 11.27,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Spirits and Liqueurs",
        description:
          "Crafted for those who appreciate the art of distillation—each pour is a journey.",
        items: [
          {
            name: "Homestyle Tangy Calvados",
            price: 16.36,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Gourmet Appetizing Frangelico",
            price: 14.88,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Mouthwatering Brandy",
            price: 13.22,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Handcrafted Comforting Pisco",
            price: 11.54,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Steamed Grappa",
            price: 16.44,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
];
