import { RestaurantMenu } from "@/lib/types/types";

/**
 * Menu data for Blue Bakery in bermuda
 */
export const bermudablueBakeryMenu: RestaurantMenu[] = [
  {
    title: "Main Course Menu",
    description: "Every plate tells a story of simple American craftsmanship",
    category: [
      {
        name: "Signature Dishes",
        description:
          "House favorites that have stood the test of time and showcase our refined approach to American cuisine.",
        items: [
          {
            name: "Wood-Fired Peking Duck with Plum Sauce",
            price: 24.8,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Age-Old Recipe Osso Buco with Gremolata",
            price: 32.78,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Charcoal Grilled Iberico Pork",
            price: 24.4,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Caribbean-Style Jerk Duck with Mango Slaw",
            price: 34.86,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Tableside Carved Chateaubriand",
            price: 26.52,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Restaurant's Namesake Signature Entrée",
            price: 37.42,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Traditional Family Paella",
            price: 25.85,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Chef's Specials",
        description:
          "Crafted daily based on what’s freshest and most inspiring at the market.",
        items: [
          {
            name: "Authentic Grilled Charcoal-Grilled Wagyu Beef",
            price: 32.14,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Succulent Locally Foraged Mushroom Selection",
            price: 36.48,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Seasonal Appetizing Hand-Selected Wine Pairing Experience",
            price: 31.59,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Classic Braised Seared Foie Gras with Fig Compote",
            price: 35.69,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Grilled Modern Interpretation of Regional Classic",
            price: 38.42,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Appetizers",
        description:
          "Flavor-forward starters that introduce our approach to American with balance and creativity.",
        items: [
          {
            name: "Traditional Exquisite Garlic Bread",
            price: 14.66,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Classic Sizzling Garlic Knots",
            price: 11.82,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Hearty Braised Ceviche",
            price: 15.55,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Handcrafted Spiced Mini Crab Cakes",
            price: 10.68,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Homestyle Tangy Antipasto Platter",
            price: 14.13,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Herbed Potstickers",
            price: 9.93,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Premium Herbed Edamame",
            price: 12.1,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Hearty Luscious Calamari",
            price: 15.43,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
        ],
      },
      {
        name: "Soups",
        description:
          "Warm, nourishing soups that reflect the heart of American cooking—perfect for any season.",
        items: [
          {
            name: "Classic Delicious Corn Chowder",
            price: 8.91,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Grilled Black Bean Soup",
            price: 11.89,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Grilled Borscht",
            price: 12.52,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Hearty Satisfying Broccoli Cheddar Soup",
            price: 11.37,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Salads",
        description:
          "Lively salads combining texture, temperature, and taste for a refreshing start or light meal.",
        items: [
          {
            name: "Broccoli Crunch Salad",
            price: 12.12,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Farro Salad",
            price: 11.38,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Waldorf Salad",
            price: 13.97,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Nicoise Salad",
            price: 11.56,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Caesar Salad",
            price: 13.49,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Main Courses",
        description:
          "Hearty and refined mains rooted in traditional American, elevated by modern techniques.",
        items: [
          {
            name: "Seasonal Zesty Salmon",
            price: 30.74,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Fresh Grilled Ramen",
            price: 19.65,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Grilled Steak",
            price: 26.8,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Authentic Grilled Fish and Chips",
            price: 22.43,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Seasonal Creamy Chicken Parmesan",
            price: 20.23,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Hearty Hearty Pulled Pork Sandwich",
            price: 21.26,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Fresh Flaky Fajitas",
            price: 21.48,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Pan-seared Jambalaya",
            price: 26.75,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: true,
          },
        ],
      },
      {
        name: "Seafood Specialties",
        description:
          "Celebrations of the sea—light, flavorful, and handled with the utmost care.",
        items: [
          {
            name: "House Special Flaky Maryland Style Crab Cakes",
            price: 32.41,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Fresh Stuffed Stuffed Flounder with Crab and Spinach",
            price: 27.91,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Seasonal Grilled Traditional Provençal Bouillabaisse",
            price: 26.16,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Mouthwatering Shrimp Scampi over Linguine",
            price: 29.71,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: true,
          },
          {
            name: "Authentic Braised Blackened Mahi-Mahi with Pineapple Salsa",
            price: 30.13,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
        ],
      },
      {
        name: "Side Dishes",
        description:
          "Flavorful companions that round out your meal with harmony and flair.",
        items: [
          {
            name: "Organic Crunchy Homestyle Baked Beans",
            price: 5.78,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Hearty Savory Wild Mushroom Risotto",
            price: 9.42,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Wholesome Grilled Zucchini and Peppers",
            price: 8.74,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Authentic Marinated Roasted Brussels Sprouts with Balsamic Glaze",
            price: 5.67,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Homestyle Satisfying Grilled Asparagus with Lemon Zest",
            price: 8.83,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Zingy Crispy Beer-Battered Onion Rings",
            price: 9.82,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Non-Alcoholic Beverages",
        description: "Cold-pressed, house-infused, and always refreshing.",
        items: [
          {
            name: "Juice",
            price: 4.11,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Lemonade",
            price: 7.72,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Tea",
            price: 4.48,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Milkshake",
            price: 4.19,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Water",
            price: 6.17,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Iced Tea",
            price: 5.8,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
  {
    title: "Dessert Menu",
    description:
      "Our pastry chef's homemade creations to end your meal on a sweet note",
    category: [
      {
        name: "Baked Goods",
        description:
          "Artisanal baked items showcasing skill, tradition, and a touch of creativity.",
        items: [
          {
            name: "Homestyle Appetizing Lemon Bars",
            price: 9.74,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Handcrafted Stuffed Chocolate Chip Cookies",
            price: 8.29,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Stuffed Tiramisu",
            price: 10.16,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Authentic Enticing Banana Bread",
            price: 6.93,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Authentic Spicy Baklava",
            price: 8.69,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
        ],
      },
      {
        name: "Frozen Desserts",
        description:
          "Smooth, rich frozen creations featuring local fruits and seasonal flavors.",
        items: [
          {
            name: "Deluxe Sizzling Frozen Fruit Bars",
            price: 8.97,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Hearty Creamy Kulfi",
            price: 8.04,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Homestyle Spicy Sherbet",
            price: 10.72,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Sizzling Popsicles",
            price: 11.6,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Hearty Smoked Ice Cream Sandwich",
            price: 11.63,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
  {
    title: "Drinks Menu",
    description: "From wines to spirits: select choices for every palate",
    category: [
      {
        name: "Signature Cocktails",
        description:
          "Unique, house-crafted cocktails that offer a memorable sip every time.",
        items: [
          {
            name: "Martini",
            price: 15.62,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Whiskey Sour",
            price: 11.97,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Margarita",
            price: 11,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Mojito",
            price: 15.59,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Bloody Mary",
            price: 12.21,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Negroni",
            price: 13.7,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Mai Tai",
            price: 15.76,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Wine Selection",
        description:
          "A spectrum of vintages and varietals—from structured reds to bright, crisp whites.",
        items: [
          {
            name: "House Special Grilled Vermentino",
            price: 11.45,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Aromatic Syrah/Shiraz",
            price: 8.48,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Traditional Zingy Chardonnay",
            price: 11.56,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Exquisite Sangiovese",
            price: 13.1,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: true,
          },
          {
            name: "Handcrafted Herbed Pinot Noir",
            price: 10.06,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Creamy Vouvray",
            price: 11.55,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Spirits and Liqueurs",
        description:
          "A curated collection of fine spirits and artisan liqueurs from around the world.",
        items: [
          {
            name: "Fresh Succulent Coffee Liqueur",
            price: 11.15,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Pan-seared Maraschino",
            price: 13.55,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Classic Flaky Armagnac",
            price: 17,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Traditional Crunchy Whiskey",
            price: 16.84,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Braised Tequila",
            price: 13.09,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
        ],
      },
    ],
  },
];
