import { RestaurantMenu } from "@/lib/types/types";

/**
 * Menu data for Italian Creamery in vancouver
 */
export const vancouveritalianCreameryMenu: RestaurantMenu[] = [
  {
    title: "Main Course Menu",
    description:
      "Our kitchen presents an array of classic offerings from across the Italian spectrum",
    category: [
      {
        name: "Signature Dishes",
        description:
          "A curated collection of our most iconic and requested plates.",
        items: [
          {
            name: "Hearty Stuffed House Famous Duck Confit",
            price: 25.24,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: true,
          },
          {
            name: "Handcrafted Appetizing Korean BBQ Short Ribs with Kimchi Rice",
            price: 34.18,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Premium Stuffed Chef's Special Surf and Turf",
            price: 26.83,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Pan-seared Molecular Gastronomy Showcase Tasting",
            price: 26.14,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Hearty Stuffed Traditional Family Paella",
            price: 27.61,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Herbed Award-Winning Seafood Boil",
            price: 29.58,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: false,
            isKosher: true,
          },
          {
            name: "Homestyle Sautéed Seasonal Tasting Platter",
            price: 31.06,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Chef's Specials",
        description:
          "A showcase of our chef's creativity, featuring dishes that are as unique as they are delicious.",
        items: [
          {
            name: "Premium Satisfying Modern Interpretation of Regional Classic",
            price: 31.64,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Seasonal Exquisite Cold-Smoked Delicacy",
            price: 27.68,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Traditional Enticing Chef's Childhood Favorite Reimagined",
            price: 32.11,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Gourmet Sizzling Charcoal-Grilled Wagyu Beef",
            price: 32.65,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Deluxe Spicy Tableside Prepared Tartare",
            price: 31.17,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Appetizers",
        description:
          "Crafted to excite the palate, our starters are a perfect introduction to the world of Italian.",
        items: [
          {
            name: "Antipasto Platter",
            price: 14.17,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Stuffed Peppers",
            price: 13.61,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Zucchini Fries",
            price: 12.24,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Caprese Salad",
            price: 15.83,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Tuna Tartare",
            price: 12.03,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Baked Brie",
            price: 9.84,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Mini Crab Cakes",
            price: 10.69,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Charcuterie Board",
            price: 13.79,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
        ],
      },
      {
        name: "Soups",
        description:
          "A comforting range of house-made soups, from clear and delicate broths to rich, hearty bowls.",
        items: [
          {
            name: "Homestyle Grilled Carrot Ginger Soup",
            price: 13.78,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Seasonal Irresistible Lentil Soup",
            price: 12.05,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Traditional Marinated Beef Stew",
            price: 13.04,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "House Special Delectable Gumbo",
            price: 8.29,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Salads",
        description:
          "Wholesome creations that blend crunch, freshness, and house-crafted dressings.",
        items: [
          {
            name: "Caesar Salad",
            price: 9.11,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Greek Salad",
            price: 9.36,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Roasted Beet and Goat Cheese Salad",
            price: 10.98,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Coleslaw",
            price: 15.32,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Cobb Salad",
            price: 10.04,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Main Courses",
        description:
          "A journey through Italian flavors, expertly prepared and beautifully presented.",
        items: [
          {
            name: "Gourmet Crunchy Lamb Chops",
            price: 21.17,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Traditional Savory Steak",
            price: 31.51,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Homestyle Zingy Eggplant Parmesan",
            price: 22.83,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Pan-seared Katsu Curry",
            price: 29.35,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Hearty Smoked Risotto",
            price: 25.66,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Homestyle Grilled Grilled Chicken",
            price: 25.98,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Homestyle Grilled Biryani",
            price: 24.36,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Savory Pizza",
            price: 24.97,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Seafood Specialties",
        description:
          "A celebration of the sea, featuring seasonal catches and artisanal techniques.",
        items: [
          {
            name: "Premium Delicious Lobster Thermidor with Gruyère Crust",
            price: 33.78,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Homestyle Marinated Grilled Lobster with Lemon Butter",
            price: 28.9,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Fresh Hearty Hearty Italian Cioppino",
            price: 26.46,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Seasonal Grilled Tempura Soft Shell Crab",
            price: 35.33,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Gourmet Spicy New England Lobster Roll",
            price: 27.82,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
        ],
      },
      {
        name: "Side Dishes",
        description:
          "Flavor-packed sides made to share—or keep all to yourself.",
        items: [
          {
            name: "Seasonal Pan-seared Sautéed Garlic Mushrooms",
            price: 6.49,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Premium Stuffed Homestyle Baked Beans",
            price: 5.31,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Classic Braised Macaroni and Aged Cheddar",
            price: 9.26,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Pan-seared Grilled Zucchini and Peppers",
            price: 7.89,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: true,
          },
          {
            name: "Handcrafted Luscious Fragrant Basmati Rice Pilaf",
            price: 8.19,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Hearty Sweet Grilled Asparagus with Lemon Zest",
            price: 9.98,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Non-Alcoholic Beverages",
        description: "Cold-pressed, house-infused, and always refreshing.",
        items: [
          {
            name: "Hearty Wholesome Juice",
            price: 6.84,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Tender Hot Chocolate",
            price: 7.04,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Homestyle Grilled Milkshake",
            price: 7.84,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Handcrafted Flavorful Smoothie",
            price: 5.23,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Seasonal Mouthwatering Soda",
            price: 5.26,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Gourmet Sizzling Water",
            price: 6.46,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
  {
    title: "Dessert Menu",
    description:
      "A curated selection of delicious desserts, inspired by Italian heritage",
    category: [
      {
        name: "Baked Goods",
        description:
          "A rotating selection of baked indulgences from sweet to savory.",
        items: [
          {
            name: "Donuts",
            price: 7.84,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Berry Tart",
            price: 10.88,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Banana Bread",
            price: 9.18,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Biscotti",
            price: 10.82,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Pumpkin Pie",
            price: 8.73,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Frozen Desserts",
        description:
          "The ultimate way to cool off and indulge—delicate, creamy, and unforgettable.",
        items: [
          {
            name: "Frozen Yogurt",
            price: 10.48,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Baked Alaska",
            price: 9.4,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Ice Cream",
            price: 10.23,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Frozen Custard",
            price: 7.29,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Frozen Pudding",
            price: 8.34,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
  {
    title: "Drinks Menu",
    description:
      "Discover our crisp drinks, perfectly paired with our Italian cuisine",
    category: [
      {
        name: "Signature Cocktails",
        description:
          "Custom-designed drinks created exclusively by our mixologists to complement our menu.",
        items: [
          {
            name: "House Special Spicy Whiskey Sour",
            price: 11.63,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Flavorful Mojito",
            price: 11.25,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Hearty Hearty Cosmopolitan",
            price: 13.48,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Handcrafted Juicy Old Fashioned",
            price: 15.47,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Homestyle Hearty Margarita",
            price: 15.8,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Organic Sautéed Mai Tai",
            price: 14.2,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Sweet Manhattan",
            price: 14.1,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Wine Selection",
        description:
          "Explore our wine list, where each bottle is a testament to craftsmanship and tradition.",
        items: [
          {
            name: "Marsanne",
            price: 11.85,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Grenache",
            price: 9.07,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Viognier",
            price: 10.12,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Pinot Noir",
            price: 13.39,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Chardonnay",
            price: 13.4,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Verdicchio",
            price: 9.31,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Spirits and Liqueurs",
        description:
          "A curated collection of fine spirits and artisan liqueurs from around the world.",
        items: [
          {
            name: "Baileys Irish Cream",
            price: 15.75,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Bourbon",
            price: 13.1,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Coffee Liqueur",
            price: 11.8,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Whiskey",
            price: 10.26,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Absinthe",
            price: 14.49,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
];
