import { Restaurant } from "@/lib/types/types";

export const maltaRestaurants: Restaurant[] = [
  {
    name: "The Chateau",
    description:
      "Located close to the cultural center, this Japanese restaurant delights with its handcrafted desserts and charming streetscapes.",
    cuisine: "Japanese",
    priceRange: "$$$$",
    rating: 4.1,
    openingHours: {
      monday: "9:00-21:00",
      tuesday: "11:00-21:00",
      wednesday: "10:00-22:00",
      thursday: "Closed",
      friday: "9:00-20:00",
      saturday: "Closed",
      sunday: "9:00-21:00",
    },
    contactInfo: {
      contactNumber: "+1-555-890-3131",
      contactEmail: "services@bluebrasseriemalta.com",
    },
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: false,
    isHalalFriendly: false,
    isKosherFriendly: false,
    isFineDining: true,
    isAdultOnly: false,
    isIndoorSeating: true,
    isReservationsAccepted: true,
    isRomantic: true,
    isPopular: false,
  },
  {
    name: "Grand & Sons",
    description:
      "A charming French restaurant near the city museum, offering regional wines and other local favorites in a setting with local ambiance.",
    cuisine: "French",
    priceRange: "$$$$",
    rating: 4.1,
    openingHours: {
      monday: "11:00-19:00",
      tuesday: "10:00-19:00",
      wednesday: "11:00-22:00",
      thursday: "10:00-20:00",
      friday: "11:00-22:00",
      saturday: "Closed",
      sunday: "10:00-20:00",
    },
    contactInfo: {
      contactNumber: "+1-555-105-1620",
      contactEmail: "services@thepatisseriemalta.com",
    },
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: true,
    isHalalFriendly: false,
    isKosherFriendly: false,
    isFineDining: true,
    isAdultOnly: true,
    isIndoorSeating: true,
    isReservationsAccepted: true,
    isRomantic: false,
    isPopular: false,
  },
  {
    name: "Grand Creperie",
    description:
      "This popular Japanese establishment combines traditional recipes and local ingredients, all served in a unique setting with charming streetscapes.",
    cuisine: "Japanese",
    priceRange: "$$$$",
    rating: 4,
    openingHours: {
      monday: "Closed",
      tuesday: "10:00-22:00",
      wednesday: "10:00-22:00",
      thursday: "11:00-21:00",
      friday: "9:00-22:00",
      saturday: "Closed",
      sunday: "10:00-22:00",
    },
    contactInfo: {
      contactNumber: "+1-555-845-9781",
      contactEmail: "services@theculinarymalta.com",
    },
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: false,
    isHalalFriendly: false,
    isKosherFriendly: false,
    isFineDining: true,
    isAdultOnly: false,
    isIndoorSeating: true,
    isReservationsAccepted: true,
    isRomantic: true,
    isPopular: true,
  },
  {
    name: "The Project",
    description:
      "A culinary gem serving Italian specialties including gourmet street food, where guests enjoy friendly service in the heart of the city.",
    cuisine: "Italian",
    priceRange: "$$$$",
    rating: 4.4,
    openingHours: {
      monday: "Closed",
      tuesday: "11:00-22:00",
      wednesday: "9:00-20:00",
      thursday: "10:00-20:00",
      friday: "Closed",
      saturday: "Closed",
      sunday: "11:00-19:00",
    },
    contactInfo: {
      contactNumber: "+1-555-866-7949",
      contactEmail: "services@therotisseriemalta.com",
    },
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: false,
    isHalalFriendly: true,
    isKosherFriendly: false,
    isFineDining: true,
    isAdultOnly: false,
    isIndoorSeating: true,
    isReservationsAccepted: true,
    isRomantic: false,
    isPopular: true,
  },
  {
    name: "The Workshop",
    description:
      "Located close to downtown, this American restaurant delights with its regional wines and charming streetscapes.",
    cuisine: "American",
    priceRange: "$$$$",
    rating: 4,
    openingHours: {
      monday: "9:00-22:00",
      tuesday: "9:00-20:00",
      wednesday: "11:00-21:00",
      thursday: "9:00-20:00",
      friday: "11:00-21:00",
      saturday: "11:00-22:00",
      sunday: "Closed",
    },
    contactInfo: {
      contactNumber: "+1-555-886-3699",
      contactEmail: "services@royaltapasbarmalta.com",
    },
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: false,
    isHalalFriendly: false,
    isKosherFriendly: true,
    isFineDining: true,
    isAdultOnly: false,
    isIndoorSeating: true,
    isReservationsAccepted: false,
    isRomantic: true,
    isPopular: false,
  },
  {
    name: "Blue Creamery",
    description:
      "A charming American restaurant near the iconic clock tower, offering artisanal creations and other local favorites in a setting with artisan markets.",
    cuisine: "American",
    priceRange: "$$$$",
    rating: 4.3,
    openingHours: {
      monday: "10:00-22:00",
      tuesday: "9:00-22:00",
      wednesday: "11:00-20:00",
      thursday: "10:00-22:00",
      friday: "9:00-21:00",
      saturday: "9:00-22:00",
      sunday: "11:00-19:00",
    },
    contactInfo: {
      contactNumber: "+1-555-655-9640",
      contactEmail: "communications@royaldiningroommalta.com",
    },
    isVegetarianFriendly: false,
    isVeganFriendly: false,
    isGlutenFreeFriendly: true,
    isHalalFriendly: false,
    isKosherFriendly: false,
    isFineDining: true,
    isAdultOnly: false,
    isIndoorSeating: true,
    isReservationsAccepted: true,
    isRomantic: false,
    isPopular: true,
  },
  {
    name: "The Craft",
    description:
      "This popular American establishment combines traditional recipes and fresh produce, all served in a unique setting with beautiful decor.",
    cuisine: "American",
    priceRange: "$$$$",
    rating: 4.6,
    openingHours: {
      monday: "11:00-20:00",
      tuesday: "10:00-20:00",
      wednesday: "Closed",
      thursday: "Closed",
      friday: "10:00-19:00",
      saturday: "11:00-20:00",
      sunday: "Closed",
    },
    contactInfo: {
      contactNumber: "+1-555-690-6963",
      contactEmail: "communications@thecollectivemalta.com",
    },
    isVegetarianFriendly: false,
    isVeganFriendly: false,
    isGlutenFreeFriendly: true,
    isHalalFriendly: false,
    isKosherFriendly: false,
    isFineDining: true,
    isAdultOnly: false,
    isIndoorSeating: true,
    isReservationsAccepted: true,
    isRomantic: true,
    isPopular: true,
  },
];
