import { CrewMember } from "@/lib/interfaces/people/staff";

export const barcelonaTeamMembers: CrewMember[] = [
  {
    name: "Deborah Chambers",
    role: "Captain",
    department: "Deck Department",
    bio: "Captain Chambers's strategic decision-making and crisis management skills, honed over 19 years, ensure smooth and safe voyages throughout Mediterranean.",
    languages: ["Russian", "Portuguese", "Arabic", "Italian", "English"],
    experienceYears: 19,
    profileImage: "https://randomuser.me/api/portraits/women/36.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Kenneth West",
    role: "First Officer",
    department: "Deck Department",
    bio: "First Officer West supports the Captain by managing daily operations and maintaining vessel readiness, backed by extensive experience in Mediterranean.",
    languages: ["English", "Russian", "French"],
    experienceYears: 14,
    profileImage: "https://randomuser.me/api/portraits/men/36.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Gary Collins",
    role: "Second Officer",
    department: "Deck Department",
    bio: "Gary Collins ensures compliance with navigation protocols and supports bridge team operations, leveraging 18 years in maritime operations across Mediterranean.",
    languages: ["Arabic", "Mandarin", "Russian", "English"],
    experienceYears: 18,
    profileImage: "https://randomuser.me/api/portraits/men/75.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Frank Morgan",
    role: "Third Officer",
    department: "Deck Department",
    bio: "Third Officer Morgan assists with cargo operations and ballast management, a key part of their 10 years of development in Mediterranean.",
    languages: [
      "Spanish",
      "Italian",
      "English",
      "French",
      "Portuguese",
      "Japanese",
    ],
    experienceYears: 10,
    profileImage: "https://randomuser.me/api/portraits/men/83.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Christian Wells",
    role: "Navigation Officer",
    department: "Deck Department",
    bio: "Navigation Officer Wells ensures all navigational equipment is calibrated and fully operational, leveraging 11 years of technical expertise in Mediterranean.",
    languages: ["Japanese", "French", "English"],
    experienceYears: 11,
    profileImage: "https://randomuser.me/api/portraits/men/17.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Gregory Crawford",
    role: "Safety Officer",
    department: "Deck Department",
    bio: "With a thorough understanding of hazard identification and mitigation, Gregory Crawford fosters a culture of safety awareness among crew and passengers.",
    languages: ["Japanese", "Italian", "Portuguese", "Spanish", "English"],
    experienceYears: 3,
    profileImage: "https://randomuser.me/api/portraits/men/26.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "George Wallace",
    role: "Deck Cadet",
    department: "Deck Department",
    bio: "Under the guidance of senior officers, Deck Cadet Wallace is developing a strong foundation in practical navigation and ship handling in Mediterranean.",
    languages: ["Russian", "English"],
    experienceYears: 17,
    profileImage: "https://randomuser.me/api/portraits/men/85.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Timothy Grant",
    role: "Bosun",
    department: "Deck Department",
    bio: "Timothy Grant ensures compliance with safety standards during deck operations, fostering teamwork and discipline among crew members across Mediterranean's vessels.",
    languages: ["French", "Italian", "English"],
    experienceYears: 12,
    profileImage: "https://randomuser.me/api/portraits/men/27.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Lawrence Warren",
    role: "Chief Engineer",
    department: "Engineering Department",
    bio: "Chief Engineer Warren's extensive 8-year background includes overseeing major overhauls and ensuring peak operational readiness of all machinery.",
    languages: ["French", "Italian", "English", "Arabic"],
    experienceYears: 8,
    profileImage: "https://randomuser.me/api/portraits/men/59.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Chen Mitchell",
    role: "First Engineer",
    department: "Engineering Department",
    bio: "First Engineer Mitchell manages spare parts inventory and oversees condition monitoring programs to prevent system failures.",
    languages: ["Spanish", "German", "French", "Italian", "English"],
    experienceYears: 7,
    profileImage: "https://randomuser.me/api/portraits/men/98.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Lerato Hayes",
    role: "Second Engineer",
    department: "Engineering Department",
    bio: "Lerato Hayes plays an integral role in maintaining fuel efficiency and reducing emissions through optimized machinery operation.",
    languages: ["English", "French", "Japanese", "Arabic", "Italian", "German"],
    experienceYears: 5,
    profileImage: "https://randomuser.me/api/portraits/women/94.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Maya Palmer",
    role: "Electrical Engineer",
    department: "Engineering Department",
    bio: "Drawing on 14 years, Maya Palmer ensures the integrity of high-voltage systems and sophisticated electronic controls throughout the vessel.",
    languages: ["Arabic", "English"],
    experienceYears: 14,
    profileImage: "https://randomuser.me/api/portraits/women/48.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Nicholas Holloway",
    role: "Mechanical Engineer",
    department: "Engineering Department",
    bio: "With 16 years dedicated to marine mechanics, Nicholas Holloway excels in the overhaul and alignment of engines and rotating machinery.",
    languages: [
      "Arabic",
      "Italian",
      "Japanese",
      "Portuguese",
      "English",
      "Russian",
    ],
    experienceYears: 16,
    profileImage: "https://randomuser.me/api/portraits/men/79.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Victoria Graham",
    role: "HVAC Engineer",
    department: "Engineering Department",
    bio: "Victoria Graham monitors system performance and implements upgrades to enhance passenger comfort and crew wellbeing.",
    languages: ["French", "English", "Italian"],
    experienceYears: 20,
    profileImage: "https://randomuser.me/api/portraits/women/11.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Aaliyah Hawkins",
    role: "Environmental Engineer",
    department: "Engineering Department",
    bio: "Environmental Engineer Hawkins monitors emissions and advises on strategies to minimize the vessel’s environmental footprint.",
    languages: [
      "Italian",
      "Japanese",
      "Mandarin",
      "Portuguese",
      "Russian",
      "English",
    ],
    experienceYears: 19,
    profileImage: "https://randomuser.me/api/portraits/women/52.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Victor Curtis",
    role: "Systems Engineer",
    department: "Engineering Department",
    bio: "With extensive knowledge of software and hardware interfaces, Victor Curtis enhances system interoperability and cybersecurity aboard vessels.",
    languages: ["Russian", "English"],
    experienceYears: 16,
    profileImage: "https://randomuser.me/api/portraits/men/0.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Laura Murray",
    role: "Technical Manager",
    department: "Engineering Department",
    bio: "With a strategic overview honed over 19 years, Laura Murray directs fleet-wide technical policies and ensures best practices are implemented.",
    languages: ["English", "Arabic", "Portuguese", "Italian"],
    experienceYears: 19,
    profileImage: "https://randomuser.me/api/portraits/women/43.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Aria Curtis",
    role: "Maintenance Engineer",
    department: "Engineering Department",
    bio: "Maintenance Engineer Curtis's 7 years include managing workshop resources and training junior staff in effective repair techniques.",
    languages: [
      "Spanish",
      "Italian",
      "German",
      "Russian",
      "Japanese",
      "English",
    ],
    experienceYears: 7,
    profileImage: "https://randomuser.me/api/portraits/women/41.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Isabella Payne",
    role: "Security Director",
    department: "Security Department",
    bio: "Isabella Payne, with 8 years in the field, is an expert in ISPS Code implementation and maritime counter-terrorism strategies.",
    languages: ["French", "Japanese", "English"],
    experienceYears: 8,
    profileImage: "https://randomuser.me/api/portraits/women/50.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Sofia Watson",
    role: "Security Officer",
    department: "Security Department",
    bio: "Focused on maintaining order, Sofia Watson collaborates with other departments to enhance overall passenger and crew safety.",
    languages: [
      "German",
      "Italian",
      "Portuguese",
      "Arabic",
      "Japanese",
      "English",
    ],
    experienceYears: 11,
    profileImage: "https://randomuser.me/api/portraits/women/24.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Caroline Watson",
    role: "Security Specialist",
    department: "Security Department",
    bio: "Known for analytical expertise, Caroline Watson conducts vulnerability assessments and designs contingency plans to address evolving threats.",
    languages: ["Italian", "Arabic", "Russian", "English"],
    experienceYears: 4,
    profileImage: "https://randomuser.me/api/portraits/women/7.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Alexa Griffin",
    role: "Cybersecurity Officer",
    department: "Security Department",
    bio: "Known for proactive defense strategies, Alexa Griffin continuously monitors network activity and coordinates responses to cyber incidents onboard.",
    languages: ["Spanish", "English", "German"],
    experienceYears: 17,
    profileImage: "https://randomuser.me/api/portraits/women/90.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Philip Payne",
    role: "Maritime Security Coordinator",
    department: "Security Department",
    bio: "Philip Payne coordinates security protocols and emergency responses, drawing on 17 years in maritime operations and multi-agency collaboration.",
    languages: ["Portuguese", "Russian", "Italian", "Arabic", "English"],
    experienceYears: 17,
    profileImage: "https://randomuser.me/api/portraits/men/62.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Robert Baker",
    role: "Access Control Officer",
    department: "Security Department",
    bio: "Focused on security integrity, Robert Baker conducts regular audits of access logs and assists in security incident investigations.",
    languages: ["Russian", "Mandarin", "French", "English"],
    experienceYears: 19,
    profileImage: "https://randomuser.me/api/portraits/men/72.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Eric Sutton",
    role: "Safety Compliance Officer",
    department: "Security Department",
    bio: "Eric Sutton works closely with regulatory bodies to ensure the vessel meets all international safety conventions and company policies.",
    languages: ["Mandarin", "Japanese", "English", "German", "Arabic"],
    experienceYears: 4,
    profileImage: "https://randomuser.me/api/portraits/men/27.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Dylan Hudson",
    role: "Youth Program Director",
    department: "Youth & Family Programs",
    bio: "Youth Program Director Hudson ensures all youth activities are not only fun but also adhere to the highest safety and child protection standards, drawing on 18 years.",
    languages: ["English", "Spanish", "French"],
    experienceYears: 18,
    profileImage: "https://randomuser.me/api/portraits/men/65.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Blake Ellis",
    role: "Family Activities Coordinator",
    department: "Youth & Family Programs",
    bio: "Blake Ellis, with 4 years of experience, excels in logistics and planning, ensuring every family event runs smoothly and delights guests.",
    languages: ["Arabic", "English", "Italian"],
    experienceYears: 4,
    profileImage: "https://randomuser.me/api/portraits/men/9.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Lawrence Dixon",
    role: "Children's Entertainment Specialist",
    department: "Youth & Family Programs",
    bio: "Experienced in youth engagement, Lawrence Dixon provides fun, educational, and culturally sensitive activities tailored for children of all ages.",
    languages: ["Italian", "English"],
    experienceYears: 8,
    profileImage: "https://randomuser.me/api/portraits/men/84.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Jessica Carpenter",
    role: "Teen Activities Coordinator",
    department: "Youth & Family Programs",
    bio: "Teen Activities Coordinator Carpenter fosters positive social environments with interactive, age-appropriate activities that encourage peer bonding.",
    languages: ["Russian", "Mandarin", "English"],
    experienceYears: 7,
    profileImage: "https://randomuser.me/api/portraits/women/89.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Sebastian Knight",
    role: "Educational Program Manager",
    department: "Youth & Family Programs",
    bio: "With a commitment to lifelong learning, Sebastian Knight curates curriculum and interactive sessions that enhance passenger knowledge and engagement.",
    languages: ["German", "Spanish", "English"],
    experienceYears: 11,
    profileImage: "https://randomuser.me/api/portraits/men/56.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Skylar Mitchell",
    role: "Child Care Specialist",
    department: "Youth & Family Programs",
    bio: "Child Care Specialist Mitchell promotes social and emotional development through structured play and educational activities.",
    languages: ["Mandarin", "Spanish", "English"],
    experienceYears: 3,
    profileImage: "https://randomuser.me/api/portraits/women/64.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Zola Hall",
    role: "Activities Director",
    department: "Activities & Recreation",
    bio: "With strong organizational skills, Zola Hall manages budgets, resources, and partnerships to deliver high-quality recreational services.",
    languages: ["German", "French", "Arabic", "Japanese", "English"],
    experienceYears: 20,
    profileImage: "https://randomuser.me/api/portraits/women/87.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Helen Coleman",
    role: "Water Sports Instructor",
    department: "Activities & Recreation",
    bio: "Helen Coleman teaches water sports safely and effectively, leveraging 11 years of professional instruction and certification in aquatic activities.",
    languages: ["English", "Italian"],
    experienceYears: 11,
    profileImage: "https://randomuser.me/api/portraits/women/52.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Jose Chambers",
    role: "Fitness Instructor",
    department: "Activities & Recreation",
    bio: "Fitness Instructor Chambers promotes wellness and physical health through tailored exercise programs, backed by 5 years of fitness training and client engagement.",
    languages: ["German", "English", "Russian"],
    experienceYears: 5,
    profileImage: "https://randomuser.me/api/portraits/men/21.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Antonio Bennett",
    role: "Excursion Coordinator",
    department: "Activities & Recreation",
    bio: "Excursion Coordinator Bennett plans enriching off-ship experiences that promote cultural immersion and memorable interactions for passengers.",
    languages: ["English", "Spanish", "Mandarin", "German"],
    experienceYears: 8,
    profileImage: "https://randomuser.me/api/portraits/men/27.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Cynthia Mitchell",
    role: "Lead Photographer",
    department: "Photography & Videography",
    bio: "Lead Photographer Mitchell manages photographic equipment, editing workflows, and passenger portrait sessions with precision and professionalism.",
    languages: ["Arabic", "Japanese", "English"],
    experienceYears: 7,
    profileImage: "https://randomuser.me/api/portraits/women/22.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Roger Fletcher",
    role: "Videographer",
    department: "Photography & Videography",
    bio: "Roger Fletcher documents ship activities, excursions, and special events, delivering high-quality video content with 15 years of professional videography experience.",
    languages: ["Portuguese", "English", "Mandarin"],
    experienceYears: 15,
    profileImage: "https://randomuser.me/api/portraits/men/74.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Ryan Montgomery",
    role: "Digital Media Specialist",
    department: "Photography & Videography",
    bio: "Known for technical proficiency and creative vision, Ryan Montgomery collaborates closely with marketing and entertainment teams to maximize reach and impact.",
    languages: ["German", "English", "Portuguese"],
    experienceYears: 11,
    profileImage: "https://randomuser.me/api/portraits/men/9.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Stella Baker",
    role: "Chief Medical Officer",
    department: "Health & Safety",
    bio: "Chief Medical Officer Baker leads all medical operations onboard, leveraging 3 years of clinical and maritime healthcare expertise to ensure passenger and crew wellbeing.",
    languages: ["Mandarin", "German", "Japanese", "English"],
    experienceYears: 3,
    profileImage: "https://randomuser.me/api/portraits/women/37.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Maria Hamilton",
    role: "Ship's Doctor",
    department: "Health & Safety",
    bio: "With 9 years practicing medicine in diverse environments, Dr. Hamilton is adept at diagnosing and treating a wide array of conditions encountered at sea.",
    languages: ["Russian", "Italian", "Spanish", "English"],
    experienceYears: 9,
    profileImage: "https://randomuser.me/api/portraits/women/82.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Larry Baker",
    role: "Nurse",
    department: "Health & Safety",
    bio: "Leveraging 3 years in diverse nursing roles, Larry Baker excels in triage, wound care, and patient advocacy within the unique maritime environment.",
    languages: ["English", "German", "Arabic", "Russian", "Spanish"],
    experienceYears: 3,
    profileImage: "https://randomuser.me/api/portraits/men/38.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Barbara Carpenter",
    role: "Safety Officer",
    department: "Health & Safety",
    bio: "Barbara Carpenter enforces safety standards and conducts training programs, drawing on 8 years of maritime safety expertise to minimize risks onboard.",
    languages: ["Portuguese", "Japanese", "English"],
    experienceYears: 8,
    profileImage: "https://randomuser.me/api/portraits/women/62.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Chloe Russell",
    role: "Hospitality Director",
    department: "Hospitality Department",
    bio: "With 14 years in hospitality management, Chloe Russell drives operational excellence and team performance onboard.",
    languages: ["German", "Japanese", "English"],
    experienceYears: 14,
    profileImage: "https://randomuser.me/api/portraits/women/14.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Emma Mason",
    role: "Guest Relations Manager",
    department: "Hospitality Department",
    bio: "Guest Relations Manager Mason enhances passenger satisfaction through attentive and personalized service.",
    languages: ["Russian", "English", "Arabic", "French"],
    experienceYears: 14,
    profileImage: "https://randomuser.me/api/portraits/women/8.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Barbara Wells",
    role: "Chief Steward",
    department: "Hospitality Department",
    bio: "Barbara Wells ensures the highest standards of cleanliness and comfort throughout passenger accommodations.",
    languages: [
      "Italian",
      "Spanish",
      "Japanese",
      "Portuguese",
      "Arabic",
      "English",
    ],
    experienceYears: 6,
    profileImage: "https://randomuser.me/api/portraits/women/55.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Lily Reed",
    role: "Senior Steward",
    department: "Hospitality Department",
    bio: "Lily Reed is skilled in managing cabin maintenance and guest requests with professionalism and care.",
    languages: ["Arabic", "Italian", "English"],
    experienceYears: 20,
    profileImage: "https://randomuser.me/api/portraits/women/13.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Jeremy Keller",
    role: "Butler",
    department: "Hospitality Department",
    bio: "Jeremy Keller anticipates guest needs to deliver tailored luxury experiences throughout the voyage.",
    languages: ["Russian", "Italian", "English"],
    experienceYears: 16,
    profileImage: "https://randomuser.me/api/portraits/men/12.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Sebastian Fletcher",
    role: "Accommodation Manager",
    department: "Hospitality Department",
    bio: "With 7 years managing large-scale accommodation facilities, Sebastian Fletcher ensures all guest cabins and public areas meet exacting standards of cleanliness and repair.",
    languages: ["German", "French", "Japanese", "English"],
    experienceYears: 7,
    profileImage: "https://randomuser.me/api/portraits/men/92.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Evelyn Morgan",
    role: "Housekeeping Supervisor",
    department: "Hospitality Department",
    bio: "Evelyn Morgan manages daily assignments, motivates the housekeeping team, and ensures efficient use of cleaning resources, drawing on 16 years of leadership.",
    languages: ["Arabic", "Japanese", "English"],
    experienceYears: 16,
    profileImage: "https://randomuser.me/api/portraits/women/24.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Larry Wells",
    role: "Guest Services Specialist",
    department: "Hospitality Department",
    bio: "Larry Wells assists guests with inquiries and special requests, drawing on 20 years in customer service roles.",
    languages: ["German", "Japanese", "French", "English"],
    experienceYears: 20,
    profileImage: "https://randomuser.me/api/portraits/men/15.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Gary Parker",
    role: "Concierge",
    department: "Hospitality Department",
    bio: "Gary Parker acts as a personal guide to onboard and onshore experiences, providing insider tips and tailored advice to create unique memories for guests.",
    languages: ["French", "Japanese", "Portuguese", "English"],
    experienceYears: 20,
    profileImage: "https://randomuser.me/api/portraits/men/34.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Kevin Hudson",
    role: "Front Desk Manager",
    department: "Hospitality Department",
    bio: "Front Desk Manager Hudson trains staff in handling diverse guest interactions and maintaining accurate records, drawing on 17 years of best practices.",
    languages: ["English"],
    experienceYears: 17,
    profileImage: "https://randomuser.me/api/portraits/men/24.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Albert Coleman",
    role: "VIP Coordinator",
    department: "Hospitality Department",
    bio: "VIP Coordinator Coleman manages exclusive guest services, ensuring privacy and personalized attention throughout the voyage.",
    languages: ["Spanish", "English", "German"],
    experienceYears: 14,
    profileImage: "https://randomuser.me/api/portraits/men/5.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Zoe Stewart",
    role: "Hospitality Trainer",
    department: "Hospitality Department",
    bio: "Zoe Stewart develops training programs to elevate hospitality team skills, with 5 years in workforce development.",
    languages: ["Japanese", "Italian", "Spanish", "English"],
    experienceYears: 5,
    profileImage: "https://randomuser.me/api/portraits/women/13.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Virginia Chambers",
    role: "Executive Chef",
    department: "Culinary Department",
    bio: "Executive Chef Chambers leads a brigade of talented chefs, orchestrating all culinary operations and menu development with 19 years of innovative leadership.",
    languages: ["Japanese", "Portuguese", "Spanish", "Mandarin", "English"],
    experienceYears: 19,
    profileImage: "https://randomuser.me/api/portraits/women/73.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Isabella Holloway",
    role: "Sous Chef",
    department: "Culinary Department",
    bio: "Sous Chef Holloway supports kitchen operations with 8 years of culinary expertise and leadership.",
    languages: ["Mandarin", "Arabic", "Italian", "English"],
    experienceYears: 8,
    profileImage: "https://randomuser.me/api/portraits/women/54.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Gabriel Marshall",
    role: "Pastry Chef",
    department: "Culinary Department",
    bio: "Gabriel Marshall manages the pastry section, from artisan breads to elaborate cakes and plated desserts, ensuring exceptional quality over 20 years.",
    languages: [
      "French",
      "Russian",
      "Portuguese",
      "Arabic",
      "Spanish",
      "English",
    ],
    experienceYears: 20,
    profileImage: "https://randomuser.me/api/portraits/men/51.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Bella Day",
    role: "Chef de Partie",
    department: "Culinary Department",
    bio: "Bella Day maintains immaculate standards of organization and hygiene at their station, contributing to the kitchen's overall efficiency with 22 years of discipline.",
    languages: ["Portuguese", "Japanese", "English", "Arabic", "French"],
    experienceYears: 22,
    profileImage: "https://randomuser.me/api/portraits/women/36.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Sarah Grant",
    role: "Specialty Chef",
    department: "Culinary Department",
    bio: "Sarah Grant specializes in unique culinary styles, offering guests diverse flavors based on 6 years of expertise.",
    languages: ["German", "Russian", "Italian", "Portuguese", "English"],
    experienceYears: 6,
    profileImage: "https://randomuser.me/api/portraits/women/15.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Kimberly Gardner",
    role: "Sushi Chef",
    department: "Culinary Department",
    bio: "Kimberly Gardner delights guests with traditional Edomae-style sushi and contemporary maki rolls, showcasing skills honed over 5 years of rigorous training.",
    languages: ["German", "French", "Mandarin", "English"],
    experienceYears: 5,
    profileImage: "https://randomuser.me/api/portraits/women/94.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Audrey Spencer",
    role: "Garde Manger",
    department: "Culinary Department",
    bio: "Audrey Spencer is responsible for creating visually stunning and delicious cold appetizers, canapés, and buffet displays, backed by 21 years of Italian expertise.",
    languages: ["Japanese", "Italian", "Spanish", "English"],
    experienceYears: 21,
    profileImage: "https://randomuser.me/api/portraits/women/33.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Nomsa Wallace",
    role: "Butcher",
    department: "Culinary Department",
    bio: "With 15 years of expertise, Butcher Wallace expertly handles all meat and poultry, providing custom cuts and ensuring optimal yield for various Pacific Rim dishes.",
    languages: ["German", "Italian", "English"],
    experienceYears: 15,
    profileImage: "https://randomuser.me/api/portraits/women/10.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Tyler Sutton",
    role: "Baker",
    department: "Culinary Department",
    bio: "Baker Sutton produces fresh breads and baked goods, leveraging 16 years of baking expertise.",
    languages: ["Arabic", "Russian", "Italian", "English"],
    experienceYears: 16,
    profileImage: "https://randomuser.me/api/portraits/men/31.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Amanda Fox",
    role: "Sommelier",
    department: "Culinary Department",
    bio: "Sommelier Fox curates wine selections, offering expert pairing advice with 17 years in fine wine service.",
    languages: ["Spanish", "Japanese", "Mandarin", "English"],
    experienceYears: 17,
    profileImage: "https://randomuser.me/api/portraits/women/72.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Skylar Wallace",
    role: "Mixologist",
    department: "Culinary Department",
    bio: "Mixologist Wallace delights guests with flair, technique, and a deep understanding of flavor profiles, creating personalized drink experiences over 9 years.",
    languages: ["Mandarin", "Portuguese", "Japanese", "English"],
    experienceYears: 9,
    profileImage: "https://randomuser.me/api/portraits/women/53.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Ryan Foster",
    role: "Barista",
    department: "Culinary Department",
    bio: "Ryan Foster combines artistry and technique to serve quality espresso and coffee beverages.",
    languages: ["German", "Portuguese", "Mandarin", "English"],
    experienceYears: 7,
    profileImage: "https://randomuser.me/api/portraits/men/84.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Samantha Collins",
    role: "Nutritionist",
    department: "Culinary Department",
    bio: "With 20 years in clinical and culinary nutrition, Samantha Collins provides personalized dietary consultations and develops specialized meal plans for guests with specific needs.",
    languages: [
      "Spanish",
      "German",
      "Portuguese",
      "Mandarin",
      "Russian",
      "English",
    ],
    experienceYears: 20,
    profileImage: "https://randomuser.me/api/portraits/women/89.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Nora Collins",
    role: "Entertainment Director",
    department: "Entertainment Department",
    bio: "Entertainment Director Collins curates diverse programming to engage and delight guests throughout voyages.",
    languages: ["Russian", "Spanish", "English"],
    experienceYears: 5,
    profileImage: "https://randomuser.me/api/portraits/women/54.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Amina Graham",
    role: "Performance Coordinator",
    department: "Entertainment Department",
    bio: "Amina Graham manages scheduling and logistics for performers, ensuring smooth entertainment operations onboard.",
    languages: ["Mandarin", "Italian", "Spanish", "English"],
    experienceYears: 11,
    profileImage: "https://randomuser.me/api/portraits/women/50.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Vincent Douglas",
    role: "Lead Vocalist",
    department: "Entertainment Department",
    bio: "Vincent Douglas consistently delivers show-stopping performances, connecting with audiences through emotive storytelling and exceptional vocal talent honed across 12 years on stage.",
    languages: ["French", "Portuguese", "Russian", "English"],
    experienceYears: 12,
    profileImage: "https://randomuser.me/api/portraits/men/84.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Chen Jennings",
    role: "Musician",
    department: "Entertainment Department",
    bio: "With 9 years entertaining audiences worldwide, Chen Jennings creates an engaging atmosphere, taking requests and interacting with guests through the power of live music.",
    languages: ["Spanish", "German", "Portuguese", "English"],
    experienceYears: 9,
    profileImage: "https://randomuser.me/api/portraits/men/41.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Jane Hamilton",
    role: "Dancer",
    department: "Entertainment Department",
    bio: "With 3 years of professional training in {danceStyle} and contemporary dance, Jane Hamilton executes complex choreography with precision and artistry in mainstage productions.",
    languages: ["English", "Portuguese", "French", "German", "Arabic"],
    experienceYears: 3,
    profileImage: "https://randomuser.me/api/portraits/women/0.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Samuel Douglas",
    role: "Choreographer",
    department: "Entertainment Department",
    bio: "Samuel Douglas leads rehearsals and performance design to enhance the entertainment experience onboard.",
    languages: ["German", "Italian", "English"],
    experienceYears: 12,
    profileImage: "https://randomuser.me/api/portraits/men/22.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Charlotte Warren",
    role: "Comedy Performer",
    department: "Entertainment Department",
    bio: "Charlotte Warren entertains guests with humor and timing, backed by 11 years in comedy performance.",
    languages: ["Portuguese", "Italian", "Russian", "English"],
    experienceYears: 11,
    profileImage: "https://randomuser.me/api/portraits/women/36.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Ellie Hamilton",
    role: "Magic Act",
    department: "Entertainment Department",
    bio: "Ellie Hamilton blends showmanship and technique to deliver captivating magic shows at sea.",
    languages: ["Japanese", "Mandarin", "English"],
    experienceYears: 4,
    profileImage: "https://randomuser.me/api/portraits/women/60.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Rajesh Fletcher",
    role: "DJ",
    department: "Entertainment Department",
    bio: "With an extensive music library and 17 years of reading crowds, DJ Fletcher seamlessly blends genres to create the perfect soundtrack for any onboard event or nightclub.",
    languages: ["English"],
    experienceYears: 17,
    profileImage: "https://randomuser.me/api/portraits/men/8.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Sofia Palmer",
    role: "Audio Technician",
    department: "Entertainment Department",
    bio: "Sofia Palmer's keen ear and technical proficiency, developed over 8 years, are essential for delivering immersive and high-quality auditory experiences.",
    languages: ["Portuguese", "Spanish", "English"],
    experienceYears: 8,
    profileImage: "https://randomuser.me/api/portraits/women/13.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Patricia Watson",
    role: "Lighting Specialist",
    department: "Entertainment Department",
    bio: "Patricia Watson's artistic vision and technical mastery over 7 years ensure that lighting plays a crucial role in the storytelling and excitement of onboard entertainment.",
    languages: ["French", "German", "English"],
    experienceYears: 7,
    profileImage: "https://randomuser.me/api/portraits/women/40.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Claire Porter",
    role: "Stage Manager",
    department: "Entertainment Department",
    bio: "Stage Manager Porter coordinates all aspects of live performances, ensuring flawless execution of entertainment programs.",
    languages: ["Russian", "French", "Portuguese", "English"],
    experienceYears: 6,
    profileImage: "https://randomuser.me/api/portraits/women/0.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Samuel Chambers",
    role: "Production Manager",
    department: "Entertainment Department",
    bio: "Samuel Chambers's strategic planning and problem-solving skills, developed over 13 years, are crucial for the successful execution of a high-quality entertainment program.",
    languages: ["Italian", "French", "Portuguese", "German", "English"],
    experienceYears: 13,
    profileImage: "https://randomuser.me/api/portraits/men/58.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Amina Hunter",
    role: "Costume Designer",
    department: "Entertainment Department",
    bio: "With 4 years of experience in theatrical costume design, Amina Hunter conceives and produces stunning wardrobes that define characters and elevate productions.",
    languages: ["Portuguese", "Arabic", "Mandarin", "Russian", "English"],
    experienceYears: 4,
    profileImage: "https://randomuser.me/api/portraits/women/2.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Lily Wells",
    role: "Cultural Program Director",
    department: "Entertainment Department",
    bio: "Cultural Program Director Wells collaborates with local artists, historians, and experts to provide authentic and immersive cultural experiences for guests.",
    languages: [
      "Japanese",
      "Arabic",
      "Italian",
      "Portuguese",
      "French",
      "English",
    ],
    experienceYears: 7,
    profileImage: "https://randomuser.me/api/portraits/women/14.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Samantha Nash",
    role: "Performance Artist",
    department: "Entertainment Department",
    bio: "Samantha Nash captivates audiences with original performances tailored to shipboard entertainment.",
    languages: ["Arabic", "Spanish", "English"],
    experienceYears: 12,
    profileImage: "https://randomuser.me/api/portraits/women/35.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Chen Chambers",
    role: "Operations Manager",
    department: "Operations Department",
    bio: "With 19 years streamlining vessel-wide processes, Chen Chambers ensures optimal efficiency, resource allocation, and inter-departmental synergy.",
    languages: ["English", "French", "Japanese", "Italian"],
    experienceYears: 19,
    profileImage: "https://randomuser.me/api/portraits/men/72.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "David Foster",
    role: "Logistics Coordinator",
    department: "Operations Department",
    bio: "Logistics Coordinator Foster manages supply chain and transport logistics, ensuring efficient resource allocation.",
    languages: ["Russian", "Mandarin", "English"],
    experienceYears: 7,
    profileImage: "https://randomuser.me/api/portraits/men/32.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Kinsley Hamilton",
    role: "Inventory Specialist",
    department: "Operations Department",
    bio: "Kinsley Hamilton's analytical skills, honed over 9 years, are key to forecasting demand and optimizing stock levels across various departments.",
    languages: ["Arabic", "English", "Spanish"],
    experienceYears: 9,
    profileImage: "https://randomuser.me/api/portraits/women/15.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Amy Griffin",
    role: "Procurement Officer",
    department: "Operations Department",
    bio: "Amy Griffin applies expertise in vendor management and cost optimization to benefit ship operations.",
    languages: ["Russian", "Italian", "English"],
    experienceYears: 10,
    profileImage: "https://randomuser.me/api/portraits/women/42.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
  {
    name: "Emma Clark",
    role: "Sustainability Coordinator",
    department: "Operations Department",
    bio: "Sustainability Coordinator Clark ensures compliance with international environmental regulations (e.g., MARPOL) and promotes a culture of sustainability among crew and guests.",
    languages: ["Japanese", "Italian", "Russian", "Arabic", "English"],
    experienceYears: 5,
    profileImage: "https://randomuser.me/api/portraits/women/84.jpg",
    city: "Barcelona",
    country: "Spain",
    region: "Mediterranean",
  },
];
