import { CrewMember } from "@/lib/interfaces/people/staff";

export const hochiminhcityTeamMembers: CrewMember[] = [
  {
    name: "Ashley Wells",
    role: "Captain",
    department: "Deck Department",
    bio: "Drawing on 16 years of command, Ashley Wells expertly manages all aspects of vessel operation in , emphasizing crew development and operational excellence.",
    languages: ["Portuguese", "Italian", "English"],
    experienceYears: 16,
    profileImage: "https://randomuser.me/api/portraits/women/45.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Peter Gibson",
    role: "First Officer",
    department: "Deck Department",
    bio: "First Officer Gibson supports the Captain by managing daily operations and maintaining vessel readiness, backed by extensive experience in .",
    languages: ["Mandarin", "Spanish", "Russian", "German", "English"],
    experienceYears: 21,
    profileImage: "https://randomuser.me/api/portraits/men/26.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Mark Wallace",
    role: "Second Officer",
    department: "Deck Department",
    bio: "Mark Wallace is skilled in passage planning software and integrated bridge systems, contributing 14 years of knowledge to operations in .",
    languages: ["Italian", "French", "English", "Portuguese"],
    experienceYears: 14,
    profileImage: "https://randomuser.me/api/portraits/men/14.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Ashley West",
    role: "Third Officer",
    department: "Deck Department",
    bio: "Third Officer West assists with cargo operations and ballast management, a key part of their 20 years of development in .",
    languages: ["Italian", "Russian", "Japanese", "English"],
    experienceYears: 20,
    profileImage: "https://randomuser.me/api/portraits/women/97.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Noah West",
    role: "Navigation Officer",
    department: "Deck Department",
    bio: "With 21 years dedicated to  routes, Noah West excels in dynamic positioning and integrated navigation systems management.",
    languages: ["Portuguese", "German", "English"],
    experienceYears: 21,
    profileImage: "https://randomuser.me/api/portraits/men/47.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Paul Maxwell",
    role: "Safety Officer",
    department: "Deck Department",
    bio: "With 15 years overseeing maritime safety, Paul Maxwell ensures strict adherence to international safety regulations (SOLAS, MARPOL) and promotes a culture of vigilance onboard vessels operating in .",
    languages: ["Russian", "French", "Spanish", "English"],
    experienceYears: 15,
    profileImage: "https://randomuser.me/api/portraits/men/29.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Timothy Montgomery",
    role: "Deck Cadet",
    department: "Deck Department",
    bio: "Under the guidance of senior officers, Deck Cadet Montgomery is developing a strong foundation in practical navigation and ship handling in .",
    languages: ["Arabic", "Mandarin", "English"],
    experienceYears: 19,
    profileImage: "https://randomuser.me/api/portraits/men/96.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Daniel Wells",
    role: "Bosun",
    department: "Deck Department",
    bio: "Daniel Wells's leadership ensures the deck department operates efficiently and safely, drawing from 14 years of hands-on experience in .",
    languages: ["Russian", "German", "English"],
    experienceYears: 14,
    profileImage: "https://randomuser.me/api/portraits/men/2.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Lily Day",
    role: "Chief Engineer",
    department: "Engineering Department",
    bio: "Chief Engineer Day manages engineering teams and coordinates preventative maintenance programs to maximize uptime and efficiency throughout voyages.",
    languages: ["Italian", "Arabic", "English"],
    experienceYears: 14,
    profileImage: "https://randomuser.me/api/portraits/women/89.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Catherine Wallace",
    role: "First Engineer",
    department: "Engineering Department",
    bio: "First Engineer Wallace is responsible for the main propulsion machinery and auxiliary systems, bringing 4 years of hands-on expertise.",
    languages: ["English", "Russian", "Spanish"],
    experienceYears: 4,
    profileImage: "https://randomuser.me/api/portraits/women/34.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Helen Dixon",
    role: "Second Engineer",
    department: "Engineering Department",
    bio: "Second Engineer Dixon meticulously manages bunkering operations and ensures the quality of fuel and lubricants, drawing on 18 years of practical knowledge.",
    languages: [
      "Mandarin",
      "English",
      "German",
      "Arabic",
      "Italian",
      "Spanish",
    ],
    experienceYears: 18,
    profileImage: "https://randomuser.me/api/portraits/women/34.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Anna Ellis",
    role: "Electrical Engineer",
    department: "Engineering Department",
    bio: "Anna Ellis manages all electrical systems on board, applying 6 years of expertise in marine electrical engineering and system integration.",
    languages: ["Portuguese", "English", "Italian"],
    experienceYears: 6,
    profileImage: "https://randomuser.me/api/portraits/women/63.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Kinsley Hawkins",
    role: "Mechanical Engineer",
    department: "Engineering Department",
    bio: "Kinsley Hawkins performs root cause analysis for mechanical failures and implements corrective action plans to minimize operational disruptions.",
    languages: ["Italian", "Spanish", "English"],
    experienceYears: 15,
    profileImage: "https://randomuser.me/api/portraits/women/8.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Jessica Chambers",
    role: "HVAC Engineer",
    department: "Engineering Department",
    bio: "Jessica Chambers plays a key role in energy conservation by optimizing HVAC operations, backed by 12 years of specialized experience.",
    languages: ["Spanish", "German", "French", "English"],
    experienceYears: 12,
    profileImage: "https://randomuser.me/api/portraits/women/10.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Ryan Clark",
    role: "Environmental Engineer",
    department: "Engineering Department",
    bio: "With 20 years focused on sustainability, Ryan Clark develops and implements environmental protection measures aboard ships, ensuring regulatory compliance.",
    languages: ["Russian", "Portuguese", "German", "Arabic", "English"],
    experienceYears: 20,
    profileImage: "https://randomuser.me/api/portraits/men/66.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Gary Chambers",
    role: "Systems Engineer",
    department: "Engineering Department",
    bio: "Gary Chambers integrates complex onboard systems, ensuring operational synergy and reliability with 17 years of maritime engineering expertise.",
    languages: ["Mandarin", "English", "Italian"],
    experienceYears: 17,
    profileImage: "https://randomuser.me/api/portraits/men/70.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Roger Carpenter",
    role: "Technical Manager",
    department: "Engineering Department",
    bio: "With a strategic overview honed over 20 years, Roger Carpenter directs fleet-wide technical policies and ensures best practices are implemented.",
    languages: ["Portuguese", "English"],
    experienceYears: 20,
    profileImage: "https://randomuser.me/api/portraits/men/59.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Gary Dunn",
    role: "Maintenance Engineer",
    department: "Engineering Department",
    bio: "Maintenance Engineer Dunn's 5 years include managing workshop resources and training junior staff in effective repair techniques.",
    languages: ["Mandarin", "French", "Portuguese", "Russian", "English"],
    experienceYears: 5,
    profileImage: "https://randomuser.me/api/portraits/men/6.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Mateo Day",
    role: "Security Director",
    department: "Security Department",
    bio: "Mateo Day, with 22 years in the field, is an expert in ISPS Code implementation and maritime counter-terrorism strategies.",
    languages: ["Mandarin", "Japanese", "Arabic", "English"],
    experienceYears: 22,
    profileImage: "https://randomuser.me/api/portraits/men/22.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Sean Warren",
    role: "Security Officer",
    department: "Security Department",
    bio: "Leveraging 6 years of maritime security experience, Sean Warren excels in threat detection and proactive deterrence measures.",
    languages: [
      "Spanish",
      "Arabic",
      "Russian",
      "French",
      "Japanese",
      "English",
    ],
    experienceYears: 6,
    profileImage: "https://randomuser.me/api/portraits/men/60.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Edward Graham",
    role: "Security Specialist",
    department: "Security Department",
    bio: "With extensive training in security technologies, Edward Graham leads specialized investigations and security audits to strengthen vessel defenses.",
    languages: ["Italian", "Russian", "Spanish", "Arabic", "English"],
    experienceYears: 4,
    profileImage: "https://randomuser.me/api/portraits/men/30.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Michael Graham",
    role: "Cybersecurity Officer",
    department: "Security Department",
    bio: "Known for proactive defense strategies, Michael Graham continuously monitors network activity and coordinates responses to cyber incidents onboard.",
    languages: ["Spanish", "Portuguese", "English"],
    experienceYears: 7,
    profileImage: "https://randomuser.me/api/portraits/men/84.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Keith Fisher",
    role: "Maritime Security Coordinator",
    department: "Security Department",
    bio: "Keith Fisher's 19 years include expertise in crisis communication and liaising with flag state and port state control on security matters.",
    languages: ["Arabic", "Japanese", "English"],
    experienceYears: 19,
    profileImage: "https://randomuser.me/api/portraits/men/79.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Johnny Coleman",
    role: "Access Control Officer",
    department: "Security Department",
    bio: "Drawing on 12 years of experience, Johnny Coleman is proficient in operating and maintaining advanced access control systems and screening equipment.",
    languages: [
      "Japanese",
      "German",
      "Arabic",
      "Russian",
      "Italian",
      "English",
    ],
    experienceYears: 12,
    profileImage: "https://randomuser.me/api/portraits/men/15.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Gabriel Dunn",
    role: "Safety Compliance Officer",
    department: "Security Department",
    bio: "Safety Compliance Officer Dunn conducts safety audits, training, and inspections to uphold the highest standards throughout vessel operations.",
    languages: ["French", "Japanese", "Mandarin", "English"],
    experienceYears: 12,
    profileImage: "https://randomuser.me/api/portraits/men/34.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Jordan Dixon",
    role: "Youth Program Director",
    department: "Youth & Family Programs",
    bio: "Jordan Dixon has a knack for inspiring young minds, developing innovative curriculums over 8 years that make learning an adventure onboard.",
    languages: ["German", "English"],
    experienceYears: 8,
    profileImage: "https://randomuser.me/api/portraits/men/72.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Leah Chambers",
    role: "Family Activities Coordinator",
    department: "Youth & Family Programs",
    bio: "With strong communication skills, Leah Chambers liaises with hospitality and entertainment teams to deliver seamless family-oriented services.",
    languages: ["Spanish", "Arabic", "Portuguese", "English"],
    experienceYears: 15,
    profileImage: "https://randomuser.me/api/portraits/women/44.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Nora Foster",
    role: "Children's Entertainment Specialist",
    department: "Youth & Family Programs",
    bio: "Nora Foster is passionate about sparking imagination, developing new and exciting entertainment formats for kids over 22 years in the field.",
    languages: ["German", "English"],
    experienceYears: 22,
    profileImage: "https://randomuser.me/api/portraits/women/13.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "George Payne",
    role: "Teen Activities Coordinator",
    department: "Youth & Family Programs",
    bio: "Teen Activities Coordinator Payne fosters positive social environments with interactive, age-appropriate activities that encourage peer bonding.",
    languages: ["Portuguese", "Spanish", "Mandarin", "English"],
    experienceYears: 21,
    profileImage: "https://randomuser.me/api/portraits/men/24.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "David Gardner",
    role: "Educational Program Manager",
    department: "Youth & Family Programs",
    bio: "Educational Program Manager Gardner forges partnerships with guest speakers and institutions to provide high-quality learning experiences, leveraging 17 years of networking.",
    languages: ["English", "Mandarin"],
    experienceYears: 17,
    profileImage: "https://randomuser.me/api/portraits/men/60.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Mason Douglas",
    role: "Child Care Specialist",
    department: "Youth & Family Programs",
    bio: "Child Care Specialist Douglas promotes social and emotional development through structured play and educational activities.",
    languages: ["French", "German", "English", "Mandarin"],
    experienceYears: 5,
    profileImage: "https://randomuser.me/api/portraits/men/55.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Gary Dunn",
    role: "Activities Director",
    department: "Activities & Recreation",
    bio: "Drawing on 3 years in recreation management, Gary Dunn curates an exciting and varied daily program of entertainment and activities for all guests.",
    languages: ["Japanese", "English", "French"],
    experienceYears: 3,
    profileImage: "https://randomuser.me/api/portraits/men/58.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Timothy Porter",
    role: "Water Sports Instructor",
    department: "Activities & Recreation",
    bio: "Timothy Porter's primary focus for 4 years has been ensuring every guest feels confident and secure while exploring the water.",
    languages: ["Spanish", "French", "Mandarin", "Russian", "English"],
    experienceYears: 4,
    profileImage: "https://randomuser.me/api/portraits/men/73.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Christine Curtis",
    role: "Fitness Instructor",
    department: "Activities & Recreation",
    bio: "Fitness Instructor Curtis integrates modern fitness trends and equipment to provide dynamic and effective workout options.",
    languages: ["Spanish", "Italian", "English"],
    experienceYears: 21,
    profileImage: "https://randomuser.me/api/portraits/women/70.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Carol Dunn",
    role: "Excursion Coordinator",
    department: "Activities & Recreation",
    bio: "Carol Dunn's meticulous planning and attention to detail, developed over 4 years, ensure every guest's off-ship adventure is seamless and unforgettable.",
    languages: ["German", "English"],
    experienceYears: 4,
    profileImage: "https://randomuser.me/api/portraits/women/94.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Sarah Murray",
    role: "Lead Photographer",
    department: "Photography & Videography",
    bio: "Known for creativity and attention to detail, Sarah Murray collaborates with other departments to produce visual content that enhances onboard marketing and memory-making.",
    languages: ["French", "English", "Russian", "Japanese"],
    experienceYears: 5,
    profileImage: "https://randomuser.me/api/portraits/women/75.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Jordan Maxwell",
    role: "Videographer",
    department: "Photography & Videography",
    bio: "Jordan Maxwell uses 16 years of editing expertise to transform raw footage into engaging narratives that resonate with passengers and promote future voyages.",
    languages: ["French", "Portuguese", "English"],
    experienceYears: 16,
    profileImage: "https://randomuser.me/api/portraits/men/63.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Luis Wallace",
    role: "Digital Media Specialist",
    department: "Photography & Videography",
    bio: "Digital Media Specialist Wallace ensures an engaging online presence by creating and curating multimedia content tailored to diverse passenger demographics.",
    languages: ["Russian", "Mandarin", "Japanese", "English"],
    experienceYears: 3,
    profileImage: "https://randomuser.me/api/portraits/men/3.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Nancy Jennings",
    role: "Chief Medical Officer",
    department: "Health & Safety",
    bio: "With extensive knowledge in maritime medicine and emergency response, Nancy Jennings ensures readiness for diverse medical situations at sea.",
    languages: ["Italian", "French", "English"],
    experienceYears: 5,
    profileImage: "https://randomuser.me/api/portraits/women/39.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Rebecca Hayes",
    role: "Ship's Doctor",
    department: "Health & Safety",
    bio: "With specialization in emergency response, preventative medicine, and maritime health protocols, Dr. Hayes ensures passenger and crew safety.",
    languages: ["Mandarin", "French", "English"],
    experienceYears: 16,
    profileImage: "https://randomuser.me/api/portraits/women/38.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Adam Clark",
    role: "Nurse",
    department: "Health & Safety",
    bio: "Nurse Clark is experienced in managing chronic health conditions at sea and providing ongoing support to guests with specific medical needs, drawing from 13 years of practice.",
    languages: [
      "German",
      "Arabic",
      "Mandarin",
      "Russian",
      "Spanish",
      "English",
    ],
    experienceYears: 13,
    profileImage: "https://randomuser.me/api/portraits/men/84.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Peter Curtis",
    role: "Safety Officer",
    department: "Health & Safety",
    bio: "Leveraging 21 years in maritime safety, Peter Curtis excels at developing and implementing targeted safety training programs relevant to 's specific operational hazards.",
    languages: ["Mandarin", "Italian", "Spanish", "English"],
    experienceYears: 21,
    profileImage: "https://randomuser.me/api/portraits/men/94.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Maya Knight",
    role: "Hospitality Director",
    department: "Hospitality Department",
    bio: "Overseeing a diverse team, Hospitality Director Knight implements innovative service strategies and maintains the highest quality standards, reflecting 15 years in the industry.",
    languages: ["Portuguese", "Japanese", "English"],
    experienceYears: 15,
    profileImage: "https://randomuser.me/api/portraits/women/74.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Michael Porter",
    role: "Guest Relations Manager",
    department: "Hospitality Department",
    bio: "Guest Relations Manager Porter is adept at handling complex guest inquiries and ensuring swift, satisfactory resolutions, fostering loyalty and positive experiences.",
    languages: ["Italian", "Russian", "Portuguese", "English"],
    experienceYears: 4,
    profileImage: "https://randomuser.me/api/portraits/men/97.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Ella Hayes",
    role: "Chief Steward",
    department: "Hospitality Department",
    bio: "Chief Steward Hayes supervises housekeeping and guest services with 13 years of maritime hospitality experience.",
    languages: ["Arabic", "Japanese", "Spanish", "Mandarin", "English"],
    experienceYears: 13,
    profileImage: "https://randomuser.me/api/portraits/women/9.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Albert Wells",
    role: "Senior Steward",
    department: "Hospitality Department",
    bio: "With 17 years of dedicated service, Senior Steward Wells ensures guest accommodations are impeccably maintained and personalized to preferences.",
    languages: ["Italian", "Japanese", "Mandarin", "Portuguese", "English"],
    experienceYears: 17,
    profileImage: "https://randomuser.me/api/portraits/men/45.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Alexa Wallace",
    role: "Butler",
    department: "Hospitality Department",
    bio: "With discreet professionalism honed over 9 years, Butler Wallace offers bespoke services, including in-suite dining, wardrobe management, and personalized arrangements.",
    languages: ["German", "Arabic", "Japanese", "Russian", "English"],
    experienceYears: 9,
    profileImage: "https://randomuser.me/api/portraits/women/95.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Hannah Montgomery",
    role: "Accommodation Manager",
    department: "Hospitality Department",
    bio: "Hannah Montgomery oversees accommodation services, ensuring comfort and efficiency with 21 years in maritime hospitality.",
    languages: ["English", "Russian", "Arabic"],
    experienceYears: 21,
    profileImage: "https://randomuser.me/api/portraits/women/86.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "James Marshall",
    role: "Housekeeping Supervisor",
    department: "Hospitality Department",
    bio: "James Marshall manages daily assignments, motivates the housekeeping team, and ensures efficient use of cleaning resources, drawing on 12 years of leadership.",
    languages: ["Mandarin", "Portuguese", "English"],
    experienceYears: 12,
    profileImage: "https://randomuser.me/api/portraits/men/88.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Miguel Graham",
    role: "Guest Services Specialist",
    department: "Hospitality Department",
    bio: "Miguel Graham's communication skills, honed over 12 years, are key to creating positive first impressions and lasting guest satisfaction.",
    languages: ["German", "French", "Italian", "Arabic", "English"],
    experienceYears: 12,
    profileImage: "https://randomuser.me/api/portraits/men/23.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Elena Hamilton",
    role: "Concierge",
    department: "Hospitality Department",
    bio: "Elena Hamilton leverages 6 years of service to provide exceptional concierge support onboard.",
    languages: ["Japanese", "German", "English"],
    experienceYears: 6,
    profileImage: "https://randomuser.me/api/portraits/women/50.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "James Marshall",
    role: "Front Desk Manager",
    department: "Hospitality Department",
    bio: "Front Desk Manager Marshall oversees reception operations, ensuring efficient guest check-in and issue resolution.",
    languages: ["English", "Spanish", "Portuguese", "Italian", "French"],
    experienceYears: 8,
    profileImage: "https://randomuser.me/api/portraits/men/42.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Barbara Baker",
    role: "VIP Coordinator",
    department: "Hospitality Department",
    bio: "Barbara Baker's expertise over 12 years lies in creating unparalleled experiences, making every VIP guest feel exceptionally valued and pampered.",
    languages: ["Spanish", "Japanese", "English", "Italian"],
    experienceYears: 12,
    profileImage: "https://randomuser.me/api/portraits/women/63.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Jeremy Price",
    role: "Hospitality Trainer",
    department: "Hospitality Department",
    bio: "Jeremy Price conducts needs assessments and measures training effectiveness to ensure continuous improvement across all hospitality departments, reflecting 3 years in adult learning.",
    languages: ["Arabic", "French", "English"],
    experienceYears: 3,
    profileImage: "https://randomuser.me/api/portraits/men/92.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Nancy Warren",
    role: "Executive Chef",
    department: "Culinary Department",
    bio: "Beyond crafting exquisite Japanese, Chef Warren expertly manages kitchen hygiene, inventory, and food cost control, honed over 20 years in demanding culinary environments.",
    languages: ["Arabic", "English"],
    experienceYears: 20,
    profileImage: "https://randomuser.me/api/portraits/women/57.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Jerry Henderson",
    role: "Sous Chef",
    department: "Culinary Department",
    bio: "Jerry Henderson excels in menu execution and team management to maintain high culinary standards.",
    languages: ["Japanese", "Russian", "English"],
    experienceYears: 15,
    profileImage: "https://randomuser.me/api/portraits/men/46.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Stephen Palmer",
    role: "Pastry Chef",
    department: "Culinary Department",
    bio: "Pastry Chef Palmer crafts exquisite desserts with 19 years of baking and pastry artistry.",
    languages: ["Spanish", "Mandarin", "English"],
    experienceYears: 19,
    profileImage: "https://randomuser.me/api/portraits/men/5.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Carol Russell",
    role: "Chef de Partie",
    department: "Culinary Department",
    bio: "Chef de Partie Russell manages specific kitchen stations with 10 years of focused culinary skill.",
    languages: ["Japanese", "Portuguese", "Spanish", "French", "English"],
    experienceYears: 10,
    profileImage: "https://randomuser.me/api/portraits/women/79.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Katherine Dixon",
    role: "Specialty Chef",
    department: "Culinary Department",
    bio: "Specialty Chef Dixon brings innovation and authenticity to the onboard dining experience.",
    languages: ["Arabic", "Portuguese", "English"],
    experienceYears: 11,
    profileImage: "https://randomuser.me/api/portraits/women/64.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Randy Stewart",
    role: "Sushi Chef",
    department: "Culinary Department",
    bio: "Sushi Chef Stewart manages the sushi bar operations, ensuring exceptional quality and presentation, reflecting 16 years of Japanese culinary excellence.",
    languages: ["Italian", "Russian", "English"],
    experienceYears: 16,
    profileImage: "https://randomuser.me/api/portraits/men/16.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Richard West",
    role: "Garde Manger",
    department: "Culinary Department",
    bio: "Garde Manger West expertly prepares cold dishes and appetizers with 20 years of culinary proficiency.",
    languages: ["English", "Italian", "Arabic", "Russian"],
    experienceYears: 20,
    profileImage: "https://randomuser.me/api/portraits/men/87.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Raymond Hudson",
    role: "Butcher",
    department: "Culinary Department",
    bio: "Raymond Hudson is responsible for precise meat cuts that meet kitchen and guest expectations.",
    languages: ["Japanese", "Italian", "French", "English"],
    experienceYears: 6,
    profileImage: "https://randomuser.me/api/portraits/men/45.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Oliver Henderson",
    role: "Baker",
    department: "Culinary Department",
    bio: "Oliver Henderson combines traditional techniques with innovation to delight guests with baked specialties.",
    languages: ["English", "Arabic", "Portuguese", "German"],
    experienceYears: 21,
    profileImage: "https://randomuser.me/api/portraits/men/28.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Luis Payne",
    role: "Sommelier",
    department: "Culinary Department",
    bio: "Sommelier Payne curates wine selections, offering expert pairing advice with 14 years in fine wine service.",
    languages: ["Mandarin", "English", "Japanese"],
    experienceYears: 14,
    profileImage: "https://randomuser.me/api/portraits/men/42.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Olivia Russell",
    role: "Mixologist",
    department: "Culinary Department",
    bio: "Olivia Russell delivers exceptional beverage experiences tailored to guest preferences onboard.",
    languages: ["German", "French", "English"],
    experienceYears: 16,
    profileImage: "https://randomuser.me/api/portraits/women/11.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Scarlett Gibson",
    role: "Barista",
    department: "Culinary Department",
    bio: "Barista Gibson ensures consistently excellent coffee quality, from bean grinding to final pour, reflecting 16 years of dedication to the craft.",
    languages: [
      "German",
      "Spanish",
      "Arabic",
      "Japanese",
      "Mandarin",
      "English",
    ],
    experienceYears: 16,
    profileImage: "https://randomuser.me/api/portraits/women/0.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Kimberly Fisher",
    role: "Nutritionist",
    department: "Culinary Department",
    bio: "Nutritionist Fisher works closely with the culinary team to create wholesome Continental options that are both flavorful and aligned with wellness goals, drawing on 12 years of expertise.",
    languages: ["Russian", "Spanish", "Italian", "German", "English"],
    experienceYears: 12,
    profileImage: "https://randomuser.me/api/portraits/women/34.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Catherine Hunter",
    role: "Entertainment Director",
    department: "Entertainment Department",
    bio: "Catherine Hunter constantly seeks innovative entertainment concepts and top-tier talent, leveraging 7 years to keep the onboard experience fresh, exciting, and memorable.",
    languages: ["French", "Italian", "Portuguese", "Japanese", "English"],
    experienceYears: 7,
    profileImage: "https://randomuser.me/api/portraits/women/31.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Virginia Graham",
    role: "Performance Coordinator",
    department: "Entertainment Department",
    bio: "Performance Coordinator Graham supports talent and technical teams to deliver seamless shows.",
    languages: [
      "Spanish",
      "German",
      "English",
      "Japanese",
      "Portuguese",
      "French",
    ],
    experienceYears: 21,
    profileImage: "https://randomuser.me/api/portraits/women/98.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Sandra Ellis",
    role: "Lead Vocalist",
    department: "Entertainment Department",
    bio: "Lead Vocalist Ellis captivates audiences with dynamic performances, backed by 5 years of professional singing.",
    languages: ["French", "Spanish", "English"],
    experienceYears: 5,
    profileImage: "https://randomuser.me/api/portraits/women/20.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Susan Fisher",
    role: "Musician",
    department: "Entertainment Department",
    bio: "Susan Fisher enriches onboard ambiance through skilled instrumental and vocal performances.",
    languages: ["Arabic", "Portuguese", "Mandarin", "English"],
    experienceYears: 5,
    profileImage: "https://randomuser.me/api/portraits/women/89.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Samantha Gibson",
    role: "Dancer",
    department: "Entertainment Department",
    bio: "Dancer Gibson delivers energetic and polished routines, drawing on 5 years of dance training.",
    languages: ["Italian", "Spanish", "Portuguese", "English"],
    experienceYears: 5,
    profileImage: "https://randomuser.me/api/portraits/women/32.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Lawrence Hamilton",
    role: "Choreographer",
    department: "Entertainment Department",
    bio: "Choreographer Hamilton creates captivating dance routines, blending creativity with 4 years of dance expertise.",
    languages: ["German", "Arabic", "Mandarin", "Spanish", "English"],
    experienceYears: 4,
    profileImage: "https://randomuser.me/api/portraits/men/88.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Patrick West",
    role: "Comedy Performer",
    department: "Entertainment Department",
    bio: "Comedy Performer West masterfully crafts clean and engaging sets suitable for a cruise environment, ensuring evenings are filled with laughter and amusement.",
    languages: ["German", "Italian", "English"],
    experienceYears: 3,
    profileImage: "https://randomuser.me/api/portraits/men/39.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "William Fletcher",
    role: "Magic Act",
    department: "Entertainment Department",
    bio: "William Fletcher blends showmanship and technique to deliver captivating magic shows at sea.",
    languages: ["Arabic", "Russian", "Spanish", "English"],
    experienceYears: 11,
    profileImage: "https://randomuser.me/api/portraits/men/6.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Jerry Hayes",
    role: "DJ",
    department: "Entertainment Department",
    bio: "With an extensive music library and 4 years of reading crowds, DJ Hayes seamlessly blends genres to create the perfect soundtrack for any onboard event or nightclub.",
    languages: ["Mandarin", "Spanish", "Italian", "English"],
    experienceYears: 4,
    profileImage: "https://randomuser.me/api/portraits/men/53.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Oliver Mitchell",
    role: "Audio Technician",
    department: "Entertainment Department",
    bio: "Oliver Mitchell supports entertainment events with technical expertise in live sound engineering.",
    languages: ["Arabic", "Russian", "Japanese", "English"],
    experienceYears: 19,
    profileImage: "https://randomuser.me/api/portraits/men/33.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Willie Mitchell",
    role: "Lighting Specialist",
    department: "Entertainment Department",
    bio: "Lighting Specialist Mitchell designs and operates lighting systems to enhance onboard shows and events.",
    languages: ["Russian", "Spanish", "Japanese", "German", "English"],
    experienceYears: 18,
    profileImage: "https://randomuser.me/api/portraits/men/68.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Rachel Knight",
    role: "Stage Manager",
    department: "Entertainment Department",
    bio: "Rachel Knight's calm under pressure and attention to detail, honed over 22 years, are vital for delivering complex, multi-layered performances without a hitch.",
    languages: ["Italian", "Russian", "Mandarin", "German", "English"],
    experienceYears: 22,
    profileImage: "https://randomuser.me/api/portraits/women/41.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Logan Maxwell",
    role: "Production Manager",
    department: "Entertainment Department",
    bio: "Logan Maxwell ensures timely and efficient delivery of shows, leveraging 17 years in production management.",
    languages: ["French", "Russian", "English"],
    experienceYears: 17,
    profileImage: "https://randomuser.me/api/portraits/men/76.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Anna Payne",
    role: "Costume Designer",
    department: "Entertainment Department",
    bio: "With 10 years of experience in theatrical costume design, Anna Payne conceives and produces stunning wardrobes that define characters and elevate productions.",
    languages: ["French", "English"],
    experienceYears: 10,
    profileImage: "https://randomuser.me/api/portraits/women/20.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Caroline Griffin",
    role: "Cultural Program Director",
    department: "Entertainment Department",
    bio: "Caroline Griffin's passion for cultural exchange, cultivated over 14 years, enriches the voyage by fostering understanding and appreciation of diverse traditions.",
    languages: ["German", "Russian", "English", "French"],
    experienceYears: 14,
    profileImage: "https://randomuser.me/api/portraits/women/15.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Oliver Day",
    role: "Performance Artist",
    department: "Entertainment Department",
    bio: "Performance Artist Day delivers unique and innovative acts, blending multiple disciplines with 11 years of artistic practice.",
    languages: ["Russian", "Mandarin", "Arabic", "English"],
    experienceYears: 11,
    profileImage: "https://randomuser.me/api/portraits/men/66.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Austin Lawson",
    role: "Operations Manager",
    department: "Operations Department",
    bio: "Operations Manager Lawson applies 15 years of leadership in maritime operations.",
    languages: ["German", "Portuguese", "English"],
    experienceYears: 15,
    profileImage: "https://randomuser.me/api/portraits/men/85.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Grace Campbell",
    role: "Logistics Coordinator",
    department: "Operations Department",
    bio: "Logistics Coordinator Campbell meticulously plans and tracks shipments, manages customs documentation, and optimizes storage solutions onboard.",
    languages: ["Russian", "Portuguese", "German", "Italian", "English"],
    experienceYears: 4,
    profileImage: "https://randomuser.me/api/portraits/women/41.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Jonathan Dixon",
    role: "Inventory Specialist",
    department: "Operations Department",
    bio: "Jonathan Dixon's analytical skills, honed over 9 years, are key to forecasting demand and optimizing stock levels across various departments.",
    languages: ["Italian", "Japanese", "French", "Arabic", "English"],
    experienceYears: 9,
    profileImage: "https://randomuser.me/api/portraits/men/24.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Carlos Henderson",
    role: "Procurement Officer",
    department: "Operations Department",
    bio: "Carlos Henderson applies expertise in vendor management and cost optimization to benefit ship operations.",
    languages: ["French", "Japanese", "Italian", "English"],
    experienceYears: 21,
    profileImage: "https://randomuser.me/api/portraits/men/45.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
  {
    name: "Susan Curtis",
    role: "Sustainability Coordinator",
    department: "Operations Department",
    bio: "Susan Curtis promotes sustainable practices aligned with maritime environmental standards.",
    languages: ["Arabic", "English", "German", "Portuguese"],
    experienceYears: 9,
    profileImage: "https://randomuser.me/api/portraits/women/14.jpg",
    city: "Ho Chi Minh City",
    country: "",
    region: "",
  },
];
