import { CrewMember } from "@/lib/interfaces/people/staff";

export const ketchikanTeamMembers: CrewMember[] = [
  {
    name: "Terry Knight",
    role: "Captain",
    department: "Deck Department",
    bio: "Captain Knight's strategic decision-making and crisis management skills, honed over 14 years, ensure smooth and safe voyages throughout .",
    languages: ["Japanese", "Russian", "Arabic", "English"],
    experienceYears: 14,
    profileImage: "https://randomuser.me/api/portraits/men/82.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Frank Clark",
    role: "First Officer",
    department: "Deck Department",
    bio: "Frank Clark specializes in  navigation with 19 years of experience managing bridge operations and ensuring adherence to safety standards.",
    languages: ["French", "English"],
    experienceYears: 19,
    profileImage: "https://randomuser.me/api/portraits/men/39.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Gabriella Griffin",
    role: "Second Officer",
    department: "Deck Department",
    bio: "Gabriella Griffin ensures compliance with navigation protocols and supports bridge team operations, leveraging 3 years in maritime operations across .",
    languages: ["English", "Mandarin", "French", "Spanish"],
    experienceYears: 3,
    profileImage: "https://randomuser.me/api/portraits/women/40.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Eleanor Bennett",
    role: "Third Officer",
    department: "Deck Department",
    bio: "Third Officer Bennett conducts regular safety inspections and coordinates emergency drills, enhancing onboard security across .",
    languages: ["Arabic", "Japanese", "Spanish", "German", "English"],
    experienceYears: 6,
    profileImage: "https://randomuser.me/api/portraits/women/28.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Genesis Foster",
    role: "Navigation Officer",
    department: "Deck Department",
    bio: "Navigation Officer Foster ensures all navigational equipment is calibrated and fully operational, leveraging 22 years of technical expertise in .",
    languages: ["Arabic", "Portuguese", "Italian", "English"],
    experienceYears: 22,
    profileImage: "https://randomuser.me/api/portraits/women/34.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Victoria Curtis",
    role: "Safety Officer",
    department: "Deck Department",
    bio: "Safety Officer Curtis documents incidents and implements corrective actions to continuously improve onboard safety performance.",
    languages: ["German", "English", "French", "Arabic", "Russian"],
    experienceYears: 12,
    profileImage: "https://randomuser.me/api/portraits/women/86.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Jason Hudson",
    role: "Deck Cadet",
    department: "Deck Department",
    bio: "Eager to learn, Deck Cadet Jason Hudson diligently assists with bridge duties and deck maintenance tasks, absorbing essential skills for navigating .",
    languages: ["English", "Italian", "Japanese"],
    experienceYears: 3,
    profileImage: "https://randomuser.me/api/portraits/men/19.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Carol Payne",
    role: "Bosun",
    department: "Deck Department",
    bio: "Bosun Payne maintains the vessel's exterior appearance and structural integrity, a testament to 12 years of dedication in .",
    languages: ["Italian", "Japanese", "Mandarin", "English"],
    experienceYears: 12,
    profileImage: "https://randomuser.me/api/portraits/women/48.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Chen Collins",
    role: "Chief Engineer",
    department: "Engineering Department",
    bio: "Known for strategic problem-solving, Chen Collins directs all technical operations, balancing safety, performance, and cost-effectiveness aboard vessels.",
    languages: ["Italian", "Japanese", "German", "Spanish", "English"],
    experienceYears: 4,
    profileImage: "https://randomuser.me/api/portraits/men/18.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Justin Cooper",
    role: "First Engineer",
    department: "Engineering Department",
    bio: "Justin Cooper supervises engineering staff during watch shifts, maintaining operational readiness and compliance with maritime safety standards.",
    languages: ["Italian", "Arabic", "German", "Spanish", "English"],
    experienceYears: 4,
    profileImage: "https://randomuser.me/api/portraits/men/80.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Jason Jennings",
    role: "Second Engineer",
    department: "Engineering Department",
    bio: "Jason Jennings's 22 years include supervising junior engineers and engine room ratings, fostering a culture of safety and competence.",
    languages: [
      "Russian",
      "Italian",
      "Japanese",
      "Arabic",
      "Portuguese",
      "English",
    ],
    experienceYears: 22,
    profileImage: "https://randomuser.me/api/portraits/men/52.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Amanda Ellis",
    role: "Electrical Engineer",
    department: "Engineering Department",
    bio: "Amanda Ellis's expertise covers power distribution, electric propulsion components, and emergency backup systems, backed by 7 years in the field.",
    languages: ["German", "Japanese", "French", "Arabic", "English"],
    experienceYears: 7,
    profileImage: "https://randomuser.me/api/portraits/women/42.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Amy Crawford",
    role: "Mechanical Engineer",
    department: "Engineering Department",
    bio: "With 19 years dedicated to marine mechanics, Amy Crawford excels in the overhaul and alignment of engines and rotating machinery.",
    languages: ["English", "French", "Arabic", "Spanish"],
    experienceYears: 19,
    profileImage: "https://randomuser.me/api/portraits/women/10.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Janet Payne",
    role: "HVAC Engineer",
    department: "Engineering Department",
    bio: "Janet Payne monitors system performance and implements upgrades to enhance passenger comfort and crew wellbeing.",
    languages: ["French", "Japanese", "English", "Spanish"],
    experienceYears: 10,
    profileImage: "https://randomuser.me/api/portraits/women/37.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Emma Hawkins",
    role: "Environmental Engineer",
    department: "Engineering Department",
    bio: "Emma Hawkins applies expertise in waste management, ballast water treatment, and pollution control, promoting eco-friendly maritime operations.",
    languages: ["Russian", "English", "Spanish", "Arabic"],
    experienceYears: 8,
    profileImage: "https://randomuser.me/api/portraits/women/34.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Layla Jennings",
    role: "Systems Engineer",
    department: "Engineering Department",
    bio: "Layla Jennings integrates complex onboard systems, ensuring operational synergy and reliability with 12 years of maritime engineering expertise.",
    languages: ["Japanese", "Spanish", "English"],
    experienceYears: 12,
    profileImage: "https://randomuser.me/api/portraits/women/17.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Paul Palmer",
    role: "Technical Manager",
    department: "Engineering Department",
    bio: "With 10 years leading technical teams, Paul Palmer ensures vessel systems meet all regulatory, safety, and performance standards.",
    languages: ["French", "German", "Portuguese", "Japanese", "English"],
    experienceYears: 10,
    profileImage: "https://randomuser.me/api/portraits/men/29.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Harry Hall",
    role: "Maintenance Engineer",
    department: "Engineering Department",
    bio: "Maintenance Engineer Hall troubleshoots system faults and implements timely repairs, maintaining vessel operational readiness.",
    languages: [
      "Russian",
      "Japanese",
      "Spanish",
      "French",
      "German",
      "English",
    ],
    experienceYears: 20,
    profileImage: "https://randomuser.me/api/portraits/men/34.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Jessica Clark",
    role: "Security Director",
    department: "Security Department",
    bio: "Drawing on 18 years and a investigations background, Jessica Clark develops and executes sophisticated security plans tailored to high-risk maritime environments.",
    languages: ["Italian", "French", "Russian", "English"],
    experienceYears: 18,
    profileImage: "https://randomuser.me/api/portraits/women/8.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Matthew Douglas",
    role: "Security Officer",
    department: "Security Department",
    bio: "Security Officer Douglas is proficient in emergency communication procedures and crowd management, vital skills honed over 5 years.",
    languages: ["Russian", "Italian", "English", "Spanish"],
    experienceYears: 5,
    profileImage: "https://randomuser.me/api/portraits/men/95.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Maria West",
    role: "Security Specialist",
    department: "Security Department",
    bio: "Maria West's 14 years include proficiency in evidence collection and report writing for maritime security incidents.",
    languages: ["Mandarin", "Japanese", "English"],
    experienceYears: 14,
    profileImage: "https://randomuser.me/api/portraits/women/8.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Thandiwe Price",
    role: "Cybersecurity Officer",
    department: "Security Department",
    bio: "Cybersecurity Officer Price conducts regular penetration testing and vulnerability assessments of ship systems, drawing on 10 years of expertise.",
    languages: ["Japanese", "Arabic", "English"],
    experienceYears: 10,
    profileImage: "https://randomuser.me/api/portraits/women/53.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Deborah Knight",
    role: "Maritime Security Coordinator",
    department: "Security Department",
    bio: "Maritime Security Coordinator Knight facilitates seamless security operations between ship and shore, a skill honed over 15 years of dedicated service.",
    languages: [
      "French",
      "German",
      "Mandarin",
      "Japanese",
      "Portuguese",
      "English",
    ],
    experienceYears: 15,
    profileImage: "https://randomuser.me/api/portraits/women/67.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Amy Lawson",
    role: "Access Control Officer",
    department: "Security Department",
    bio: "Amy Lawson ensures all personnel and visitors comply with security clearance, manifests, and international maritime access regulations.",
    languages: ["Italian", "Mandarin", "Russian", "Spanish", "English"],
    experienceYears: 10,
    profileImage: "https://randomuser.me/api/portraits/women/10.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Emily Spencer",
    role: "Safety Compliance Officer",
    department: "Security Department",
    bio: "Emily Spencer works closely with regulatory bodies to ensure the vessel meets all international safety conventions and company policies.",
    languages: ["German", "Italian", "English"],
    experienceYears: 16,
    profileImage: "https://randomuser.me/api/portraits/women/17.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Virginia Chambers",
    role: "Youth Program Director",
    department: "Youth & Family Programs",
    bio: "With 15 years shaping children's experiences at sea, Virginia Chambers excels at creating memorable and enriching programs for all age groups.",
    languages: [
      "Japanese",
      "Portuguese",
      "Spanish",
      "Italian",
      "Arabic",
      "Russian",
      "English",
    ],
    experienceYears: 15,
    profileImage: "https://randomuser.me/api/portraits/women/76.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Randy Palmer",
    role: "Family Activities Coordinator",
    department: "Youth & Family Programs",
    bio: "Randy Palmer, with 17 years of experience, excels in logistics and planning, ensuring every family event runs smoothly and delights guests.",
    languages: ["English", "Mandarin"],
    experienceYears: 17,
    profileImage: "https://randomuser.me/api/portraits/men/5.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Keith West",
    role: "Children's Entertainment Specialist",
    department: "Youth & Family Programs",
    bio: "Drawing on 14 years of delighting young audiences, Keith West brings a unique blend of magic, storytelling, and interactive games to the ship.",
    languages: ["Russian", "Italian", "Japanese", "Arabic", "English"],
    experienceYears: 14,
    profileImage: "https://randomuser.me/api/portraits/men/86.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Stephanie Warren",
    role: "Teen Activities Coordinator",
    department: "Youth & Family Programs",
    bio: "Stephanie Warren develops dynamic programs catering to teenage guests, drawing on 11 years of youth facilitation and event management expertise.",
    languages: ["Italian", "French", "Mandarin", "English"],
    experienceYears: 11,
    profileImage: "https://randomuser.me/api/portraits/women/8.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Roger Murray",
    role: "Educational Program Manager",
    department: "Youth & Family Programs",
    bio: "Known for strong organizational skills, Roger Murray evaluates program effectiveness and implements improvements based on passenger feedback.",
    languages: ["Arabic", "English"],
    experienceYears: 7,
    profileImage: "https://randomuser.me/api/portraits/men/41.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Diego Montgomery",
    role: "Child Care Specialist",
    department: "Youth & Family Programs",
    bio: "Child Care Specialist Montgomery ensures safety, comfort, and developmentally appropriate activities in a nurturing onboard environment.",
    languages: ["Japanese", "Portuguese", "English"],
    experienceYears: 10,
    profileImage: "https://randomuser.me/api/portraits/men/82.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Jose Collins",
    role: "Activities Director",
    department: "Activities & Recreation",
    bio: "Known for innovative programming, Jose Collins continuously evaluates activity trends and passenger feedback to refresh and improve offerings.",
    languages: ["Portuguese", "Spanish", "German", "Mandarin", "English"],
    experienceYears: 17,
    profileImage: "https://randomuser.me/api/portraits/men/45.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Amanda Morgan",
    role: "Water Sports Instructor",
    department: "Activities & Recreation",
    bio: "With expertise in various water sports, Amanda Morgan provides personalized coaching that accommodates different skill levels and abilities.",
    languages: ["English", "Russian"],
    experienceYears: 14,
    profileImage: "https://randomuser.me/api/portraits/women/92.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Eric Palmer",
    role: "Fitness Instructor",
    department: "Activities & Recreation",
    bio: "Fitness Instructor Palmer integrates modern fitness trends and equipment to provide dynamic and effective workout options.",
    languages: ["Italian", "Japanese", "English"],
    experienceYears: 21,
    profileImage: "https://randomuser.me/api/portraits/men/81.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Ariana Spencer",
    role: "Excursion Coordinator",
    department: "Activities & Recreation",
    bio: "Excursion Coordinator Spencer prioritizes compliance with local regulations and emergency preparedness during all shore activities.",
    languages: ["Portuguese", "French", "Mandarin", "Spanish", "English"],
    experienceYears: 5,
    profileImage: "https://randomuser.me/api/portraits/women/67.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Christine Dunn",
    role: "Lead Photographer",
    department: "Photography & Videography",
    bio: "Lead Photographer Dunn's portfolio showcases 21 years of diverse work, including breathtaking drone shots and artistic compositions from around the world.",
    languages: ["Portuguese", "Italian", "English", "Spanish", "Arabic"],
    experienceYears: 21,
    profileImage: "https://randomuser.me/api/portraits/women/48.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Joe Nash",
    role: "Videographer",
    department: "Photography & Videography",
    bio: "With a strong understanding of narrative flow and audience engagement, Joe Nash produces videos for promotional and archival purposes.",
    languages: ["Spanish", "German", "Italian", "English"],
    experienceYears: 22,
    profileImage: "https://randomuser.me/api/portraits/men/75.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Frank Mason",
    role: "Digital Media Specialist",
    department: "Photography & Videography",
    bio: "Frank Mason manages digital content and multimedia production, applying 14 years in digital media, marketing, and audience engagement strategies.",
    languages: ["English", "German"],
    experienceYears: 14,
    profileImage: "https://randomuser.me/api/portraits/men/70.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Larry Wells",
    role: "Chief Medical Officer",
    department: "Health & Safety",
    bio: "Committed to preventive care, Larry Wells promotes health education and wellness initiatives throughout the voyage.",
    languages: ["Japanese", "Russian", "Arabic", "English"],
    experienceYears: 7,
    profileImage: "https://randomuser.me/api/portraits/men/87.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Gabriel Lawson",
    role: "Ship's Doctor",
    department: "Health & Safety",
    bio: "With specialization in emergency response, preventative medicine, and maritime health protocols, Dr. Lawson ensures passenger and crew safety.",
    languages: ["Italian", "German", "Portuguese", "Arabic", "English"],
    experienceYears: 7,
    profileImage: "https://randomuser.me/api/portraits/men/75.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Cynthia Fletcher",
    role: "Nurse",
    department: "Health & Safety",
    bio: "Cynthia Fletcher delivers compassionate nursing care onboard, backed by 7 years of clinical practice in maritime and travel healthcare settings.",
    languages: [
      "Portuguese",
      "Italian",
      "Spanish",
      "Arabic",
      "Mandarin",
      "English",
    ],
    experienceYears: 7,
    profileImage: "https://randomuser.me/api/portraits/women/34.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "George Price",
    role: "Safety Officer",
    department: "Health & Safety",
    bio: "With 19 years overseeing maritime safety, George Price ensures strict adherence to international safety regulations (SOLAS, MARPOL) and promotes a culture of vigilance onboard vessels operating in .",
    languages: ["Spanish", "English", "Mandarin"],
    experienceYears: 19,
    profileImage: "https://randomuser.me/api/portraits/men/29.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Philip Maxwell",
    role: "Hospitality Director",
    department: "Hospitality Department",
    bio: "Philip Maxwell manages all hospitality services, ensuring exceptional guest experiences with 11 years of leadership.",
    languages: ["English", "Russian", "Italian", "Portuguese"],
    experienceYears: 11,
    profileImage: "https://randomuser.me/api/portraits/men/1.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Nomsa Griffin",
    role: "Guest Relations Manager",
    department: "Hospitality Department",
    bio: "Nomsa Griffin champions a guest-first culture, utilizing 8 years of experience to train and motivate staff in delivering exceptional, personalized care.",
    languages: ["Japanese", "French", "English"],
    experienceYears: 8,
    profileImage: "https://randomuser.me/api/portraits/women/46.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Samantha Graham",
    role: "Chief Steward",
    department: "Hospitality Department",
    bio: "With 14 years leading stewardship teams, Chief Steward Graham meticulously manages cabin services, laundry operations, and public area upkeep.",
    languages: ["Russian", "Portuguese", "English"],
    experienceYears: 14,
    profileImage: "https://randomuser.me/api/portraits/women/61.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "George Bennett",
    role: "Senior Steward",
    department: "Hospitality Department",
    bio: "With 18 years of dedicated service, Senior Steward Bennett ensures guest accommodations are impeccably maintained and personalized to preferences.",
    languages: ["French", "Italian", "Spanish", "Japanese", "English"],
    experienceYears: 18,
    profileImage: "https://randomuser.me/api/portraits/men/82.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Juan Henderson",
    role: "Butler",
    department: "Hospitality Department",
    bio: "Butler Henderson provides personalized guest services, backed by 22 years of elite hospitality expertise.",
    languages: ["Mandarin", "Russian", "German", "English"],
    experienceYears: 22,
    profileImage: "https://randomuser.me/api/portraits/men/54.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Amelia Reeves",
    role: "Accommodation Manager",
    department: "Hospitality Department",
    bio: "Amelia Reeves expertly handles guest feedback regarding accommodations, implementing swift solutions and driving continuous improvement based on 11 years of experience.",
    languages: ["Japanese", "Italian", "English"],
    experienceYears: 11,
    profileImage: "https://randomuser.me/api/portraits/women/9.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Paul Hall",
    role: "Housekeeping Supervisor",
    department: "Hospitality Department",
    bio: "Housekeeping Supervisor Hall is committed to sustainability in cleaning practices, implementing eco-friendly procedures throughout their 6 years of service.",
    languages: ["German", "Arabic", "English"],
    experienceYears: 6,
    profileImage: "https://randomuser.me/api/portraits/men/47.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Nicole Warren",
    role: "Guest Services Specialist",
    department: "Hospitality Department",
    bio: "Nicole Warren assists guests with inquiries and special requests, drawing on 19 years in customer service roles.",
    languages: ["English", "Spanish", "German", "French"],
    experienceYears: 19,
    profileImage: "https://randomuser.me/api/portraits/women/77.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Amelia Dixon",
    role: "Concierge",
    department: "Hospitality Department",
    bio: "Amelia Dixon acts as a personal guide to onboard and onshore experiences, providing insider tips and tailored advice to create unique memories for guests.",
    languages: ["German", "Portuguese", "Mandarin", "English"],
    experienceYears: 11,
    profileImage: "https://randomuser.me/api/portraits/women/6.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Amelia Marshall",
    role: "Front Desk Manager",
    department: "Hospitality Department",
    bio: "Front Desk Manager Marshall oversees reception operations, ensuring efficient guest check-in and issue resolution.",
    languages: ["Mandarin", "French", "Italian", "English"],
    experienceYears: 20,
    profileImage: "https://randomuser.me/api/portraits/women/94.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Michael Jennings",
    role: "VIP Coordinator",
    department: "Hospitality Department",
    bio: "Michael Jennings's expertise over 12 years lies in creating unparalleled experiences, making every VIP guest feel exceptionally valued and pampered.",
    languages: ["Portuguese", "English", "Russian", "Japanese"],
    experienceYears: 12,
    profileImage: "https://randomuser.me/api/portraits/men/80.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Kinsley Jennings",
    role: "Hospitality Trainer",
    department: "Hospitality Department",
    bio: "Hospitality Trainer Jennings specializes in areas like luxury service standards, complaint resolution, and upselling techniques, drawing on 20 years of industry best practices.",
    languages: ["Portuguese", "Russian", "English"],
    experienceYears: 20,
    profileImage: "https://randomuser.me/api/portraits/women/15.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Jeremy Price",
    role: "Executive Chef",
    department: "Culinary Department",
    bio: "Mastering Caribbean and international gastronomy, Jeremy Price ensures every dish reflects the highest standards of quality, presentation, and flavor, backed by 6 years of award-winning experience.",
    languages: ["Spanish", "Russian", "English"],
    experienceYears: 6,
    profileImage: "https://randomuser.me/api/portraits/men/61.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Christine Hall",
    role: "Sous Chef",
    department: "Culinary Department",
    bio: "As second-in-command, Sous Chef Hall ensures seamless kitchen workflow and consistent dish quality, drawing on 5 years of hands-on Pacific Rim experience.",
    languages: ["Italian", "German", "Mandarin", "English"],
    experienceYears: 5,
    profileImage: "https://randomuser.me/api/portraits/women/14.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Joseph Day",
    role: "Pastry Chef",
    department: "Culinary Department",
    bio: "Joseph Day blends creativity and technique to deliver memorable pastry experiences for guests.",
    languages: ["Arabic", "Portuguese", "Italian", "English"],
    experienceYears: 9,
    profileImage: "https://randomuser.me/api/portraits/men/46.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Anthony Spencer",
    role: "Chef de Partie",
    department: "Culinary Department",
    bio: "Anthony Spencer ensures consistency and quality in dish preparation across assigned kitchen areas.",
    languages: ["Portuguese", "German", "Spanish", "English"],
    experienceYears: 5,
    profileImage: "https://randomuser.me/api/portraits/men/62.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Terry Montgomery",
    role: "Specialty Chef",
    department: "Culinary Department",
    bio: "Terry Montgomery specializes in unique culinary styles, offering guests diverse flavors based on 15 years of expertise.",
    languages: ["French", "English", "Spanish", "German"],
    experienceYears: 15,
    profileImage: "https://randomuser.me/api/portraits/men/1.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Brooklyn Harper",
    role: "Sushi Chef",
    department: "Culinary Department",
    bio: "Brooklyn Harper delights guests with traditional Edomae-style sushi and contemporary maki rolls, showcasing skills honed over 6 years of rigorous training.",
    languages: ["German", "Russian", "English"],
    experienceYears: 6,
    profileImage: "https://randomuser.me/api/portraits/women/57.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Mark Mason",
    role: "Garde Manger",
    department: "Culinary Department",
    bio: "Garde Manger Mason expertly prepares cold dishes and appetizers with 15 years of culinary proficiency.",
    languages: ["Arabic", "Italian", "Russian", "English"],
    experienceYears: 15,
    profileImage: "https://randomuser.me/api/portraits/men/35.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Carol Lawson",
    role: "Butcher",
    department: "Culinary Department",
    bio: "With 5 years of expertise, Butcher Lawson expertly handles all meat and poultry, providing custom cuts and ensuring optimal yield for various Japanese dishes.",
    languages: ["Mandarin", "Portuguese", "Italian", "English"],
    experienceYears: 5,
    profileImage: "https://randomuser.me/api/portraits/women/4.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Bobby Hayes",
    role: "Baker",
    department: "Culinary Department",
    bio: "Bobby Hayes combines traditional techniques with innovation to delight guests with baked specialties.",
    languages: [
      "Spanish",
      "Italian",
      "Japanese",
      "Mandarin",
      "French",
      "Portuguese",
      "English",
    ],
    experienceYears: 19,
    profileImage: "https://randomuser.me/api/portraits/men/92.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Dorothy Harper",
    role: "Sommelier",
    department: "Culinary Department",
    bio: "Dorothy Harper enhances dining experiences by sourcing and recommending premium wines.",
    languages: ["French", "English", "Mandarin", "Spanish", "Portuguese"],
    experienceYears: 19,
    profileImage: "https://randomuser.me/api/portraits/women/58.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Justin Douglas",
    role: "Mixologist",
    department: "Culinary Department",
    bio: "With 8 years behind the bar, Justin Douglas designs innovative signature cocktails and perfectly executes classic recipes using premium spirits and fresh ingredients.",
    languages: ["Mandarin", "Italian", "English"],
    experienceYears: 8,
    profileImage: "https://randomuser.me/api/portraits/men/88.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Carol Mason",
    role: "Barista",
    department: "Culinary Department",
    bio: "Barista Mason prepares specialty coffees with precision, backed by 7 years in coffee service.",
    languages: ["Arabic", "Russian", "German", "English"],
    experienceYears: 7,
    profileImage: "https://randomuser.me/api/portraits/women/67.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Isabella Cooper",
    role: "Nutritionist",
    department: "Culinary Department",
    bio: "Isabella Cooper collaborates with chefs to ensure nutritious and delicious meal options onboard.",
    languages: ["French", "Russian", "Mandarin", "English"],
    experienceYears: 14,
    profileImage: "https://randomuser.me/api/portraits/women/97.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Miguel Baker",
    role: "Entertainment Director",
    department: "Entertainment Department",
    bio: "Miguel Baker plans and oversees all entertainment activities, applying 18 years of event and talent management.",
    languages: ["Arabic", "Portuguese", "Mandarin", "Japanese", "English"],
    experienceYears: 18,
    profileImage: "https://randomuser.me/api/portraits/men/18.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Ariana Griffin",
    role: "Performance Coordinator",
    department: "Entertainment Department",
    bio: "Ariana Griffin's organizational skills, honed over 18 years, are crucial for maintaining a complex entertainment calendar and ensuring all performers are well-supported.",
    languages: ["Japanese", "German", "English"],
    experienceYears: 18,
    profileImage: "https://randomuser.me/api/portraits/women/39.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Peter Curtis",
    role: "Lead Vocalist",
    department: "Entertainment Department",
    bio: "Lead Vocalist Curtis captivates audiences with dynamic performances, backed by 12 years of professional singing.",
    languages: ["Japanese", "Italian", "Arabic", "Portuguese", "English"],
    experienceYears: 12,
    profileImage: "https://randomuser.me/api/portraits/men/25.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Mason Fisher",
    role: "Musician",
    department: "Entertainment Department",
    bio: "Musician Fisher adapts their repertoire to suit different moods and themes, from relaxing background melodies to upbeat sets, drawing on 4 years of diverse musical experience.",
    languages: ["English", "Russian"],
    experienceYears: 4,
    profileImage: "https://randomuser.me/api/portraits/men/57.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Robert Graham",
    role: "Dancer",
    department: "Entertainment Department",
    bio: "Dancer Graham brings dynamism and grace to every performance, captivating audiences with technical skill and expressive movement honed over 5 years.",
    languages: ["Arabic", "English", "German", "French"],
    experienceYears: 5,
    profileImage: "https://randomuser.me/api/portraits/men/64.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Gregory Parker",
    role: "Choreographer",
    department: "Entertainment Department",
    bio: "Choreographer Parker creates captivating dance routines, blending creativity with 18 years of dance expertise.",
    languages: ["Italian", "Arabic", "Mandarin", "English"],
    experienceYears: 18,
    profileImage: "https://randomuser.me/api/portraits/men/77.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Joan Crawford",
    role: "Comedy Performer",
    department: "Entertainment Department",
    bio: "Comedy Performer Crawford masterfully crafts clean and engaging sets suitable for a cruise environment, ensuring evenings are filled with laughter and amusement.",
    languages: ["French", "English", "Arabic", "Russian", "Mandarin"],
    experienceYears: 11,
    profileImage: "https://randomuser.me/api/portraits/women/81.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Aaliyah Price",
    role: "Magic Act",
    department: "Entertainment Department",
    bio: "Aaliyah Price brings a unique brand of enchantment to the ship's entertainment, drawing on 16 years of professional magic and a flair for theatrical presentation.",
    languages: ["French", "German", "English"],
    experienceYears: 16,
    profileImage: "https://randomuser.me/api/portraits/women/49.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Raymond Price",
    role: "DJ",
    department: "Entertainment Department",
    bio: "DJ Price creates vibrant atmospheres with expertly mixed music, drawing on 8 years in live DJing.",
    languages: ["Japanese", "Portuguese", "English"],
    experienceYears: 8,
    profileImage: "https://randomuser.me/api/portraits/men/82.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Angela Wallace",
    role: "Audio Technician",
    department: "Entertainment Department",
    bio: "Angela Wallace's keen ear and technical proficiency, developed over 20 years, are essential for delivering immersive and high-quality auditory experiences.",
    languages: [
      "Japanese",
      "Italian",
      "French",
      "German",
      "Portuguese",
      "English",
    ],
    experienceYears: 20,
    profileImage: "https://randomuser.me/api/portraits/women/47.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Nicole Wallace",
    role: "Lighting Specialist",
    department: "Entertainment Department",
    bio: "Nicole Wallace applies 3 years of technical skill to create immersive visual experiences.",
    languages: ["English", "Russian", "Italian", "Portuguese"],
    experienceYears: 3,
    profileImage: "https://randomuser.me/api/portraits/women/24.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Steven Crawford",
    role: "Stage Manager",
    department: "Entertainment Department",
    bio: "Steven Crawford supervises stage operations and talent, drawing on 21 years of event management.",
    languages: ["German", "Mandarin", "Japanese", "French", "English"],
    experienceYears: 21,
    profileImage: "https://randomuser.me/api/portraits/men/27.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Caroline Morgan",
    role: "Production Manager",
    department: "Entertainment Department",
    bio: "Caroline Morgan ensures timely and efficient delivery of shows, leveraging 13 years in production management.",
    languages: ["Italian", "Mandarin", "English"],
    experienceYears: 13,
    profileImage: "https://randomuser.me/api/portraits/women/57.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Vincent Russell",
    role: "Costume Designer",
    department: "Entertainment Department",
    bio: "With 20 years of experience in theatrical costume design, Vincent Russell conceives and produces stunning wardrobes that define characters and elevate productions.",
    languages: ["Italian", "Spanish", "English", "German"],
    experienceYears: 20,
    profileImage: "https://randomuser.me/api/portraits/men/17.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Roy Dixon",
    role: "Cultural Program Director",
    department: "Entertainment Department",
    bio: "Cultural Program Director Dixon collaborates with local artists, historians, and experts to provide authentic and immersive cultural experiences for guests.",
    languages: [
      "Russian",
      "Portuguese",
      "German",
      "English",
      "Arabic",
      "Spanish",
    ],
    experienceYears: 9,
    profileImage: "https://randomuser.me/api/portraits/men/29.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Savannah Campbell",
    role: "Performance Artist",
    department: "Entertainment Department",
    bio: "Performance Artist Campbell combines elements of {artisticDisciplineCombination} to create truly unique and memorable entertainment experiences for discerning audiences.",
    languages: ["Japanese", "English", "Russian"],
    experienceYears: 11,
    profileImage: "https://randomuser.me/api/portraits/women/96.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Elijah Bennett",
    role: "Operations Manager",
    department: "Operations Department",
    bio: "Elijah Bennett plays a crucial role in port operations coordination, safety compliance oversight, and emergency response planning, backed by 18 years of maritime expertise.",
    languages: ["French", "Arabic", "Italian", "Spanish", "English"],
    experienceYears: 18,
    profileImage: "https://randomuser.me/api/portraits/men/48.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Jennifer Maxwell",
    role: "Logistics Coordinator",
    department: "Operations Department",
    bio: "With 15 years coordinating complex supply chains, Jennifer Maxwell ensures timely delivery of provisions, spare parts, and equipment essential for uninterrupted voyages.",
    languages: ["Russian", "Japanese", "Mandarin", "English", "Spanish"],
    experienceYears: 15,
    profileImage: "https://randomuser.me/api/portraits/women/42.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Christopher Hawkins",
    role: "Inventory Specialist",
    department: "Operations Department",
    bio: "Inventory Specialist Hawkins implements efficient stock rotation (FIFO) and conducts regular audits to prevent shortages and minimize waste.",
    languages: ["German", "English", "French", "Russian"],
    experienceYears: 22,
    profileImage: "https://randomuser.me/api/portraits/men/78.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Nicholas Watson",
    role: "Procurement Officer",
    department: "Operations Department",
    bio: "Nicholas Watson's sharp negotiation skills and 15 years of experience contribute significantly to controlling operational costs while maintaining quality standards.",
    languages: ["Arabic", "Portuguese", "German", "Japanese", "English"],
    experienceYears: 15,
    profileImage: "https://randomuser.me/api/portraits/men/3.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
  {
    name: "Albert Spencer",
    role: "Sustainability Coordinator",
    department: "Operations Department",
    bio: "Sustainability Coordinator Spencer implements green initiatives to minimize environmental impact.",
    languages: ["German", "Arabic", "English", "Russian"],
    experienceYears: 14,
    profileImage: "https://randomuser.me/api/portraits/men/95.jpg",
    city: "Ketchikan",
    country: "",
    region: "",
  },
];
