import { CrewMember } from "@/lib/interfaces/people/staff";

export const kielTeamMembers: CrewMember[] = [
  {
    name: "Rachel Fisher",
    role: "Captain",
    department: "Deck Department",
    bio: "Captain Fisher has navigated the challenging waters of Northern Europe for over 10 years, consistently prioritizing sustainable maritime practices and regulatory compliance.",
    languages: ["Japanese", "Russian", "Mandarin", "German", "English"],
    experienceYears: 10,
    profileImage: "https://randomuser.me/api/portraits/women/73.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Avery Stewart",
    role: "First Officer",
    department: "Deck Department",
    bio: "Avery Stewart specializes in Northern Europe navigation with 10 years of experience managing bridge operations and ensuring adherence to safety standards.",
    languages: ["Arabic", "Japanese", "German", "Russian", "English"],
    experienceYears: 10,
    profileImage: "https://randomuser.me/api/portraits/women/14.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Carol Foster",
    role: "Second Officer",
    department: "Deck Department",
    bio: "With a strong focus on electronic navigation and safety equipment, Carol Foster brings 17 years of experience navigating Northern Europe's challenging routes.",
    languages: ["Russian", "Italian", "German", "Arabic", "English"],
    experienceYears: 17,
    profileImage: "https://randomuser.me/api/portraits/women/83.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Jack Montgomery",
    role: "Third Officer",
    department: "Deck Department",
    bio: "Third Officer Montgomery conducts regular safety inspections and coordinates emergency drills, enhancing onboard security across Northern Europe.",
    languages: ["French", "Italian", "Portuguese", "German", "English"],
    experienceYears: 19,
    profileImage: "https://randomuser.me/api/portraits/men/46.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Eleanor Griffin",
    role: "Navigation Officer",
    department: "Deck Department",
    bio: "Eleanor Griffin utilizes advanced navigational technology with 7 years ensuring precise route planning and safe passage in Northern Europe.",
    languages: ["Mandarin", "Japanese", "English"],
    experienceYears: 7,
    profileImage: "https://randomuser.me/api/portraits/women/16.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Jacob Porter",
    role: "Safety Officer",
    department: "Deck Department",
    bio: "Safety Officer Porter documents incidents and implements corrective actions to continuously improve onboard safety performance.",
    languages: ["Portuguese", "Arabic", "English"],
    experienceYears: 10,
    profileImage: "https://randomuser.me/api/portraits/men/2.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Mason Watson",
    role: "Deck Cadet",
    department: "Deck Department",
    bio: "Mason Watson supports deck crew activities while developing skills in seamanship, navigation, and emergency response tailored to Northern Europe's maritime environment.",
    languages: ["Mandarin", "Russian", "English"],
    experienceYears: 12,
    profileImage: "https://randomuser.me/api/portraits/men/16.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Johnny Collins",
    role: "Bosun",
    department: "Deck Department",
    bio: "Bosun Collins mentors junior deck crew, promoting professional development and adherence to best practices in Northern Europe's maritime industry.",
    languages: [
      "French",
      "Portuguese",
      "Spanish",
      "Italian",
      "German",
      "English",
    ],
    experienceYears: 12,
    profileImage: "https://randomuser.me/api/portraits/men/22.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Darrell West",
    role: "Chief Engineer",
    department: "Engineering Department",
    bio: "Known for strategic problem-solving, Darrell West directs all technical operations, balancing safety, performance, and cost-effectiveness aboard vessels.",
    languages: ["Spanish", "Arabic", "English"],
    experienceYears: 11,
    profileImage: "https://randomuser.me/api/portraits/men/81.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Jack Wallace",
    role: "First Engineer",
    department: "Engineering Department",
    bio: "First Engineer Wallace is responsible for the main propulsion machinery and auxiliary systems, bringing 8 years of hands-on expertise.",
    languages: ["French", "German", "Russian", "Japanese", "English"],
    experienceYears: 8,
    profileImage: "https://randomuser.me/api/portraits/men/49.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Samantha Day",
    role: "Second Engineer",
    department: "Engineering Department",
    bio: "Samantha Day plays an integral role in maintaining fuel efficiency and reducing emissions through optimized machinery operation.",
    languages: ["Arabic", "Spanish", "French", "Russian", "English"],
    experienceYears: 11,
    profileImage: "https://randomuser.me/api/portraits/women/71.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Diego Campbell",
    role: "Electrical Engineer",
    department: "Engineering Department",
    bio: "Drawing on 22 years, Diego Campbell ensures the integrity of high-voltage systems and sophisticated electronic controls throughout the vessel.",
    languages: [
      "Spanish",
      "Arabic",
      "Mandarin",
      "English",
      "Japanese",
      "French",
    ],
    experienceYears: 22,
    profileImage: "https://randomuser.me/api/portraits/men/37.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Valentina Murray",
    role: "Mechanical Engineer",
    department: "Engineering Department",
    bio: "With 7 years dedicated to marine mechanics, Valentina Murray excels in the overhaul and alignment of engines and rotating machinery.",
    languages: [
      "Italian",
      "Portuguese",
      "Arabic",
      "Japanese",
      "Russian",
      "English",
    ],
    experienceYears: 7,
    profileImage: "https://randomuser.me/api/portraits/women/13.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Roy Watson",
    role: "HVAC Engineer",
    department: "Engineering Department",
    bio: "Roy Watson plays a key role in energy conservation by optimizing HVAC operations, backed by 22 years of specialized experience.",
    languages: ["French", "Japanese", "English"],
    experienceYears: 22,
    profileImage: "https://randomuser.me/api/portraits/men/62.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Angela Harper",
    role: "Environmental Engineer",
    department: "Engineering Department",
    bio: "Environmental Engineer Harper monitors emissions and advises on strategies to minimize the vessel’s environmental footprint.",
    languages: ["Spanish", "Arabic", "English", "French"],
    experienceYears: 10,
    profileImage: "https://randomuser.me/api/portraits/women/40.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Jerry Price",
    role: "Systems Engineer",
    department: "Engineering Department",
    bio: "Jerry Price is pivotal in troubleshooting and resolving complex issues across interconnected electronic and control systems, thanks to 8 years of in-depth experience.",
    languages: [
      "Spanish",
      "Russian",
      "Italian",
      "French",
      "Mandarin",
      "English",
    ],
    experienceYears: 8,
    profileImage: "https://randomuser.me/api/portraits/men/66.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Margaret Maxwell",
    role: "Technical Manager",
    department: "Engineering Department",
    bio: "With 21 years leading technical teams, Margaret Maxwell ensures vessel systems meet all regulatory, safety, and performance standards.",
    languages: ["Arabic", "Italian", "English", "Mandarin"],
    experienceYears: 21,
    profileImage: "https://randomuser.me/api/portraits/women/68.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Riley Wells",
    role: "Maintenance Engineer",
    department: "Engineering Department",
    bio: "Riley Wells meticulously documents all maintenance activities, ensuring a comprehensive history for all critical machinery, built over 17 years of service.",
    languages: ["Mandarin", "Russian", "French", "English"],
    experienceYears: 17,
    profileImage: "https://randomuser.me/api/portraits/women/65.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Albert Wells",
    role: "Security Director",
    department: "Security Department",
    bio: "Albert Wells, with 15 years in the field, is an expert in ISPS Code implementation and maritime counter-terrorism strategies.",
    languages: ["German", "French", "English"],
    experienceYears: 15,
    profileImage: "https://randomuser.me/api/portraits/men/79.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Claire Curtis",
    role: "Security Officer",
    department: "Security Department",
    bio: "Claire Curtis is trained in conflict resolution and emergency protocols, ensuring rapid and effective response to security incidents.",
    languages: ["Russian", "Italian", "Spanish", "English"],
    experienceYears: 13,
    profileImage: "https://randomuser.me/api/portraits/women/77.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Jeffrey Fox",
    role: "Security Specialist",
    department: "Security Department",
    bio: "Known for analytical expertise, Jeffrey Fox conducts vulnerability assessments and designs contingency plans to address evolving threats.",
    languages: ["Mandarin", "French", "English"],
    experienceYears: 21,
    profileImage: "https://randomuser.me/api/portraits/men/75.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Christopher Nash",
    role: "Cybersecurity Officer",
    department: "Security Department",
    bio: "Cybersecurity Officer Nash conducts regular penetration testing and vulnerability assessments of ship systems, drawing on 16 years of expertise.",
    languages: ["German", "Mandarin", "Italian", "English"],
    experienceYears: 16,
    profileImage: "https://randomuser.me/api/portraits/men/38.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Billy Day",
    role: "Maritime Security Coordinator",
    department: "Security Department",
    bio: "With 20 years in the role, Billy Day is adept at developing and updating the Ship Security Plan (SSP) and ensuring its effective implementation.",
    languages: [
      "German",
      "Arabic",
      "French",
      "Italian",
      "Russian",
      "Japanese",
      "English",
    ],
    experienceYears: 20,
    profileImage: "https://randomuser.me/api/portraits/men/63.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Donna Stewart",
    role: "Access Control Officer",
    department: "Security Department",
    bio: "With expertise in surveillance and monitoring, Donna Stewart detects and prevents unauthorized access to restricted vessel areas.",
    languages: ["French", "Russian", "Spanish", "Arabic", "English"],
    experienceYears: 16,
    profileImage: "https://randomuser.me/api/portraits/women/62.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "William Douglas",
    role: "Safety Compliance Officer",
    department: "Security Department",
    bio: "Safety Compliance Officer Douglas is an expert in ISM, ISPS, and MLC compliance, bringing 5 years of dedicated focus to these areas.",
    languages: [
      "Japanese",
      "Portuguese",
      "French",
      "Mandarin",
      "Arabic",
      "English",
    ],
    experienceYears: 5,
    profileImage: "https://randomuser.me/api/portraits/men/31.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Harper Lawson",
    role: "Youth Program Director",
    department: "Youth & Family Programs",
    bio: "Youth Program Director Lawson ensures all youth activities are not only fun but also adhere to the highest safety and child protection standards, drawing on 5 years.",
    languages: ["Mandarin", "Italian", "French", "Japanese", "English"],
    experienceYears: 5,
    profileImage: "https://randomuser.me/api/portraits/women/46.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Genesis Fisher",
    role: "Family Activities Coordinator",
    department: "Youth & Family Programs",
    bio: "Leveraging 5 years in family entertainment, Genesis Fisher curates a diverse schedule of events appealing to all members of the family.",
    languages: ["Japanese", "Italian", "Arabic", "English"],
    experienceYears: 5,
    profileImage: "https://randomuser.me/api/portraits/women/68.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Johnny Foster",
    role: "Children's Entertainment Specialist",
    department: "Youth & Family Programs",
    bio: "Children's Entertainment Specialist Foster has a talent for making every child feel special, using 20 years of experience to tailor activities to individual personalities.",
    languages: ["French", "Italian", "Japanese", "English"],
    experienceYears: 20,
    profileImage: "https://randomuser.me/api/portraits/men/37.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Virginia Marshall",
    role: "Teen Activities Coordinator",
    department: "Youth & Family Programs",
    bio: "Teen Activities Coordinator Marshall fosters positive social environments with interactive, age-appropriate activities that encourage peer bonding.",
    languages: ["German", "Mandarin", "Japanese", "English"],
    experienceYears: 5,
    profileImage: "https://randomuser.me/api/portraits/women/97.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Dennis Fox",
    role: "Educational Program Manager",
    department: "Youth & Family Programs",
    bio: "Dennis Fox oversees onboard educational initiatives, combining 12 years of academic and program management experience to enrich passenger learning.",
    languages: ["Spanish", "German", "English"],
    experienceYears: 12,
    profileImage: "https://randomuser.me/api/portraits/men/3.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Angela Fisher",
    role: "Child Care Specialist",
    department: "Youth & Family Programs",
    bio: "Known for patience and professionalism, Angela Fisher communicates effectively with parents and crew to support child wellbeing.",
    languages: ["Spanish", "French", "Japanese", "Mandarin", "English"],
    experienceYears: 8,
    profileImage: "https://randomuser.me/api/portraits/women/71.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Evelyn Wallace",
    role: "Activities Director",
    department: "Activities & Recreation",
    bio: "With a focus on guest engagement and satisfaction, Evelyn Wallace designs diverse activity schedules that cater to a wide range of interests and age groups onboard.",
    languages: [
      "German",
      "Japanese",
      "Russian",
      "Arabic",
      "Spanish",
      "English",
    ],
    experienceYears: 6,
    profileImage: "https://randomuser.me/api/portraits/women/47.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Stella Hawkins",
    role: "Water Sports Instructor",
    department: "Activities & Recreation",
    bio: "Water Sports Instructor Hawkins possesses an in-depth knowledge of local water conditions and marine life, enhancing guest experiences over 17 years.",
    languages: ["German", "English", "Russian"],
    experienceYears: 17,
    profileImage: "https://randomuser.me/api/portraits/women/60.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Zachary Curtis",
    role: "Fitness Instructor",
    department: "Activities & Recreation",
    bio: "Zachary Curtis is passionate about inspiring guests to discover the joy of movement, bringing energy and expertise from 5 years in the fitness industry.",
    languages: ["French", "English"],
    experienceYears: 5,
    profileImage: "https://randomuser.me/api/portraits/men/14.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Timothy Foster",
    role: "Excursion Coordinator",
    department: "Activities & Recreation",
    bio: "Excursion Coordinator Foster plans enriching off-ship experiences that promote cultural immersion and memorable interactions for passengers.",
    languages: ["English", "Spanish", "German"],
    experienceYears: 17,
    profileImage: "https://randomuser.me/api/portraits/men/20.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Brandon Grant",
    role: "Lead Photographer",
    department: "Photography & Videography",
    bio: "Brandon Grant directs all photographic projects onboard, blending technical skill and artistic vision to create visually compelling narratives.",
    languages: ["Mandarin", "Spanish", "Russian", "German", "English"],
    experienceYears: 17,
    profileImage: "https://randomuser.me/api/portraits/men/69.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Carlos Fisher",
    role: "Videographer",
    department: "Photography & Videography",
    bio: "Carlos Fisher documents ship activities, excursions, and special events, delivering high-quality video content with 6 years of professional videography experience.",
    languages: ["German", "Mandarin", "English"],
    experienceYears: 6,
    profileImage: "https://randomuser.me/api/portraits/men/73.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Pamela Fletcher",
    role: "Digital Media Specialist",
    department: "Photography & Videography",
    bio: "With 16 years in the digital realm, Pamela Fletcher crafts compelling online stories and manages the ship's social media channels to connect with guests.",
    languages: ["Mandarin", "Japanese", "Spanish", "Russian", "English"],
    experienceYears: 16,
    profileImage: "https://randomuser.me/api/portraits/women/86.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Gary Stewart",
    role: "Chief Medical Officer",
    department: "Health & Safety",
    bio: "Chief Medical Officer Stewart maintains medical supplies and liaises with shore-based health facilities to support comprehensive care.",
    languages: [
      "Arabic",
      "French",
      "Japanese",
      "Italian",
      "Russian",
      "English",
    ],
    experienceYears: 3,
    profileImage: "https://randomuser.me/api/portraits/men/30.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Dorothy Keller",
    role: "Ship's Doctor",
    department: "Health & Safety",
    bio: "Known for calm professionalism, Dr. Keller leads medical emergency interventions and coordinates evacuation when necessary.",
    languages: ["Mandarin", "Spanish", "Russian", "Portuguese", "English"],
    experienceYears: 8,
    profileImage: "https://randomuser.me/api/portraits/women/85.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Olivia Gibson",
    role: "Nurse",
    department: "Health & Safety",
    bio: "Nurse Gibson supports the medical team by administering treatments, monitoring patient conditions, and maintaining comprehensive medical records.",
    languages: ["English", "Italian"],
    experienceYears: 11,
    profileImage: "https://randomuser.me/api/portraits/women/21.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Louis Crawford",
    role: "Safety Officer",
    department: "Health & Safety",
    bio: "Safety Officer Crawford documents incidents and implements corrective actions to continuously improve onboard safety performance.",
    languages: ["English", "Arabic"],
    experienceYears: 6,
    profileImage: "https://randomuser.me/api/portraits/men/15.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Lisa Wallace",
    role: "Hospitality Director",
    department: "Hospitality Department",
    bio: "With 6 years in hospitality management, Lisa Wallace drives operational excellence and team performance onboard.",
    languages: ["English", "Russian", "Spanish", "French", "Mandarin"],
    experienceYears: 6,
    profileImage: "https://randomuser.me/api/portraits/women/24.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Joseph Hawkins",
    role: "Guest Relations Manager",
    department: "Hospitality Department",
    bio: "Guest Relations Manager Hawkins is adept at handling complex guest inquiries and ensuring swift, satisfactory resolutions, fostering loyalty and positive experiences.",
    languages: ["French", "English", "Mandarin", "Arabic", "Portuguese"],
    experienceYears: 19,
    profileImage: "https://randomuser.me/api/portraits/men/56.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Steven Clark",
    role: "Chief Steward",
    department: "Hospitality Department",
    bio: "With 18 years leading stewardship teams, Chief Steward Clark meticulously manages cabin services, laundry operations, and public area upkeep.",
    languages: ["Russian", "Japanese", "English"],
    experienceYears: 18,
    profileImage: "https://randomuser.me/api/portraits/men/74.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Julie Hamilton",
    role: "Senior Steward",
    department: "Hospitality Department",
    bio: "Julie Hamilton provides exceptional valet services and anticipates guest needs, contributing to a luxurious and comfortable onboard experience over 3 years.",
    languages: ["Japanese", "Arabic", "Portuguese", "English"],
    experienceYears: 3,
    profileImage: "https://randomuser.me/api/portraits/women/51.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Wayne Foster",
    role: "Butler",
    department: "Hospitality Department",
    bio: "Wayne Foster anticipates guest needs to deliver tailored luxury experiences throughout the voyage.",
    languages: ["German", "Russian", "Italian", "Portuguese", "English"],
    experienceYears: 20,
    profileImage: "https://randomuser.me/api/portraits/men/75.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Kinsley Ellis",
    role: "Accommodation Manager",
    department: "Hospitality Department",
    bio: "Accommodation Manager Ellis plays a key role in inventory control for linens, amenities, and cleaning supplies, optimizing resources over 4 years.",
    languages: ["Mandarin", "Portuguese", "English"],
    experienceYears: 4,
    profileImage: "https://randomuser.me/api/portraits/women/34.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Christine Baker",
    role: "Housekeeping Supervisor",
    department: "Hospitality Department",
    bio: "Housekeeping Supervisor Baker is committed to sustainability in cleaning practices, implementing eco-friendly procedures throughout their 19 years of service.",
    languages: ["Russian", "Portuguese", "Japanese", "English"],
    experienceYears: 19,
    profileImage: "https://randomuser.me/api/portraits/women/72.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Liam Parker",
    role: "Guest Services Specialist",
    department: "Hospitality Department",
    bio: "Guest Services Specialist Parker efficiently handles onboard account management, reservations for activities, and general assistance with a friendly and professional demeanor.",
    languages: ["Japanese", "Italian", "German", "Arabic", "French", "English"],
    experienceYears: 15,
    profileImage: "https://randomuser.me/api/portraits/men/69.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Mason Mason",
    role: "Concierge",
    department: "Hospitality Department",
    bio: "Mason Mason acts as a personal guide to onboard and onshore experiences, providing insider tips and tailored advice to create unique memories for guests.",
    languages: ["German", "Japanese", "Portuguese", "French", "English"],
    experienceYears: 17,
    profileImage: "https://randomuser.me/api/portraits/men/44.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Roger Wallace",
    role: "Front Desk Manager",
    department: "Hospitality Department",
    bio: "With 20 years in front office management, Roger Wallace ensures a welcoming and organized reception area, managing all aspects of guest registration and billing.",
    languages: ["Portuguese", "French", "Italian", "English"],
    experienceYears: 20,
    profileImage: "https://randomuser.me/api/portraits/men/15.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Jeremy Hall",
    role: "VIP Coordinator",
    department: "Hospitality Department",
    bio: "Jeremy Hall's expertise over 12 years lies in creating unparalleled experiences, making every VIP guest feel exceptionally valued and pampered.",
    languages: ["Russian", "Portuguese", "English"],
    experienceYears: 12,
    profileImage: "https://randomuser.me/api/portraits/men/56.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Scott Palmer",
    role: "Hospitality Trainer",
    department: "Hospitality Department",
    bio: "Scott Palmer conducts needs assessments and measures training effectiveness to ensure continuous improvement across all hospitality departments, reflecting 10 years in adult learning.",
    languages: ["Portuguese", "English", "Russian"],
    experienceYears: 10,
    profileImage: "https://randomuser.me/api/portraits/men/15.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Alan Mason",
    role: "Executive Chef",
    department: "Culinary Department",
    bio: "Beyond crafting exquisite Pacific Rim, Chef Mason expertly manages kitchen hygiene, inventory, and food cost control, honed over 12 years in demanding culinary environments.",
    languages: ["Portuguese", "Mandarin", "English"],
    experienceYears: 12,
    profileImage: "https://randomuser.me/api/portraits/men/38.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Sandra Reed",
    role: "Sous Chef",
    department: "Culinary Department",
    bio: "Sandra Reed excels in menu execution and team management to maintain high culinary standards.",
    languages: ["French", "Japanese", "English"],
    experienceYears: 12,
    profileImage: "https://randomuser.me/api/portraits/women/67.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Christine Griffin",
    role: "Pastry Chef",
    department: "Culinary Department",
    bio: "Pastry Chef Griffin crafts exquisite desserts with 4 years of baking and pastry artistry.",
    languages: ["Russian", "English"],
    experienceYears: 4,
    profileImage: "https://randomuser.me/api/portraits/women/48.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Dorothy Henderson",
    role: "Chef de Partie",
    department: "Culinary Department",
    bio: "With 14 years as a section chef, Dorothy Henderson is responsible for stock control and guiding commis chefs within their designated area of the Pacific Rim kitchen.",
    languages: ["Japanese", "Arabic", "English"],
    experienceYears: 14,
    profileImage: "https://randomuser.me/api/portraits/women/49.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Jacob Dunn",
    role: "Specialty Chef",
    department: "Culinary Department",
    bio: "With 10 years perfecting {cuisineSpecific} artistry, Jacob Dunn ensures each plate is a true representation of its cultural heritage and bold flavors.",
    languages: ["Spanish", "French", "English"],
    experienceYears: 10,
    profileImage: "https://randomuser.me/api/portraits/men/38.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Michelle Douglas",
    role: "Sushi Chef",
    department: "Culinary Department",
    bio: "Sushi Chef Douglas manages the sushi bar operations, ensuring exceptional quality and presentation, reflecting 18 years of Japanese culinary excellence.",
    languages: ["Spanish", "Mandarin", "Portuguese", "English"],
    experienceYears: 18,
    profileImage: "https://randomuser.me/api/portraits/women/96.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Eleanor Payne",
    role: "Garde Manger",
    department: "Culinary Department",
    bio: "Eleanor Payne is responsible for creating visually stunning and delicious cold appetizers, canapés, and buffet displays, backed by 6 years of Pan-Asian expertise.",
    languages: ["German", "Mandarin", "English"],
    experienceYears: 6,
    profileImage: "https://randomuser.me/api/portraits/women/41.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Jack Graham",
    role: "Butcher",
    department: "Culinary Department",
    bio: "Butcher Graham ensures quality meat preparation, supported by 14 years of skilled butchery work.",
    languages: ["Russian", "German", "Mandarin", "English"],
    experienceYears: 14,
    profileImage: "https://randomuser.me/api/portraits/men/94.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Patricia Fisher",
    role: "Baker",
    department: "Culinary Department",
    bio: "Baker Fisher produces fresh breads and baked goods, leveraging 9 years of baking expertise.",
    languages: ["Japanese", "Portuguese", "English"],
    experienceYears: 9,
    profileImage: "https://randomuser.me/api/portraits/women/4.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Joseph Dixon",
    role: "Sommelier",
    department: "Culinary Department",
    bio: "Sommelier Dixon curates wine selections, offering expert pairing advice with 11 years in fine wine service.",
    languages: ["French", "Spanish", "Russian", "Japanese", "English"],
    experienceYears: 11,
    profileImage: "https://randomuser.me/api/portraits/men/38.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Tyler Palmer",
    role: "Mixologist",
    department: "Culinary Department",
    bio: "Tyler Palmer manages bar inventory and contributes to menu development, ensuring a sophisticated and exciting beverage program, backed by 12 years in the art of mixology.",
    languages: ["French", "Russian", "Mandarin", "English", "Japanese"],
    experienceYears: 12,
    profileImage: "https://randomuser.me/api/portraits/men/57.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Ariana Baker",
    role: "Barista",
    department: "Culinary Department",
    bio: "Barista Baker prepares specialty coffees with precision, backed by 19 years in coffee service.",
    languages: ["Italian", "German", "English"],
    experienceYears: 19,
    profileImage: "https://randomuser.me/api/portraits/women/94.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Chloe Jennings",
    role: "Nutritionist",
    department: "Culinary Department",
    bio: "Nutritionist Jennings works closely with the culinary team to create wholesome Nordic options that are both flavorful and aligned with wellness goals, drawing on 10 years of expertise.",
    languages: ["German", "Mandarin", "English"],
    experienceYears: 10,
    profileImage: "https://randomuser.me/api/portraits/women/20.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Joel Wallace",
    role: "Entertainment Director",
    department: "Entertainment Department",
    bio: "With 22 years orchestrating spectacular onboard entertainment, Joel Wallace manages everything from Broadway-style shows to intimate musical performances and themed parties.",
    languages: ["Portuguese", "Japanese", "Spanish", "English"],
    experienceYears: 22,
    profileImage: "https://randomuser.me/api/portraits/men/66.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Joel Spencer",
    role: "Performance Coordinator",
    department: "Entertainment Department",
    bio: "Performance Coordinator Spencer serves as the key liaison between artists, production staff, and management, ensuring clear communication and efficient problem-solving.",
    languages: ["French", "English"],
    experienceYears: 13,
    profileImage: "https://randomuser.me/api/portraits/men/14.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Frank Morgan",
    role: "Lead Vocalist",
    department: "Entertainment Department",
    bio: "Frank Morgan consistently delivers show-stopping performances, connecting with audiences through emotive storytelling and exceptional vocal talent honed across 10 years on stage.",
    languages: ["Japanese", "English", "Italian", "Russian", "Mandarin"],
    experienceYears: 10,
    profileImage: "https://randomuser.me/api/portraits/men/45.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Jesse Stewart",
    role: "Musician",
    department: "Entertainment Department",
    bio: "Musician Stewart performs live music across genres, engaging guests with 9 years of performance experience.",
    languages: ["Spanish", "Japanese", "Russian", "Mandarin", "English"],
    experienceYears: 9,
    profileImage: "https://randomuser.me/api/portraits/men/73.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Lily Lawson",
    role: "Dancer",
    department: "Entertainment Department",
    bio: "Lily Lawson is a dedicated member of the ensemble, contributing to high-energy production numbers and themed events, showcasing 19 years of professional dance experience.",
    languages: ["Japanese", "Russian", "English"],
    experienceYears: 19,
    profileImage: "https://randomuser.me/api/portraits/women/33.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Rachel Hudson",
    role: "Choreographer",
    department: "Entertainment Department",
    bio: "Choreographer Hudson creates captivating dance routines, blending creativity with 20 years of dance expertise.",
    languages: [
      "French",
      "Mandarin",
      "Japanese",
      "Russian",
      "Spanish",
      "English",
    ],
    experienceYears: 20,
    profileImage: "https://randomuser.me/api/portraits/women/61.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Aaliyah Palmer",
    role: "Comedy Performer",
    department: "Entertainment Department",
    bio: "Aaliyah Palmer's ability to connect with the audience and improvise, developed over 8 years, makes each show a unique and highly enjoyable experience.",
    languages: ["Mandarin", "Japanese", "English"],
    experienceYears: 8,
    profileImage: "https://randomuser.me/api/portraits/women/97.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Scarlett Payne",
    role: "Magic Act",
    department: "Entertainment Department",
    bio: "Scarlett Payne blends showmanship and technique to deliver captivating magic shows at sea.",
    languages: ["French", "Arabic", "English"],
    experienceYears: 8,
    profileImage: "https://randomuser.me/api/portraits/women/60.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Benjamin Dean",
    role: "DJ",
    department: "Entertainment Department",
    bio: "Benjamin Dean utilizes professional mixing skills and an energetic presence to ensure high-energy parties and memorable nights for guests, backed by 10 years of club experience.",
    languages: ["Italian", "Arabic", "Spanish", "English"],
    experienceYears: 10,
    profileImage: "https://randomuser.me/api/portraits/men/69.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Jack Fox",
    role: "Audio Technician",
    department: "Entertainment Department",
    bio: "With 12 years of experience in mixing live sound for theatre, music, and events, Jack Fox guarantees crystal-clear audio for all onboard productions.",
    languages: ["Russian", "Arabic", "Japanese", "Italian", "English"],
    experienceYears: 12,
    profileImage: "https://randomuser.me/api/portraits/men/54.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Aaron Dunn",
    role: "Lighting Specialist",
    department: "Entertainment Department",
    bio: "Aaron Dunn's artistic vision and technical mastery over 7 years ensure that lighting plays a crucial role in the storytelling and excitement of onboard entertainment.",
    languages: ["English", "Mandarin", "Japanese"],
    experienceYears: 7,
    profileImage: "https://randomuser.me/api/portraits/men/89.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Jerry Griffin",
    role: "Stage Manager",
    department: "Entertainment Department",
    bio: "Stage Manager Griffin is the organizational backbone of the production, liaising between performers, technicians, and the director to maintain artistic integrity and timing.",
    languages: ["Portuguese", "Spanish", "German", "English"],
    experienceYears: 21,
    profileImage: "https://randomuser.me/api/portraits/men/6.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "David Baker",
    role: "Production Manager",
    department: "Entertainment Department",
    bio: "David Baker's strategic planning and problem-solving skills, developed over 8 years, are crucial for the successful execution of a high-quality entertainment program.",
    languages: ["English"],
    experienceYears: 8,
    profileImage: "https://randomuser.me/api/portraits/men/83.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Robert Holloway",
    role: "Costume Designer",
    department: "Entertainment Department",
    bio: "Robert Holloway's artistic flair and attention to historical detail, honed over 8 years, bring visual richness and authenticity to the stage.",
    languages: ["Mandarin", "Portuguese", "German", "Arabic", "English"],
    experienceYears: 8,
    profileImage: "https://randomuser.me/api/portraits/men/29.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Donna Gibson",
    role: "Cultural Program Director",
    department: "Entertainment Department",
    bio: "Cultural Program Director Gibson collaborates with local artists, historians, and experts to provide authentic and immersive cultural experiences for guests.",
    languages: ["Portuguese", "Spanish", "Russian", "English"],
    experienceYears: 10,
    profileImage: "https://randomuser.me/api/portraits/women/64.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Sophia Morgan",
    role: "Performance Artist",
    department: "Entertainment Department",
    bio: "A specialist in {artisticDiscipline}, Sophia Morgan presents breathtaking and thought-provoking performances honed over 21 years of dedicated artistic exploration.",
    languages: ["Italian", "Portuguese", "English"],
    experienceYears: 21,
    profileImage: "https://randomuser.me/api/portraits/women/45.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Alexa Hunter",
    role: "Operations Manager",
    department: "Operations Department",
    bio: "Operations Manager Hunter applies 6 years of leadership in maritime operations.",
    languages: [
      "German",
      "Japanese",
      "Arabic",
      "Spanish",
      "Italian",
      "English",
    ],
    experienceYears: 6,
    profileImage: "https://randomuser.me/api/portraits/women/62.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Nathan Campbell",
    role: "Logistics Coordinator",
    department: "Operations Department",
    bio: "Logistics Coordinator Campbell meticulously plans and tracks shipments, manages customs documentation, and optimizes storage solutions onboard.",
    languages: ["Arabic", "Spanish", "Russian", "English"],
    experienceYears: 8,
    profileImage: "https://randomuser.me/api/portraits/men/38.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Louis Keller",
    role: "Inventory Specialist",
    department: "Operations Department",
    bio: "With 18 years in inventory management, Louis Keller meticulously maintains records for all consumables, technical spares, and retail goods onboard.",
    languages: ["Arabic", "Portuguese", "English"],
    experienceYears: 18,
    profileImage: "https://randomuser.me/api/portraits/men/49.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Brian Hunter",
    role: "Procurement Officer",
    department: "Operations Department",
    bio: "Procurement Officer Hunter sources and negotiates contracts for goods and services needed onboard.",
    languages: ["French", "Arabic", "English"],
    experienceYears: 22,
    profileImage: "https://randomuser.me/api/portraits/men/23.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
  {
    name: "Antonio West",
    role: "Sustainability Coordinator",
    department: "Operations Department",
    bio: "Sustainability Coordinator West ensures compliance with international environmental regulations (e.g., MARPOL) and promotes a culture of sustainability among crew and guests.",
    languages: ["Russian", "Portuguese", "Arabic", "English"],
    experienceYears: 15,
    profileImage: "https://randomuser.me/api/portraits/men/18.jpg",
    city: "Kiel",
    country: "Germany",
    region: "Northern Europe",
  },
];
