import { CrewMember } from "@/lib/interfaces/people/staff";

export const melbourneTeamMembers: CrewMember[] = [
  {
    name: "James Thompson",
    role: "Captain",
    department: "Deck Department",
    bio: "Captain Thompson brings over 20 years of experience navigating Australasian waters with specialized knowledge of the Southern Ocean and Tasman Sea.",
    languages: ["English", "Maori", "Indonesian"],
    experienceYears: 23,
    profileImage: "/images/crew/captain-thompson.jpg",
    city: "Melbourne",
    country: "Australia",
    state: "Victoria",
    region: "Oceania",
  },
  {
    name: "Olivia Chen",
    role: "First Officer",
    department: "Deck Department",
    bio: "Olivia specializes in South Pacific navigation with expertise in challenging southern waters and seasonal weather patterns.",
    languages: ["English", "Mandarin", "Cantonese"],
    experienceYears: 11,
    profileImage: "/images/crew/officer-chen.jpg",
    city: "Melbourne",
    country: "Australia",
    state: "Victoria",
    region: "Oceania",
  },
  {
    name: "Stuart Wilson",
    role: "Chief Engineer",
    department: "Engineering Department",
    bio: "Stuart ensures optimal performance of all vessel systems with specialization in Southern Ocean conditions and environmental compliance.",
    languages: ["English", "German"],
    experienceYears: 17,
    profileImage: "/images/crew/engineer-wilson.jpg",
    city: "Melbourne",
    country: "Australia",
    state: "Victoria",
    region: "Oceania",
  },
  {
    name: "Chef Emma Hughes",
    role: "Executive Chef",
    department: "Hospitality Department",
    bio: "Chef Hughes creates modern Australian cuisine with Pacific influences, showcasing Victoria's exceptional produce and seafood.",
    languages: ["English", "French", "Italian"],
    experienceYears: 15,
    profileImage: "/images/crew/chef-hughes.jpg",
    city: "Melbourne",
    country: "Australia",
    state: "Victoria",
    region: "Oceania",
  },
  {
    name: "Dylan Parker",
    role: "Cruise Director",
    department: "Entertainment Department",
    bio: "Dylan coordinates sophisticated entertainment programs highlighting Australian culture, from aboriginal heritage to contemporary arts and music.",
    languages: ["English", "French", "Indonesian"],
    experienceYears: 9,
    profileImage: "/images/crew/director-parker.jpg",
    city: "Melbourne",
    country: "Australia",
    state: "Victoria",
    region: "Oceania",
  },
  {
    name: "Dr. Sophie Williams",
    role: "Ship's Doctor",
    department: "Health & Safety",
    bio: "Dr. Williams provides comprehensive medical care with expertise in travel medicine across Pacific and Southern Ocean routes.",
    languages: ["English", "French", "Spanish"],
    experienceYears: 14,
    profileImage: "/images/crew/doctor-williams.jpg",
    city: "Melbourne",
    country: "Australia",
    state: "Victoria",
    region: "Oceania",
  },
];
