import { CrewMember } from "@/lib/interfaces/people/staff";

export const neworleansTeamMembers: CrewMember[] = [
  {
    name: "Vincent Graves",
    role: "Captain",
    department: "Deck Department",
    bio: "Captain Graves is a veteran mariner with 18 years in Caribbean, known for meticulous voyage planning and a steadfast commitment to maritime law.",
    languages: ["English", "French", "Portuguese", "Haitian"],
    experienceYears: 18,
    profileImage: "https://randomuser.me/api/portraits/men/93.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Daniel Knight",
    role: "First Officer",
    department: "Deck Department",
    bio: "Daniel Knight specializes in Caribbean navigation with 16 years of experience managing bridge operations and ensuring adherence to safety standards.",
    languages: ["English", "Haitian", "Guarani"],
    experienceYears: 16,
    profileImage: "https://randomuser.me/api/portraits/men/42.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Matthew Henderson",
    role: "Second Officer",
    department: "Deck Department",
    bio: "Second Officer Henderson's responsibilities include managing the ship's medical stores and providing medical assistance, drawing on 21 years of maritime service in Caribbean.",
    languages: ["English", "French", "Haitian"],
    experienceYears: 21,
    profileImage: "https://randomuser.me/api/portraits/men/93.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Douglas Crawford",
    role: "Third Officer",
    department: "Deck Department",
    bio: "Douglas Crawford supports communication and lookout duties during watches, maintaining high situational awareness in Caribbean's maritime environment.",
    languages: ["English", "Haitian", "Guarani"],
    experienceYears: 4,
    profileImage: "https://randomuser.me/api/portraits/men/53.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Laura Crawford",
    role: "Navigation Officer",
    department: "Deck Department",
    bio: "Laura Crawford collaborates with the bridge team to optimize voyage efficiency, integrating real-time data and weather information specific to Caribbean.",
    languages: ["English", "Haitian", "Portuguese"],
    experienceYears: 5,
    profileImage: "https://randomuser.me/api/portraits/women/55.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Jacob Hudson",
    role: "Safety Officer",
    department: "Deck Department",
    bio: "Committed to regulatory adherence, Jacob Hudson stays updated on maritime safety laws and best practices, facilitating crew training and certification.",
    languages: ["English", "Spanish", "Portuguese"],
    experienceYears: 4,
    profileImage: "https://randomuser.me/api/portraits/men/55.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Vincent Marshall",
    role: "Deck Cadet",
    department: "Deck Department",
    bio: "Under the guidance of senior officers, Deck Cadet Marshall is developing a strong foundation in practical navigation and ship handling in Caribbean.",
    languages: ["English", "French", "Aymara"],
    experienceYears: 6,
    profileImage: "https://randomuser.me/api/portraits/men/23.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Marcus Grant",
    role: "Bosun",
    department: "Deck Department",
    bio: "Bosun Grant maintains the vessel's exterior appearance and structural integrity, a testament to 7 years of dedication in Caribbean.",
    languages: ["English", "Spanish", "Guarani"],
    experienceYears: 7,
    profileImage: "https://randomuser.me/api/portraits/men/87.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Nancy Chambers",
    role: "Chief Engineer",
    department: "Engineering Department",
    bio: "Nancy Chambers brings 13 years of engineering excellence, leading innovations in sustainable maritime technology and driving continuous improvement in vessel operations.",
    languages: ["English", "French", "Aymara", "Quechua"],
    experienceYears: 13,
    profileImage: "https://randomuser.me/api/portraits/women/8.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Kennedy Jennings",
    role: "First Engineer",
    department: "Engineering Department",
    bio: "With a focus on propulsion and power systems, Kennedy Jennings applies 15 years of expertise to optimize engine performance and troubleshoot complex mechanical issues.",
    languages: ["English", "French", "Spanish"],
    experienceYears: 15,
    profileImage: "https://randomuser.me/api/portraits/women/28.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Amelia Ellis",
    role: "Second Engineer",
    department: "Engineering Department",
    bio: "Amelia Ellis supports engineering operations with 9 years focused on mechanical maintenance, diagnostics, and equipment troubleshooting aboard vessels.",
    languages: ["English", "Haitian", "French"],
    experienceYears: 9,
    profileImage: "https://randomuser.me/api/portraits/women/9.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Layla Hayes",
    role: "Electrical Engineer",
    department: "Engineering Department",
    bio: "Layla Hayes manages all electrical systems on board, applying 13 years of expertise in marine electrical engineering and system integration.",
    languages: ["English", "Guarani", "Spanish"],
    experienceYears: 13,
    profileImage: "https://randomuser.me/api/portraits/women/54.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Betty Graves",
    role: "Mechanical Engineer",
    department: "Engineering Department",
    bio: "Betty Graves is skilled in preventive maintenance scheduling and compliance with technical documentation and safety protocols.",
    languages: ["English", "Haitian", "Portuguese", "French"],
    experienceYears: 15,
    profileImage: "https://randomuser.me/api/portraits/women/6.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Joseph Baker",
    role: "HVAC Engineer",
    department: "Engineering Department",
    bio: "Joseph Baker designs, installs, and maintains heating, ventilation, and air conditioning systems with 4 years of maritime specialization.",
    languages: ["English", "Guarani", "French"],
    experienceYears: 4,
    profileImage: "https://randomuser.me/api/portraits/men/33.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Jesse Montgomery",
    role: "Environmental Engineer",
    department: "Engineering Department",
    bio: "Leveraging 13 years in marine environmental science, Jesse Montgomery ensures strict adherence to all international and local environmental laws.",
    languages: ["English", "Quechua", "Aymara", "Haitian"],
    experienceYears: 13,
    profileImage: "https://randomuser.me/api/portraits/men/27.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Henry Gibson",
    role: "Systems Engineer",
    department: "Engineering Department",
    bio: "Drawing upon 4 years, Henry Gibson specializes in the architecture and maintenance of integrated automation systems (IAS) critical for modern vessel operations.",
    languages: ["English", "Haitian", "Guarani", "Spanish"],
    experienceYears: 4,
    profileImage: "https://randomuser.me/api/portraits/men/51.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Joe Gardner",
    role: "Technical Manager",
    department: "Engineering Department",
    bio: "With 22 years leading technical teams, Joe Gardner ensures vessel systems meet all regulatory, safety, and performance standards.",
    languages: ["English", "Haitian", "French", "Quechua"],
    experienceYears: 22,
    profileImage: "https://randomuser.me/api/portraits/men/31.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Antonio Day",
    role: "Maintenance Engineer",
    department: "Engineering Department",
    bio: "Maintenance Engineer Day troubleshoots system faults and implements timely repairs, maintaining vessel operational readiness.",
    languages: ["English", "Quechua", "Portuguese"],
    experienceYears: 20,
    profileImage: "https://randomuser.me/api/portraits/men/26.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Jerry Wallace",
    role: "Security Director",
    department: "Security Department",
    bio: "Security Director Wallace leads threat analysis initiatives and implements advanced security measures to safeguard vessel integrity.",
    languages: ["English", "Spanish", "French"],
    experienceYears: 12,
    profileImage: "https://randomuser.me/api/portraits/men/55.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Susan Dean",
    role: "Security Officer",
    department: "Security Department",
    bio: "With keen attention to risk, Susan Dean has 14 years experience protecting vessel personnel, property, and critical infrastructure against diverse threats.",
    languages: ["English", "Haitian", "French"],
    experienceYears: 14,
    profileImage: "https://randomuser.me/api/portraits/women/44.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Ella Douglas",
    role: "Security Specialist",
    department: "Security Department",
    bio: "Ella Douglas's 16 years include proficiency in evidence collection and report writing for maritime security incidents.",
    languages: ["English", "French", "Guarani"],
    experienceYears: 16,
    profileImage: "https://randomuser.me/api/portraits/women/78.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Sofia Marshall",
    role: "Cybersecurity Officer",
    department: "Security Department",
    bio: "Cybersecurity Officer Marshall protects vessel networks and data with 5 years of specialized cybersecurity expertise in maritime digital infrastructure.",
    languages: ["English", "Aymara", "Quechua", "Portuguese"],
    experienceYears: 5,
    profileImage: "https://randomuser.me/api/portraits/women/38.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Ralph Jennings",
    role: "Maritime Security Coordinator",
    department: "Security Department",
    bio: "With 9 years in the role, Ralph Jennings is adept at developing and updating the Ship Security Plan (SSP) and ensuring its effective implementation.",
    languages: ["English", "Portuguese", "French", "Aymara"],
    experienceYears: 9,
    profileImage: "https://randomuser.me/api/portraits/men/98.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Linda Graves",
    role: "Access Control Officer",
    department: "Security Department",
    bio: "Drawing on 19 years of experience, Linda Graves is proficient in operating and maintaining advanced access control systems and screening equipment.",
    languages: ["English", "Guarani", "French"],
    experienceYears: 19,
    profileImage: "https://randomuser.me/api/portraits/women/87.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Dorothy Grant",
    role: "Safety Compliance Officer",
    department: "Security Department",
    bio: "Dorothy Grant meticulously prepares the vessel for internal and external safety audits, ensuring all documentation and practices meet or exceed standards, backed by 4 years.",
    languages: ["English", "French", "Aymara", "Spanish"],
    experienceYears: 4,
    profileImage: "https://randomuser.me/api/portraits/women/96.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Roger Sutton",
    role: "Youth Program Director",
    department: "Youth & Family Programs",
    bio: "Committed to positive youth engagement, Roger Sutton integrates educational content with fun, age-appropriate activities tailored to diverse passenger groups.",
    languages: ["English", "Spanish", "French"],
    experienceYears: 12,
    profileImage: "https://randomuser.me/api/portraits/men/41.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Anna Hamilton",
    role: "Family Activities Coordinator",
    department: "Youth & Family Programs",
    bio: "With strong communication skills, Anna Hamilton liaises with hospitality and entertainment teams to deliver seamless family-oriented services.",
    languages: ["English", "Quechua", "Aymara"],
    experienceYears: 9,
    profileImage: "https://randomuser.me/api/portraits/women/46.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Miguel Knight",
    role: "Children's Entertainment Specialist",
    department: "Youth & Family Programs",
    bio: "Miguel Knight engages young guests with creative entertainment programs, leveraging 8 years in children’s recreational services and event planning.",
    languages: ["English", "Portuguese", "Haitian", "French"],
    experienceYears: 8,
    profileImage: "https://randomuser.me/api/portraits/men/91.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "David Curtis",
    role: "Teen Activities Coordinator",
    department: "Youth & Family Programs",
    bio: "Teen Activities Coordinator Curtis is skilled at mentoring and connecting with teenagers, ensuring they have a fantastic and safe experience, drawing on 17 years.",
    languages: ["English", "Guarani", "Aymara"],
    experienceYears: 17,
    profileImage: "https://randomuser.me/api/portraits/men/38.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Eleanor Holloway",
    role: "Educational Program Manager",
    department: "Youth & Family Programs",
    bio: "Eleanor Holloway, with 22 years in curriculum development, ensures educational content is engaging, accurate, and inspiring for passengers of all ages.",
    languages: ["English", "Spanish", "French"],
    experienceYears: 22,
    profileImage: "https://randomuser.me/api/portraits/women/53.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Caroline Palmer",
    role: "Child Care Specialist",
    department: "Youth & Family Programs",
    bio: "Child Care Specialist Palmer promotes social and emotional development through structured play and educational activities.",
    languages: ["English", "Aymara", "Guarani"],
    experienceYears: 5,
    profileImage: "https://randomuser.me/api/portraits/women/23.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Leah Palmer",
    role: "Activities Director",
    department: "Activities & Recreation",
    bio: "Drawing on 22 years in recreation management, Leah Palmer curates an exciting and varied daily program of entertainment and activities for all guests.",
    languages: ["English", "Spanish", "Quechua"],
    experienceYears: 22,
    profileImage: "https://randomuser.me/api/portraits/women/69.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Chen Graham",
    role: "Water Sports Instructor",
    department: "Activities & Recreation",
    bio: "With expertise in various water sports, Chen Graham provides personalized coaching that accommodates different skill levels and abilities.",
    languages: ["English", "Portuguese", "Haitian"],
    experienceYears: 9,
    profileImage: "https://randomuser.me/api/portraits/men/19.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Ronald Day",
    role: "Fitness Instructor",
    department: "Activities & Recreation",
    bio: "Drawing on 14 years of expertise, Ronald Day offers specialized classes like yoga, Pilates, and high-intensity interval training (HIIT).",
    languages: ["English", "French", "Portuguese", "Haitian"],
    experienceYears: 14,
    profileImage: "https://randomuser.me/api/portraits/men/8.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Bella Price",
    role: "Excursion Coordinator",
    department: "Activities & Recreation",
    bio: "Leveraging 7 years of experience, Bella Price curates a portfolio of unique and authentic shore excursions that showcase the best of each port.",
    languages: ["English", "Aymara", "Spanish"],
    experienceYears: 7,
    profileImage: "https://randomuser.me/api/portraits/women/20.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Ariana Porter",
    role: "Lead Photographer",
    department: "Photography & Videography",
    bio: "Ariana Porter directs all photographic projects onboard, blending technical skill and artistic vision to create visually compelling narratives.",
    languages: ["English", "French", "Aymara"],
    experienceYears: 3,
    profileImage: "https://randomuser.me/api/portraits/women/40.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Isabella Dixon",
    role: "Videographer",
    department: "Photography & Videography",
    bio: "Isabella Dixon documents ship activities, excursions, and special events, delivering high-quality video content with 16 years of professional videography experience.",
    languages: ["English", "Guarani", "Spanish", "Portuguese"],
    experienceYears: 16,
    profileImage: "https://randomuser.me/api/portraits/women/43.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Caroline Clark",
    role: "Digital Media Specialist",
    department: "Photography & Videography",
    bio: "Digital Media Specialist Clark ensures an engaging online presence by creating and curating multimedia content tailored to diverse passenger demographics.",
    languages: ["English", "Haitian", "Guarani"],
    experienceYears: 8,
    profileImage: "https://randomuser.me/api/portraits/women/40.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Randy Grant",
    role: "Chief Medical Officer",
    department: "Health & Safety",
    bio: "Committed to preventive care, Randy Grant promotes health education and wellness initiatives throughout the voyage.",
    languages: ["English", "Haitian", "Aymara", "French"],
    experienceYears: 12,
    profileImage: "https://randomuser.me/api/portraits/men/74.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Joshua Hayes",
    role: "Ship's Doctor",
    department: "Health & Safety",
    bio: "With specialization in emergency response, preventative medicine, and maritime health protocols, Dr. Hayes ensures passenger and crew safety.",
    languages: ["English", "Guarani", "Portuguese"],
    experienceYears: 14,
    profileImage: "https://randomuser.me/api/portraits/men/98.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Melissa Fox",
    role: "Nurse",
    department: "Health & Safety",
    bio: "With 9 years of experience, Melissa Fox is proficient in emergency care, routine medical procedures, and health education for passengers and crew.",
    languages: ["English", "Portuguese", "Quechua"],
    experienceYears: 9,
    profileImage: "https://randomuser.me/api/portraits/women/15.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Nancy Porter",
    role: "Safety Officer",
    department: "Health & Safety",
    bio: "Safety Officer Porter works proactively to prevent accidents by inspecting equipment, conducting drills, and ensuring regulatory compliance.",
    languages: ["English", "Spanish", "Portuguese"],
    experienceYears: 18,
    profileImage: "https://randomuser.me/api/portraits/women/40.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Amelia Bennett",
    role: "Hospitality Director",
    department: "Hospitality Department",
    bio: "Overseeing a diverse team, Hospitality Director Bennett implements innovative service strategies and maintains the highest quality standards, reflecting 20 years in the industry.",
    languages: ["English", "Quechua", "Aymara"],
    experienceYears: 20,
    profileImage: "https://randomuser.me/api/portraits/women/24.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Stephanie Curtis",
    role: "Guest Relations Manager",
    department: "Hospitality Department",
    bio: "Stephanie Curtis champions a guest-first culture, utilizing 18 years of experience to train and motivate staff in delivering exceptional, personalized care.",
    languages: ["English", "Portuguese", "Aymara"],
    experienceYears: 18,
    profileImage: "https://randomuser.me/api/portraits/women/29.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Ethan Cooper",
    role: "Chief Steward",
    department: "Hospitality Department",
    bio: "Ethan Cooper ensures the highest standards of cleanliness and comfort throughout passenger accommodations.",
    languages: ["English", "French", "Portuguese", "Aymara"],
    experienceYears: 15,
    profileImage: "https://randomuser.me/api/portraits/men/13.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Amanda Mitchell",
    role: "Senior Steward",
    department: "Hospitality Department",
    bio: "Senior Steward Mitchell also assists in training junior stewards, sharing expertise gained from 22 years in maritime hospitality.",
    languages: ["English", "French", "Guarani"],
    experienceYears: 22,
    profileImage: "https://randomuser.me/api/portraits/women/91.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Oliver Reeves",
    role: "Butler",
    department: "Hospitality Department",
    bio: "Oliver Reeves anticipates guest needs to deliver tailored luxury experiences throughout the voyage.",
    languages: ["English", "Haitian", "Portuguese"],
    experienceYears: 8,
    profileImage: "https://randomuser.me/api/portraits/men/45.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Roy Montgomery",
    role: "Accommodation Manager",
    department: "Hospitality Department",
    bio: "Accommodation Manager Montgomery coordinates housekeeping and maintenance teams for optimal guest satisfaction.",
    languages: ["English", "Aymara", "Quechua", "Guarani"],
    experienceYears: 19,
    profileImage: "https://randomuser.me/api/portraits/men/72.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Michael Campbell",
    role: "Housekeeping Supervisor",
    department: "Hospitality Department",
    bio: "Michael Campbell manages daily assignments, motivates the housekeeping team, and ensures efficient use of cleaning resources, drawing on 11 years of leadership.",
    languages: ["English", "Haitian", "French", "Spanish"],
    experienceYears: 11,
    profileImage: "https://randomuser.me/api/portraits/men/66.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Zola Gardner",
    role: "Guest Services Specialist",
    department: "Hospitality Department",
    bio: "Guest Services Specialist Gardner efficiently handles onboard account management, reservations for activities, and general assistance with a friendly and professional demeanor.",
    languages: ["English", "Quechua", "Portuguese"],
    experienceYears: 12,
    profileImage: "https://randomuser.me/api/portraits/women/86.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Noah Russell",
    role: "Concierge",
    department: "Hospitality Department",
    bio: "With an extensive network and 12 years of experience, Concierge Russell arranges bespoke shore excursions, dining reservations, and special occasion services.",
    languages: ["English", "French", "Quechua", "Portuguese"],
    experienceYears: 12,
    profileImage: "https://randomuser.me/api/portraits/men/42.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Emma Coleman",
    role: "Front Desk Manager",
    department: "Hospitality Department",
    bio: "Front Desk Manager Coleman oversees reception operations, ensuring efficient guest check-in and issue resolution.",
    languages: ["English", "Portuguese", "Spanish"],
    experienceYears: 13,
    profileImage: "https://randomuser.me/api/portraits/women/40.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Margaret Payne",
    role: "VIP Coordinator",
    department: "Hospitality Department",
    bio: "Margaret Payne designs and executes VIP programs that exceed the highest standards of luxury and discretion.",
    languages: ["English", "Portuguese", "Haitian", "Aymara"],
    experienceYears: 8,
    profileImage: "https://randomuser.me/api/portraits/women/50.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Skylar Jennings",
    role: "Hospitality Trainer",
    department: "Hospitality Department",
    bio: "Hospitality Trainer Jennings focuses on enhancing guest service quality through targeted education and coaching.",
    languages: ["English", "Portuguese", "Aymara"],
    experienceYears: 18,
    profileImage: "https://randomuser.me/api/portraits/women/33.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Adam Lawson",
    role: "Executive Chef",
    department: "Culinary Department",
    bio: "Executive Chef Lawson leads a brigade of talented chefs, orchestrating all culinary operations and menu development with 8 years of innovative leadership.",
    languages: ["English", "Spanish", "French"],
    experienceYears: 8,
    profileImage: "https://randomuser.me/api/portraits/men/37.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Wei Russell",
    role: "Sous Chef",
    department: "Culinary Department",
    bio: "Sous Chef Russell supports kitchen operations with 4 years of culinary expertise and leadership.",
    languages: ["English", "Guarani", "Portuguese"],
    experienceYears: 4,
    profileImage: "https://randomuser.me/api/portraits/men/77.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Justin Graham",
    role: "Pastry Chef",
    department: "Culinary Department",
    bio: "Specializing in delicate Japanese pastries and innovative dessert creations, Pastry Chef Graham brings 7 years of refined skill to the culinary team.",
    languages: ["English", "Guarani", "French"],
    experienceYears: 7,
    profileImage: "https://randomuser.me/api/portraits/men/63.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Isabella Carpenter",
    role: "Chef de Partie",
    department: "Culinary Department",
    bio: "Isabella Carpenter maintains immaculate standards of organization and hygiene at their station, contributing to the kitchen's overall efficiency with 4 years of discipline.",
    languages: ["English", "Aymara", "French"],
    experienceYears: 4,
    profileImage: "https://randomuser.me/api/portraits/women/49.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Elizabeth Day",
    role: "Specialty Chef",
    department: "Culinary Department",
    bio: "Specialty Chef Day curates exclusive menus for themed dining venues, showcasing 21 years of passion for {cuisineSpecific} traditions and techniques.",
    languages: ["English", "Aymara", "French"],
    experienceYears: 21,
    profileImage: "https://randomuser.me/api/portraits/women/42.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Peter Watson",
    role: "Sushi Chef",
    department: "Culinary Department",
    bio: "Sushi Chef Watson manages the sushi bar operations, ensuring exceptional quality and presentation, reflecting 9 years of Japanese culinary excellence.",
    languages: ["English", "Spanish", "Haitian", "Guarani"],
    experienceYears: 9,
    profileImage: "https://randomuser.me/api/portraits/men/1.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Helen Jennings",
    role: "Garde Manger",
    department: "Culinary Department",
    bio: "Helen Jennings maintains high standards in food presentation and safety for all cold kitchen offerings.",
    languages: ["English", "French", "Haitian"],
    experienceYears: 13,
    profileImage: "https://randomuser.me/api/portraits/women/16.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Cynthia Clark",
    role: "Butcher",
    department: "Culinary Department",
    bio: "Cynthia Clark maintains the highest standards of hygiene and technique in meat processing, a skill perfected over 9 years in professional butchery.",
    languages: ["English", "Spanish", "Portuguese", "Haitian"],
    experienceYears: 9,
    profileImage: "https://randomuser.me/api/portraits/women/59.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Hannah Dixon",
    role: "Baker",
    department: "Culinary Department",
    bio: "Hannah Dixon combines traditional techniques with innovation to delight guests with baked specialties.",
    languages: ["English", "Portuguese", "Guarani"],
    experienceYears: 10,
    profileImage: "https://randomuser.me/api/portraits/women/72.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Steven Graves",
    role: "Sommelier",
    department: "Culinary Department",
    bio: "Sommelier Graves curates wine selections, offering expert pairing advice with 17 years in fine wine service.",
    languages: ["English", "Guarani", "Aymara"],
    experienceYears: 17,
    profileImage: "https://randomuser.me/api/portraits/men/16.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Brooklyn Gardner",
    role: "Mixologist",
    department: "Culinary Department",
    bio: "Brooklyn Gardner manages bar inventory and contributes to menu development, ensuring a sophisticated and exciting beverage program, backed by 14 years in the art of mixology.",
    languages: ["English", "Aymara", "French", "Portuguese"],
    experienceYears: 14,
    profileImage: "https://randomuser.me/api/portraits/women/43.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Sofia Dean",
    role: "Barista",
    department: "Culinary Department",
    bio: "Sofia Dean provides friendly and efficient service at the coffee bar, sharing knowledge and passion for specialty coffee honed over 19 years.",
    languages: ["English", "Haitian", "Spanish", "Aymara"],
    experienceYears: 19,
    profileImage: "https://randomuser.me/api/portraits/women/37.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Logan Fletcher",
    role: "Nutritionist",
    department: "Culinary Department",
    bio: "Logan Fletcher collaborates with chefs to ensure nutritious and delicious meal options onboard.",
    languages: ["English", "Aymara", "French"],
    experienceYears: 16,
    profileImage: "https://randomuser.me/api/portraits/men/97.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Caroline Coleman",
    role: "Entertainment Director",
    department: "Entertainment Department",
    bio: "Entertainment Director Coleman leads a dynamic team of performers and technicians, ensuring flawless execution and high-energy engagement across all venues, backed by 10 years of industry leadership.",
    languages: ["English", "Aymara", "Spanish"],
    experienceYears: 10,
    profileImage: "https://randomuser.me/api/portraits/women/72.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Carol Clark",
    role: "Performance Coordinator",
    department: "Entertainment Department",
    bio: "Carol Clark manages scheduling and logistics for performers, ensuring smooth entertainment operations onboard.",
    languages: ["English", "Spanish", "Quechua", "Aymara"],
    experienceYears: 18,
    profileImage: "https://randomuser.me/api/portraits/women/74.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Stephanie Holloway",
    role: "Lead Vocalist",
    department: "Entertainment Department",
    bio: "As a key figure in production shows, Lead Vocalist Holloway collaborates with the cast and creative team, bringing 6 years of professional discipline and artistry.",
    languages: ["English", "Guarani", "Aymara"],
    experienceYears: 6,
    profileImage: "https://randomuser.me/api/portraits/women/40.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Gabriella Maxwell",
    role: "Musician",
    department: "Entertainment Department",
    bio: "Gabriella Maxwell enriches onboard ambiance through skilled instrumental and vocal performances.",
    languages: ["English", "Quechua", "Spanish"],
    experienceYears: 16,
    profileImage: "https://randomuser.me/api/portraits/women/70.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Anna Montgomery",
    role: "Dancer",
    department: "Entertainment Department",
    bio: "Dancer Montgomery delivers energetic and polished routines, drawing on 20 years of dance training.",
    languages: ["English", "Haitian", "Guarani"],
    experienceYears: 20,
    profileImage: "https://randomuser.me/api/portraits/women/58.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Julie Crawford",
    role: "Choreographer",
    department: "Entertainment Department",
    bio: "Julie Crawford leads rehearsals and performance design to enhance the entertainment experience onboard.",
    languages: ["English", "French", "Portuguese"],
    experienceYears: 14,
    profileImage: "https://randomuser.me/api/portraits/women/40.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Ashley Hudson",
    role: "Comedy Performer",
    department: "Entertainment Department",
    bio: "Ashley Hudson entertains guests with humor and timing, backed by 22 years in comedy performance.",
    languages: ["English", "Haitian", "Spanish", "French"],
    experienceYears: 22,
    profileImage: "https://randomuser.me/api/portraits/women/77.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Jeffrey Lawson",
    role: "Magic Act",
    department: "Entertainment Department",
    bio: "Magic Act specialist Lawson mystifies audiences with skilled illusions and interactive performances.",
    languages: ["English", "Aymara", "Haitian", "Spanish"],
    experienceYears: 13,
    profileImage: "https://randomuser.me/api/portraits/men/22.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Zola Reed",
    role: "DJ",
    department: "Entertainment Department",
    bio: "Zola Reed utilizes professional mixing skills and an energetic presence to ensure high-energy parties and memorable nights for guests, backed by 22 years of club experience.",
    languages: ["English", "Portuguese", "Aymara"],
    experienceYears: 22,
    profileImage: "https://randomuser.me/api/portraits/women/58.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Sarah Hawkins",
    role: "Audio Technician",
    department: "Entertainment Department",
    bio: "With 17 years of experience in mixing live sound for theatre, music, and events, Sarah Hawkins guarantees crystal-clear audio for all onboard productions.",
    languages: ["English", "French", "Quechua"],
    experienceYears: 17,
    profileImage: "https://randomuser.me/api/portraits/women/84.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Sarah Holloway",
    role: "Lighting Specialist",
    department: "Entertainment Department",
    bio: "With 14 years in theatrical lighting design and operation, Sarah Holloway transforms stages and venues with dynamic and atmospheric lighting cues.",
    languages: ["English", "Quechua", "Aymara"],
    experienceYears: 14,
    profileImage: "https://randomuser.me/api/portraits/women/72.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Jerry Sutton",
    role: "Stage Manager",
    department: "Entertainment Department",
    bio: "Jerry Sutton's calm under pressure and attention to detail, honed over 19 years, are vital for delivering complex, multi-layered performances without a hitch.",
    languages: ["English", "Spanish", "Quechua", "Haitian"],
    experienceYears: 19,
    profileImage: "https://randomuser.me/api/portraits/men/58.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Amelia Henderson",
    role: "Production Manager",
    department: "Entertainment Department",
    bio: "Production Manager Henderson oversees logistics and technical coordination for large-scale entertainment productions.",
    languages: ["English", "Spanish", "Guarani", "French"],
    experienceYears: 9,
    profileImage: "https://randomuser.me/api/portraits/women/96.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Gabriella Wallace",
    role: "Costume Designer",
    department: "Entertainment Department",
    bio: "Costume Designer Wallace creates unique and period-appropriate costumes, enhancing visual storytelling in performances.",
    languages: ["English", "Quechua", "French", "Spanish"],
    experienceYears: 10,
    profileImage: "https://randomuser.me/api/portraits/women/55.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Bobby Keller",
    role: "Cultural Program Director",
    department: "Entertainment Department",
    bio: "Bobby Keller's passion for cultural exchange, cultivated over 13 years, enriches the voyage by fostering understanding and appreciation of diverse traditions.",
    languages: ["English", "Quechua", "Spanish"],
    experienceYears: 13,
    profileImage: "https://randomuser.me/api/portraits/men/15.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Victoria Jennings",
    role: "Performance Artist",
    department: "Entertainment Department",
    bio: "With 19 years pushing artistic boundaries, Victoria Jennings offers a distinctive and captivating addition to the ship's diverse entertainment offerings.",
    languages: ["English", "Aymara", "Guarani"],
    experienceYears: 19,
    profileImage: "https://randomuser.me/api/portraits/women/15.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Jonathan Price",
    role: "Operations Manager",
    department: "Operations Department",
    bio: "Jonathan Price plays a crucial role in port operations coordination, safety compliance oversight, and emergency response planning, backed by 7 years of maritime expertise.",
    languages: ["English", "Aymara", "Haitian"],
    experienceYears: 7,
    profileImage: "https://randomuser.me/api/portraits/men/49.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Leah Warren",
    role: "Logistics Coordinator",
    department: "Operations Department",
    bio: "With 4 years coordinating complex supply chains, Leah Warren ensures timely delivery of provisions, spare parts, and equipment essential for uninterrupted voyages.",
    languages: ["English", "French", "Aymara"],
    experienceYears: 4,
    profileImage: "https://randomuser.me/api/portraits/women/37.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Maya Hayes",
    role: "Inventory Specialist",
    department: "Operations Department",
    bio: "Inventory Specialist Hayes implements efficient stock rotation (FIFO) and conducts regular audits to prevent shortages and minimize waste.",
    languages: ["English", "French", "Quechua"],
    experienceYears: 9,
    profileImage: "https://randomuser.me/api/portraits/women/73.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Liam Hawkins",
    role: "Procurement Officer",
    department: "Operations Department",
    bio: "Procurement Officer Hawkins sources and negotiates contracts for goods and services needed onboard.",
    languages: ["English", "Portuguese", "Spanish", "Guarani"],
    experienceYears: 6,
    profileImage: "https://randomuser.me/api/portraits/men/41.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Stella Price",
    role: "Sustainability Coordinator",
    department: "Operations Department",
    bio: "With 12 years dedicated to environmental stewardship in the maritime sector, Stella Price develops and manages programs for waste reduction, recycling, and energy conservation.",
    languages: ["English", "Quechua", "Portuguese", "Haitian"],
    experienceYears: 12,
    profileImage: "https://randomuser.me/api/portraits/women/40.jpg",
    city: "New Orleans",
    country: "United States",
    region: "Caribbean",
  },
];
