import { CrewMember } from "@/lib/interfaces/people/staff";

export const seattleTeamMembers: CrewMember[] = [
  {
    name: "Aaron Cooper",
    role: "Captain",
    department: "Deck Department",
    bio: "With 21 years at sea, Captain Cooper is renowned for expertise in Alaska navigation, crew leadership, and passenger safety protocols.",
    languages: ["French", "Portuguese", "English"],
    experienceYears: 21,
    profileImage: "https://randomuser.me/api/portraits/men/14.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Austin Gibson",
    role: "First Officer",
    department: "Deck Department",
    bio: "Austin Gibson, with 14 years navigating Alaska, plays a vital role in safety drills, crew training, and maintaining navigational equipment.",
    languages: ["English", "Spanish", "French"],
    experienceYears: 14,
    profileImage: "https://randomuser.me/api/portraits/men/14.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Ralph Dean",
    role: "Second Officer",
    department: "Deck Department",
    bio: "Ralph Dean is skilled in passage planning software and integrated bridge systems, contributing 20 years of knowledge to operations in Alaska.",
    languages: ["Arabic", "German", "Spanish", "Mandarin", "English"],
    experienceYears: 20,
    profileImage: "https://randomuser.me/api/portraits/men/30.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Adeline Morgan",
    role: "Third Officer",
    department: "Deck Department",
    bio: "With 3 years dedicated to bridge operations, Adeline Morgan contributes to seamless voyages through Alaska's waterways by monitoring safety and compliance.",
    languages: ["Spanish", "French", "German", "Mandarin", "English"],
    experienceYears: 3,
    profileImage: "https://randomuser.me/api/portraits/women/45.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Nicholas Harper",
    role: "Navigation Officer",
    department: "Deck Department",
    bio: "Navigation Officer Harper maintains detailed voyage records and monitors navigation aids, ensuring compliance with maritime regulations in Alaska.",
    languages: ["Spanish", "French", "Arabic", "German", "English"],
    experienceYears: 19,
    profileImage: "https://randomuser.me/api/portraits/men/8.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Valentina Carpenter",
    role: "Safety Officer",
    department: "Deck Department",
    bio: "Valentina Carpenter enforces safety standards and conducts training programs, drawing on 4 years of maritime safety expertise to minimize risks onboard.",
    languages: [
      "German",
      "Portuguese",
      "French",
      "Japanese",
      "Mandarin",
      "Russian",
      "English",
    ],
    experienceYears: 4,
    profileImage: "https://randomuser.me/api/portraits/women/32.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Tyler Knight",
    role: "Deck Cadet",
    department: "Deck Department",
    bio: "As a dedicated Deck Cadet, Tyler Knight is gaining 20 years of hands-on knowledge in deck maintenance, watchkeeping, and safety procedures in Alaska.",
    languages: ["Portuguese", "Italian", "German", "English"],
    experienceYears: 20,
    profileImage: "https://randomuser.me/api/portraits/men/80.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Jack Ellis",
    role: "Bosun",
    department: "Deck Department",
    bio: "With 20 years managing deck teams, Jack Ellis coordinates tasks such as mooring, cargo handling, and routine repairs, maintaining operational readiness in Alaska.",
    languages: ["Russian", "English"],
    experienceYears: 20,
    profileImage: "https://randomuser.me/api/portraits/men/15.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Jacob Nash",
    role: "Chief Engineer",
    department: "Engineering Department",
    bio: "Jacob Nash brings 17 years of engineering excellence, leading innovations in sustainable maritime technology and driving continuous improvement in vessel operations.",
    languages: ["Italian", "Russian", "Arabic", "Spanish", "English"],
    experienceYears: 17,
    profileImage: "https://randomuser.me/api/portraits/men/18.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Austin Knight",
    role: "First Engineer",
    department: "Engineering Department",
    bio: "Austin Knight plays a key role in implementing engineering upgrades and system modifications, leveraging extensive technical knowledge.",
    languages: ["Arabic", "French", "English", "Russian", "Japanese"],
    experienceYears: 14,
    profileImage: "https://randomuser.me/api/portraits/men/25.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Carl Palmer",
    role: "Second Engineer",
    department: "Engineering Department",
    bio: "With 8 years of experience, Carl Palmer is responsible for specific auxiliary engines, boilers, and associated systems, ensuring their reliability.",
    languages: ["Italian", "French", "Arabic", "English"],
    experienceYears: 8,
    profileImage: "https://randomuser.me/api/portraits/men/9.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Louis Ellis",
    role: "Electrical Engineer",
    department: "Engineering Department",
    bio: "Drawing on 16 years, Louis Ellis ensures the integrity of high-voltage systems and sophisticated electronic controls throughout the vessel.",
    languages: ["Spanish", "Italian", "English"],
    experienceYears: 16,
    profileImage: "https://randomuser.me/api/portraits/men/33.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Christine Payne",
    role: "Mechanical Engineer",
    department: "Engineering Department",
    bio: "Christine Payne's problem-solving abilities are crucial for addressing unexpected mechanical challenges, ensuring vessel safety and uptime through 12 years of service.",
    languages: ["Italian", "Arabic", "English"],
    experienceYears: 12,
    profileImage: "https://randomuser.me/api/portraits/women/44.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Joan Harper",
    role: "HVAC Engineer",
    department: "Engineering Department",
    bio: "With expertise in refrigeration cycles and ventilation design, Joan Harper addresses environmental control challenges in varying maritime conditions.",
    languages: ["Russian", "Mandarin", "English"],
    experienceYears: 13,
    profileImage: "https://randomuser.me/api/portraits/women/71.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Amanda Baker",
    role: "Environmental Engineer",
    department: "Engineering Department",
    bio: "With in-depth knowledge of MARPOL regulations, Amanda Baker leads training and awareness programs on environmental best practices among crew members.",
    languages: ["Russian", "German", "English"],
    experienceYears: 22,
    profileImage: "https://randomuser.me/api/portraits/women/30.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Ethan Maxwell",
    role: "Systems Engineer",
    department: "Engineering Department",
    bio: "Ethan Maxwell manages system diagnostics and upgrades to improve vessel performance and crew operational efficiency.",
    languages: ["Mandarin", "Spanish", "English"],
    experienceYears: 20,
    profileImage: "https://randomuser.me/api/portraits/men/35.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Linda Foster",
    role: "Technical Manager",
    department: "Engineering Department",
    bio: "Known for strong leadership, Linda Foster fosters a culture of technical excellence and cross-functional collaboration onboard.",
    languages: ["Italian", "Arabic", "Spanish", "English"],
    experienceYears: 18,
    profileImage: "https://randomuser.me/api/portraits/women/55.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Ronald Payne",
    role: "Maintenance Engineer",
    department: "Engineering Department",
    bio: "Maintenance Engineer Payne's 12 years include managing workshop resources and training junior staff in effective repair techniques.",
    languages: ["Japanese", "Arabic", "English"],
    experienceYears: 12,
    profileImage: "https://randomuser.me/api/portraits/men/51.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Bobby Crawford",
    role: "Security Director",
    department: "Security Department",
    bio: "Security Director Crawford has 11 years of experience liaising with international maritime security agencies and port authorities.",
    languages: ["Mandarin", "Russian", "English"],
    experienceYears: 11,
    profileImage: "https://randomuser.me/api/portraits/men/26.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Christine Hudson",
    role: "Security Officer",
    department: "Security Department",
    bio: "Focused on maintaining order, Christine Hudson collaborates with other departments to enhance overall passenger and crew safety.",
    languages: [
      "French",
      "Japanese",
      "Italian",
      "Portuguese",
      "German",
      "English",
    ],
    experienceYears: 19,
    profileImage: "https://randomuser.me/api/portraits/women/16.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Andrew Spencer",
    role: "Security Specialist",
    department: "Security Department",
    bio: "Known for analytical expertise, Andrew Spencer conducts vulnerability assessments and designs contingency plans to address evolving threats.",
    languages: ["English", "Italian"],
    experienceYears: 15,
    profileImage: "https://randomuser.me/api/portraits/men/10.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Michael Hawkins",
    role: "Cybersecurity Officer",
    department: "Security Department",
    bio: "Cybersecurity Officer Hawkins conducts regular penetration testing and vulnerability assessments of ship systems, drawing on 4 years of expertise.",
    languages: ["German", "English", "Portuguese", "Japanese"],
    experienceYears: 4,
    profileImage: "https://randomuser.me/api/portraits/men/12.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Catherine Wells",
    role: "Maritime Security Coordinator",
    department: "Security Department",
    bio: "Catherine Wells coordinates security protocols and emergency responses, drawing on 7 years in maritime operations and multi-agency collaboration.",
    languages: ["Italian", "Japanese", "English"],
    experienceYears: 7,
    profileImage: "https://randomuser.me/api/portraits/women/55.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Philip Maxwell",
    role: "Access Control Officer",
    department: "Security Department",
    bio: "Philip Maxwell ensures all personnel and visitors comply with security clearance, manifests, and international maritime access regulations.",
    languages: ["Mandarin", "Spanish", "Portuguese", "Italian", "English"],
    experienceYears: 15,
    profileImage: "https://randomuser.me/api/portraits/men/31.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Samantha Watson",
    role: "Safety Compliance Officer",
    department: "Security Department",
    bio: "With a thorough understanding of hazard identification and mitigation, Samantha Watson leads incident investigations and corrective action plans.",
    languages: ["English", "Spanish", "Portuguese", "Italian"],
    experienceYears: 11,
    profileImage: "https://randomuser.me/api/portraits/women/73.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Jose Fisher",
    role: "Youth Program Director",
    department: "Youth & Family Programs",
    bio: "Jose Fisher designs and leads engaging youth programs, applying 10 years in educational, recreational, and developmental management onboard.",
    languages: ["French", "Italian", "Mandarin", "Japanese", "English"],
    experienceYears: 10,
    profileImage: "https://randomuser.me/api/portraits/men/73.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Lawrence Hamilton",
    role: "Family Activities Coordinator",
    department: "Youth & Family Programs",
    bio: "Family Activities Coordinator Hamilton gathers feedback to adapt programs that enhance passenger satisfaction and engagement.",
    languages: ["Russian", "Portuguese", "English"],
    experienceYears: 6,
    profileImage: "https://randomuser.me/api/portraits/men/84.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Nicholas Carpenter",
    role: "Children's Entertainment Specialist",
    department: "Youth & Family Programs",
    bio: "Nicholas Carpenter is passionate about sparking imagination, developing new and exciting entertainment formats for kids over 11 years in the field.",
    languages: ["Mandarin", "Portuguese", "English"],
    experienceYears: 11,
    profileImage: "https://randomuser.me/api/portraits/men/50.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Bruce Carpenter",
    role: "Teen Activities Coordinator",
    department: "Youth & Family Programs",
    bio: "Leveraging 7 years working with adolescents, Bruce Carpenter creates cool and engaging hangouts and events that resonate with teens.",
    languages: ["English", "Japanese"],
    experienceYears: 7,
    profileImage: "https://randomuser.me/api/portraits/men/10.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Victor Curtis",
    role: "Educational Program Manager",
    department: "Youth & Family Programs",
    bio: "Educational Program Manager Curtis forges partnerships with guest speakers and institutions to provide high-quality learning experiences, leveraging 15 years of networking.",
    languages: [
      "Russian",
      "French",
      "Spanish",
      "Japanese",
      "Mandarin",
      "English",
    ],
    experienceYears: 15,
    profileImage: "https://randomuser.me/api/portraits/men/94.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Wei Dunn",
    role: "Child Care Specialist",
    department: "Youth & Family Programs",
    bio: "Known for patience and professionalism, Wei Dunn communicates effectively with parents and crew to support child wellbeing.",
    languages: ["Arabic", "Spanish", "English"],
    experienceYears: 16,
    profileImage: "https://randomuser.me/api/portraits/men/39.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Louis Dunn",
    role: "Activities Director",
    department: "Activities & Recreation",
    bio: "Louis Dunn plans and coordinates all recreational activities, utilizing 4 years of event management expertise to create engaging, inclusive programs.",
    languages: ["Portuguese", "Mandarin", "English"],
    experienceYears: 4,
    profileImage: "https://randomuser.me/api/portraits/men/58.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Elijah Dixon",
    role: "Water Sports Instructor",
    department: "Activities & Recreation",
    bio: "Elijah Dixon's primary focus for 16 years has been ensuring every guest feels confident and secure while exploring the water.",
    languages: ["English", "Mandarin", "Spanish", "Italian"],
    experienceYears: 16,
    profileImage: "https://randomuser.me/api/portraits/men/73.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Oliver Campbell",
    role: "Fitness Instructor",
    department: "Activities & Recreation",
    bio: "Fitness Instructor Campbell provides nutritional advice and wellness coaching, empowering guests to achieve their health goals over 4 years.",
    languages: [
      "Italian",
      "Mandarin",
      "Spanish",
      "Russian",
      "Arabic",
      "English",
    ],
    experienceYears: 4,
    profileImage: "https://randomuser.me/api/portraits/men/64.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Joseph Maxwell",
    role: "Excursion Coordinator",
    department: "Activities & Recreation",
    bio: "Excursion Coordinator Maxwell has built strong relationships with local tour operators worldwide over 20 years, guaranteeing quality and value.",
    languages: ["Russian", "French", "German", "Italian", "Spanish", "English"],
    experienceYears: 20,
    profileImage: "https://randomuser.me/api/portraits/men/49.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Ariana Stewart",
    role: "Lead Photographer",
    department: "Photography & Videography",
    bio: "With extensive experience in portrait, event, and environmental photography, Ariana Stewart ensures high-quality imagery that reflects the voyage’s unique character.",
    languages: ["Italian", "Arabic", "English"],
    experienceYears: 22,
    profileImage: "https://randomuser.me/api/portraits/women/68.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Mary Day",
    role: "Videographer",
    department: "Photography & Videography",
    bio: "Mary Day uses 5 years of editing expertise to transform raw footage into engaging narratives that resonate with passengers and promote future voyages.",
    languages: ["Portuguese", "Italian", "German", "English"],
    experienceYears: 5,
    profileImage: "https://randomuser.me/api/portraits/women/43.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Mary Marshall",
    role: "Digital Media Specialist",
    department: "Photography & Videography",
    bio: "Digital Media Specialist Marshall analyzes content performance and audience metrics to optimize digital strategies and engagement.",
    languages: ["Spanish", "Portuguese", "Mandarin", "English"],
    experienceYears: 17,
    profileImage: "https://randomuser.me/api/portraits/women/82.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Luis Coleman",
    role: "Chief Medical Officer",
    department: "Health & Safety",
    bio: "Chief Medical Officer Coleman leads all medical operations onboard, leveraging 18 years of clinical and maritime healthcare expertise to ensure passenger and crew wellbeing.",
    languages: ["Russian", "Portuguese", "Japanese", "Mandarin", "English"],
    experienceYears: 18,
    profileImage: "https://randomuser.me/api/portraits/men/70.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Brenda Wells",
    role: "Ship's Doctor",
    department: "Health & Safety",
    bio: "Dr. Wells collaborates with medical officers and safety teams to uphold the highest health standards aboard.",
    languages: ["English", "German", "Mandarin", "Arabic"],
    experienceYears: 10,
    profileImage: "https://randomuser.me/api/portraits/women/74.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Isabella Henderson",
    role: "Nurse",
    department: "Health & Safety",
    bio: "Nurse Henderson provides empathetic and skilled assistance, ensuring patient comfort and adherence to strict hygiene and infection control protocols.",
    languages: ["Portuguese", "Japanese", "English"],
    experienceYears: 19,
    profileImage: "https://randomuser.me/api/portraits/women/17.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Sarah Marshall",
    role: "Safety Officer",
    department: "Health & Safety",
    bio: "Safety Officer Marshall works proactively to prevent accidents by inspecting equipment, conducting drills, and ensuring regulatory compliance.",
    languages: ["Japanese", "Italian", "Spanish", "Portuguese", "English"],
    experienceYears: 7,
    profileImage: "https://randomuser.me/api/portraits/women/20.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Logan Henderson",
    role: "Hospitality Director",
    department: "Hospitality Department",
    bio: "Overseeing a diverse team, Hospitality Director Henderson implements innovative service strategies and maintains the highest quality standards, reflecting 11 years in the industry.",
    languages: ["French", "Japanese", "English"],
    experienceYears: 11,
    profileImage: "https://randomuser.me/api/portraits/men/83.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Gerald Wells",
    role: "Guest Relations Manager",
    department: "Hospitality Department",
    bio: "Gerald Wells champions a guest-first culture, utilizing 20 years of experience to train and motivate staff in delivering exceptional, personalized care.",
    languages: ["Mandarin", "French", "Italian", "English"],
    experienceYears: 20,
    profileImage: "https://randomuser.me/api/portraits/men/49.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Jason Bennett",
    role: "Chief Steward",
    department: "Hospitality Department",
    bio: "Chief Steward Bennett trains and mentors the housekeeping staff, instilling a keen eye for detail and a commitment to impeccable service honed over 18 years.",
    languages: ["Spanish", "Portuguese", "French", "English"],
    experienceYears: 18,
    profileImage: "https://randomuser.me/api/portraits/men/23.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Julie Douglas",
    role: "Senior Steward",
    department: "Hospitality Department",
    bio: "Julie Douglas provides exceptional valet services and anticipates guest needs, contributing to a luxurious and comfortable onboard experience over 4 years.",
    languages: ["French", "Portuguese", "Russian", "English"],
    experienceYears: 4,
    profileImage: "https://randomuser.me/api/portraits/women/51.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Melissa Baker",
    role: "Butler",
    department: "Hospitality Department",
    bio: "Butler Baker provides personalized guest services, backed by 4 years of elite hospitality expertise.",
    languages: ["Japanese", "Arabic", "English"],
    experienceYears: 4,
    profileImage: "https://randomuser.me/api/portraits/women/74.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Brandon Hayes",
    role: "Accommodation Manager",
    department: "Hospitality Department",
    bio: "Accommodation Manager Hayes coordinates housekeeping and maintenance teams for optimal guest satisfaction.",
    languages: ["German", "Mandarin", "English"],
    experienceYears: 18,
    profileImage: "https://randomuser.me/api/portraits/men/28.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Valentina Spencer",
    role: "Housekeeping Supervisor",
    department: "Hospitality Department",
    bio: "With a keen eye for detail developed over 13 years, Housekeeping Supervisor Spencer conducts rigorous inspections to uphold pristine conditions.",
    languages: ["Arabic", "Mandarin", "English"],
    experienceYears: 13,
    profileImage: "https://randomuser.me/api/portraits/women/90.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Emma Palmer",
    role: "Guest Services Specialist",
    department: "Hospitality Department",
    bio: "With 21 years providing frontline support, Emma Palmer is adept at information sharing, problem-solving, and ensuring guests feel valued and well-informed.",
    languages: ["Mandarin", "English", "Japanese", "German"],
    experienceYears: 21,
    profileImage: "https://randomuser.me/api/portraits/women/3.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Gabriella Marshall",
    role: "Concierge",
    department: "Hospitality Department",
    bio: "Concierge Marshall offers expert local knowledge and personalized recommendations to enrich guest journeys.",
    languages: ["Arabic", "English"],
    experienceYears: 8,
    profileImage: "https://randomuser.me/api/portraits/women/56.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Philip Fox",
    role: "Front Desk Manager",
    department: "Hospitality Department",
    bio: "Philip Fox leads front office teams with a focus on excellent customer service and operational efficiency.",
    languages: ["Portuguese", "Mandarin", "German", "English"],
    experienceYears: 6,
    profileImage: "https://randomuser.me/api/portraits/men/59.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Blake Foster",
    role: "VIP Coordinator",
    department: "Hospitality Department",
    bio: "VIP Coordinator Foster liaises with all departments to provide seamless, anticipatory service for distinguished guests, maintaining utmost confidentiality.",
    languages: ["French", "Russian", "English"],
    experienceYears: 21,
    profileImage: "https://randomuser.me/api/portraits/men/13.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Scarlett Clark",
    role: "Hospitality Trainer",
    department: "Hospitality Department",
    bio: "Scarlett Clark develops training programs to elevate hospitality team skills, with 17 years in workforce development.",
    languages: ["German", "Russian", "English"],
    experienceYears: 17,
    profileImage: "https://randomuser.me/api/portraits/women/97.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Gary Price",
    role: "Executive Chef",
    department: "Culinary Department",
    bio: "Mastering Mediterranean and international gastronomy, Gary Price ensures every dish reflects the highest standards of quality, presentation, and flavor, backed by 14 years of award-winning experience.",
    languages: [
      "Arabic",
      "Mandarin",
      "Portuguese",
      "German",
      "English",
      "Russian",
    ],
    experienceYears: 14,
    profileImage: "https://randomuser.me/api/portraits/men/6.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Gregory Hunter",
    role: "Sous Chef",
    department: "Culinary Department",
    bio: "As second-in-command, Sous Chef Hunter ensures seamless kitchen workflow and consistent dish quality, drawing on 11 years of hands-on Caribbean experience.",
    languages: ["Japanese", "German", "English"],
    experienceYears: 11,
    profileImage: "https://randomuser.me/api/portraits/men/5.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Maya Parker",
    role: "Pastry Chef",
    department: "Culinary Department",
    bio: "With a passion for sweet masterpieces, Pastry Chef Parker continually develops new recipes, delighting guests with 21 years of dedication to the art of patisserie.",
    languages: ["English", "Arabic", "Spanish", "German"],
    experienceYears: 21,
    profileImage: "https://randomuser.me/api/portraits/women/64.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Hannah Hamilton",
    role: "Chef de Partie",
    department: "Culinary Department",
    bio: "With 14 years as a section chef, Hannah Hamilton is responsible for stock control and guiding commis chefs within their designated area of the Nordic kitchen.",
    languages: ["Japanese", "English"],
    experienceYears: 14,
    profileImage: "https://randomuser.me/api/portraits/women/41.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Paul Russell",
    role: "Specialty Chef",
    department: "Culinary Department",
    bio: "Master of {cuisineSpecific} cuisine, Paul Russell creates authentic dishes that transport guests to Alaska, drawing on 21 years of dedicated culinary exploration.",
    languages: ["Russian", "French", "English"],
    experienceYears: 21,
    profileImage: "https://randomuser.me/api/portraits/men/37.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Ryan Marshall",
    role: "Sushi Chef",
    department: "Culinary Department",
    bio: "With 12 years dedicated to the art of sushi and sashimi, Chef Marshall meticulously selects the freshest seafood and crafts each piece with mastery.",
    languages: [
      "Italian",
      "Portuguese",
      "Spanish",
      "Russian",
      "French",
      "English",
    ],
    experienceYears: 12,
    profileImage: "https://randomuser.me/api/portraits/men/53.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Chloe Warren",
    role: "Garde Manger",
    department: "Culinary Department",
    bio: "Garde Manger Warren ensures all cold food items are stored and handled with the utmost care, upholding critical food safety protocols over 6 years.",
    languages: ["English", "Spanish", "Japanese", "Portuguese"],
    experienceYears: 6,
    profileImage: "https://randomuser.me/api/portraits/women/15.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Nomsa Hayes",
    role: "Butcher",
    department: "Culinary Department",
    bio: "With 11 years of expertise, Butcher Hayes expertly handles all meat and poultry, providing custom cuts and ensuring optimal yield for various Nordic dishes.",
    languages: ["Arabic", "Spanish", "French", "Russian", "English"],
    experienceYears: 11,
    profileImage: "https://randomuser.me/api/portraits/women/93.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Nancy Graham",
    role: "Baker",
    department: "Culinary Department",
    bio: "Nancy Graham combines traditional techniques with innovation to delight guests with baked specialties.",
    languages: ["English", "Japanese", "German", "Mandarin", "Arabic"],
    experienceYears: 10,
    profileImage: "https://randomuser.me/api/portraits/women/75.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Harper Chambers",
    role: "Sommelier",
    department: "Culinary Department",
    bio: "Harper Chambers enhances dining experiences by sourcing and recommending premium wines.",
    languages: ["French", "Mandarin", "Japanese", "German", "English"],
    experienceYears: 14,
    profileImage: "https://randomuser.me/api/portraits/women/22.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Betty Graves",
    role: "Mixologist",
    department: "Culinary Department",
    bio: "Mixologist Graves delights guests with flair, technique, and a deep understanding of flavor profiles, creating personalized drink experiences over 6 years.",
    languages: ["Italian", "Spanish", "English"],
    experienceYears: 6,
    profileImage: "https://randomuser.me/api/portraits/women/83.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Sophia Fisher",
    role: "Barista",
    department: "Culinary Department",
    bio: "With 21 years of expertise in coffee origins, brewing methods, and latte art, Sophia Fisher crafts the perfect cup for every guest.",
    languages: [
      "Italian",
      "Japanese",
      "German",
      "French",
      "Russian",
      "English",
    ],
    experienceYears: 21,
    profileImage: "https://randomuser.me/api/portraits/women/72.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Joel Baker",
    role: "Nutritionist",
    department: "Culinary Department",
    bio: "With 7 years in clinical and culinary nutrition, Joel Baker provides personalized dietary consultations and develops specialized meal plans for guests with specific needs.",
    languages: ["Portuguese", "English", "Spanish"],
    experienceYears: 7,
    profileImage: "https://randomuser.me/api/portraits/men/83.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Nora Marshall",
    role: "Entertainment Director",
    department: "Entertainment Department",
    bio: "Entertainment Director Marshall curates diverse programming to engage and delight guests throughout voyages.",
    languages: ["Portuguese", "Japanese", "Russian", "English"],
    experienceYears: 13,
    profileImage: "https://randomuser.me/api/portraits/women/14.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Sean Crawford",
    role: "Performance Coordinator",
    department: "Entertainment Department",
    bio: "Performance Coordinator Crawford serves as the key liaison between artists, production staff, and management, ensuring clear communication and efficient problem-solving.",
    languages: ["Russian", "Portuguese", "English"],
    experienceYears: 13,
    profileImage: "https://randomuser.me/api/portraits/men/83.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Philip Morgan",
    role: "Lead Vocalist",
    department: "Entertainment Department",
    bio: "As a key figure in production shows, Lead Vocalist Morgan collaborates with the cast and creative team, bringing 4 years of professional discipline and artistry.",
    languages: [
      "Arabic",
      "Russian",
      "Portuguese",
      "English",
      "Mandarin",
      "Japanese",
    ],
    experienceYears: 4,
    profileImage: "https://randomuser.me/api/portraits/men/73.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Paul Graves",
    role: "Musician",
    department: "Entertainment Department",
    bio: "Musician Graves performs live music across genres, engaging guests with 15 years of performance experience.",
    languages: [
      "Mandarin",
      "Japanese",
      "Arabic",
      "German",
      "Russian",
      "English",
    ],
    experienceYears: 15,
    profileImage: "https://randomuser.me/api/portraits/men/52.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Jordan Marshall",
    role: "Dancer",
    department: "Entertainment Department",
    bio: "Jordan Marshall engages audiences with versatile dance styles across entertainment programs.",
    languages: ["Italian", "French", "Japanese", "Mandarin", "English"],
    experienceYears: 17,
    profileImage: "https://randomuser.me/api/portraits/men/75.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Maria Campbell",
    role: "Choreographer",
    department: "Entertainment Department",
    bio: "Maria Campbell leads rehearsals and performance design to enhance the entertainment experience onboard.",
    languages: ["Arabic", "Russian", "English", "Spanish"],
    experienceYears: 16,
    profileImage: "https://randomuser.me/api/portraits/women/84.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Janet Graves",
    role: "Comedy Performer",
    department: "Entertainment Department",
    bio: "Comedy Performer Graves masterfully crafts clean and engaging sets suitable for a cruise environment, ensuring evenings are filled with laughter and amusement.",
    languages: ["English", "Russian", "French", "Spanish", "Japanese"],
    experienceYears: 22,
    profileImage: "https://randomuser.me/api/portraits/women/75.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Jessica Griffin",
    role: "Magic Act",
    department: "Entertainment Department",
    bio: "Magic Act specialist Griffin mystifies audiences with skilled illusions and interactive performances.",
    languages: ["German", "Russian", "French", "Japanese", "English"],
    experienceYears: 13,
    profileImage: "https://randomuser.me/api/portraits/women/79.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Michelle Graham",
    role: "DJ",
    department: "Entertainment Department",
    bio: "DJ Graham creates vibrant atmospheres with expertly mixed music, drawing on 9 years in live DJing.",
    languages: ["English", "Arabic", "Mandarin", "Russian"],
    experienceYears: 9,
    profileImage: "https://randomuser.me/api/portraits/women/50.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Gerald Dixon",
    role: "Audio Technician",
    department: "Entertainment Department",
    bio: "Gerald Dixon supports entertainment events with technical expertise in live sound engineering.",
    languages: ["Portuguese", "Japanese", "English"],
    experienceYears: 5,
    profileImage: "https://randomuser.me/api/portraits/men/76.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Sofia Fletcher",
    role: "Lighting Specialist",
    department: "Entertainment Department",
    bio: "Sofia Fletcher applies 4 years of technical skill to create immersive visual experiences.",
    languages: ["Italian", "Russian", "English"],
    experienceYears: 4,
    profileImage: "https://randomuser.me/api/portraits/women/35.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Rachel Dean",
    role: "Stage Manager",
    department: "Entertainment Department",
    bio: "Rachel Dean supervises stage operations and talent, drawing on 7 years of event management.",
    languages: ["Japanese", "Arabic", "English"],
    experienceYears: 7,
    profileImage: "https://randomuser.me/api/portraits/women/92.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Pamela Dixon",
    role: "Production Manager",
    department: "Entertainment Department",
    bio: "Pamela Dixon ensures timely and efficient delivery of shows, leveraging 6 years in production management.",
    languages: ["Mandarin", "English", "Italian", "Russian"],
    experienceYears: 6,
    profileImage: "https://randomuser.me/api/portraits/women/8.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Christopher Dean",
    role: "Costume Designer",
    department: "Entertainment Department",
    bio: "With 7 years of experience in theatrical costume design, Christopher Dean conceives and produces stunning wardrobes that define characters and elevate productions.",
    languages: ["French", "Spanish", "Mandarin", "English"],
    experienceYears: 7,
    profileImage: "https://randomuser.me/api/portraits/men/74.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Gabriella Mitchell",
    role: "Cultural Program Director",
    department: "Entertainment Department",
    bio: "Gabriella Mitchell's passion for cultural exchange, cultivated over 3 years, enriches the voyage by fostering understanding and appreciation of diverse traditions.",
    languages: ["Spanish", "Arabic", "Portuguese", "Mandarin", "English"],
    experienceYears: 3,
    profileImage: "https://randomuser.me/api/portraits/women/42.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Arthur Coleman",
    role: "Performance Artist",
    department: "Entertainment Department",
    bio: "Arthur Coleman captivates audiences with original performances tailored to shipboard entertainment.",
    languages: ["English", "Spanish", "Italian"],
    experienceYears: 14,
    profileImage: "https://randomuser.me/api/portraits/men/71.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Sarah Palmer",
    role: "Operations Manager",
    department: "Operations Department",
    bio: "Operations Manager Palmer is adept at problem-solving complex logistical challenges and implementing solutions that enhance overall ship performance and guest satisfaction.",
    languages: ["Spanish", "Japanese", "Portuguese", "English"],
    experienceYears: 3,
    profileImage: "https://randomuser.me/api/portraits/women/56.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Joseph Chambers",
    role: "Logistics Coordinator",
    department: "Operations Department",
    bio: "With 19 years coordinating complex supply chains, Joseph Chambers ensures timely delivery of provisions, spare parts, and equipment essential for uninterrupted voyages.",
    languages: ["Russian", "Spanish", "English"],
    experienceYears: 19,
    profileImage: "https://randomuser.me/api/portraits/men/48.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Emma Parker",
    role: "Inventory Specialist",
    department: "Operations Department",
    bio: "With 13 years in inventory management, Emma Parker meticulously maintains records for all consumables, technical spares, and retail goods onboard.",
    languages: ["Japanese", "Mandarin", "English"],
    experienceYears: 13,
    profileImage: "https://randomuser.me/api/portraits/women/72.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Darrell Porter",
    role: "Procurement Officer",
    department: "Operations Department",
    bio: "Procurement Officer Porter manages supplier relationships, monitors market trends, and ensures compliance with ethical purchasing policies.",
    languages: ["Italian", "Arabic", "German", "English"],
    experienceYears: 3,
    profileImage: "https://randomuser.me/api/portraits/men/39.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
  {
    name: "Naomi Curtis",
    role: "Sustainability Coordinator",
    department: "Operations Department",
    bio: "With 19 years dedicated to environmental stewardship in the maritime sector, Naomi Curtis develops and manages programs for waste reduction, recycling, and energy conservation.",
    languages: ["Mandarin", "Arabic", "Spanish", "French", "English"],
    experienceYears: 19,
    profileImage: "https://randomuser.me/api/portraits/women/39.jpg",
    city: "Seattle",
    country: "United States",
    region: "Alaska",
  },
];
