import { CrewMember } from "@/lib/interfaces/people/staff";

export const tampaTeamMembers: CrewMember[] = [
  {
    name: "Randy Graves",
    role: "Captain",
    department: "Deck Department",
    bio: "Captain Graves's strategic decision-making and crisis management skills, honed over 18 years, ensure smooth and safe voyages throughout Caribbean.",
    languages: ["English", "French", "Guarani"],
    experienceYears: 18,
    profileImage: "https://randomuser.me/api/portraits/men/50.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Gabriel Knight",
    role: "First Officer",
    department: "Deck Department",
    bio: "Gabriel Knight, with 6 years navigating Caribbean, plays a vital role in safety drills, crew training, and maintaining navigational equipment.",
    languages: ["English", "Haitian", "French"],
    experienceYears: 6,
    profileImage: "https://randomuser.me/api/portraits/men/55.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Dorothy Ellis",
    role: "Second Officer",
    department: "Deck Department",
    bio: "Dorothy Ellis plays a critical role in voyage planning and watchkeeping, backed by 3 years ensuring operational integrity in Caribbean.",
    languages: ["English", "French", "Aymara"],
    experienceYears: 3,
    profileImage: "https://randomuser.me/api/portraits/women/35.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Samantha Harper",
    role: "Third Officer",
    department: "Deck Department",
    bio: "Samantha Harper's expertise in safety and lifesaving equipment maintenance comes from 13 years at sea within Caribbean, ensuring crew and passenger preparedness.",
    languages: ["English", "Quechua", "French"],
    experienceYears: 13,
    profileImage: "https://randomuser.me/api/portraits/women/36.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Jennifer Henderson",
    role: "Navigation Officer",
    department: "Deck Department",
    bio: "Experienced in electronic chart systems (ECDIS) and radar, Jennifer Henderson has 4 years navigating the complex and often congested waters of Caribbean.",
    languages: ["English", "French", "Haitian"],
    experienceYears: 4,
    profileImage: "https://randomuser.me/api/portraits/women/23.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Isabella Grant",
    role: "Safety Officer",
    department: "Deck Department",
    bio: "Safety Officer Grant documents incidents and implements corrective actions to continuously improve onboard safety performance.",
    languages: ["English", "Aymara", "Portuguese"],
    experienceYears: 6,
    profileImage: "https://randomuser.me/api/portraits/women/68.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Louis Dean",
    role: "Deck Cadet",
    department: "Deck Department",
    bio: "Deck Cadet Dean learns shipboard operations under experienced officers, preparing for a future leadership role in Caribbean waters.",
    languages: ["English", "French", "Quechua"],
    experienceYears: 9,
    profileImage: "https://randomuser.me/api/portraits/men/61.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Skylar Russell",
    role: "Bosun",
    department: "Deck Department",
    bio: "Leveraging 13 years of seamanship, Bosun Russell is an expert in rigging, anchoring, and all aspects of deck machinery operation in Caribbean.",
    languages: ["English", "Quechua", "Spanish"],
    experienceYears: 13,
    profileImage: "https://randomuser.me/api/portraits/women/84.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Dylan Henderson",
    role: "Chief Engineer",
    department: "Engineering Department",
    bio: "Chief Engineer Henderson's extensive 13-year background includes overseeing major overhauls and ensuring peak operational readiness of all machinery.",
    languages: ["English", "Quechua", "Guarani"],
    experienceYears: 13,
    profileImage: "https://randomuser.me/api/portraits/men/73.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Timothy Sutton",
    role: "First Engineer",
    department: "Engineering Department",
    bio: "With 4 years in marine engineering, Timothy Sutton excels in diagnosing faults and executing prompt, effective repairs to critical shipboard machinery.",
    languages: ["English", "Portuguese", "Guarani"],
    experienceYears: 4,
    profileImage: "https://randomuser.me/api/portraits/men/82.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Elizabeth Knight",
    role: "Second Engineer",
    department: "Engineering Department",
    bio: "Second Engineer Knight conducts routine inspections and coordinates repairs for critical propulsion and auxiliary machinery.",
    languages: ["English", "Haitian", "Aymara", "Guarani"],
    experienceYears: 7,
    profileImage: "https://randomuser.me/api/portraits/women/91.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Maya Douglas",
    role: "Electrical Engineer",
    department: "Engineering Department",
    bio: "With 14 years designing, installing, and maintaining vessel electrical infrastructure, Maya Douglas ensures continuous power supply and safety.",
    languages: ["English", "Portuguese", "Guarani", "Haitian"],
    experienceYears: 14,
    profileImage: "https://randomuser.me/api/portraits/women/97.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Diego Baker",
    role: "Mechanical Engineer",
    department: "Engineering Department",
    bio: "Diego Baker's problem-solving abilities are crucial for addressing unexpected mechanical challenges, ensuring vessel safety and uptime through 19 years of service.",
    languages: ["English", "Guarani", "Spanish"],
    experienceYears: 19,
    profileImage: "https://randomuser.me/api/portraits/men/47.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Audrey Douglas",
    role: "HVAC Engineer",
    department: "Engineering Department",
    bio: "Audrey Douglas monitors system performance and implements upgrades to enhance passenger comfort and crew wellbeing.",
    languages: ["English", "Guarani", "Portuguese"],
    experienceYears: 17,
    profileImage: "https://randomuser.me/api/portraits/women/42.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Amina Hudson",
    role: "Environmental Engineer",
    department: "Engineering Department",
    bio: "Amina Hudson conducts environmental impact assessments to support sustainable voyage planning and operational improvements.",
    languages: ["English", "Quechua", "French"],
    experienceYears: 4,
    profileImage: "https://randomuser.me/api/portraits/women/61.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Henry Parker",
    role: "Systems Engineer",
    department: "Engineering Department",
    bio: "Drawing upon 18 years, Henry Parker specializes in the architecture and maintenance of integrated automation systems (IAS) critical for modern vessel operations.",
    languages: ["English", "Aymara", "Quechua", "Portuguese"],
    experienceYears: 18,
    profileImage: "https://randomuser.me/api/portraits/men/77.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Adam Gibson",
    role: "Technical Manager",
    department: "Engineering Department",
    bio: "Technical Manager Gibson oversees budgeting, procurement, and scheduling of maintenance to optimize vessel availability and lifecycle costs.",
    languages: ["English", "Quechua", "Haitian"],
    experienceYears: 9,
    profileImage: "https://randomuser.me/api/portraits/men/97.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Deborah Griffin",
    role: "Maintenance Engineer",
    department: "Engineering Department",
    bio: "Maintenance Engineer Griffin troubleshoots system faults and implements timely repairs, maintaining vessel operational readiness.",
    languages: ["English", "Guarani", "Portuguese"],
    experienceYears: 7,
    profileImage: "https://randomuser.me/api/portraits/women/22.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Christian Dunn",
    role: "Security Director",
    department: "Security Department",
    bio: "Known for decisive leadership, Christian Dunn fosters a culture of vigilance and continuous improvement in maritime security standards.",
    languages: ["English", "Aymara", "Guarani"],
    experienceYears: 13,
    profileImage: "https://randomuser.me/api/portraits/men/66.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Avery Crawford",
    role: "Security Officer",
    department: "Security Department",
    bio: "Avery Crawford conducts routine security patrols and enforces safety regulations, backed by 17 years in maritime security operations and incident response.",
    languages: ["English", "Quechua", "Portuguese"],
    experienceYears: 17,
    profileImage: "https://randomuser.me/api/portraits/women/14.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Chloe Harper",
    role: "Security Specialist",
    department: "Security Department",
    bio: "Chloe Harper provides expert assessment and response coordination to maritime security challenges, leveraging advanced knowledge in risk management and compliance.",
    languages: ["English", "French", "Haitian"],
    experienceYears: 11,
    profileImage: "https://randomuser.me/api/portraits/women/63.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Virginia Hall",
    role: "Cybersecurity Officer",
    department: "Security Department",
    bio: "Leveraging 13 years in cyber defense, Virginia Hall specializes in securing operational technology (OT) unique to maritime assets.",
    languages: ["English", "Aymara", "French", "Haitian"],
    experienceYears: 13,
    profileImage: "https://randomuser.me/api/portraits/women/13.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Cynthia Graves",
    role: "Maritime Security Coordinator",
    department: "Security Department",
    bio: "With 22 years in the role, Cynthia Graves is adept at developing and updating the Ship Security Plan (SSP) and ensuring its effective implementation.",
    languages: ["English", "Quechua", "Spanish"],
    experienceYears: 22,
    profileImage: "https://randomuser.me/api/portraits/women/91.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Dennis Crawford",
    role: "Access Control Officer",
    department: "Security Department",
    bio: "Access Control Officer Crawford manages secure boarding and access with 22 years maintaining maritime entry protocols and identification verification.",
    languages: ["English", "Aymara", "Quechua"],
    experienceYears: 22,
    profileImage: "https://randomuser.me/api/portraits/men/24.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Walter Ellis",
    role: "Safety Compliance Officer",
    department: "Security Department",
    bio: "Safety Compliance Officer Ellis promotes a safety-first culture through continuous education and enforcement of best practices.",
    languages: ["English", "Spanish", "French"],
    experienceYears: 17,
    profileImage: "https://randomuser.me/api/portraits/men/21.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Nora Nash",
    role: "Youth Program Director",
    department: "Youth & Family Programs",
    bio: "Committed to positive youth engagement, Nora Nash integrates educational content with fun, age-appropriate activities tailored to diverse passenger groups.",
    languages: ["English", "Quechua", "French"],
    experienceYears: 21,
    profileImage: "https://randomuser.me/api/portraits/women/46.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Samantha Mitchell",
    role: "Family Activities Coordinator",
    department: "Youth & Family Programs",
    bio: "Leveraging 21 years in family entertainment, Samantha Mitchell curates a diverse schedule of events appealing to all members of the family.",
    languages: ["English", "Haitian", "Spanish"],
    experienceYears: 21,
    profileImage: "https://randomuser.me/api/portraits/women/87.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Donna Cooper",
    role: "Children's Entertainment Specialist",
    department: "Youth & Family Programs",
    bio: "With strong interpersonal skills, Donna Cooper ensures a safe and welcoming environment for all child participants.",
    languages: ["English", "French", "Quechua"],
    experienceYears: 14,
    profileImage: "https://randomuser.me/api/portraits/women/48.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Mia Campbell",
    role: "Teen Activities Coordinator",
    department: "Youth & Family Programs",
    bio: "Focused on safety and inclusivity, Mia Campbell maintains open communication with parents and guardians regarding teen program activities.",
    languages: ["English", "Guarani", "Haitian"],
    experienceYears: 11,
    profileImage: "https://randomuser.me/api/portraits/women/57.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Jessica Marshall",
    role: "Educational Program Manager",
    department: "Youth & Family Programs",
    bio: "Educational Program Manager Marshall coordinates with external educators and experts to deliver diverse and culturally relevant content.",
    languages: ["English", "Guarani", "French"],
    experienceYears: 15,
    profileImage: "https://randomuser.me/api/portraits/women/58.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Helen Keller",
    role: "Child Care Specialist",
    department: "Youth & Family Programs",
    bio: "Helen Keller provides attentive care and supervision for young passengers, backed by 10 years in professional child care and early childhood education.",
    languages: ["English", "French", "Haitian", "Spanish"],
    experienceYears: 10,
    profileImage: "https://randomuser.me/api/portraits/women/22.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Jennifer Reed",
    role: "Activities Director",
    department: "Activities & Recreation",
    bio: "With strong organizational skills, Jennifer Reed manages budgets, resources, and partnerships to deliver high-quality recreational services.",
    languages: ["English", "Guarani", "Quechua"],
    experienceYears: 16,
    profileImage: "https://randomuser.me/api/portraits/women/16.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Betty Douglas",
    role: "Water Sports Instructor",
    department: "Activities & Recreation",
    bio: "Betty Douglas teaches water sports safely and effectively, leveraging 11 years of professional instruction and certification in aquatic activities.",
    languages: ["English", "Aymara", "French"],
    experienceYears: 11,
    profileImage: "https://randomuser.me/api/portraits/women/35.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Isabella Hudson",
    role: "Fitness Instructor",
    department: "Activities & Recreation",
    bio: "Isabella Hudson is passionate about inspiring guests to discover the joy of movement, bringing energy and expertise from 14 years in the fitness industry.",
    languages: ["English", "Portuguese", "Haitian", "Aymara"],
    experienceYears: 14,
    profileImage: "https://randomuser.me/api/portraits/women/85.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Amina Stewart",
    role: "Excursion Coordinator",
    department: "Activities & Recreation",
    bio: "Excursion Coordinator Stewart plans enriching off-ship experiences that promote cultural immersion and memorable interactions for passengers.",
    languages: ["English", "Haitian", "Portuguese"],
    experienceYears: 21,
    profileImage: "https://randomuser.me/api/portraits/women/25.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Kenneth Morgan",
    role: "Lead Photographer",
    department: "Photography & Videography",
    bio: "Drawing on 4 years behind the lens, Kenneth Morgan expertly captures the essence of the cruise experience, from grand events to intimate moments.",
    languages: ["English", "Haitian", "Aymara", "Quechua"],
    experienceYears: 4,
    profileImage: "https://randomuser.me/api/portraits/men/28.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Elizabeth West",
    role: "Videographer",
    department: "Photography & Videography",
    bio: "With a strong understanding of narrative flow and audience engagement, Elizabeth West produces videos for promotional and archival purposes.",
    languages: ["English", "Guarani", "Haitian"],
    experienceYears: 21,
    profileImage: "https://randomuser.me/api/portraits/women/22.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Frank Montgomery",
    role: "Digital Media Specialist",
    department: "Photography & Videography",
    bio: "Known for technical proficiency and creative vision, Frank Montgomery collaborates closely with marketing and entertainment teams to maximize reach and impact.",
    languages: ["English", "Haitian", "Quechua"],
    experienceYears: 21,
    profileImage: "https://randomuser.me/api/portraits/men/42.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Jeremy Wells",
    role: "Chief Medical Officer",
    department: "Health & Safety",
    bio: "Jeremy Wells oversees health protocols, emergency medical services, and public health compliance, coordinating medical teams and resources effectively.",
    languages: ["English", "Haitian", "Portuguese", "Guarani"],
    experienceYears: 22,
    profileImage: "https://randomuser.me/api/portraits/men/10.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Blake Cooper",
    role: "Ship's Doctor",
    department: "Health & Safety",
    bio: "Dr. Cooper provides comprehensive medical care with 12 years of expertise in maritime and travel medicine, addressing acute and chronic conditions onboard.",
    languages: ["English", "Quechua", "Haitian"],
    experienceYears: 12,
    profileImage: "https://randomuser.me/api/portraits/men/64.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Miguel West",
    role: "Nurse",
    department: "Health & Safety",
    bio: "Known for meticulous attention to detail and a caring demeanor, Miguel West has been a vital part of shipboard medical teams for 17 years.",
    languages: ["English", "Aymara", "French", "Portuguese"],
    experienceYears: 17,
    profileImage: "https://randomuser.me/api/portraits/men/41.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Alan Maxwell",
    role: "Safety Officer",
    department: "Health & Safety",
    bio: "Committed to regulatory adherence, Alan Maxwell stays updated on maritime safety laws and best practices, facilitating crew training and certification.",
    languages: ["English", "Spanish", "Haitian"],
    experienceYears: 4,
    profileImage: "https://randomuser.me/api/portraits/men/12.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Sean Hunter",
    role: "Hospitality Director",
    department: "Hospitality Department",
    bio: "Sean Hunter is dedicated to fostering a welcoming and memorable atmosphere for all guests, drawing upon 10 years of cultivating outstanding hospitality teams.",
    languages: ["English", "Spanish", "Guarani"],
    experienceYears: 10,
    profileImage: "https://randomuser.me/api/portraits/men/8.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Henry Reeves",
    role: "Guest Relations Manager",
    department: "Hospitality Department",
    bio: "Henry Reeves champions a guest-first culture, utilizing 19 years of experience to train and motivate staff in delivering exceptional, personalized care.",
    languages: ["English", "Quechua", "Portuguese"],
    experienceYears: 19,
    profileImage: "https://randomuser.me/api/portraits/men/77.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Russell Crawford",
    role: "Chief Steward",
    department: "Hospitality Department",
    bio: "Russell Crawford ensures the highest standards of cleanliness and comfort throughout passenger accommodations.",
    languages: ["English", "Quechua", "Portuguese", "Guarani"],
    experienceYears: 13,
    profileImage: "https://randomuser.me/api/portraits/men/13.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Rebecca West",
    role: "Senior Steward",
    department: "Hospitality Department",
    bio: "Rebecca West provides exceptional valet services and anticipates guest needs, contributing to a luxurious and comfortable onboard experience over 3 years.",
    languages: ["English", "Portuguese", "Spanish"],
    experienceYears: 3,
    profileImage: "https://randomuser.me/api/portraits/women/91.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Andrew Gardner",
    role: "Butler",
    department: "Hospitality Department",
    bio: "Butler Gardner provides personalized guest services, backed by 5 years of elite hospitality expertise.",
    languages: ["English", "Portuguese", "Guarani", "Haitian"],
    experienceYears: 5,
    profileImage: "https://randomuser.me/api/portraits/men/9.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Amanda Sutton",
    role: "Accommodation Manager",
    department: "Hospitality Department",
    bio: "Amanda Sutton oversees accommodation services, ensuring comfort and efficiency with 3 years in maritime hospitality.",
    languages: ["English", "Aymara", "French", "Quechua"],
    experienceYears: 3,
    profileImage: "https://randomuser.me/api/portraits/women/47.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Avery Hawkins",
    role: "Housekeeping Supervisor",
    department: "Hospitality Department",
    bio: "Avery Hawkins manages daily assignments, motivates the housekeeping team, and ensures efficient use of cleaning resources, drawing on 3 years of leadership.",
    languages: ["English", "Guarani", "Quechua", "Haitian"],
    experienceYears: 3,
    profileImage: "https://randomuser.me/api/portraits/women/68.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Lucas Watson",
    role: "Guest Services Specialist",
    department: "Hospitality Department",
    bio: "With 22 years providing frontline support, Lucas Watson is adept at information sharing, problem-solving, and ensuring guests feel valued and well-informed.",
    languages: ["English", "Spanish", "Guarani"],
    experienceYears: 22,
    profileImage: "https://randomuser.me/api/portraits/men/90.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Ella Hunter",
    role: "Concierge",
    department: "Hospitality Department",
    bio: "Ella Hunter leverages 22 years of service to provide exceptional concierge support onboard.",
    languages: ["English", "Haitian", "Spanish"],
    experienceYears: 22,
    profileImage: "https://randomuser.me/api/portraits/women/63.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Alan Mason",
    role: "Front Desk Manager",
    department: "Hospitality Department",
    bio: "Front Desk Manager Mason oversees reception operations, ensuring efficient guest check-in and issue resolution.",
    languages: ["English", "Haitian", "French", "Aymara"],
    experienceYears: 8,
    profileImage: "https://randomuser.me/api/portraits/men/21.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Rebecca Russell",
    role: "VIP Coordinator",
    department: "Hospitality Department",
    bio: "VIP Coordinator Russell manages exclusive guest services, ensuring privacy and personalized attention throughout the voyage.",
    languages: ["English", "Haitian", "Spanish"],
    experienceYears: 16,
    profileImage: "https://randomuser.me/api/portraits/women/92.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Liam Porter",
    role: "Hospitality Trainer",
    department: "Hospitality Department",
    bio: "Hospitality Trainer Porter focuses on enhancing guest service quality through targeted education and coaching.",
    languages: ["English", "Guarani", "French"],
    experienceYears: 3,
    profileImage: "https://randomuser.me/api/portraits/men/29.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Kennedy Griffin",
    role: "Executive Chef",
    department: "Culinary Department",
    bio: "Beyond crafting exquisite Asian fusion, Chef Griffin expertly manages kitchen hygiene, inventory, and food cost control, honed over 13 years in demanding culinary environments.",
    languages: ["English", "Guarani", "Aymara"],
    experienceYears: 13,
    profileImage: "https://randomuser.me/api/portraits/women/79.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Cynthia West",
    role: "Sous Chef",
    department: "Culinary Department",
    bio: "Cynthia West trains and supervises junior chefs, playing a key role in maintaining discipline and motivation within the culinary team with 21 years of mentorship.",
    languages: ["English", "Haitian", "Quechua", "Aymara"],
    experienceYears: 21,
    profileImage: "https://randomuser.me/api/portraits/women/33.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Patricia Coleman",
    role: "Pastry Chef",
    department: "Culinary Department",
    bio: "Patricia Coleman manages the pastry section, from artisan breads to elaborate cakes and plated desserts, ensuring exceptional quality over 5 years.",
    languages: ["English", "Quechua", "Guarani", "Aymara"],
    experienceYears: 5,
    profileImage: "https://randomuser.me/api/portraits/women/3.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Eleanor Hall",
    role: "Chef de Partie",
    department: "Culinary Department",
    bio: "With 17 years as a section chef, Eleanor Hall is responsible for stock control and guiding commis chefs within their designated area of the Pacific Rim kitchen.",
    languages: ["English", "Spanish", "French"],
    experienceYears: 17,
    profileImage: "https://randomuser.me/api/portraits/women/60.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Peter Carpenter",
    role: "Specialty Chef",
    department: "Culinary Department",
    bio: "Specialty Chef Carpenter brings innovation and authenticity to the onboard dining experience.",
    languages: ["English", "Spanish", "Aymara"],
    experienceYears: 3,
    profileImage: "https://randomuser.me/api/portraits/men/77.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Genesis Lawson",
    role: "Sushi Chef",
    department: "Culinary Department",
    bio: "Sushi Chef Lawson manages the sushi bar operations, ensuring exceptional quality and presentation, reflecting 7 years of Japanese culinary excellence.",
    languages: ["English", "Spanish", "Quechua", "Portuguese"],
    experienceYears: 7,
    profileImage: "https://randomuser.me/api/portraits/women/66.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Aaron Hudson",
    role: "Garde Manger",
    department: "Culinary Department",
    bio: "Garde Manger Hudson expertly prepares cold dishes and appetizers with 11 years of culinary proficiency.",
    languages: ["English", "Aymara", "Guarani", "Haitian"],
    experienceYears: 11,
    profileImage: "https://randomuser.me/api/portraits/men/44.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Dylan Watson",
    role: "Butcher",
    department: "Culinary Department",
    bio: "Butcher Watson ensures quality meat preparation, supported by 17 years of skilled butchery work.",
    languages: ["English", "Quechua", "Portuguese", "Spanish"],
    experienceYears: 17,
    profileImage: "https://randomuser.me/api/portraits/men/56.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Willie Bennett",
    role: "Baker",
    department: "Culinary Department",
    bio: "With 6 years dedicated to the art of baking, Willie Bennett fills the ship with the aroma of freshly baked artisan breads, pastries, and viennoiserie.",
    languages: ["English", "Spanish", "Portuguese", "Haitian"],
    experienceYears: 6,
    profileImage: "https://randomuser.me/api/portraits/men/21.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Victoria Day",
    role: "Sommelier",
    department: "Culinary Department",
    bio: "Certified Sommelier Day navigates an extensive cellar to find the perfect wine for every palate and Latin American, drawing on 8 years of oenological expertise.",
    languages: ["English", "Portuguese", "French"],
    experienceYears: 8,
    profileImage: "https://randomuser.me/api/portraits/women/59.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Scarlett Murray",
    role: "Mixologist",
    department: "Culinary Department",
    bio: "With 13 years behind the bar, Scarlett Murray designs innovative signature cocktails and perfectly executes classic recipes using premium spirits and fresh ingredients.",
    languages: ["English", "Aymara", "Quechua"],
    experienceYears: 13,
    profileImage: "https://randomuser.me/api/portraits/women/58.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Randy Baker",
    role: "Barista",
    department: "Culinary Department",
    bio: "Randy Baker combines artistry and technique to serve quality espresso and coffee beverages.",
    languages: ["English", "Portuguese", "Guarani"],
    experienceYears: 18,
    profileImage: "https://randomuser.me/api/portraits/men/12.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Paul Cooper",
    role: "Nutritionist",
    department: "Culinary Department",
    bio: "Nutritionist Cooper works closely with the culinary team to create wholesome Japanese options that are both flavorful and aligned with wellness goals, drawing on 6 years of expertise.",
    languages: ["English", "Spanish", "French"],
    experienceYears: 6,
    profileImage: "https://randomuser.me/api/portraits/men/73.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Joan Lawson",
    role: "Entertainment Director",
    department: "Entertainment Department",
    bio: "With 11 years orchestrating spectacular onboard entertainment, Joan Lawson manages everything from Broadway-style shows to intimate musical performances and themed parties.",
    languages: ["English", "Guarani", "Haitian", "Spanish"],
    experienceYears: 11,
    profileImage: "https://randomuser.me/api/portraits/women/18.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Ralph Wells",
    role: "Performance Coordinator",
    department: "Entertainment Department",
    bio: "Performance Coordinator Wells supports talent and technical teams to deliver seamless shows.",
    languages: ["English", "Spanish", "Haitian"],
    experienceYears: 22,
    profileImage: "https://randomuser.me/api/portraits/men/28.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Angela Hudson",
    role: "Lead Vocalist",
    department: "Entertainment Department",
    bio: "Lead Vocalist Hudson captivates audiences with dynamic performances, backed by 12 years of professional singing.",
    languages: ["English", "Spanish", "Haitian"],
    experienceYears: 12,
    profileImage: "https://randomuser.me/api/portraits/women/73.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Isabella Collins",
    role: "Musician",
    department: "Entertainment Department",
    bio: "A master of the {instrument}, Isabella Collins brings 11 years of versatile musicianship, performing solo or as part of an ensemble in various ship venues.",
    languages: ["English", "Aymara", "Spanish"],
    experienceYears: 11,
    profileImage: "https://randomuser.me/api/portraits/women/91.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Eleanor Spencer",
    role: "Dancer",
    department: "Entertainment Department",
    bio: "Eleanor Spencer engages audiences with versatile dance styles across entertainment programs.",
    languages: ["English", "Quechua", "Spanish"],
    experienceYears: 20,
    profileImage: "https://randomuser.me/api/portraits/women/57.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Antonio Warren",
    role: "Choreographer",
    department: "Entertainment Department",
    bio: "Choreographer Warren works closely with dancers to teach and refine intricate movements, ensuring performances are polished and impactful, reflecting 17 years of artistic direction.",
    languages: ["English", "Guarani", "French", "Quechua"],
    experienceYears: 17,
    profileImage: "https://randomuser.me/api/portraits/men/66.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Christine Hamilton",
    role: "Comedy Performer",
    department: "Entertainment Department",
    bio: "Christine Hamilton's ability to connect with the audience and improvise, developed over 7 years, makes each show a unique and highly enjoyable experience.",
    languages: ["English", "Guarani", "Portuguese"],
    experienceYears: 7,
    profileImage: "https://randomuser.me/api/portraits/women/73.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Evelyn Nash",
    role: "Magic Act",
    department: "Entertainment Department",
    bio: "Evelyn Nash blends showmanship and technique to deliver captivating magic shows at sea.",
    languages: ["English", "Portuguese", "Guarani", "Aymara"],
    experienceYears: 19,
    profileImage: "https://randomuser.me/api/portraits/women/27.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Benjamin Montgomery",
    role: "DJ",
    department: "Entertainment Department",
    bio: "Benjamin Montgomery keeps dance floors lively with dynamic sets tailored for diverse guest preferences.",
    languages: ["English", "French", "Portuguese"],
    experienceYears: 13,
    profileImage: "https://randomuser.me/api/portraits/men/93.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Brandon Hudson",
    role: "Audio Technician",
    department: "Entertainment Department",
    bio: "Brandon Hudson's keen ear and technical proficiency, developed over 13 years, are essential for delivering immersive and high-quality auditory experiences.",
    languages: ["English", "Haitian", "French"],
    experienceYears: 13,
    profileImage: "https://randomuser.me/api/portraits/men/10.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Joan Ellis",
    role: "Lighting Specialist",
    department: "Entertainment Department",
    bio: "Lighting Specialist Ellis designs and operates lighting systems to enhance onboard shows and events.",
    languages: ["English", "Guarani", "Portuguese", "Spanish"],
    experienceYears: 16,
    profileImage: "https://randomuser.me/api/portraits/women/0.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Johnny Graham",
    role: "Stage Manager",
    department: "Entertainment Department",
    bio: "With 20 years in professional stage management, Johnny Graham meticulously calls cues, manages backstage operations, and ensures the smooth running of every show.",
    languages: ["English", "Haitian", "Quechua"],
    experienceYears: 20,
    profileImage: "https://randomuser.me/api/portraits/men/93.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Nathan Hayes",
    role: "Production Manager",
    department: "Entertainment Department",
    bio: "Nathan Hayes's strategic planning and problem-solving skills, developed over 21 years, are crucial for the successful execution of a high-quality entertainment program.",
    languages: ["English", "Haitian", "Guarani", "Portuguese"],
    experienceYears: 21,
    profileImage: "https://randomuser.me/api/portraits/men/4.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Eric Parker",
    role: "Costume Designer",
    department: "Entertainment Department",
    bio: "With 5 years of experience in theatrical costume design, Eric Parker conceives and produces stunning wardrobes that define characters and elevate productions.",
    languages: ["English", "Aymara", "Portuguese", "French"],
    experienceYears: 5,
    profileImage: "https://randomuser.me/api/portraits/men/79.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Katherine Porter",
    role: "Cultural Program Director",
    department: "Entertainment Department",
    bio: "Cultural Program Director Porter curates culturally enriching events and experiences for guests.",
    languages: ["English", "Spanish", "Haitian"],
    experienceYears: 14,
    profileImage: "https://randomuser.me/api/portraits/women/2.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "George Carpenter",
    role: "Performance Artist",
    department: "Entertainment Department",
    bio: "Performance Artist Carpenter combines elements of {artisticDisciplineCombination} to create truly unique and memorable entertainment experiences for discerning audiences.",
    languages: ["English", "Aymara", "Portuguese"],
    experienceYears: 5,
    profileImage: "https://randomuser.me/api/portraits/men/82.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Michelle Chambers",
    role: "Operations Manager",
    department: "Operations Department",
    bio: "With 9 years streamlining vessel-wide processes, Michelle Chambers ensures optimal efficiency, resource allocation, and inter-departmental synergy.",
    languages: ["English", "Spanish", "Portuguese"],
    experienceYears: 9,
    profileImage: "https://randomuser.me/api/portraits/women/75.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Betty Curtis",
    role: "Logistics Coordinator",
    department: "Operations Department",
    bio: "Logistics Coordinator Curtis meticulously plans and tracks shipments, manages customs documentation, and optimizes storage solutions onboard.",
    languages: ["English", "Portuguese", "Quechua"],
    experienceYears: 14,
    profileImage: "https://randomuser.me/api/portraits/women/17.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Diego Knight",
    role: "Inventory Specialist",
    department: "Operations Department",
    bio: "Inventory Specialist Knight tracks and manages stock levels, maintaining operational readiness.",
    languages: ["English", "Guarani", "Haitian"],
    experienceYears: 17,
    profileImage: "https://randomuser.me/api/portraits/men/70.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Victor Grant",
    role: "Procurement Officer",
    department: "Operations Department",
    bio: "Victor Grant applies expertise in vendor management and cost optimization to benefit ship operations.",
    languages: ["English", "Aymara", "French"],
    experienceYears: 7,
    profileImage: "https://randomuser.me/api/portraits/men/40.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
  {
    name: "Caroline Clark",
    role: "Sustainability Coordinator",
    department: "Operations Department",
    bio: "Sustainability Coordinator Clark implements green initiatives to minimize environmental impact.",
    languages: ["English", "Quechua", "Portuguese"],
    experienceYears: 12,
    profileImage: "https://randomuser.me/api/portraits/women/32.jpg",
    city: "Tampa",
    country: "United States",
    region: "Caribbean",
  },
];
