import { CrewMember } from "@/lib/interfaces/people/staff";

export const vancouverTeamMembers: CrewMember[] = [
  {
    name: "William Fraser",
    role: "Captain",
    department: "Deck Department",
    bio: "Captain Fraser brings over 20 years of experience navigating the complex Pacific Northwest coastal waters and Inside Passage.",
    languages: ["English", "French"],
    experienceYears: 22,
    profileImage: "/images/crew/captain-fraser.jpg",
    city: "Vancouver",
    country: "Canada",
    region: "British Columbia",
  },
  {
    name: "Sarah Ng",
    role: "Captain",
    department: "Deck Department",
    bio: "Captain Ng specializes in navigating Pacific coastal routes from Vancouver to Alaska, with expertise in glacier approaches.",
    languages: ["English", "Cantonese", "French"],
    experienceYears: 18,
    profileImage: "/images/crew/captain-ng.jpg",
    city: "Vancouver",
    country: "Canada",
    region: "British Columbia",
  },
  {
    name: "Robert Thompson",
    role: "First Officer",
    department: "Deck Department",
    bio: "Robert's extensive knowledge of Pacific Northwest tides and currents ensures safe passage through challenging waterways.",
    languages: ["English", "French"],
    experienceYears: 15,
    profileImage: "/images/crew/officer-thompson.jpg",
    city: "Vancouver",
    country: "Canada",
    region: "British Columbia",
  },
  {
    name: "Amelia Singh",
    role: "First Officer",
    department: "Deck Department",
    bio: "Former Canadian Coast Guard officer Amelia brings exceptional navigation skills and local knowledge to every expedition.",
    languages: ["English", "Punjabi", "French"],
    experienceYears: 13,
    profileImage: "/images/crew/officer-singh.jpg",
    city: "Vancouver",
    country: "Canada",
    region: "British Columbia",
  },
  {
    name: "David Suzuki",
    role: "Chief Engineer",
    department: "Engineering Department",
    bio: "David ensures optimal vessel performance with specialized knowledge of eco-friendly marine engineering systems.",
    languages: ["English", "Japanese"],
    experienceYears: 20,
    profileImage: "/images/crew/engineer-suzuki.jpg",
    city: "Vancouver",
    country: "Canada",
    region: "British Columbia",
  },
  {
    name: "Olivia Chen",
    role: "Chief Engineer",
    department: "Engineering Department",
    bio: "Olivia leads our engineering team with expertise in cold-water operations and sustainable marine technologies.",
    languages: ["English", "Mandarin", "French"],
    experienceYears: 16,
    profileImage: "/images/crew/engineer-chen.jpg",
    city: "Vancouver",
    country: "Canada",
    region: "British Columbia",
  },
  {
    name: "Chef Michael Williams",
    role: "Executive Chef",
    department: "Hospitality Department",
    bio: "Chef Williams creates exceptional Pacific Northwest cuisine featuring locally sourced seafood and indigenous ingredients.",
    languages: ["English", "French"],
    experienceYears: 22,
    profileImage: "/images/crew/chef-williams.jpg",
    city: "Vancouver",
    country: "Canada",
    region: "British Columbia",
  },
  {
    name: "Chef Jun Park",
    role: "Executive Chef",
    department: "Hospitality Department",
    bio: "Chef Park's innovative fusion approach combines Pacific Rim flavors with classic techniques using sustainable local ingredients.",
    languages: ["English", "Korean", "Japanese"],
    experienceYears: 17,
    profileImage: "/images/crew/chef-park.jpg",
    city: "Vancouver",
    country: "Canada",
    region: "British Columbia",
  },
  {
    name: "Jessica Lee",
    role: "Cruise Director",
    department: "Entertainment Department",
    bio: "Jessica creates immersive experiences highlighting the natural beauty and cultural heritage of the Pacific Northwest.",
    languages: ["English", "Mandarin", "French"],
    experienceYears: 12,
    profileImage: "/images/crew/director-lee.jpg",
    city: "Vancouver",
    country: "Canada",
    region: "British Columbia",
  },
  {
    name: "Daniel Wilson",
    role: "Cruise Director",
    department: "Entertainment Department",
    bio: "Daniel's background in eco-tourism creates unique onboard programs focused on natural exploration and cultural appreciation.",
    languages: ["English", "French", "Spanish"],
    experienceYears: 9,
    profileImage: "/images/crew/director-wilson.jpg",
    city: "Vancouver",
    country: "Canada",
    region: "British Columbia",
  },
  {
    name: "Dr. Emily Clark",
    role: "Ship's Doctor",
    department: "Health & Safety",
    bio: "Dr. Clark provides comprehensive medical care with specialization in wilderness medicine and remote emergency response.",
    languages: ["English", "French"],
    experienceYears: 16,
    profileImage: "/images/crew/doctor-clark.jpg",
    city: "Vancouver",
    country: "Canada",
    region: "British Columbia",
  },
  {
    name: "Dr. Arjun Patel",
    role: "Ship's Doctor",
    department: "Health & Safety",
    bio: "Dr. Patel ensures exceptional medical services with expertise in travel medicine and maritime healthcare delivery.",
    languages: ["English", "Hindi", "Punjabi"],
    experienceYears: 14,
    profileImage: "/images/crew/doctor-patel.jpg",
    city: "Vancouver",
    country: "Canada",
    region: "British Columbia",
  },
  {
    name: "Thomas Hill",
    role: "Naturalist",
    department: "Activities & Recreation",
    bio: "Marine biologist Thomas leads wildlife expeditions with deep knowledge of Pacific Northwest marine ecosystems.",
    languages: ["English", "French"],
    experienceYears: 18,
    profileImage: "/images/crew/naturalist-hill.jpg",
    city: "Vancouver",
    country: "Canada",
    region: "British Columbia",
  },
  {
    name: "Lisa Johnson",
    role: "Naturalist",
    department: "Activities & Recreation",
    bio: "Wildlife specialist Lisa shares her passion for orcas, eagles and coastal ecology through informative excursions.",
    languages: ["English", "French"],
    experienceYears: 11,
    profileImage: "/images/crew/naturalist-johnson.jpg",
    city: "Vancouver",
    country: "Canada",
    region: "British Columbia",
  },
];
