import { RestaurantMenu } from "@/lib/types/types";

/**
 * Menu data for Singaporean & Co. in singapore
 */
export const singaporesingaporeanCoMenu: RestaurantMenu[] = [
  {
    title: "Main Course Menu",
    description:
      "A showcase of homestyle culinary artistry rooted in Malaysian heritage",
    category: [
      {
        name: "Signature Dishes",
        description:
          "A hand-picked menu selection that reflects the chef’s current inspirations and exceptional skill.",
        items: [
          {
            name: "Fresh Zingy Dry-Aged Tomahawk Steak",
            price: 34.56,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Traditional Wholesome Seasonal Tasting Platter",
            price: 30.8,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Comforting Age-Old Recipe Osso Buco with Gremolata",
            price: 30.89,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Spiced Korean BBQ Short Ribs with Kimchi Rice",
            price: 29.44,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "House Special Baked Heritage Recipe Lamb Shank",
            price: 31.71,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Handcrafted Crispy Traditional Family Paella",
            price: 33.16,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Traditional Irresistible Local Bounty Harvest Plate (Vegetarian)",
            price: 32.12,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Chef's Specials",
        description:
          "Seasonal offerings crafted by our executive chef, available for a limited time to reflect peak freshness.",
        items: [
          {
            name: "Locally Foraged Mushroom Selection",
            price: 35.17,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Wild Mushroom Risotto",
            price: 38.76,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Duck Confit with Roasted Root Vegetables",
            price: 29.91,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Signature Spice-Rubbed Protein",
            price: 39.31,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Aged and House-Cured Charcuterie Selection",
            price: 37.88,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: true,
          },
        ],
      },
      {
        name: "Appetizers",
        description:
          "A delightful array of appetizers that highlight the best of Malaysian flavors—perfect for sharing or enjoying solo.",
        items: [
          {
            name: "Cheese Nachos",
            price: 12.01,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Calamari",
            price: 14.7,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Crostini",
            price: 10.7,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Bruschetta",
            price: 8.07,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Cheese Platter",
            price: 11.36,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Antipasto Platter",
            price: 15.37,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Sweet Potato Fries",
            price: 9.66,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Mini Sliders",
            price: 13.21,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Soups",
        description:
          "Rich flavors and slow-simmered ingredients that speak of home and tradition.",
        items: [
          {
            name: "Hearty Mouthwatering Black Bean Soup",
            price: 8.14,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Organic Baked French Onion Soup",
            price: 13.62,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Hearty Tortilla Soup",
            price: 11.03,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Creamy Lobster Bisque",
            price: 7.55,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
        ],
      },
      {
        name: "Salads",
        description:
          "Lively salads combining texture, temperature, and taste for a refreshing start or light meal.",
        items: [
          {
            name: "Watermelon Feta Salad",
            price: 13.9,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Apple Pecan Salad",
            price: 13.29,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Chef Salad",
            price: 10.19,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Nicoise Salad",
            price: 13.48,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Potato Salad",
            price: 10.73,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Main Courses",
        description:
          "Crafted with the finest ingredients, our mains are a testament to our culinary philosophy.",
        items: [
          {
            name: "Authentic Juicy Chili con Carne",
            price: 30.3,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Authentic Roasted Lamb Chops",
            price: 20.28,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Homestyle Grilled Currywurst",
            price: 26.07,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Handcrafted Grilled Biryani",
            price: 21.72,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Roasted Beef Burger",
            price: 31.12,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: true,
          },
          {
            name: "Gourmet Stuffed Grilled Chicken",
            price: 23.17,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Hearty Enticing Pho",
            price: 25.98,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Seasonal Smoked Tacos",
            price: 19.34,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Seafood Specialties",
        description:
          "A celebration of the sea, featuring seasonal catches and artisanal techniques.",
        items: [
          {
            name: "Garlic Butter Shrimp Skillet",
            price: 35.25,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Pan-Seared Scallops with Pea Purée",
            price: 30.16,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Linguine with Clam Sauce",
            price: 34.39,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Smoked Salmon Platter with Dill Crème",
            price: 29.47,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Maryland Style Crab Cakes",
            price: 31.58,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Side Dishes",
        description:
          "Crafted to enhance your main course, these sides are anything but ordinary.",
        items: [
          {
            name: "Homestyle Luscious French Fries",
            price: 5.84,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Classic Herbed Maple-Glazed Baby Carrots",
            price: 7.65,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Gourmet Spicy Cauliflower Gratin with Gruyère",
            price: 5.28,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Stuffed Creamy Colcannon (Irish Potato Mash)",
            price: 9.5,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Classic Baked Wild Mushroom Risotto",
            price: 8.01,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Flaky Roasted Root Vegetables",
            price: 5.42,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: true,
          },
        ],
      },
      {
        name: "Non-Alcoholic Beverages",
        description:
          "Bright, invigorating options that cleanse the palate and refresh the spirit.",
        items: [
          {
            name: "Tea",
            price: 5.59,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Juice",
            price: 5.52,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Iced Tea",
            price: 4.08,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Milkshake",
            price: 5.06,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Coffee",
            price: 7.49,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Smoothie",
            price: 6.37,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
  {
    title: "Dessert Menu",
    description:
      "A comforting selection of desserts that celebrate the art of pastry",
    category: [
      {
        name: "Baked Goods",
        description:
          "Indulge in our selection of baked treats, each one a labor of love.",
        items: [
          {
            name: "Shortbread",
            price: 10.2,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Custard Tart",
            price: 9.61,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Lemon Bars",
            price: 9.74,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Apple Pie",
            price: 8.02,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Brownies",
            price: 10.39,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Frozen Desserts",
        description:
          "Smooth, rich frozen creations featuring local fruits and seasonal flavors.",
        items: [
          {
            name: "Traditional Zesty Sherbet",
            price: 7.03,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Flaky Frozen Pudding",
            price: 11.43,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Flaky Granita",
            price: 9.72,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Hearty Marinated Gelato",
            price: 9.18,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Grilled Kulfi",
            price: 11.8,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
  {
    title: "Drinks Menu",
    description:
      "Discover our quality drinks, perfectly paired with our Malaysian cuisine",
    category: [
      {
        name: "Signature Cocktails",
        description:
          "A cocktail experience that transcends the ordinary—crafted for the discerning palate.",
        items: [
          {
            name: "Whiskey Sour",
            price: 15.24,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Margarita",
            price: 13.19,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Old Fashioned",
            price: 15.27,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Martini",
            price: 11.32,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Mai Tai",
            price: 11.38,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Mojito",
            price: 13.77,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Manhattan",
            price: 13.04,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Wine Selection",
        description:
          "Perfect pairings for any palate, with guidance available from our trained staff.",
        items: [
          {
            name: "Homestyle Tangy Merlot",
            price: 12.86,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Golden Pinot Blanc",
            price: 9.22,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Premium Sweet Pinot Noir",
            price: 8.71,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Classic Hearty Torrontés",
            price: 10.24,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Marinated Champagne/Sparkling Wine",
            price: 11.94,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Seasonal Sweet Syrah/Shiraz",
            price: 9.01,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Spirits and Liqueurs",
        description:
          "A refined range of aged whiskeys, fine brandies, and international specialties.",
        items: [
          {
            name: "Mezcal",
            price: 10.64,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Baileys Irish Cream",
            price: 14.4,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Absinthe",
            price: 13.03,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Cointreau",
            price: 11.36,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Bourbon",
            price: 12.99,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
];
