import { RestaurantMenu } from "@/lib/types/types";

/**
 * Menu data for Grand Juice Bar in bangkok
 */
export const bangkokgrandJuiceBarMenu: RestaurantMenu[] = [
  {
    title: "Main Course Menu",
    description:
      "A thoughtfully curated lineup of flavorful Japanese dishes to suit every palate",
    category: [
      {
        name: "Signature Dishes",
        description:
          "Distinctive creations that have become synonymous with our name—prepared with precision and purpose.",
        items: [
          {
            name: "Organic Pan-seared Japanese A5 Wagyu with Ponzu Butter",
            price: 34.57,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Handcrafted Smoked Signature Truffle Pasta with Aged Pecorino",
            price: 27.82,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Traditional Zingy Seasonal Tasting Platter",
            price: 27.65,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Gourmet Sautéed Award-Winning Seafood Boil",
            price: 32.68,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Handcrafted Spiced Wood-Fired Peking Duck with Plum Sauce",
            price: 26.98,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Fresh Roasted 24-Hour Braised Short Ribs",
            price: 30.37,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Seasonal Luscious Crusted Rack of Lamb with Dijon Herb Crust",
            price: 25.14,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
        ],
      },
      {
        name: "Chef's Specials",
        description:
          "Inventive dishes that explore rare ingredients, bold flavors, and progressive cooking techniques.",
        items: [
          {
            name: "Deluxe Flavorful Aged and House-Cured Charcuterie Selection",
            price: 39.99,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Hearty Smoked Seasonal Truffle Risotto",
            price: 25.4,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Handcrafted Grilled Modern Interpretation of Regional Classic",
            price: 25.2,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Zingy Braised Short Ribs with Red Wine Sauce",
            price: 25.15,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Authentic Grilled Locally Foraged Mushroom Selection",
            price: 25.48,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
        ],
      },
      {
        name: "Appetizers",
        description:
          "Mouthwatering previews of what's to come—crafted to tease and please.",
        items: [
          {
            name: "Classic Exquisite Calamari",
            price: 8.23,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Handcrafted Irresistible Falafel",
            price: 14.52,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Organic Marinated Tuna Tartare",
            price: 12.08,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Homestyle Stuffed Hummus Platter",
            price: 14.79,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Handcrafted Grilled Tzatziki with Pita",
            price: 14.81,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Traditional Sweet Sweet Potato Fries",
            price: 15.25,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Handcrafted Sizzling Dumplings",
            price: 12.83,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Traditional Savory Zucchini Fries",
            price: 8.45,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Soups",
        description:
          "Each bowl is a journey through the heart of Japanese, crafted with care and expertise.",
        items: [
          {
            name: "Miso Soup",
            price: 8.35,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Butternut Squash Soup",
            price: 7.57,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Tomato Soup",
            price: 13.26,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Corn Chowder",
            price: 11.7,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Salads",
        description:
          "From classic combinations to innovative creations, our salads are a feast for the senses.",
        items: [
          {
            name: "Apple Pecan Salad",
            price: 11.04,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Pear and Gorgonzola Salad",
            price: 12.88,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Tabbouleh",
            price: 9.19,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Mango Avocado Salad",
            price: 9.01,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fruit Salad",
            price: 12.24,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Main Courses",
        description:
          "Robust and satisfying center-of-plate dishes that deliver flavor and artistry.",
        items: [
          {
            name: "Authentic Grilled Bibimbap",
            price: 18.36,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "House Special Delicious Salmon",
            price: 31.19,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Gourmet Sweet Chili con Carne",
            price: 29.26,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Traditional Delectable Beef Burger",
            price: 29.54,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Traditional Grilled Mac and Cheese",
            price: 25,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Zesty Currywurst",
            price: 31.7,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "House Special Flavorful Pasta Primavera",
            price: 28.87,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Pan-seared Spaghetti Bolognese",
            price: 29.16,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: true,
          },
        ],
      },
      {
        name: "Seafood Specialties",
        description:
          "From the sea to your plate—each dish is a tribute to the ocean’s bounty.",
        items: [
          {
            name: "Cedar Plank Roasted Salmon",
            price: 26.79,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Grilled Lobster with Lemon Butter",
            price: 23.49,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Maryland Style Crab Cakes",
            price: 35.99,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Sushi-Grade Sashimi Platter",
            price: 33.16,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Shrimp Scampi over Linguine",
            price: 35.24,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Side Dishes",
        description:
          "Flavorful companions that round out your meal with harmony and flair.",
        items: [
          {
            name: "Gourmet Luscious Maple-Glazed Baby Carrots",
            price: 5.81,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Handcrafted Spicy Creamy Colcannon (Irish Potato Mash)",
            price: 8.3,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Hearty Grilled Israeli Couscous with Roasted Tomatoes",
            price: 5.27,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Hearty Fried Steamed Jasmine Rice",
            price: 6.99,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Classic Fried Crispy Beer-Battered Onion Rings",
            price: 5.18,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Zingy Roasted Root Vegetables",
            price: 8.85,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: false,
            isKosher: true,
          },
        ],
      },
      {
        name: "Non-Alcoholic Beverages",
        description:
          "Bright and revitalizing beverages for all ages and preferences.",
        items: [
          {
            name: "Milkshake",
            price: 7.68,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Smoothie",
            price: 5.78,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Lemonade",
            price: 7.72,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Water",
            price: 6.63,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Tea",
            price: 7.36,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Hot Chocolate",
            price: 5.92,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
  {
    title: "Dessert Menu",
    description: "Complete your meal with our classic dessert selection",
    category: [
      {
        name: "Baked Goods",
        description:
          "Pastries, breads, and treats prepared in-house using classic and modern methods.",
        items: [
          {
            name: "Crumb Cake",
            price: 6.21,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Biscotti",
            price: 7.66,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Carrot Cake",
            price: 10.76,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Vanilla Cake",
            price: 6.68,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Soufflé",
            price: 9.4,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Frozen Desserts",
        description:
          "A delightful way to end your meal—cool, creamy, and bursting with flavor.",
        items: [
          {
            name: "Frozen Yogurt",
            price: 7.16,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Snow Cone",
            price: 10.28,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Gelato",
            price: 7.38,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Sorbet",
            price: 9.76,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Frozen Banana",
            price: 11.84,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
  {
    title: "Drinks Menu",
    description: "From wines to spirits: inviting choices for every palate",
    category: [
      {
        name: "Signature Cocktails",
        description:
          "Unique, house-crafted cocktails that offer a memorable sip every time.",
        items: [
          {
            name: "Organic Smoked Martini",
            price: 14.55,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Hearty Margarita",
            price: 10.93,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Premium Crispy Manhattan",
            price: 14.08,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Hearty Fried Mai Tai",
            price: 14.59,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Enticing Bloody Mary",
            price: 15.45,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Homestyle Savory Cosmopolitan",
            price: 10.71,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Premium Smoked Old Fashioned",
            price: 10.17,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Wine Selection",
        description:
          "Our sommelier's picks, chosen for balance, terroir expression, and quality.",
        items: [
          {
            name: "Gewürztraminer",
            price: 10.75,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Roussanne",
            price: 12.93,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Prosecco",
            price: 11.32,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fiano",
            price: 10.06,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Sauvignon Blanc",
            price: 13.62,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Torrontés",
            price: 12.09,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Spirits and Liqueurs",
        description:
          "Crafted for those who appreciate the art of distillation—each pour is a journey.",
        items: [
          {
            name: "Pisco",
            price: 13.03,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Maraschino",
            price: 13.07,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Tequila",
            price: 17.12,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Cointreau",
            price: 17.57,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Drambuie",
            price: 11.98,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
];
