import { RestaurantMenu } from "@/lib/types/types";

/**
 * Menu data for Quincy Provisions in boston
 */
export const bostonquincyProvisionsMenu: RestaurantMenu[] = [
  {
    title: "Main Course Menu",
    description:
      "Elevated American dishes showcasing our most delicious culinary ideas",
    category: [
      {
        name: "Signature Dishes",
        description:
          "House favorites that have stood the test of time and showcase our refined approach to American cuisine.",
        items: [
          {
            name: "Award-Winning Seafood Boil",
            price: 27.22,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Traditional Family Paella",
            price: 30.95,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Modernist Foie Gras Sphere with Rhubarb Gel",
            price: 32.57,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Local Bounty Harvest Plate (Vegetarian)",
            price: 33.25,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Seasonal Tasting Menu Experience",
            price: 37.52,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Executive Chef's Daily Inspiration Entrée",
            price: 33.16,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Crusted Rack of Lamb with Dijon Herb Crust",
            price: 36.25,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
        ],
      },
      {
        name: "Chef's Specials",
        description:
          "Unique culinary compositions that rotate frequently to keep each visit fresh and surprising.",
        items: [
          {
            name: "Locally Foraged Mushroom Selection",
            price: 26.31,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fire-Roasted Seasonal Centerpiece",
            price: 37.71,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Chef's Tasting Menu Experience",
            price: 35.89,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Aged and House-Cured Charcuterie Selection",
            price: 39.8,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Modern Interpretation of Regional Classic",
            price: 25.92,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Appetizers",
        description:
          "Thoughtfully prepared small plates to begin your culinary experience with elegance and taste.",
        items: [
          {
            name: "Tempura",
            price: 12.96,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Baked Brie",
            price: 11.37,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Falafel",
            price: 15.37,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Ceviche",
            price: 15.2,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Mini Quesadillas",
            price: 14.77,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Calamari",
            price: 13.33,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Cheese Nachos",
            price: 14.14,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Chicken Satay",
            price: 15.99,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
        ],
      },
      {
        name: "Soups",
        description:
          "Crafted with care, our soups are a celebration of American flavors and traditions.",
        items: [
          {
            name: "Authentic Grilled Avgolemono (Greek Lemon Soup)",
            price: 9.97,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Organic Exquisite Tomato Soup",
            price: 8.82,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Sizzling Turkey and Wild Rice Soup",
            price: 9.89,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Deluxe Creamy Chicken Noodle Soup",
            price: 9.25,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Salads",
        description:
          "A blend of local and organic ingredients, thoughtfully combined for maximum flavor.",
        items: [
          {
            name: "Pear and Gorgonzola Salad",
            price: 12.54,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Mango Avocado Salad",
            price: 9.81,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Apple Pecan Salad",
            price: 10.28,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Thai Green Papaya Salad",
            price: 10.52,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Roasted Beet and Goat Cheese Salad",
            price: 10.15,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: true,
          },
        ],
      },
      {
        name: "Main Courses",
        description:
          "Signature entrées crafted with precision, embodying the core of our American vision.",
        items: [
          {
            name: "Authentic Steamed Tacos",
            price: 20.31,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Handcrafted Crunchy Beef Burger",
            price: 31.37,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Authentic Grilled Katsu Curry",
            price: 27.6,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Classic Pan-seared Teriyaki Chicken",
            price: 18.43,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "House Special Hearty Pizza",
            price: 30.53,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Gourmet Creamy Beef Wellington",
            price: 26.6,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: true,
          },
          {
            name: "Handcrafted Herbed Shish Kebabs",
            price: 24.37,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Sautéed Bibimbap",
            price: 21,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Seafood Specialties",
        description:
          "Ocean-inspired dishes crafted with respect for delicate textures and bold seasoning.",
        items: [
          {
            name: "Handcrafted Braised Cedar Plank Roasted Salmon",
            price: 22.12,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Hearty Smoked Valencian Seafood Paella",
            price: 32.81,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Seasonal Succulent Basa Fillet with Dill Cream Sauce",
            price: 29.41,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Homestyle Marinated Stuffed Flounder with Crab and Spinach",
            price: 22.01,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Seasonal Luscious Prawn Curry in Coconut Masala",
            price: 32.89,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Side Dishes",
        description:
          "A selection of thoughtfully prepared sides that bring out the best in our mains.",
        items: [
          {
            name: "Green Beans Almondine",
            price: 5.64,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Warm Buttermilk Dinner Rolls",
            price: 9.09,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Herbed Bulgur Wheat with Lemon",
            price: 7.43,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Charred Broccolini with Garlic Oil",
            price: 7.08,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fragrant Basmati Rice Pilaf",
            price: 7.8,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Garlic Bread with Herb Butter",
            price: 6.68,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Non-Alcoholic Beverages",
        description:
          "Sophisticated non-alcoholic choices made to complement any dish.",
        items: [
          {
            name: "Lemonade",
            price: 4.36,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Smoothie",
            price: 4.35,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Iced Tea",
            price: 5.28,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Milkshake",
            price: 6.13,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Tea",
            price: 7.57,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Juice",
            price: 5.1,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
  {
    title: "Dessert Menu",
    description:
      "Our dessert menu features gooey selections to satisfy every craving",
    category: [
      {
        name: "Baked Goods",
        description:
          "From flaky pastries to hearty breads, our baked goods are a must-try.",
        items: [
          {
            name: "Authentic Marinated Soufflé",
            price: 9.46,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Authentic Steamed Cheesecake",
            price: 6.83,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Seasonal Marinated Tiramisu",
            price: 8.63,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Handcrafted Hearty Muffins",
            price: 10.48,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Homestyle Marinated Fruit Galette",
            price: 8.24,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Frozen Desserts",
        description:
          "Handmade with care, our frozen desserts are a celebration of texture and taste.",
        items: [
          {
            name: "Organic Creamy Sorbet",
            price: 9.51,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Homestyle Roasted Frozen Custard",
            price: 7.97,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Sizzling Gelato",
            price: 11.49,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Hearty Smoked Ice Cream",
            price: 9.02,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Hearty Flaky Frozen Cheesecake",
            price: 11.13,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
  {
    title: "Drinks Menu",
    description:
      "A carefully chosen assortment of libations to accompany your culinary journey",
    category: [
      {
        name: "Signature Cocktails",
        description:
          "Crafted with precision, our cocktails are designed to elevate your dining experience.",
        items: [
          {
            name: "Mojito",
            price: 14.06,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Manhattan",
            price: 14.74,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Old Fashioned",
            price: 15.28,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Mai Tai",
            price: 12.22,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Whiskey Sour",
            price: 13.69,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Negroni",
            price: 14.86,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Margarita",
            price: 14.02,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Wine Selection",
        description:
          "A spectrum of vintages and varietals—from structured reds to bright, crisp whites.",
        items: [
          {
            name: "Cabernet Franc",
            price: 13.16,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Petit Verdot",
            price: 11.5,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Riesling",
            price: 12.89,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Vouvray",
            price: 11.12,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Dolcetto",
            price: 11.87,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Verdicchio",
            price: 13.01,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Spirits and Liqueurs",
        description:
          "A curated collection of fine spirits and artisan liqueurs from around the world.",
        items: [
          {
            name: "Maraschino",
            price: 12.33,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Vodka",
            price: 10.89,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Armagnac",
            price: 16.95,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Gin",
            price: 17.58,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Drambuie",
            price: 13.48,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
];
