import { RestaurantMenu } from "@/lib/types/types";

/**
 * Menu data for Italian Experience in seattle
 */
export const seattleitalianExperienceMenu: RestaurantMenu[] = [
  {
    title: "Main Course Menu",
    description: "Modern dining rooted in fresh Japanese techniques",
    category: [
      {
        name: "Signature Dishes",
        description:
          "A curated collection of our most iconic and requested plates.",
        items: [
          {
            name: "Gourmet Appetizing House Famous Duck Confit",
            price: 24.07,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Fresh Zingy Age-Old Recipe Osso Buco with Gremolata",
            price: 26.11,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Sweet Signature Truffle Pasta with Aged Pecorino",
            price: 32.58,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Deluxe Grilled Chef's Special Surf and Turf",
            price: 36.6,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Marinated Founder's Family Recipe Pasta",
            price: 33.39,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Authentic Grilled Flambéed Tableside Specialty",
            price: 29.84,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Traditional Delicious Secret Recipe Bouillabaisse",
            price: 25.61,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Chef's Specials",
        description:
          "Inventive dishes that explore rare ingredients, bold flavors, and progressive cooking techniques.",
        items: [
          {
            name: "Chef's Tasting Menu Experience",
            price: 29.9,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Aged and House-Cured Charcuterie Selection",
            price: 28.17,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Daily Fresh Catch with Seasonal Accompaniments",
            price: 25.65,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Cold-Smoked Delicacy",
            price: 25.04,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Tomahawk Ribeye for Two",
            price: 29.15,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Appetizers",
        description:
          "A tempting assortment of beginning bites to pair with your first drink.",
        items: [
          {
            name: "Authentic Pan-seared Crostini",
            price: 11.16,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Classic Golden Shrimp Cocktail",
            price: 8.49,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Fresh Flavorful Charcuterie Board",
            price: 15.68,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Handcrafted Grilled Tuna Tartare",
            price: 8.03,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "House Special Wholesome Antipasto Platter",
            price: 15.75,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Homestyle Grilled Falafel",
            price: 10.06,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Grilled Deviled Eggs",
            price: 9.12,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Homestyle Luscious Cheese Nachos",
            price: 11.52,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Soups",
        description:
          "Daily-prepared soups made from seasonal ingredients and traditional Japanese methods.",
        items: [
          {
            name: "Avgolemono (Greek Lemon Soup)",
            price: 10.93,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Borscht",
            price: 8.88,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Zuppa Toscana",
            price: 10.05,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Mushroom Soup",
            price: 13.93,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Salads",
        description:
          "From classic combinations to innovative creations, our salads are a feast for the senses.",
        items: [
          {
            name: "Spinach Salad",
            price: 12.89,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Pear and Gorgonzola Salad",
            price: 9.48,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Chef Salad",
            price: 11.57,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Beet Salad",
            price: 12.25,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fruit Salad",
            price: 12.87,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Main Courses",
        description:
          "A journey through Japanese flavors, expertly prepared and beautifully presented.",
        items: [
          {
            name: "Grilled Tofu",
            price: 21.99,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fish and Chips",
            price: 30.63,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Shish Kebabs",
            price: 31.44,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Tacos",
            price: 25.15,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Stuffed Zucchini Boats",
            price: 20.72,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Biryani",
            price: 31.06,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Steak",
            price: 25.34,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Grilled Chicken",
            price: 20.82,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
        ],
      },
      {
        name: "Seafood Specialties",
        description:
          "Celebrations of the sea—light, flavorful, and handled with the utmost care.",
        items: [
          {
            name: "Grilled Lobster with Lemon Butter",
            price: 23.95,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Shrimp Scampi over Linguine",
            price: 29.82,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Classic British Fish and Chips",
            price: 25.99,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Pan-Seared Scallops with Pea Purée",
            price: 34.75,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Cedar Plank Roasted Salmon",
            price: 28.83,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
        ],
      },
      {
        name: "Side Dishes",
        description:
          "Classic Japanese side dishes with our own unique interpretation.",
        items: [
          {
            name: "Grilled Asparagus with Lemon Zest",
            price: 5.69,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Mashed Potatoes",
            price: 8.3,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fragrant Basmati Rice Pilaf",
            price: 8.37,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Macaroni and Aged Cheddar",
            price: 9.39,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "French Fries",
            price: 7.45,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Green Beans Almondine",
            price: 5.35,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Non-Alcoholic Beverages",
        description:
          "Bright, invigorating options that cleanse the palate and refresh the spirit.",
        items: [
          {
            name: "Deluxe Crispy Hot Chocolate",
            price: 4.93,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Homestyle Juicy Water",
            price: 6.51,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Pan-seared Juice",
            price: 4.63,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Deluxe Smoked Coffee",
            price: 6.11,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Baked Milkshake",
            price: 6.14,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: false,
            isKosher: true,
          },
          {
            name: "Gourmet Herbed Tea",
            price: 5.99,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
  {
    title: "Dessert Menu",
    description: "Satisfy your sweet tooth with our comforting treats",
    category: [
      {
        name: "Baked Goods",
        description:
          "Indulge in our selection of baked treats, each one a labor of love.",
        items: [
          {
            name: "Homestyle Delicious Crumb Cake",
            price: 8.86,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Organic Delectable Custard Tart",
            price: 9.74,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Homestyle Mouthwatering Sticky Toffee Pudding",
            price: 7.24,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "House Special Irresistible Muffins",
            price: 7.69,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Handcrafted Appetizing Soufflé",
            price: 7.46,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Frozen Desserts",
        description:
          "Smooth, rich frozen creations featuring local fruits and seasonal flavors.",
        items: [
          {
            name: "Gourmet Zingy Granita",
            price: 11.27,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Marinated Frozen Fruit Bars",
            price: 9.63,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Spiced Frozen Pudding",
            price: 7.41,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Seasonal Sweet Frozen Cheesecake",
            price: 9.54,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Smoked Snow Cone",
            price: 7.65,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
  {
    title: "Drinks Menu",
    description: "Our bartenders' inviting creations to complete your meal",
    category: [
      {
        name: "Signature Cocktails",
        description:
          "Crafted with precision, our cocktails are designed to elevate your dining experience.",
        items: [
          {
            name: "Hearty Stuffed Manhattan",
            price: 12.26,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Spiced Mojito",
            price: 13.67,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Steamed Old Fashioned",
            price: 11,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Seasonal Delectable Margarita",
            price: 11.39,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Homestyle Stuffed Mai Tai",
            price: 14.3,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Handcrafted Spiced Whiskey Sour",
            price: 12.65,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Hearty Tangy Cosmopolitan",
            price: 12.07,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Wine Selection",
        description:
          "A diverse collection of varietals and vintages, chosen for quality and character.",
        items: [
          {
            name: "Traditional Sizzling Fiano",
            price: 9.48,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Herbed Zinfandel",
            price: 8.33,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: true,
          },
          {
            name: "Handcrafted Delicious Syrah/Shiraz",
            price: 10.37,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Aromatic Nebbiolo",
            price: 10.2,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Sizzling Sangiovese",
            price: 9.49,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Seasonal Herbed Sémillon",
            price: 11.85,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Spirits and Liqueurs",
        description:
          "Ideal for slow sipping or celebratory toasts—each bottle has a story.",
        items: [
          {
            name: "Traditional Crunchy Grappa",
            price: 16.65,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Homestyle Stuffed Rum",
            price: 15.48,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Seasonal Comforting Cognac",
            price: 14.88,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Premium Satisfying Calvados",
            price: 13.93,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Handcrafted Sautéed Amaretto",
            price: 14.68,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
];
