import { RestaurantMenu } from "@/lib/types/types";

/**
 * Menu data for Italian Boulangerie in seattle
 */
export const seattleitalianBoulangerieMenu: RestaurantMenu[] = [
  {
    title: "Main Course Menu",
    description:
      "A classic dining experience featuring the essence of Italian gastronomy",
    category: [
      {
        name: "Signature Dishes",
        description:
          "Unforgettable signatures that define who we are and what we serve, crafted to perfection.",
        items: [
          {
            name: "Homestyle Grilled 24-Hour Braised Short Ribs",
            price: 28.92,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Fresh Satisfying Black Garlic Glazed Beef Tenderloin",
            price: 33.94,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: true,
          },
          {
            name: "Premium Crispy Age-Old Recipe Osso Buco with Gremolata",
            price: 33.34,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Handcrafted Enticing Chef's Special Surf and Turf",
            price: 34.77,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Satisfying Chef's Childhood Inspired Creation",
            price: 31.86,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Traditional Tender Executive Chef's Daily Inspiration Entrée",
            price: 31.37,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Homestyle Irresistible Flambéed Tableside Specialty",
            price: 24.13,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
        ],
      },
      {
        name: "Chef's Specials",
        description:
          "Unique culinary compositions that rotate frequently to keep each visit fresh and surprising.",
        items: [
          {
            name: "Black Garlic Marinated Octopus",
            price: 24.33,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Live-Fire Grilled Feature",
            price: 34.59,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Tableside Prepared Tartare",
            price: 31.58,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Signature Spice-Rubbed Protein",
            price: 37.5,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Truffle-Infused Filet Mignon",
            price: 38.2,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: false,
            isKosher: false,
          },
        ],
      },
      {
        name: "Appetizers",
        description:
          "A tempting assortment of beginning bites to pair with your first drink.",
        items: [
          {
            name: "Fresh Marinated Caprese Salad",
            price: 10.24,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Homestyle Creamy Bruschetta",
            price: 9.6,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Handcrafted Sizzling Meatballs",
            price: 12.54,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: true,
          },
          {
            name: "Fresh Grilled Mini Crab Cakes",
            price: 11.69,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Classic Satisfying Tuna Tartare",
            price: 15.47,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Hearty Smoked Samosas",
            price: 13.46,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Hearty Savory Mini Tacos",
            price: 8.11,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Mouthwatering Calamari",
            price: 10.61,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
        ],
      },
      {
        name: "Soups",
        description:
          "Crafted with care, our soups are a celebration of Italian flavors and traditions.",
        items: [
          {
            name: "Fresh Creamy Pho",
            price: 13.43,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Classic Pan-seared Butternut Squash Soup",
            price: 11.59,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Organic Marinated Miso Soup",
            price: 7.05,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "House Special Zesty Vegetable Barley Soup",
            price: 11.53,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Salads",
        description:
          "Lively salads combining texture, temperature, and taste for a refreshing start or light meal.",
        items: [
          {
            name: "Roasted Beet and Goat Cheese Salad",
            price: 13.79,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Farro Salad",
            price: 13.53,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Nicoise Salad",
            price: 12.51,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Caesar Salad",
            price: 14.1,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Kale Salad",
            price: 14.36,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Main Courses",
        description:
          "Each dish is a culinary journey, showcasing the richness of Italian traditions.",
        items: [
          {
            name: "Homestyle Tangy Steak",
            price: 25,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Seasonal Golden Shish Kebabs",
            price: 26.58,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Seasonal Spicy Pesto Pasta",
            price: 25.16,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Spiced Grilled Chicken",
            price: 22.09,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Seasonal Sizzling Thai Curry",
            price: 27.19,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Classic Zingy Lentil Stew",
            price: 26.22,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "House Special Zingy Lasagna",
            price: 23.92,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "House Special Zesty Gnocchi",
            price: 24.77,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Seafood Specialties",
        description:
          "Crafted with care, our seafood offerings are a testament to our commitment to quality.",
        items: [
          {
            name: "Seared Tuna Steak with Sesame Crust",
            price: 26.55,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Miso-Marinated Chilean Sea Bass",
            price: 31.93,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Cedar Plank Roasted Salmon",
            price: 24.13,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Sushi-Grade Sashimi Platter",
            price: 35.04,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Seafood Gumbo with Okra",
            price: 27.11,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
        ],
      },
      {
        name: "Side Dishes",
        description:
          "Small dishes with big impact—each one crafted to complement without overpowering.",
        items: [
          {
            name: "Seasonal Baked Garlic Bread with Herb Butter",
            price: 7.5,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Seasonal Crunchy Steamed Jasmine Rice",
            price: 5.21,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Gourmet Smoked Provencal Ratatouille",
            price: 6.25,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Baked Baked Idaho Potato with Sour Cream",
            price: 5.38,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Seasonal Pan-seared Wild Mushroom Risotto",
            price: 6.49,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Gourmet Spiced Homestyle Baked Beans",
            price: 8.55,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Non-Alcoholic Beverages",
        description:
          "Refreshing selections ranging from house-made sodas to premium juices.",
        items: [
          {
            name: "House Special Herbed Juice",
            price: 7.73,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Hearty Delicious Lemonade",
            price: 6.8,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Classic Spiced Milkshake",
            price: 4.37,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Sizzling Water",
            price: 6.57,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Hearty Tea",
            price: 4.76,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Exquisite Soda",
            price: 7.66,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
        ],
      },
    ],
  },
  {
    title: "Dessert Menu",
    description: "From oven to plate – comforting desserts made with care",
    category: [
      {
        name: "Baked Goods",
        description:
          "Artisanal baked items showcasing skill, tradition, and a touch of creativity.",
        items: [
          {
            name: "Strawberry Shortcake",
            price: 10.94,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Sticky Toffee Pudding",
            price: 6.02,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Lemon Bars",
            price: 7.38,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Apple Pie",
            price: 10.4,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Macarons",
            price: 6.2,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Frozen Desserts",
        description:
          "Made in-house with premium dairy and plant-based alternatives.",
        items: [
          {
            name: "Seasonal Grilled Frozen Yogurt",
            price: 10.76,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Classic Marinated Frozen Banana",
            price: 11.84,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Organic Braised Paletas",
            price: 10.2,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Steamed Gelato",
            price: 7.98,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Gourmet Grilled Kulfi",
            price: 10.5,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
  {
    title: "Drinks Menu",
    description: "Treat yourself to a fine nightcap from our curated selection",
    category: [
      {
        name: "Signature Cocktails",
        description:
          "Elevate your evening with our signature cocktails, each a unique expression of flavor.",
        items: [
          {
            name: "Traditional Herbed Bloody Mary",
            price: 12.01,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Classic Spicy Mojito",
            price: 13.71,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Spicy Manhattan",
            price: 10.77,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Organic Satisfying Old Fashioned",
            price: 13.92,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Wholesome Whiskey Sour",
            price: 15.54,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "House Special Sweet Cosmopolitan",
            price: 15.64,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Gourmet Delectable Negroni",
            price: 12.19,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Wine Selection",
        description:
          "From crisp whites to structured reds, our wine list offers something for every palate.",
        items: [
          {
            name: "Pinot Grigio",
            price: 12.69,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fiano",
            price: 13.38,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Dolcetto",
            price: 13.11,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Riesling",
            price: 8.36,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Zinfandel",
            price: 12.83,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Roussanne",
            price: 10.67,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Spirits and Liqueurs",
        description:
          "From timeless classics to innovative new blends, our spirits menu is a celebration of flavor.",
        items: [
          {
            name: "Authentic Savory Frangelico",
            price: 12.14,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Traditional Spiced Limoncello",
            price: 17.06,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Sizzling Vodka",
            price: 16.96,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Homestyle Marinated Calvados",
            price: 13.2,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Handcrafted Pan-seared Chartreuse",
            price: 17.35,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
];
