import { Restaurant } from "@/lib/types/types";

export const osloRestaurants: Restaurant[] = [
  {
    name: "Royal Lab",
    description:
      "A culinary gem serving Mediterranean specialties including local ingredients, where guests enjoy live street performances in the heart of the city.",
    cuisine: "Mediterranean",
    priceRange: "$$$",
    rating: 4.7,
    openingHours: {
      monday: "9:00-22:00",
      tuesday: "9:00-20:00",
      wednesday: "Closed",
      thursday: "9:00-22:00",
      friday: "10:00-22:00",
      saturday: "Closed",
      sunday: "11:00-19:00",
    },
    contactInfo: {
      contactNumber: "+1-555-385-7894",
      contactEmail: "support@goldenpavilionoslo.com",
    },
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: false,
    isHalalFriendly: false,
    isKosherFriendly: false,
    isFineDining: false,
    isAdultOnly: false,
    isIndoorSeating: false,
    isReservationsAccepted: true,
    isRomantic: false,
    isPopular: true,
  },
  {
    name: "Grand Provisions",
    description:
      "This popular French establishment combines traditional recipes and farm-to-table meals, all served in a unique setting with ambient lighting.",
    cuisine: "French",
    priceRange: "$$$",
    rating: 4.3,
    openingHours: {
      monday: "9:00-19:00",
      tuesday: "9:00-19:00",
      wednesday: "9:00-21:00",
      thursday: "10:00-19:00",
      friday: "10:00-21:00",
      saturday: "11:00-21:00",
      sunday: "10:00-20:00",
    },
    contactInfo: {
      contactNumber: "+1-555-463-4455",
      contactEmail: "support@theramen-yaoslo.com",
    },
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: true,
    isHalalFriendly: true,
    isKosherFriendly: false,
    isFineDining: false,
    isAdultOnly: false,
    isIndoorSeating: true,
    isReservationsAccepted: true,
    isRomantic: true,
    isPopular: false,
  },
  {
    name: "The Workshop",
    description:
      "A culinary gem serving French specialties including fresh produce, where guests enjoy beautiful decor in the heart of the city.",
    cuisine: "French",
    priceRange: "$$$",
    rating: 4,
    openingHours: {
      monday: "9:00-20:00",
      tuesday: "11:00-21:00",
      wednesday: "9:00-20:00",
      thursday: "Closed",
      friday: "9:00-20:00",
      saturday: "Closed",
      sunday: "9:00-21:00",
    },
    contactInfo: {
      contactNumber: "+1-555-754-9187",
      contactEmail: "support@grandnoodlebaroslo.com",
    },
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: true,
    isHalalFriendly: false,
    isKosherFriendly: true,
    isFineDining: false,
    isAdultOnly: true,
    isIndoorSeating: true,
    isReservationsAccepted: true,
    isRomantic: false,
    isPopular: true,
  },
  {
    name: "The Club",
    description:
      "Experience authentic Italian cuisine with a local twist, featuring gourmet street food served in an atmosphere of boutique shops overlooking the main square.",
    cuisine: "Italian",
    priceRange: "$$$",
    rating: 3.9,
    openingHours: {
      monday: "11:00-21:00",
      tuesday: "9:00-22:00",
      wednesday: "11:00-20:00",
      thursday: "Closed",
      friday: "9:00-20:00",
      saturday: "10:00-20:00",
      sunday: "Closed",
    },
    contactInfo: {
      contactNumber: "+1-555-638-5206",
      contactEmail: "support@thegourmetoslo.com",
    },
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: true,
    isHalalFriendly: false,
    isKosherFriendly: false,
    isFineDining: false,
    isAdultOnly: false,
    isIndoorSeating: true,
    isReservationsAccepted: true,
    isRomantic: true,
    isPopular: true,
  },
  {
    name: "Royal Atelier",
    description:
      "A culinary gem serving American specialties including heritage recipes, where guests enjoy artisan markets in the heart of the city.",
    cuisine: "American",
    priceRange: "$$$",
    rating: 3.9,
    openingHours: {
      monday: "9:00-20:00",
      tuesday: "9:00-19:00",
      wednesday: "11:00-19:00",
      thursday: "10:00-21:00",
      friday: "10:00-22:00",
      saturday: "10:00-21:00",
      sunday: "Closed",
    },
    contactInfo: {
      contactNumber: "+1-555-943-1252",
      contactEmail: "support@blueworkshoposlo.com",
    },
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: true,
    isHalalFriendly: false,
    isKosherFriendly: false,
    isFineDining: false,
    isAdultOnly: false,
    isIndoorSeating: true,
    isReservationsAccepted: true,
    isRomantic: true,
    isPopular: true,
  },
  {
    name: "Golden Charcuterie",
    description:
      "This popular American establishment combines traditional recipes and regional wines, all served in a unique setting with local ambiance.",
    cuisine: "American",
    priceRange: "$",
    rating: 4.6,
    openingHours: {
      monday: "9:00-21:00",
      tuesday: "11:00-20:00",
      wednesday: "9:00-19:00",
      thursday: "9:00-21:00",
      friday: "11:00-20:00",
      saturday: "10:00-21:00",
      sunday: "10:00-20:00",
    },
    contactInfo: {
      contactNumber: "+1-555-623-6987",
      contactEmail: "services@bluebakeryoslo.com",
    },
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: false,
    isHalalFriendly: false,
    isKosherFriendly: false,
    isFineDining: false,
    isAdultOnly: false,
    isIndoorSeating: true,
    isReservationsAccepted: false,
    isRomantic: true,
    isPopular: true,
  },
  {
    name: "Blue Dim Sum Palace",
    description:
      "A culinary gem serving Japanese specialties including signature dishes, where guests enjoy seasonal floral displays in the heart of the city.",
    cuisine: "Japanese",
    priceRange: "$",
    rating: 4.5,
    openingHours: {
      monday: "11:00-19:00",
      tuesday: "9:00-20:00",
      wednesday: "11:00-21:00",
      thursday: "11:00-20:00",
      friday: "11:00-21:00",
      saturday: "11:00-21:00",
      sunday: "10:00-21:00",
    },
    contactInfo: {
      contactNumber: "+1-555-601-6141",
      contactEmail: "services@thecharcuterieoslo.com",
    },
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: false,
    isHalalFriendly: true,
    isKosherFriendly: false,
    isFineDining: false,
    isAdultOnly: false,
    isIndoorSeating: true,
    isReservationsAccepted: true,
    isRomantic: true,
    isPopular: false,
  },
  {
    name: "Grand Rooftop",
    description:
      "Located close to the city museum, this French restaurant delights with its signature dishes and local ambiance.",
    cuisine: "French",
    priceRange: "$",
    rating: 4.6,
    openingHours: {
      monday: "11:00-20:00",
      tuesday: "9:00-19:00",
      wednesday: "10:00-20:00",
      thursday: "10:00-19:00",
      friday: "11:00-20:00",
      saturday: "10:00-19:00",
      sunday: "9:00-22:00",
    },
    contactInfo: {
      contactNumber: "+1-555-663-3028",
      contactEmail: "services@thecommissaryoslo.com",
    },
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: false,
    isHalalFriendly: true,
    isKosherFriendly: false,
    isFineDining: false,
    isAdultOnly: false,
    isIndoorSeating: false,
    isReservationsAccepted: true,
    isRomantic: false,
    isPopular: true,
  },
];
