import { RestaurantMenu } from "@/lib/types/types";

/**
 * Menu data for Chinese Bakery in yokohama
 */
export const yokohamachineseBakeryMenu: RestaurantMenu[] = [
  {
    title: "Main Course Menu",
    description: "Timeless tastes, elevated by our simple approach to Italian",
    category: [
      {
        name: "Signature Dishes",
        description:
          "Distinctive creations that have become synonymous with our name—prepared with precision and purpose.",
        items: [
          {
            name: "Legendary Prime Rib",
            price: 37.67,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Chef’s Wild Game Selection",
            price: 27.79,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Secret Recipe Bouillabaisse",
            price: 35.29,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Caribbean-Style Jerk Duck with Mango Slaw",
            price: 33.83,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Black Garlic Glazed Beef Tenderloin",
            price: 32.68,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Award-Winning Seafood Boil",
            price: 33.85,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Traditional Family Paella",
            price: 33.19,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Chef's Specials",
        description:
          "A showcase of our chef's creativity, featuring dishes that are as unique as they are delicious.",
        items: [
          {
            name: "Pan-Seared Scallops with Citrus Beurre Blanc",
            price: 34.62,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Duck Confit with Roasted Root Vegetables",
            price: 26.14,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Chef's Childhood Favorite Reimagined",
            price: 31.72,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Volcanic Stone-Cooked Specialty",
            price: 39.54,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Collaborative Limited Edition Special",
            price: 37.78,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Appetizers",
        description:
          "Flavor-forward starters that introduce our approach to Italian with balance and creativity.",
        items: [
          {
            name: "Premium Steamed Zucchini Fries",
            price: 12.41,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Homestyle Creamy Garlic Bread",
            price: 11.24,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Marinated Baked Brie",
            price: 11.08,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Classic Marinated Calamari",
            price: 11.6,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Handcrafted Stuffed Cheese Platter",
            price: 14.52,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Premium Flavorful Stuffed Peppers",
            price: 11.25,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Gourmet Creamy Bruschetta",
            price: 9.63,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Zingy Tempura",
            price: 9.17,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
        ],
      },
      {
        name: "Soups",
        description:
          "Daily-prepared soups made from seasonal ingredients and traditional Italian methods.",
        items: [
          {
            name: "House Special Appetizing Hot and Sour Soup",
            price: 8.68,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Handcrafted Steamed Clam Chowder",
            price: 10.13,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "House Special Savory Pumpkin Soup",
            price: 8.88,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Premium Succulent Split Pea Soup",
            price: 11.63,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Salads",
        description:
          "A blend of local and organic ingredients, thoughtfully combined for maximum flavor.",
        items: [
          {
            name: "Watermelon Feta Salad",
            price: 14.95,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Farro Salad",
            price: 13.45,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Coleslaw",
            price: 10.87,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Thai Green Papaya Salad",
            price: 13.29,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fruit Salad",
            price: 9.61,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Main Courses",
        description:
          "A selection of mains that reflect the heart and soul of Italian, prepared with care.",
        items: [
          {
            name: "Chicken Parmesan",
            price: 30.29,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Quiche",
            price: 30.84,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Lasagna",
            price: 25.18,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Tagine",
            price: 22.58,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Risotto",
            price: 28.09,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Mac and Cheese",
            price: 31.24,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Grilled Tofu",
            price: 24.51,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Bibimbap",
            price: 22.28,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Seafood Specialties",
        description:
          "From the sea to your plate—each dish is a tribute to the ocean’s bounty.",
        items: [
          {
            name: "Premium Hearty Grilled Spanish Octopus with Smoked Paprika",
            price: 32.03,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Authentic Mouthwatering Steamed Littleneck Clams in Garlic Broth",
            price: 28.32,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: true,
          },
          {
            name: "Fresh Grilled Basa Fillet with Dill Cream Sauce",
            price: 33.65,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Premium Sweet Miso-Marinated Chilean Sea Bass",
            price: 24.41,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Classic Pan-seared Linguine with Clam Sauce",
            price: 29.58,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: false,
          },
        ],
      },
      {
        name: "Side Dishes",
        description:
          "Crafted to enhance your main course, these sides are anything but ordinary.",
        items: [
          {
            name: "Homestyle Flavorful Soft Polenta with Parmesan",
            price: 5.87,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Gourmet Smoked Crispy Zucchini Fritters",
            price: 8.17,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Premium Baked Charred Broccolini with Garlic Oil",
            price: 5.34,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Premium Herbed Scalloped Potatoes with Thyme",
            price: 5.69,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Authentic Smoked Quinoa Pilaf with Herbs",
            price: 5.58,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Fresh Juicy Braised Red Cabbage with Apple",
            price: 7.65,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Non-Alcoholic Beverages",
        description:
          "Refreshing selections ranging from house-made sodas to premium juices.",
        items: [
          {
            name: "Hearty Crispy Smoothie",
            price: 6.31,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Premium Zesty Water",
            price: 4.77,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Handcrafted Pan-seared Juice",
            price: 4.31,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Homestyle Exquisite Tea",
            price: 6.24,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Gourmet Marinated Lemonade",
            price: 7.44,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Deluxe Steamed Coffee",
            price: 7.32,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
  {
    title: "Dessert Menu",
    description:
      "Handcrafted homemade desserts that celebrate Italian traditions",
    category: [
      {
        name: "Baked Goods",
        description:
          "From flaky croissants to rich breads—our oven's finest, ready to enjoy.",
        items: [
          {
            name: "Carrot Cake",
            price: 8.16,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Biscotti",
            price: 7.56,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Pumpkin Pie",
            price: 9.02,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Muffins",
            price: 6.14,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Berry Tart",
            price: 10.33,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Frozen Desserts",
        description:
          "Classic and contemporary frozen delights that cool and satisfy.",
        items: [
          {
            name: "Gourmet Crispy Ice Cream",
            price: 8.16,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Seasonal Steamed Frozen Mousse",
            price: 10.35,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Seasonal Pan-seared Paletas",
            price: 8.46,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Organic Sweet Ice Cream Cake",
            price: 11.82,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Appetizing Kulfi",
            price: 11.04,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
  {
    title: "Drinks Menu",
    description:
      "Indulge in our thoughtfully selected drinks menu crafted to accentuate flavors",
    category: [
      {
        name: "Signature Cocktails",
        description:
          "Custom-designed drinks created exclusively by our mixologists to complement our menu.",
        items: [
          {
            name: "Homestyle Creamy Martini",
            price: 14.1,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Delicious Margarita",
            price: 10.86,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Savory Manhattan",
            price: 13.38,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: true,
          },
          {
            name: "House Special Zingy Whiskey Sour",
            price: 12.4,
            isVegetarian: true,
            isVegan: true,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "House Special Zesty Bloody Mary",
            price: 12.12,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Zingy Old Fashioned",
            price: 10.59,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: false,
          },
          {
            name: "Organic Zesty Mai Tai",
            price: 10.56,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Wine Selection",
        description: "A wine list as thoughtful and layered as our cuisine.",
        items: [
          {
            name: "Premium Smoked Merlot",
            price: 10.03,
            isVegetarian: false,
            isVegan: true,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Crispy Roussanne",
            price: 12.34,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Handcrafted Fried Pinot Grigio",
            price: 9.82,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Homestyle Delectable Dolcetto",
            price: 9.97,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Authentic Pan-seared Cabernet Sauvignon",
            price: 11.17,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
          },
          {
            name: "Authentic Zesty Riesling",
            price: 11.24,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: true,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
      {
        name: "Spirits and Liqueurs",
        description:
          "Whether neat, on the rocks, or mixed—our premium selection is built to impress.",
        items: [
          {
            name: "Deluxe Hearty Whiskey",
            price: 10,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Organic Crispy Armagnac",
            price: 12.59,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Fresh Pan-seared Maraschino",
            price: 13.24,
            isVegetarian: true,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "House Special Luscious Kahlúa",
            price: 12.63,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
          {
            name: "Classic Delectable Vodka",
            price: 10.84,
            isVegetarian: false,
            isVegan: false,
            isGlutenFree: false,
            isHalal: true,
            isKosher: true,
          },
        ],
      },
    ],
  },
];
